################################################################################

BOT_TIMER="60"        # loop timer, in seconds (default 60)

################################################################################

LOG_LENGTH="21"       # log length (default 21)
LOG_DIR="/tmp"        # data folder (leeloo)

################################################################################

API_TIMEOUT="10s"     # timeout (default 10s)

################################################################################

GRAPH_TIME="0"            # 1d = one day, 1w = one week, 0 = Auto (graph sizing)
GRAPH_DATA="525600"       # 1-minute interval (default 525600 = 1 year)
GRAPH_FONT_SIZE="21"      # adjust the font size for the entire row (default 21)
GRAPH_FONT_WEIGHT="bold"  # adjust the font weight for the entire row (default bold)
GRAPH_FONT_COLOR="white"  # set the text color (default bold)
GRAPH_ORDERS_LENGTH="100" # set the limit for the number of orders to display (default 100)

################################################################################

# sort positions (exchange, strategy, currency, amount, cost, result, age)
POSITION_SORT_BY="age"

################################################################################

IRSSI_PORT=""
IRSSI_SERVER=""
IRSSI_NICKNAME=""

################################################################################

MAX_LOG="5000" # log lines (each log)
