################################################################################

LOG_DIR="/tmp"

### SouthXchange ###############################################################

# Key & Secret
API_SOUTHX_KEY=""    # Your API key
API_SOUTHX_SECRET="" # Your API secret

################################################################################
