#!/bin/bash

export LC_ALL=en_US.utf8 2>/dev/null
export NCURSES_NO_UTF8_ACS=1 2>/dev/null

# I'll not rest till I have me gold

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/ema
source /usr/local/bin/include/leeloo/indicators/rsi

# menu
HEIGHT=19
WIDTH=44
CHOICE_HEIGHT=11
BACKTITLE="Leeloo (Multipass)"
TITLE="Main Menu"
MENU="Multipass $DATE
Load: $LOAD :: $REPO_HEAD $REPO_DATE"

OPTIONS=(1 "Balance          Account Balance"
  2 "Market           View Market"
  3 "Search           Search Market"
  4 "Order            Setup order"
  5 "Update           New law & order"
  6 "Debug            Debug logs"
  7 "Config           API Config"
  A "Robot            Auto strategy"
  C "Chat             IRC Chat"
  D "Donate           Donation"
  0 "Quit             Exit Menu")

CHOICE=$(dialog --clear \
  --nocancel \
  --backtitle "$BACKTITLE" \
  --title "$TITLE" \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in

"1")

  if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
    if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then
      if [[ "$(cat "${LOG_DIR:?}"/leeloo/southxchange/balances | egrep "[0-9]+.[0-9]+" | wc -l)" -gt "0" ]] &>/dev/null; then

        BALANCE_TIMER="$(echo "$BOT_TIMER*3" | bc 2>/dev/null)"

        function result_balance() {
          listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
        }

        # update data every n seconds
        if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)))" 2>/dev/null)" -gt "$BALANCE_TIMER" ]] &>/dev/null; then
          result_balance
          # update data if missing
        elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
          result_balance
          # update data if empty
        elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
          result_balance
        fi

        sleep 1

        display_result() {
          dialog --title "Account Balance" \
            --no-collapse \
            --msgbox "$RESULT" 0 0
        }

        RESULT="Coins:  Deposited    Available   Unconfirmed

$(cat "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)"
        display_result 2>/dev/null
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi
  fi

  ;;

"2")

  MARKET_TIMER="$(echo "$BOT_TIMER*3" | bc 2>/dev/null)"

  function result_market {
    prices | awk '{for(i=1;i<=NF;i++) {if($i~/^[0-9]*\.?[0-9]*[eE][-+]?[0-9]+$/) {printf("%.6f\t",$i);} else {printf("%s\t",$i)}} printf("\n")}' | column -t >"${LOG_DIR:?}"/leeloo/southxchange/market
  }

  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null)))" 2>/dev/null)" -gt "$MARKET_TIMER" ]] &>/dev/null; then
    result_market
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/market ]] &>/dev/null; then
    result_market
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/market ]] &>/dev/null; then
    result_market
  fi

  # 450 max before dialog breaks
  MARKET_RESULT="$(cat "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null | sort -k2 -n -r | head -100)"
  MARKET_COUNT="$(echo "$MARKET_RESULT" | wc -l)"
  MARKET_MOON="$(cat "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null | awk '{ print $5 }' | awk '{ SUM += $1} END { print SUM }')"
  MARKET_MOON_COUNT="$(cat "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null | awk '{ print $5 }' | wc -l)"
  MARKET_MOON_VALUE="$(echo "$MARKET_MOON/$MARKET_MOON_COUNT" | bc -l | awk '{ printf "%.2f\n", $1 }')"
  WIDTH="$(echo "$(echo "$MARKET_RESULT" | wc -L)+5" | bc 2>/dev/null)"

  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="100"
  fi

  display_result() {
    dialog --title "100 Market: +$MARKET_COUNT :: $DATE :: ${MARKET_MOON_VALUE:?}%" \
      --no-collapse \
      --scrollbar \
      --msgbox "$(echo "$RESULT" | column -t)" 25 "$WIDTH"
  }

  RESULT="Market:       Bid             Ask             Last           (%)      Volume24Hr

$MARKET_RESULT"
  display_result 2>/dev/null

  ;;

"3")

  search

  if [[ ! -z "$MARKET_INPUT" ]] &>/dev/null; then

    MARKET_TIMER="$(echo "$BOT_TIMER*3" | bc 2>/dev/null)"

    function result_market {
      prices | awk '{for(i=1;i<=NF;i++) {if($i~/^[0-9]*\.?[0-9]*[eE][-+]?[0-9]+$/) {printf("%.6f\t",$i);} else {printf("%s\t",$i)}} printf("\n")}' | column -t >"${LOG_DIR:?}"/leeloo/southxchange/market
    }

    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null)))" 2>/dev/null)" -gt "$MARKET_TIMER" ]] &>/dev/null; then
      result_market
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/market ]] &>/dev/null; then
      result_market
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/market ]] &>/dev/null; then
      result_market
    fi

    MARKET_SEARCH="$(echo "$MARKET_INPUT" | tr '[:lower:]' '[:upper:]')"
    MARKET_RESULT="$(grep "$MARKET_SEARCH" "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null)"
    MARKET_COUNT="$(echo "$MARKET_RESULT" | wc -l)"
    MARKET_MOON="$(echo "$MARKET_RESULT" | awk '{ print $5 }' | awk '{ SUM += $1} END { print SUM }')"
    MARKET_MOON_COUNT="$(echo "$MARKET_RESULT" | awk '{ print $5 }' | wc -l)"
    MARKET_MOON_VALUE="$(echo "$MARKET_MOON/$MARKET_MOON_COUNT" | bc -l | awk '{ printf "%.2f\n", $1 }')"
    LENGTH="$(echo "$MARKET_COUNT+5" | bc 2>/dev/null)"
    WIDTH="$(echo "$(echo "$MARKET_RESULT" | column -t | wc -L)+6" | bc 2>/dev/null)"

    if [[ "$LENGTH" -gt "25" ]] &>/dev/null; then
      LENGTH="25"
    fi

    if [[ "$WIDTH" -lt "70" ]] &>/dev/null; then
      WIDTH="70"
    elif [[ "$(echo "$MARKET_RESULT" | wc -L)" -eq "0" ]] &>/dev/null; then
      WIDTH="70"
    fi

    display_result() {
      dialog --title "Search result: +$MARKET_COUNT :: $DATE :: ${MARKET_MOON_VALUE:?}%" \
        --no-collapse \
        --msgbox "$(echo "$RESULT" | column -t)" "$LENGTH" "$WIDTH"
    }

    RESULT="Market:       Bid           Ask          Last       (%)      Volume24Hr

$MARKET_RESULT"
    display_result 2>/dev/null
  else
    display_result() {
      dialog --title "Market info (empty)" \
        --no-collapse \
        --msgbox "$RESULT" 0 0
    }

    RESULT="No data found!"
    display_result 2>/dev/null
  fi

  ;;

  # orders

"4")

  if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
    if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

      # menu
      HEIGHT=10
      WIDTH=40
      CHOICE_HEIGHT=3
      BACKTITLE="Leeloo (Multipass)"
      TITLE="Order Menu"
      MENU="${DATE:?}"

      OPTIONS=(1 "Buy              Buy Order"
        2 "Sell             Sell Order"
        3 "Status           Open Orders")

      CHOICE=$(dialog --clear \
        --backtitle "$BACKTITLE" \
        --title "$TITLE" \
        --menu "$MENU" \
        $HEIGHT $WIDTH $CHOICE_HEIGHT \
        "${OPTIONS[@]}" \
        2>&1 >/dev/tty)

      clear
      case $CHOICE in

      "1")

        TYPE="buy"
        HEIGHT=9
        WIDTH=23
        CHOICE_HEIGHT=2
        BACKTITLE="Leeloo (Multipass)"
        TITLE="Buy Order Menu"
        AMOUNT_IN_REFERENCE_CURRENCY="true"
        MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

        OPTIONS=(
          1 "Market Order"
          2 "Limit Order")

        CHOICE=$(dialog --clear \
          --backtitle "$BACKTITLE" \
          --title "$TITLE" \
          --menu "$MENU" \
          $HEIGHT $WIDTH $CHOICE_HEIGHT \
          "${OPTIONS[@]}" \
          2>&1 >/dev/tty)

        clear
        case $CHOICE in

        "1")

          setup_market_order
          if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
            if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
              if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then
                PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                echo "$LOG_DATE :: Manual $TYPE :: Market Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT" >>"${LOG_DIR:?}"/leeloo/broker.log
                echo "$LOG_DATE :: Output: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
              fi
            fi
          fi

          ;;

        "2")

          setup_limit_order
          if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
            if [[ ! -z "$PRICE" ]] &>/dev/null; then
              if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
                if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then
                  PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                  echo "$LOG_DATE :: Manual $TYPE :: Limit Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log
                  echo "$LOG_DATE :: Output: $PLACE_ORDER :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log
                fi
              fi
            fi
          fi

          ;;

        esac

        last_log

        ;;

      "2")

        TYPE="sell"
        HEIGHT=9
        WIDTH=23
        CHOICE_HEIGHT=2
        BACKTITLE="Leeloo (Multipass)"
        TITLE="Sell Order Menu"
        AMOUNT_IN_REFERENCE_CURRENCY="false"
        MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

        OPTIONS=(
          1 "Market Order"
          2 "Limit Order")

        CHOICE=$(dialog --clear \
          --backtitle "$BACKTITLE" \
          --title "$TITLE" \
          --menu "$MENU" \
          $HEIGHT $WIDTH $CHOICE_HEIGHT \
          "${OPTIONS[@]}" \
          2>&1 >/dev/tty)

        clear
        case $CHOICE in

        "1")

          setup_market_order
          if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
            if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
              if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then
                PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                echo "$LOG_DATE :: Manual $TYPE :: Market Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT" >>"${LOG_DIR:?}"/leeloo/broker.log
                echo "$LOG_DATE :: Output: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
              fi
            fi
          fi

          ;;

        "2")

          setup_limit_order
          if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
            if [[ ! -z "$PRICE" ]] &>/dev/null; then
              if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
                if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then
                  PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                  echo "$LOG_DATE :: Manual $TYPE :: Limit Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log
                  echo "$LOG_DATE :: Output: $PLACE_ORDER :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log
                fi
              fi
            fi
          fi

          ;;

        esac

        last_log

        ;;

      "3")

        function result_orders {
          listOrders | jq -r '.[] | "\(.Code): \(.Type) \(.Amount) \(.OriginalAmount) \(.LimitPrice) \(.ListingCurrency) \(.ReferenceCurrency) \(.DateAdded)"' | awk '{for(i=1;i<=NF;i++) {if($i~/^[0-9]*\.?[0-9]*[eE][-+]?[0-9]+$/) {printf("%0.8f ",$i);} else if($i~/^[0-9]+$/) {printf("%0.8f ",$i);} else {printf("%s ",$i)}} printf("\n")}' | column -t | sort -r >"${LOG_DIR:?}"/leeloo/southxchange/orders
        }

        # update data every n seconds
        if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null)))" 2>/dev/null)" -gt "15" ]] &>/dev/null; then
          result_orders
          # update data if missing
        elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/orders ]] &>/dev/null; then
          result_orders
          # update data if empty
        elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/orders ]] &>/dev/null; then
          result_orders
        fi

        ORDER_TOTAL="$(wc -l "${LOG_DIR:?}"/leeloo/southxchange/orders | awk '{ print $1 }')"

        display_result() {
          dialog --title "Open Orders: +$ORDER_TOTAL" \
            --no-collapse \
            --msgbox "$RESULT" 0 0
        }

        RESULT="OrderID:    Type  Amount      Original    LimitPrice     List   Ref  DateAdded
$(cat "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null | sort -r)"
        display_result 2>/dev/null

        ;;

      esac
    else
      no_key_no_secret
    fi
  else
    no_key_no_secret
  fi

  ;;

  # update repo

"5")

  display_result() {
    dialog --title "Updating Leeloo (Multipass)" \
      --no-collapse \
      --msgbox "$RESULT" 0 0
  }

  cd || exit && cd "${HOME_DIR:?}"/leeloo || exit && git pull >"${LOG_DIR:?}"/leeloo/updating 2>/dev/null

  # restart looper if any updates
  if [[ "$(egrep "looper|leeloo" "${LOG_DIR:?}"/leeloo/updating 2>/dev/null | grep '[+-]' | wc -l)" -eq "1" ]] &>/dev/null; then
    ROBOT_UPDATES="$(egrep "looper|leeloo" "${LOG_DIR:?}"/leeloo/updating 2>/dev/null | awk '{ print $3,$4 }')"
    echo " Robot updated! $ROBOT_UPDATES" >>"${LOG_DIR:?}"/leeloo/updating

    if [[ "$(screen -list | grep "leeloo" 2>/dev/null | wc -l)" -eq "1" ]] &>/dev/null; then
      screen -S "$(screen -list | grep "leeloo" | awk -F. '{ print $1 }' | head -1 | xargs)".leeloo -p 0 -X quit
      echo " -- Robot stopping!" >>"${LOG_DIR:?}"/leeloo/updating
      if [[ "$(screen -list | grep "leeloo" 2>/dev/null | wc -l)" -eq "1" ]] &>/dev/null; then
        killall screen &>/dev/null
      fi
      bash "${SYS_DIR:?}"/robot/looper
      echo " ++ Robot restarting!" >>"${LOG_DIR:?}"/leeloo/updating
    fi
  fi

  # if any updates, skip
  if [[ ! "$(grep "Updating" "${LOG_DIR:?}"/leeloo/updating | wc -l)" -gt "0" ]] &>/dev/null; then
    echo "
$(echo "$(cat "${LOG_DIR:?}"/leeloo/updating) $REPO_HEAD")" >"${LOG_DIR:?}"/leeloo/updating
  fi

  RESULT="$(cat "${LOG_DIR:?}"/leeloo/updating 2>/dev/null)"
  display_result 2>/dev/null
  cd || exit && cd "${HOME_DIR:?}"/leeloo || exit && bash include/install 2>/dev/null
  rm "${LOG_DIR:?}"/leeloo/repo &>/dev/null
  cd "${HOME_DIR:?}"/leeloo || exit && git rev-parse --short HEAD 2>&1 | grep -Eo '[a0-z9]{7}' 2>&1 | head -1 >"${LOG_DIR:?}"/leeloo/repo 2>/dev/null
  cd "${HOME_DIR:?}"/leeloo || exit && git log -1 --format="%at" | xargs -I{} date -d @{} '+%Y' >>"${LOG_DIR:?}"/leeloo/repo 2>/dev/null
  clear

  if [[ ! "$(grep "Already up to date." "${LOG_DIR:?}"/leeloo/updating | wc -l)" -gt "0" ]] &>/dev/null; then
    exit
  fi

  ;;

"6")

  last_log

  ;;

"7")

  nano "${SYS_DIR:?}"/broker.conf

  ;;

"A")

  if [[ "$(screen -list | grep "leeloo" | wc -l)" -eq "1" ]] &>/dev/null; then
    ROBOT_RUNNING="Online"
    ROBOT_PID="$(screen -list | grep "leeloo" | awk -F. '{ print $1 }' | xargs)"
    ROBOT_TIME=$(ps -p $ROBOT_PID -o etimes=)
    ROBOT_UPTIME=$(printf '%dh:%dm:%ds\n' $(("$(echo "${ROBOT_TIME:?}" 2>&1)/3600")) $(("$(echo "${ROBOT_TIME:?}" 2>&1)%3600/60")) $(("$(echo "${ROBOT_TIME:?}" 2>&1)%60")))
    ROBOT_STRAT="$(ls -l "${SYS_DIR:?}"/robot/*.config | wc -l)"
  else
    ROBOT_STRAT="0"
    ROBOT_RUNNING="Offline"
    ROBOT_UPTIME="0h:0m:0s"
  fi

  HEIGHT=17
  WIDTH=45
  CHOICE_HEIGHT=10
  BACKTITLE="Leeloo (Multipass)"
  TITLE="Robot Strategy Menu"
  MENU="Multipass $DATE
Bots: $ROBOT_STRAT $ROBOT_RUNNING :: Uptime: $ROBOT_UPTIME"

  OPTIONS=(1 "Data             Strategy data"
    2 "Check            Indicator info"
    3 "Positions        Open positions"
    4 "Config           Configurations"
    5 "Create           Create strategy"
    6 "Control          Robot controller"
    7 "Bots             robot.log"
    8 "Debug            Specific log"
    0 "Delete           Remove strategy")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  # dashbord

  "1")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        while true; do
          CONFIG_FILES=("${SYS_DIR:?}"/robot/*.data)
          NUM_FILES="${#CONFIG_FILES[@]}"
          # shellcheck disable=SC2128
          WIDTH="$(echo "$CONFIG_FILES" | awk '{print length, $0}' | sort -nr | head -1 | awk '{ print $1 }')"
          WIDTH="$(echo "$WIDTH+11" | bc 2>/dev/null)"

          if [ $NUM_FILES -eq 0 ] &>/dev/null; then
            echo "Error: No data files found in $SYS_DIR/robot"
            exit 1
          fi

          OPTIONS=()
          for ((i = 0; i < "$NUM_FILES"; i++)); do
            OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
          done

          if [[ "$NUM_FILES" -lt "6" ]] &>/dev/null; then
            NUM_FILES="4"
          fi

          CHOICE=$(dialog --clear --title "Strategy Data" --menu "Choose one of the following data configurations:" "$(echo "$NUM_FILES+3" | bc 2>/dev/null)" "$WIDTH" 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)

          if [ -n "$CHOICE" ]; then
            SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
            display_result() {
              dialog --title "Data $SELECTED_FILE" \
                --no-collapse \
                --msgbox "$RESULT" 0 0
            }
            RESULT="$(cat "$SELECTED_FILE" 2>/dev/null)"
            display_result 2>/dev/null
            break
          else
            break
          fi
        done
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

    # check

  "2")

    HEIGHT=10
    WIDTH=55
    CHOICE_HEIGHT=10
    BACKTITLE="Leeloo (Multipass)"
    TITLE="Indicator Menu"
    MENU="Multipass $DATE"

    OPTIONS=(1 "RSI & EMA        RSI & EMA check"
      2 "RSI              Relative Strength Index"
      3 "EMA              Exponential Moving Average")

    CHOICE=$(dialog --clear \
      --backtitle "$BACKTITLE" \
      --title "$TITLE" \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      2>&1 >/dev/tty)

    clear
    case $CHOICE in

    # rsi & ema

    "1")

      coin_token_search

      if [[ ! -z "$COIN_TOKEN" ]] &>/dev/null; then

        COIN_TOKEN="$(echo "$COIN_TOKEN" | tr '[:lower:]' '[:upper:]')"

        function get_rsi_ema() {
          echo "-" >"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"

          GET_RSI_14="$(get_rsi 14 "$COIN_TOKEN" 2>/dev/null)"
          GET_RSI_21="$(get_rsi 21 "$COIN_TOKEN" 2>/dev/null)"
          GET_RSI_14_NR="$(echo "$GET_RSI_14" | awk '{ print $NF }')"
          GET_RSI_21_NR="$(echo "$GET_RSI_21" | awk '{ print $NF }')"
          GET_EMA_6_20="$(get_ema 6 20 "$COIN_TOKEN" 2>/dev/null)"
          GET_EMA_8_20="$(get_ema 8 20 "$COIN_TOKEN" 2>/dev/null)"
          GET_EMA_10_38="$(get_ema 10 38 "$COIN_TOKEN" 2>/dev/null)"
          GET_EMA_12_26="$(get_ema 12 26 "$COIN_TOKEN" 2>/dev/null)"
          GET_EMA_50_200="$(get_ema 50 200 "$COIN_TOKEN" 2>/dev/null)"

          echo "$GET_RSI_14" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_RSI_21" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "-" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          GET_RSI_CALC="$(echo "$GET_RSI_14_NR+$GET_RSI_21_NR" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
          GET_RSI_SIGNAL="$(echo "$GET_RSI_CALC/2" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"

          if (($(echo "$GET_RSI_SIGNAL > 70" | bc -l 2>/dev/null))); then
            echo "RSI_Signal Overbought ${GET_RSI_SIGNAL:?}" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          elif (($(echo "$GET_RSI_SIGNAL < 30" | bc -l 2>/dev/null))); then
            echo "RSI_Signal Oversold ${GET_RSI_SIGNAL:?}" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          else
            echo "RSI_Signal Neutral ${GET_RSI_SIGNAL:?}" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          fi

          echo "-" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_EMA_6_20" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_EMA_8_20" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_EMA_10_38" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_EMA_12_26" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "$GET_EMA_50_200" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          echo "-" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"

          BEARISH_SIGNAL="$(grep -c "Bearish" "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN")"
          BULLISH_SIGNAL="$(grep -c "Bullish" "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN")"
          TOTAL_SIGNAL="$(echo "$BEARISH_SIGNAL+$BULLISH_SIGNAL" | bc 2>/dev/null)"
          BEARISH_PERCENTAGE="$(echo "100/$TOTAL_SIGNAL*$BEARISH_SIGNAL" | bc 2>/dev/null)"
          BULLISH_PERCENTAGE="$(echo "100/$TOTAL_SIGNAL*$BULLISH_SIGNAL" | bc 2>/dev/null)"

          if [[ "$BEARISH_SIGNAL" -gt "$BULLISH_SIGNAL" ]] &>/dev/null; then
            echo "EMA_Signal Bearish ${BEARISH_PERCENTAGE:?}%" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          elif [[ "$BULLISH_SIGNAL" -gt "$BEARISH_SIGNAL" ]] &>/dev/null; then
            echo "EMA_Signal Bullish ${BULLISH_PERCENTAGE:?}%" >>"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
          fi

          echo "$(cat "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN"
        }

        # update data every n seconds
        if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" 2>/dev/null)))" 2>/dev/null)" -gt "180" ]] &>/dev/null; then
          get_rsi_ema
          GET_RSI_EMA="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" 2>/dev/null)"
        fi

        if [[ -f "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" ]] &>/dev/null; then
          GET_RSI_EMA="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" 2>/dev/null)"
        else
          get_rsi_ema
          GET_RSI_EMA="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" 2>/dev/null)"
        fi

        if [[ ! "$(grep "EMA" "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" | awk '{ print $5 }' | head -1)" == "0.00000000" ]] &>/dev/null; then

          LENGTH="$(echo "$(wc -l "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" | awk '{ print $1 }')+7" | bc 2>/dev/null)"
          WIDTH="$(echo "$(wc -L "${LOG_DIR:?}"/leeloo/indicators/check_rsi_ema_"$COIN_TOKEN" | awk '{ print $1 }')+5" | bc 2>/dev/null)"

          display_result() {
            dialog --title "Indicators ($COIN_TOKEN)" \
              --no-collapse \
              --msgbox "$RESULT" "$LENGTH" "$WIDTH"
          }

          RESULT="$GET_RSI_EMA"
          display_result 2>/dev/null
        else
          display_result() {
            dialog --title "Market info (404)" \
              --no-collapse \
              --msgbox "$RESULT" 5 25
          }

          RESULT="No $COIN_TOKEN EMA found!"
          display_result 2>/dev/null
        fi
      else
        display_result() {
          dialog --title "Market info (empty)" \
            --no-collapse \
            --msgbox "$RESULT" 0 0
        }

        RESULT="No data found!"
        display_result 2>/dev/null
      fi

      ;;

    "2")

      coin_token_search
      rsi_value_output

      COIN_TOKEN="$(echo "$COIN_TOKEN" | tr '[:lower:]' '[:upper:]')"

      # update data every n seconds
      if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT" 2>/dev/null)))" 2>/dev/null)" -gt "60" ]] &>/dev/null; then
        GET_RSI_CUSTOM="$(get_rsi "$RSI_VALUE_OUTPUT" "$COIN_TOKEN" 2>/dev/null)"
        echo "$GET_RSI_CUSTOM" >"${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT"
      fi

      if [[ -f "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT" ]] &>/dev/null; then
        GET_RSI_CUSTOM="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT" 2>/dev/null)"
      else
        GET_RSI_CUSTOM="$(get_rsi "$RSI_VALUE_OUTPUT" "$COIN_TOKEN" 2>/dev/null)"
        echo "$GET_RSI_CUSTOM" >"${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT"
        GET_RSI_CUSTOM="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_rsi_"$RSI_VALUE_OUTPUT" 2>/dev/null)"
      fi

      WIDTH="$(echo "$(echo "$GET_RSI_CUSTOM" | wc -L)+4" | bc 2>/dev/null)"

      if [[ -z "$WIDTH" ]] &>/dev/null; then
        WIDTH="30"
      fi
      if [[ "$WIDTH" -lt "30" ]] &>/dev/null; then
        WIDTH="30"
      fi

      if [[ ! -z "$COIN_TOKEN" ]] &>/dev/null; then
        if [[ ! -z "$GET_RSI_CUSTOM" ]] &>/dev/null; then
          display_result() {
            dialog --title "RSI $COIN_TOKEN" \
              --no-collapse \
              --msgbox "$RESULT" 5 "$WIDTH"
          }

          RESULT="$(echo "$GET_RSI_CUSTOM")"
          display_result 2>/dev/null
        fi
      fi

      ;;

    "3")

      coin_token_search
      ema_value_output

      COIN_TOKEN="$(echo "$COIN_TOKEN" | tr '[:lower:]' '[:upper:]')"

      # update data every n seconds
      if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT" 2>/dev/null)))" 2>/dev/null)" -gt "60" ]] &>/dev/null; then
        GET_EMA_CUSTOM="$(get_ema "$EMA_SHORT_OUTPUT" "$EMA_LONG_OUTPUT" "$COIN_TOKEN" 2>/dev/null)"
        echo "$GET_EMA_CUSTOM" >"${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT"
      fi

      if [[ -f "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT" ]] &>/dev/null; then
        GET_EMA_CUSTOM="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT" 2>/dev/null)"
      else
        GET_EMA_CUSTOM="$(get_ema "$EMA_SHORT_OUTPUT" "$EMA_LONG_OUTPUT" "$COIN_TOKEN" 2>/dev/null)"
        echo "$GET_EMA_CUSTOM" >"${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT"
        GET_EMA_CUSTOM="$(cat "${LOG_DIR:?}"/leeloo/indicators/check_"$COIN_TOKEN"_ema_"$EMA_SHORT_OUTPUT"_"$EMA_LONG_OUTPUT" 2>/dev/null)"
      fi

      WIDTH="$(echo "$(echo "$GET_EMA_CUSTOM" | wc -L)+4" | bc 2>/dev/null)"

      if [[ -z "$WIDTH" ]] &>/dev/null; then
        WIDTH="60"
      fi
      if [[ "$WIDTH" -lt "60" ]] &>/dev/null; then
        WIDTH="60"
      fi

      if [[ ! -z "$COIN_TOKEN" ]] &>/dev/null; then
        if [[ ! -z "$GET_EMA_CUSTOM" ]] &>/dev/null; then
          display_result() {
            dialog --title "EMA $COIN_TOKEN" \
              --no-collapse \
              --msgbox "$RESULT" 5 "$WIDTH"
          }

          RESULT="$(echo "$GET_EMA_CUSTOM")"
          display_result 2>/dev/null
        fi
      fi

      ;;

    esac

    ;;

    # open positions

  "3")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then
        if [[ "$(grep "Result" "${SYS_DIR:?}"/robot/pool 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then

          OPEN_COUNT="$(echo "$(wc -l "${SYS_DIR:?}"/robot/pool | awk '{ print $1 }')-1" | bc 2>/dev/null)"
          if [[ "$(echo "$OPEN_COUNT" | grep '[-]' | wc -l)" -gt "0" ]] &>/dev/null; then
            OPEN_COUNT="0"
          fi
          OPEN_PERCENTAGE="$(cat "${SYS_DIR:?}"/robot/pool | awk '{ print $5 }' | grep -v "Result" | tr -d '%' | awk '{ SUM += $1} END { print SUM }')"
          OPEN_PERCENTAGE_AVERAGE="$(echo "$OPEN_PERCENTAGE/$OPEN_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

          WIDTH="$(echo "$(tail -10 "${SYS_DIR:?}"/robot/pool | wc -L | awk '{ print $1 }')+4" | bc 2>/dev/null)"
          LENGTH="$(echo "$(tail -10 "${SYS_DIR:?}"/robot/pool | wc -l | awk '{ print $1 }')+5" | bc 2>/dev/null)"

          if [[ -z "$LENGTH" ]] &>/dev/null; then
            LENGTH="8"
          fi
          if [[ "$LENGTH" -lt "8" ]] &>/dev/null; then
            LENGTH="8"
          fi

          if [[ -z "$WIDTH" ]] &>/dev/null; then
            WIDTH="68"
          fi
          if [[ "$WIDTH" -lt "68" ]] &>/dev/null; then
            WIDTH="68"
          fi

          display_result() {
            dialog --title "Open Positions $OPEN_COUNT :: ${OPEN_PERCENTAGE_AVERAGE:?}%" \
              --no-collapse \
              --keep-window \
              --tailbox "$RESULT" "$LENGTH" "$WIDTH"
          }

          RESULT="${SYS_DIR:?}/robot/pool"
          display_result 2>/dev/null
        else
          no_key_no_secret
        fi
      else
        no_key_no_secret
      fi
    fi

    ;;

    # configurations

  "4")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        while true; do
          CONFIG_FILES=("${SYS_DIR:?}"/robot/*.config)
          NUM_FILES="${#CONFIG_FILES[@]}"
          # shellcheck disable=SC2128
          WIDTH="$(echo "$CONFIG_FILES" | awk '{print length, $0}' | sort -nr | head -1 | awk '{ print $1 }')"
          WIDTH="$(echo "$WIDTH+11" | bc 2>/dev/null)"

          if [ $NUM_FILES -eq 0 ] &>/dev/null; then
            echo "Error: No config files found in $SYS_DIR/robot"
            exit 1
          fi

          OPTIONS=()
          for ((i = 0; i < "$NUM_FILES"; i++)); do
            OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
          done

          if [[ "$NUM_FILES" -lt "6" ]] &>/dev/null; then
            NUM_FILES="4"
          fi

          CHOICE=$(dialog --clear --title "Strategy Menu" --menu "Choose one of the following strategy configurations:" "$(echo "$NUM_FILES+3" | bc 2>/dev/null)" "$WIDTH" 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)

          if [ -n "$CHOICE" ]; then
            SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
            nano "$SELECTED_FILE"
            break
          else
            break
          fi
        done
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

    # create strategies

  "5")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        HEIGHT=10
        WIDTH=45
        CHOICE_HEIGHT=4
        BACKTITLE="Leeloo (Multipass)"
        TITLE="Create strategies"
        MENU="Multipass $DATE"

        OPTIONS=(1 "BST              Buy/Sell trigger"
          2 "EMA              EMA trading"
          3 "RSI              RSI trading")

        CHOICE=$(dialog --clear \
          --backtitle "$BACKTITLE" \
          --title "$TITLE" \
          --menu "$MENU" \
          $HEIGHT $WIDTH $CHOICE_HEIGHT \
          "${OPTIONS[@]}" \
          2>&1 >/dev/tty)

        clear
        case $CHOICE in

        "1")

          cp "${HOME_DIR:?}"/leeloo/include/strategies/buy_sell_config "${LOG_DIR:?}"/stgc.tmp &>/dev/null
          cp "${HOME_DIR:?}"/leeloo/include/strategies/buy_sell_strategy "${LOG_DIR:?}"/stgt.tmp &>/dev/null
          nano "${LOG_DIR:?}"/stgc.tmp

          DIALOG_OPTIONS=(
            --backtitle "Leeloo (Multipass)"
            --title "Creating Buy/Sell strategy"
            --yesno "Install new strategy?"
            0 0
          )

          dialog "${DIALOG_OPTIONS[@]}"
          DIALOG_RESULT=$?

          if [ $DIALOG_RESULT -eq "0" ] &>/dev/null; then
            # installing strategy

            display_result() {
              dialog --title "Creating Buy/Sell strategy" \
                --no-collapse \
                --msgbox "$RESULT" 0 0
            }

            # create strategy.robot_id
            ROBOT_CONFIG="$(egrep "STRATEGY_NAME|TYPE|COOLDOWN|MARKET_LIMIT|REFERENCE_STATUS|LISTING_CURRENCY|REFERENCE_CURRENCY" "${LOG_DIR:?}"/stgc.tmp | head -6 | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '".' | xargs | tr -d ' ')"
            # install new strategy.robot_id
            mv "${LOG_DIR:?}"/stgc.tmp "${SYS_DIR:?}"/robot/"$ROBOT_CONFIG".config
            mv "${LOG_DIR:?}"/stgt.tmp "${SYS_DIR:?}"/robot/"$ROBOT_CONFIG".strategy

            RESULT="$ROBOT_CONFIG strategy installed!
$(ls -lSah "${SYS_DIR:?}"/robot* 2>/dev/null | column -t)"
            display_result 2>/dev/null
          else
            # not installing strategy
            rm "${LOG_DIR:?}"/stgc.tmp &>/dev/null
            rm "${LOG_DIR:?}"/stgt.tmp &>/dev/null
          fi

          ;;

        "2")

          cp "${HOME_DIR:?}"/leeloo/include/strategies/ema_config "${LOG_DIR:?}"/stgc.tmp &>/dev/null
          cp "${HOME_DIR:?}"/leeloo/include/strategies/ema_strategy "${LOG_DIR:?}"/stgt.tmp &>/dev/null
          nano "${LOG_DIR:?}"/stgc.tmp

          DIALOG_OPTIONS=(
            --backtitle "Leeloo (Multipass)"
            --title "Creating EMA strategy"
            --yesno "Install new strategy?"
            0 0
          )

          dialog "${DIALOG_OPTIONS[@]}"
          DIALOG_RESULT=$?

          if [ $DIALOG_RESULT -eq "0" ] &>/dev/null; then
            # installing strategy

            display_result() {
              dialog --title "Creating EMA strategy" \
                --no-collapse \
                --msgbox "$RESULT" 0 0
            }

            # create strategy.robot_id
            ROBOT_CONFIG="$(egrep "STRATEGY_NAME|EMA_SHORT|EMA_LONG|MARKET_LIMIT|REFERENCE_STATUS|LISTING_CURRENCY|REFERENCE_CURRENCY" "${LOG_DIR:?}"/stgc.tmp | head -6 | awk -F= '{ print $2 }' | awk '{ print $1 }' | tr -d '".' | xargs | tr -d ' ')"
            # install new strategy.robot_id
            mv "${LOG_DIR:?}"/stgc.tmp "${SYS_DIR:?}"/robot/"$ROBOT_CONFIG".config
            mv "${LOG_DIR:?}"/stgt.tmp "${SYS_DIR:?}"/robot/"$ROBOT_CONFIG".strategy

            RESULT="$ROBOT_CONFIG strategy installed!
$(ls -lSah "${SYS_DIR:?}"/robot* 2>/dev/null | column -t)"
            display_result 2>/dev/null
          else
            # not installing strategy
            rm "${LOG_DIR:?}"/stgc.tmp &>/dev/null
            rm "${LOG_DIR:?}"/stgt.tmp &>/dev/null
          fi

          ;;

        "3")

          # code

          ;;

        "4")

          # code

          ;;

        "5")

          # code

          ;;

        esac
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

    # robot controller

  "6")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        HEIGHT=11
        WIDTH=41
        CHOICE_HEIGHT=4
        BACKTITLE="Leeloo (Multipass)"
        TITLE="Robot controller"
        MENU="Choose one option:"

        OPTIONS=(1 "Status           Robot status"
          2 "Start            Start robot"
          3 "Stop             Stop robot"
          4 "Crontab          Linux jobs")

        CHOICE=$(dialog --clear \
          --backtitle "$BACKTITLE" \
          --title "$TITLE" \
          --menu "$MENU" \
          $HEIGHT $WIDTH $CHOICE_HEIGHT \
          "${OPTIONS[@]}" \
          2>&1 >/dev/tty)

        clear
        case $CHOICE in

        "1")

          display_result() {
            dialog --title "Robot status" \
              --no-collapse \
              --msgbox "$RESULT" 0 0
          }

          RESULT="$(screen -list 2>/dev/null)"
          display_result 2>/dev/null

          ;;

        "2")

          bash "${SYS_DIR:?}"/robot/looper

          ;;

        "3")

          screen -S "$(screen -list | grep "leeloo" | awk -F. '{ print $1 }' | head -1 | xargs)".leeloo -p 0 -X quit

          if [[ "$(screen -list | grep "leeloo" | wc -l)" -eq "1" ]] &>/dev/null; then
            killall screen &>/dev/null
          fi

          echo "leeloo line: */1 * * * * bash /usr/local/bin/include/leeloo/robot/looper"
          echo "Remove leeloo line for total stop"
          read -r -p "Press Enter to continue" </dev/tty
          echo
          crontab -e

          ;;

        "4")

          crontab -e

          ;;

        esac
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

  "7")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then
        last_log_robot
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

  "8")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        while true; do
          CONFIG_FILES=("${LOG_DIR:?}"/leeloo/robot.*.log)
          NUM_FILES="${#CONFIG_FILES[@]}"
          # shellcheck disable=SC2128
          WIDTH="$(echo "$CONFIG_FILES" | awk '{print length, $0}' | sort -nr | head -1 | awk '{ print $1 }')"
          WIDTH="$(echo "$WIDTH+11" | bc 2>/dev/null)"

          if [[ "$WIDTH" -lt "25" ]] &>/dev/null; then
            WIDTH="45"
          fi

          if [ $NUM_FILES -eq 0 ] &>/dev/null; then
            echo "Error: No log files found in $LOG_DIR/leeloo"
            exit 1
          fi

          OPTIONS=()
          for ((i = 0; i < "$NUM_FILES"; i++)); do
            OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
          done

          if [[ "$NUM_FILES" -lt "6" ]] &>/dev/null; then
            NUM_FILES="4"
          fi

          CHOICE=$(dialog --clear --title "Robot logs" --menu "Choose one of the following robot logs:" "$(echo "$NUM_FILES+3" | bc 2>/dev/null)" "$WIDTH" 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)

          if [ -n "$CHOICE" ]; then
            SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
            WIDTH="$(echo "$(tail -25 "${SELECTED_FILE:?}" | wc -L | awk '{ print $1 }')+6" | bc 2>/dev/null)"
            if [[ "$WIDTH" -lt "7" ]] &>/dev/null; then
              WIDTH="77"
            fi
            LOG_COUNT="$(wc -l "${SELECTED_FILE:?}" | awk '{ print $1 }')"
            display_result() {
              dialog --title "Robot Log: $LOG_COUNT :: $SELECTED_FILE:" \
                --no-collapse \
                --tailbox "$RESULT" 25 "$WIDTH"
            }
            RESULT="${SELECTED_FILE:?}"
            display_result 2>/dev/null
            break
          else
            break
          fi
        done
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

  "0")

    if [[ ! -z "$API_SOUTHX_KEY" ]] &>/dev/null; then
      if [[ ! -z "$API_SOUTHX_SECRET" ]] &>/dev/null; then

        if dialog --stdout --title "DELETE WARNING!" \
          --backtitle "DELETING" \
          --yesno "Yes: Delete!, No:  Go back!" 5 30; then

          while true; do
            CONFIG_FILES=("${SYS_DIR:?}"/robot/*.config)
            NUM_FILES="${#CONFIG_FILES[@]}"
            # shellcheck disable=SC2128
            WIDTH="$(echo "$CONFIG_FILES" | awk '{print length, $0}' | sort -nr | head -1 | awk '{ print $1 }')"
            WIDTH="$(echo "$WIDTH+11" | bc 2>/dev/null)"

            if [ $NUM_FILES -eq 0 ] &>/dev/null; then
              echo "Error: No config files found in $SYS_DIR/robot"
              exit 1
            fi

            OPTIONS=()
            for ((i = 0; i < "$NUM_FILES"; i++)); do
              OPTIONS+=("$((i + 1))" "${CONFIG_FILES[$i]}")
            done

            if [[ "$NUM_FILES" -lt "6" ]] &>/dev/null; then
              NUM_FILES="4"
            fi

            CHOICE=$(dialog --clear --title "Delete Strategy Menu" --menu "Choose one of the following strategy configurations:" "$(echo "$NUM_FILES+3" | bc 2>/dev/null)" "$WIDTH" 0 "${OPTIONS[@]}" 2>&1 >/dev/tty)

            if [ -n "$CHOICE" ] &>/dev/null; then
              SELECTED_FILE="${CONFIG_FILES[$((CHOICE - 1))]}"
              FILE_NAME="$(echo "$SELECTED_FILE" | awk -F. '{ print $1 }' | awk -F/ '{ print $NF }')"
              rm "$SELECTED_FILE" &>/dev/null
              rm "${SYS_DIR:?}"/robot/"$FILE_NAME".* &>/dev/null
              rm "${LOG_DIR:?}"/leeloo/robot."$FILE_NAME".* &>/dev/null
              break
            else
              break
            fi
          done
        fi
      else
        no_key_no_secret
      fi
    else
      no_key_no_secret
    fi

    ;;

  esac

  ;;

"D")

  if [[ "$(echo "$BTC_DNT_ADDR" | egrep "bc1.*.c2" | wc -l)" -eq "0" ]] &>/dev/null; then
    echo "grifters are a plague.."
    exit
  fi

  HEIGHT=9
  WIDTH=42
  CHOICE_HEIGHT=3
  BACKTITLE="Leeloo (Multipass)"
  TITLE="Donation"
  MENU="Choose one option:"

  OPTIONS=(1 "Address          Plain Text"
    2 "QRCODE           QRCODE address")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  "1")

    display_result() {
      dialog --title "Donation" \
        --no-collapse \
        --msgbox "$RESULT" 7 77
    }

    RESULT="$(
      echo "Bitcoin (BTC): $BTC_DNT_ADDR

$BTC_MEMPOOL"
    )"
    display_result 2>/dev/null

    if dialog --stdout --title "Save information?" \
      --backtitle "Donate information" \
      --yesno "Yes: Save!, No:  Go back!" 5 30; then

      echo "Bitcoin (BTC): $BTC_DNT_ADDR

$BTC_MEMPOOL" >/home/"$(whoami)"/donate 2>/dev/null

      display_result() {
        dialog --title "BTC Donation" \
          --no-collapse \
          --msgbox "$RESULT" 5 37
      }

      RESULT="$(echo "info saved: /home/$(whoami)/donate")"
      display_result 2>/dev/null
    fi

    ;;

  "2")

    if ! [ -x "$(command -v "qrcode-terminal")" ] &>/dev/null; then
      if dialog --stdout --title "QRCODE" \
        --backtitle "Install" \
        --yesno "Install QRCode-Terminal?" 5 29; then
        # install npm
        if ! [ -x "$(command -v "npm")" ] &>/dev/null; then
          sudo apt-get install npm -y
        fi
        # https://github.com/vercel/install-node
        if ! [ -x "$(command -v "node")" ] &>/dev/null; then
          sudo curl -s https://install-node.now.sh | bash -s --
        fi
        # https://github.com/gtanner/qrcode-terminal
        sudo npm install -g qrcode-terminal
      fi
    fi

    # if non existing, continue
    if [[ ! -f "${LOG_DIR:?}"/leeloo/donate_qr ]] &>/dev/null; then
      qrcode-terminal "$BTC_DNT_ADDR" "{small: true}" >"${LOG_DIR:?}"/leeloo/donate_qr 2>/dev/null
    # if empty, continue
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/donate_qr ]] &>/dev/null; then
      qrcode-terminal "$BTC_DNT_ADDR" "{small: true}" >"${LOG_DIR:?}"/leeloo/donate_qr 2>/dev/null
    fi

    clear
    echo "Bitcoin (BTC): $BTC_DNT_ADDR"
    BTC_DNT_ADDR_QR="$(cat "${LOG_DIR:?}"/leeloo/donate_qr 2>/dev/null)"
    echo "$BTC_DNT_ADDR_QR"
    read -r -p "Press Enter to continue" </dev/tty
    echo

    ;;

  esac

  ;;

"C")

  if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.client ]] &>/dev/null; then
    echo "$(irssi -v 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/irc.client
  fi
  if [[ ! -f "${LOG_DIR:?}"/leeloo/tor.client ]] &>/dev/null; then
    echo "$(tor --version 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/tor.client
  fi

  IRSSI_RAW="$(cat "${LOG_DIR:?}"/leeloo/irc.client 2>/dev/null)"
  PROXY_TOR="$(cat "${LOG_DIR:?}"/leeloo/tor.client 2>/dev/null)"

  if [[ -z "$PROXY_TOR" ]] &>/dev/null; then
    PROXY_TOR="?"
  fi

  if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
    PROXY_CHAT_STATUS="Enabled"
  else
    PROXY_CHAT_STATUS="Disabled"
  fi

  HEIGHT=10
  WIDTH=42
  CHOICE_HEIGHT=3
  BACKTITLE="Leeloo (Multipass)"
  TITLE="IRC Chat"
  MENU="Choose one option:"

  OPTIONS=(1 "Chat             Internet Relay"
    2 "Servers          IRC Servers"
    3 "Information      IRC Status")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  "1")

    # irc chat
    display_result() {
      dialog --title "IRC Chat (irssi)" \
        --no-collapse \
        --msgbox "$RESULT" 13 38
    }

    IRSSI_NAME="$(echo "$IRSSI_RAW" 2>/dev/null | awk '{ print $1 }')"
    IRSSI_VERSION="$(echo "$IRSSI_RAW" 2>/dev/null | awk '{ print $2 }')"
    IRSSI_VERSION_DATE="$(echo "$IRSSI_RAW" 2>/dev/null | awk '{ print $3,$NF }')"
    IRSSI_VERSION="$IRSSI_NAME $IRSSI_VERSION"

    if [[ -z "$IRSSI_RAW" ]] &>/dev/null; then
      IRSSI_VERSION="Not installed"
      IRSSI_VERSION_DATE="?"
    fi

    # if all empty, connect something
    if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
      TRIGGER_NICK="1"
    fi
    if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
      TRIGGER_PORT="1"
    fi
    if [[ -z "$IRSSI_SERVER" ]] &>/dev/null; then
      TRIGGER_SERVER="1"
    fi

    # all triggers accounted for, continue
    if [[ "$(echo "$TRIGGER_NICK+$TRIGGER_PORT+$TRIGGER_SERVER" | bc 2>/dev/null)" -eq "3" ]] &>/dev/null; then
      IRSSI_PORTS=(6661 6662 6663 6664 6665 6666 6667 6668 6669 6697 7000 8000)
      IRSSI_INDEX="$((RANDOM % ${#IRSSI_PORTS[@]}))"
      IRSSI_PORT="${IRSSI_PORTS[$IRSSI_INDEX]}"
      if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.servers ]] &>/dev/null; then
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
          torify curl -s https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers
        else
          curl -s https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers
        fi
      fi
      # random irc server
      IRSSI_SERVER="$(cat "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null | sort -R | head -1)"
      IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
    fi

    # default port
    if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
      IRSSI_PORT="6667"
    fi
    # default random nickname
    if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
      IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
    fi

    RESULT="$(echo "
Client...: $IRSSI_VERSION
Version..: $IRSSI_VERSION_DATE
Server...: $IRSSI_SERVER $IRSSI_PORT
Nick.....: $IRSSI_NICKNAME
Proxy....: $PROXY_CHAT_STATUS
Version..: $PROXY_TOR

COMMANDS.: /help")"
    display_result 2>/dev/null

    if ! [ -x "$(command -v irssi)" ] &>/dev/null; then
      START_INSTALL="Install"
      WIDTH="28"
    else
      START_INSTALL="Start"
      WIDTH="26"
    fi

    if dialog --stdout --title "${START_INSTALL:?} IRC Client?" \
      --backtitle "Starting client" \
      --yesno "Yes: ${START_INSTALL:?}!, No: Quit" 5 "$WIDTH"; then

      if ! [ -x "$(command -v irssi)" ] &>/dev/null; then
        sudo apt-get install irssi
      fi

      if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
        torify irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
      else
        irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
      fi
    fi

    ;;

  "2")

    nano "${LOG_DIR:?}"/leeloo/irc.servers

    ;;

  "3")

    display_result() {
      dialog --title "IRC Chat" \
        --no-collapse \
        --msgbox "$RESULT" 10 55
    }

    RESULT="Chat information

Client..: $IRSSI_RAW
Proxy...: $PROXY_CHAT_STATUS $PROXY_TOR
Servers.: $(wc -l "${LOG_DIR:?}"/leeloo/irc.servers | awk '{ print $1 }')"
    display_result 2>/dev/null

    ;;

  esac

  ;;

"0")

  echo "Exiting..."
  exit 0

  ;;

esac

# shellcheck disable=SC2093 # dialog exec
exec /bin/bash "$0" "$@"
clear

# END
