### SouthXchange ###############################################################

# Key & Secret
API_SOUTHX_KEY=""    # Your API key
API_SOUTHX_SECRET="" # Your API secret

################################################################################

BOT_TIMER="30"                          # loop timer in seconds
BST_TIMER="60"                          # BST data timer
EMA_TIMER="120"                         # EMA data timer
LOG_DIR="/tmp"                          # data folder (leeloo)
SYS_DIR="/usr/local/bin/include/leeloo" # system folder

################################################################################

IRSSI_PORT=""
IRSSI_SERVER=""
IRSSI_NICKNAME=""

################################################################################

MAX_LOG="25000" # log lines
