#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf
source include/api/southxchange/private_API
source include/api/southxchange/public_API
source include/install

# menu
HEIGHT=16
WIDTH=45
CHOICE_HEIGHT=9
BACKTITLE="Leeloo (Multipass)"
TITLE="Main Menu"
MENU="Multipass $(date | xargs)"

OPTIONS=(1 "Balance          Account Balance"
  2 "Market           View Market"
  3 "Search           Search Market"
  4 "Order            Buy/Sell order"
  0 "Quit             Exit Menu")

CHOICE=$(dialog --clear \
  --nocancel \
  --backtitle "$BACKTITLE" \
  --title "$TITLE" \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in

"1")

  function result_jq() {
    listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  }

  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)))" 2>/dev/null)" -gt "15" ]] &>/dev/null; then
    result_jq
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
  fi

  sleep 1

  display_result() {
    dialog --title "Account Balance" \
      --no-collapse \
      --msgbox "$RESULT" 0 0
  }

  RESULT="Currency: Deposited Available Unconfirmed

$(cat "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)"
  display_result 2>/dev/null

  ;;

"2")

  MARKET_SEARCH="$(echo "$MARKET_INPUT" | tr '[:lower:]' '[:upper:]')"
  MARKET_RESULT="$(prices | grep "$MARKET_SEARCH" | sort -k2 -n -r)"
  MARKET_COUNT="$(echo "$MARKET_RESULT" | grep -c "$MARKET_INPUT")"

  display_result() {
    dialog --title "Search result: $MARKET_COUNT" \
      --no-collapse \
      --msgbox "$RESULT" 20 80
  }

  RESULT="Market:    Bid      Ask       Last      Variation (%)      Volume (crypto)

$MARKET_RESULT"
  display_result 2>/dev/null

  ;;

"3")

  # market (example)
  MARKET_INPUT=$(
    dialog --title "Market (BTC/USDT) (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )

  if [[ ! -z "$MARKET_INPUT" ]] &>/dev/null; then

    MARKET_SEARCH="$(echo "$MARKET_INPUT" | tr '[:lower:]' '[:upper:]')"
    MARKET_RESULT="$(prices | grep "$MARKET_SEARCH" | sort -k2 -n -r)"
    MARKET_COUNT="$(echo "$MARKET_RESULT" | wc -l)"

    display_result() {
      dialog --title "Search result: $MARKET_COUNT" \
        --no-collapse \
        --msgbox "$RESULT" 20 80
    }

    RESULT="Market:    Bid      Ask       Last      Variation (%)      Volume (crypto)

$MARKET_RESULT"
    display_result 2>/dev/null
  else
    display_result() {
      dialog --title "Search result: empty!" \
        --no-collapse \
        --msgbox "$RESULT" 0 0
    }

    RESULT="No data found!"
    display_result 2>/dev/null
  fi

  ;;

"4")

  function setup_order {
    LISTING_CURRENCY=$(
      dialog --title "Listing Currency (BTC)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
    REFERENCE_CURRENCY=$(
      dialog --title "Reference Currency (USDT)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
    AMOUNT=$(
      dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
        --inputbox "Enter amount:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
  }

  function setup_ref_order {
    LISTING_CURRENCY=$(
      dialog --title "Listing Currency (BTC)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
    REFERENCE_CURRENCY=$(
      dialog --title "Reference Currency (USDT)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
    AMOUNT=$(
      dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
        --inputbox "Enter amount:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
    PRICE=$(
      dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
        --inputbox "Enter amount:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
  }

  function last_log {
    display_result() {
      dialog --title "Log Message:" \
        --no-collapse \
        --msgbox "$RESULT" 0 0
    }
    RESULT="$(tail -1 "${LOG_DIR:?}"/leeloo/broker.log)"
    display_result 2>/dev/null
  }

  # order menu
  HEIGHT=10
  WIDTH=40
  CHOICE_HEIGHT=3
  BACKTITLE="Leeloo (Multipass)"
  TITLE="Order Menu"
  MENU="$(date | xargs)"

  OPTIONS=(1 "Buy              Buy Order"
    2 "Sell             Sell Order"
    3 "Orders           List Orders")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  "1")

    TYPE="buy"
    HEIGHT=9
    WIDTH=23
    CHOICE_HEIGHT=2
    BACKTITLE="Leeloo (Multipass)"
    TITLE="Buy Order Menu"
    MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

    OPTIONS=(
      1 "Market Order"
      2 "Limit Order")

    CHOICE=$(dialog --clear \
      --backtitle "$BACKTITLE" \
      --title "$TITLE" \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      2>&1 >/dev/tty)

    clear
    case $CHOICE in

    "1")

      LIMIT_ORDER="false"

      setup_order
      placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$LIMIT_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
      last_log

      ;;

    "2")

      LIMIT_ORDER="true"

      setup_ref_order
      placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$LIMIT_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
      last_log

      ;;

    esac

    ;;

  "2")

    TYPE="sell"
    HEIGHT=9
    WIDTH=23
    CHOICE_HEIGHT=2
    BACKTITLE="Leeloo (Multipass)"
    TITLE="Sell Order Menu"
    MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

    OPTIONS=(
      1 "Market Order"
      2 "Limit Order")

    CHOICE=$(dialog --clear \
      --backtitle "$BACKTITLE" \
      --title "$TITLE" \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      2>&1 >/dev/tty)

    clear
    case $CHOICE in

    "1")

      LIMIT_ORDER="false"

      setup_order
      placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$LIMIT_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
      last_log

      ;;

    "2")

      LIMIT_ORDER="true"

      setup_ref_order
      placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$LIMIT_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
      last_log

      ;;

    esac

    ;;

  "3")

    display_result() {
      dialog --title "Orders:" \
        --no-collapse \
        --msgbox "$RESULT" 0 0
    }

    RESULT="$(listOrders)"
    display_result 2>/dev/null

    ;;

  esac

  ;;

"0")

  echo "Exiting..."
  exit 0

  ;;

esac

# shellcheck disable=SC2093 # dialog exec
exec /bin/bash "$0" "$@"
clear

# END
