#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# returnBalances ###############################################################
# https://poloniex.com/tradingApi
# Return balances for all currencies. Permission required: Return Balances

function returnBalances {
  API_NONCE=$(date +%s%N)
  DATA="command=returnBalances&nonce=$API_NONCE"
  SIGNATURE=$(echo -n "$DATA" | openssl dgst -sha512 -hmac "$API_POLONIEX_SECRET" | awk '{print $NF}')
  URL="https://api.poloniex.com/tradingApi"
  curl -s -X POST -d "$DATA" -H "Key: $API_POLONIEX_KEY" -H "Sign: $SIGNATURE" -H "Content-Type: application/x-www-form-urlencoded" "$URL"
}

# END
