#!/bin/bash

# getPrices ####################################################################
# https://poloniex.com/public
# Example: getPrices

function getPrices {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    torify curl -s -X GET "https://api.poloniex.com/markets/ticker24h" -H "accept: application/json" | jq -r '.[] | "\(.symbol): \(.bid) \(.ask) \(.markPrice) \(.dailyChange) \(.quantity)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}'
  else
    curl -s -X GET "https://api.poloniex.com/markets/ticker24h" -H "accept: application/json" | jq -r '.[] | "\(.symbol): \(.bid) \(.ask) \(.markPrice) \(.dailyChange) \(.quantity)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}'
  fi
}

# END
