#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

get_rsi() {
  PERIOD=$1
  SYMBOL=$2
  API_RSI_EXCHANGE="CCCAGG"
  TMP_FILE=$(mktemp)
  torify curl -s "https://min-api.cryptocompare.com/data/v2/histoday?fsym=${SYMBOL}&tsym=USD&limit=$((PERIOD + 1))&aggregate=1&e=${API_RSI_EXCHANGE}" >"$TMP_FILE"
  PRICES=$(jq -r '.Data.Data[].close' "$TMP_FILE")
  CHANGE=$(echo "$PRICES" | awk '{if (NR>1) {print $1-prev} ; prev=$1 }' | tail -n+2)
  UP=$(echo "$CHANGE" | awk '{if ($1>=0) sum+= $1} END {printf "%.8f", sum}')
  DOWN=$(echo "$CHANGE" | awk '{if ($1<0) sum+= -$1} END {printf "%.8f", sum}')
  RS=$(echo "$UP/$DOWN" | bc -l)
  RSI=$(echo "100 - (100/(1+$RS))" | bc -l)
  if (($(echo "$RSI > 70" | bc -l))); then
    BEAR_BULL="Overbought"
  elif (($(echo "$RSI < 30" | bc -l))); then
    BEAR_BULL="Oversold"
  else
    BEAR_BULL="Neutral"
  fi
  printf "$SYMBOL %s :: RSI: %.2f :: %d\n" "$BEAR_BULL" "$RSI" "$PERIOD"
  rm "$TMP_FILE"
}

# END
