#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# tickers ######################################################################
# https://api.nonkyc.io/api/v2/tickers
# Example: tickers

function tickers_nky {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.nonkyc.io/api/v2/tickers" -H "accept: application/json" | jq -r '.[]? | "\(.ticker_id): \(.bid) \(.ask) \(.last_price) \(.change_percent) \(.usd_volume_est)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}' 2>/dev/null
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.nonkyc.io/api/v2/tickers" -H "accept: application/json" | jq -r '.[]? | "\(.ticker_id): \(.bid) \(.ask) \(.last_price) \(.change_percent) \(.usd_volume_est)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}' 2>/dev/null
  fi
}

# getlist ######################################################################
# https://api.nonkyc.io/api/v2/market/getlist
# Example: getlist

function getlist_nky {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.nonkyc.io/api/v2/market/getlist" -H "accept: application/json" | jq -r '.[]? | "\(.symbol): \(.quantityDecimals) \(.spreadPercentNumber)"' 2>/dev/null
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.nonkyc.io/api/v2/market/getlist" -H "accept: application/json" | jq -r '.[]? | "\(.symbol): \(.quantityDecimals) \(.spreadPercentNumber)"' 2>/dev/null
  fi
}

# getbyticker ##################################################################
# https://api.nonkyc.io/api/v2/asset/getbyticker
# Example: getbyticker BTC

function getbyticker_nky {
  SYMBOL="$1"
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.nonkyc.io/api/v2/asset/getbyticker/$SYMBOL" -H "accept: application/json" | jq -r 2>/dev/null
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.nonkyc.io/api/v2/asset/getbyticker/$SYMBOL" -H "accept: application/json" | jq -r 2>/dev/null
  fi
}

# END
