#!/bin/bash

# https://www.southxchange.com/api/listBalances
# Lists balances for all currencies. Permission required: List Balances

source /usr/local/bin/include/leeloo/broker.conf

function listBalances {
  API_SOUTHX_NONCE="$(date +%s)"
  # construct JSON data string
  JSON_DATA=$(
    cat <<EOF
      {
        "nonce": "$API_SOUTHX_NONCE",
        "key": "$API_SOUTHX_KEY"
      }
EOF
  )
  # API url
  API_SOUTHX_BALANCES="https://www.southxchange.com/api/listBalances"
  # calculate HMAC-SHA512 hash
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  # send API request
  RESULT="$(curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" "$API_SOUTHX_BALANCES")"
  # result_jq function
  function result_jq() {
    echo "$RESULT" | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  }
  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)))" 2>/dev/null)" -gt "15" ]] &>/dev/null; then
    result_jq
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
  fi

  sleep 1
}
