#!/bin/bash

# https://www.southxchange.com/api/listBalances
# Lists balances for all currencies. Permission required: List Balances

source /usr/local/bin/include/leeloo/broker.conf

function listBalances {
  API_SOUTHX_NONCE="$(date +%s)"
  # construct JSON data string
  JSON_DATA=$(
    cat <<EOF
      {
        "nonce": "$API_SOUTHX_NONCE",
        "key": "$API_SOUTHX_KEY"
      }
EOF
  )
  # API url
  API_SOUTHX_BALANCES="https://www.southxchange.com/api/listBalances"
  # calculate HMAC-SHA512 hash
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  # send API request
  RESULT="$(curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" $API_SOUTHX_BALANCES)"
  echo "$RESULT" >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
}
