#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# listBalances #################################################################
# https://www.southxchange.com/api/listBalances
# Lists balances for all currencies. Permission required: List Balances

function listBalances {
  API_BALANCES_TIMER="30"
  if [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    touch "${LOG_DIR:?}"/leeloo/southxchange/balances &>/dev/null
    API_BALANCES_TIMER="0"
    sleep 1
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    API_BALANCES_TIMER="0"
    sleep 1
  fi
  TMP_FILE=$(mktemp)
  API_BALANCES_SECONDS="$(stat -c '%Y' "${LOG_DIR:?}"/leeloo/southxchange/balances | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  if [[ "$API_BALANCES_SECONDS" -gt "$API_BALANCES_TIMER" ]] &>/dev/null; then
    API_SOUTHX_NONCE=$(($(date +%s) * 10))
    JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"key\":\"$API_SOUTHX_KEY\"}"
    HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
    curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/listBalances >"$TMP_FILE"
    echo "$TMP_FILE"
  else
    cat "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  fi
}

# placeOrder_market ############################################################
# https://www.southxchange.com/api/placeOrder
# Places an order in a given market. Permission required: Place Order
# Example: placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT"

function placeOrder_market {
  TYPE="$1"
  LISTING_CURRENCY="$2"
  REFERENCE_CURRENCY="$3"
  AMOUNT="$4"
  AMOUNT_IN_REFERENCE_CURRENCY="$5"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"listingCurrency\":\"$LISTING_CURRENCY\",\"referenceCurrency\":\"$REFERENCE_CURRENCY\",\"type\":\"$TYPE\",\"amount\":\"$AMOUNT\",\"amountInReferenceCurrency\":\"$AMOUNT_IN_REFERENCE_CURRENCY\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/placeOrder
}

# placeOrder_limit #############################################################
# https://www.southxchange.com/api/placeOrder
# Places an order in a given market. Permission required: Place Order
# Example: placeOrder "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT"

function placeOrder_limit {
  TYPE="$1"
  LISTING_CURRENCY="$2"
  REFERENCE_CURRENCY="$3"
  PRICE="$4"
  AMOUNT="$5"
  AMOUNT_IN_REFERENCE_CURRENCY="$6"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"listingCurrency\":\"$LISTING_CURRENCY\",\"referenceCurrency\":\"$REFERENCE_CURRENCY\",\"type\":\"$TYPE\",\"amount\":\"$AMOUNT\",\"amountInReferenceCurrency\":\"$AMOUNT_IN_REFERENCE_CURRENCY\",\"limitPrice\":\"$PRICE\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/placeOrder
}

# cancelOrder ##################################################################
# https://www.southxchange.com/api/cancelOrder
# Cancels a given order. Permission required: Cancel Order
# Example: cancelOrder "$ORDER_ID"

function cancelOrder {
  ORDER_ID="$1"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"orderCode\":\"$ORDER_ID\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/cancelOrder
}

# cancelMarketOrders ###########################################################
# https://www.southxchange.com/api/cancelMarketOrders
# Cancels all orders in a given market. Permission required: Cancel Order
# Example: cancelMarketOrders "$LISTING_CURRENCY" "$REFERENCE_CURRENCY"

function cancelMarketOrders() {
  LISTING_CURRENCY="$1"
  REFERENCE_CURRENCY="$2"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"listingCurrency\":\"$LISTING_CURRENCY\",\"referenceCurrency\":\"$REFERENCE_CURRENCY\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/cancelMarketOrders
}

# listOrders ####################################################################
# https://www.southxchange.com/api/listOrders
# Lists your open orders. Permission required: List Orders
# Example: listOrders "$LISTING_CURRENCY" "$REFERENCE_CURRENCY"

function listOrders {
  LISTING_CURRENCY="$1"
  REFERENCE_CURRENCY="$2"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"listingCurrency\":\"$LISTING_CURRENCY\",\"referenceCurrency\":\"$REFERENCE_CURRENCY\",\"key\":\"$API_SOUTHX_KEY\",\"Code\":\"\",\"Type\":\"\",\"Amount\":0,\"OriginalAmount\":0,\"LimitPrice\":0,\"ListingCurrency\":\"\",\"ReferenceCurrency\":\"\",\"DateAdded\":\"\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" -X POST https://www.southxchange.com/api/listOrders
}

# getOrder #####################################################################
# https://www.southxchange.com/api/getOrder
# Gets a given order. Permission required: List Orders
# Example: getOrder "$ORDER_CODE"

function getOrder {
  ORDER_CODE="$1"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"code\":\"$ORDER_CODE\",\"nonce\":\"$API_SOUTHX_NONCE\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/getOrder
}

# getOrders ####################################################################
# https://www.southxchange.com/api/getOrders
# Gets a list of your executed orders. Permission required: List Orders
# Example: getOrders "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" 10

function getOrders {
  CODES="$1"
  PAGE_INDEX="$2"
  PAGE_SIZE="$3"
  API_SOUTHX_NONCE=$(date +%s)
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"codes\":[\"$CODES\"],\"pageIndex\":\"$PAGE_INDEX\",\"pageSize\":$PAGE_SIZE,\"key\":\"$API_SOUTHX_KEY\",\"pageCount\":true}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" -X POST https://www.southxchange.com/api/getOrders
}

# generateNewAddress ###########################################################
# https://www.southxchange.com/api/generateNewAddress
# Generates a new address for a given cryptocurrency. Permission required: Generate New Address
# Example generateNewAddress "$CURRENCY"

function generateNewAddress() {
  CURRENCY="$1"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"currency\":\"$CURRENCY\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/generateNewAddress
}

# listAddresses ################################################################
# https://www.southxchange.com/api/listAddresses
# Lists addresses of a given currency. Permission required: Generate New Address
# Example: listAddresses "$CURRENCY" 1 50, list the first 50 "$CURRENCY" addresses.

function listAddresses {
  CURRENCY="$1"
  PAGE_INDEX="$2"
  PAGE_SIZE="$3"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"currency\":\"$CURRENCY\",\"pageIndex\":$PAGE_INDEX,\"pageSize\":$PAGE_SIZE,\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/listAddresses
}

# getLNInvoice #################################################################
# https://www.southxchange.com/api/getLNInvoice
# Generates a new Lightning Network invoice for a given cryptocurrency. Permission required: Generate New Address
# Example: getLNInvoice "$CURRENCY" "$AMOUNT"

function getLNInvoice {
  CURRENCY="$1"
  AMOUNT="$2"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"currency\":\"$CURRENCY\",\"amount\":$AMOUNT,\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/getLNInvoice
}

# withdraw #####################################################################
# https://www.southxchange.com/api/withdraw
# Withdraws to a given address. Permission required: Withdraw
# Example: withdraw "$CURRENCY" 0 "$AMOUNT"

function withdraw {
  CURRENCY="$1"
  DESTINATION="$2"
  DESTINATION_TYPE="$3"
  AMOUNT="$4"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"currency\":\"$CURRENCY\",\"destination\":\"$DESTINATION\",\"destinationType\":$DESTINATION_TYPE,\"amount\":$AMOUNT,\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/withdraw
}

# listTransactions #############################################################
# https://www.southxchange.com/api/listTransactions
# List all transactions. Permission required: List Balances
# Example: listTransactions "$CURRENCY" deposits "" 1 50 "" false

function listTransactions {
  CURRENCY="$1"
  TRANSACTION_TYPE="$2"
  OPTIONAL_FILTER="$3"
  PAGE_INDEX="$4"
  PAGE_SIZE="$5"
  SORT_FIELD="$6"
  DESCENDING="$7"
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"currency\":\"$CURRENCY\",\"transactionType\":\"$TRANSACTION_TYPE\",\"optionalFilter\":\"$OPTIONAL_FILTER\",\"pageIndex\":$PAGE_INDEX,\"pageSize\":$PAGE_SIZE,\"sortField\":\"$SORT_FIELD\",\"descending\":$DESCENDING,\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/listTransactions
}

# getUserInfo ##################################################################
# https://www.southxchange.com/api/getUserInfo
# Gets user information. Permission required: Get info
# Example: getUserInfo

function getUserInfo {
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"key\":\"$API_SOUTHX_KEY\"}"
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/getUserInfo
}

# END
