#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf

# listBalances #################################################################
# https://www.southxchange.com/api/listBalances
# Lists balances for all currencies. Permission required: List Balances

function listBalances {
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  # construct JSON data string
  JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"key\":\"$API_SOUTHX_KEY\"}"

  function result_jq() {
    # calculate HMAC-SHA512 hash
    HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
    # send API request
    RESULT="$(curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/listBalances)"
    echo "$RESULT" | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  }

  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)))" 2>/dev/null)" -gt "15" ]] &>/dev/null; then
    result_jq
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_jq
  fi

  sleep 1
}

# checkMarket ##################################################################
# Example: checkMarket BTC

function checkMarket {
  local SYMBOL=$1
  local MARKETS
  MARKETS="$(curl -s https://www.southxchange.com/api/markets)"
  if [[ "$(echo "$MARKETS" | grep "$SYMBOL" | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then
    CHECK_MARKETS_MAIN="$(echo "$MARKETS" | tr -d '"' | egrep -o "$SYMBOL,[aA0-zZ9]+" | tr -d '[]' | sed '/^$/d')"
    CHECK_MARKETS_SECOND="$(echo "$MARKETS" | tr -d '"' | egrep -o "[aA0-zZ9]+,$SYMBOL" | tr -d '[]' | sed '/^$/d')"
    CHECK_COUNT_MAIN="$(echo "$CHECK_MARKETS_MAIN" | sed '/^$/d' | wc -l)"
    CHECK_COUNT_SECOND="$(echo "$CHECK_MARKETS_SECOND" | sed '/^$/d' | wc -l)"
    CHECK_COUNT_TOTAL="$(echo "$CHECK_COUNT_MAIN+$CHECK_COUNT_SECOND" | bc)"
    echo "Found $CHECK_COUNT_TOTAL market(s) for $SYMBOL"
    echo "$CHECK_MARKETS_MAIN"
    echo "$CHECK_MARKETS_SECOND"
  else
    echo "No markets found for $SYMBOL"
  fi
}

# placeOrder ###################################################################
# https://www.southxchange.com/api/placeOrder
# Places an order in a given market. Permission required: Place Order
# Example: placeOrder "$TYPE" "$PRICE" "$AMOUNT" "$MARKET" "true"

function placeOrder {
  API_SOUTHX_NONCE=$(($(date +%s) * 10))
  # construct JSON data string
  if [ "$LIMIT_ORDER" = "true" ] &>/dev/null; then
    JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"type\":\"$TYPE\",\"price\":$PRICE,\"amount\":$AMOUNT,\"market\":\"$MARKET\"}"
  else
    JSON_DATA="{\"nonce\":\"$API_SOUTHX_NONCE\",\"type\":\"$TYPE\",\"amount\":$AMOUNT,\"market\":\"$MARKET\"}"
  fi
  # calculate HMAC-SHA512 hash
  HASH=$(echo -n "$JSON_DATA" | openssl sha512 -hmac "$API_SOUTHX_SECRET" | awk '{print $NF}')
  # send API request
  RESULT="$(curl -s -H "Hash: $HASH" -H "Content-Type: application/json" -d "$JSON_DATA" https://www.southxchange.com/api/placeOrder)"
}

# END
