#!/bin/bash

# markets ######################################################################
# https://www.southxchange.com/api/markets
# Example: markets BTC

function markets {
  torify curl -s https://www.southxchange.com/api/markets | egrep -o '"[aA0-zZ9]+","[aA0-zZ9]+"' | tr -d '"' | tr "," /
}

# prices #######################################################################
# https://market.southxchange.com/api/v4/prices
# Example: prices

function prices {
  torify curl -s -X GET "https://market.southxchange.com/api/v4/prices" -H "accept: application/json" | jq -r '.[] | "\(.Market): \(.Bid) \(.Ask) \(.Last) \(.Variation24Hr) \(.Volume24Hr)"'
}

# fees #########################################################################
# https://market.southxchange.com/api/v4/fees
# Example: fees

function fees {
  torify curl -X GET "https://market.southxchange.com/api/v4/fees" -H "accept: application/json" | jq -s
}

# END
