#!/bin/bash

# checkMarket ##################################################################
# Example: checkMarket BTC

function checkMarket {
  local MARKET_INPUT=$1
  local MARKET_LIST
  MARKET_LIST="$(curl -s https://www.southxchange.com/api/MARKET_LIST)"
  MARKET_CHECK="$(echo "$MARKET_LIST" | egrep -o '"[aA0-zZ9]+","[aA0-zZ9]+"' | tr -d '"' | tr "," /)"
  MARKET_SEARCH="$(echo "$MARKET_CHECK" | grep -o "$MARKET_INPUT")"
  MARKET_COUNT="$(echo "$MARKET_CHECK" | grep -o "$MARKET_INPUT" | wc -l)"
  if [[ "$MARKET_COUNT" -gt "0" ]] &>/dev/null; then
    echo "Ok found $MARKET_COUNT market(s) for $MARKET_INPUT"
    echo "$MARKET_SEARCH"
  else
    echo "No market(s) found for $MARKET_INPUT"
  fi
}

################################################################################
