#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf

# markets ######################################################################
# https://www.southxchange.com/api/markets
# Example: markets BTC

if [[ "$PUBLIC_API_PROXY" == "true" ]] &>/dev/null; then
  function markets {
    torify curl -s https://www.southxchange.com/api/markets | egrep -o '"[aA0-zZ9]+","[aA0-zZ9]+"' | tr -d '"' | tr "," /
  }
else
  function markets {
    curl -s https://www.southxchange.com/api/markets | egrep -o '"[aA0-zZ9]+","[aA0-zZ9]+"' | tr -d '"' | tr "," /
  }
fi

# prices #######################################################################
# https://market.southxchange.com/api/v4/prices
# Example: prices

if [[ "$PUBLIC_API_PROXY" == "true" ]] &>/dev/null; then
  function prices {
    torify curl -s -X GET "https://market.southxchange.com/api/v4/prices" -H "accept: application/json" | jq -r '.[] | "\(.Market): \(.Bid) \(.Ask) \(.Last) \(.Variation24Hr) \(.Volume24Hr)"'
  }
else
  function prices {
    curl -s -X GET "https://market.southxchange.com/api/v4/prices" -H "accept: application/json" | jq -r '.[] | "\(.Market): \(.Bid) \(.Ask) \(.Last) \(.Variation24Hr) \(.Volume24Hr)"'
  }
fi

# fees #########################################################################
# https://market.southxchange.com/api/v4/fees
# Example: fees

if [[ "$PUBLIC_API_PROXY" == "true" ]] &>/dev/null; then
  function fees {
    torify curl -X GET "https://market.southxchange.com/api/v4/fees" -H "accept: application/json" | jq -s
  }
else
  function fees {
    curl -X GET "https://market.southxchange.com/api/v4/fees" -H "accept: application/json" | jq -s
  }
fi

# END
