#!/bin/bash

# Balances #################################################################
# https://api.xeggex.com/api/v2/balances
# Lists balances for all currencies. Permission required: List Balances

function Balances() {
  curl -s -X GET -H "accept: application/json" -u "$API_XEGGEX_KEY:$API_XEGGEX_SECRET" "https://api.xeggex.com/api/v2/balances"
}
