#!/bin/bash

# tickers ######################################################################
# https://api.xeggex.com/api/v2/tickers
# Example: tickers

function tickers {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.xeggex.com/api/v2/tickers" -H "accept: application/json" | jq -r '.[]? | "\(.ticker_id): \(.bid) \(.ask) \(.last_price) \(.change_percent) \(.usd_volume_est)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}'
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.xeggex.com/api/v2/tickers" -H "accept: application/json" | jq -r '.[]? | "\(.ticker_id): \(.bid) \(.ask) \(.last_price) \(.change_percent) \(.usd_volume_est)"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}'
  fi
}

# getlist ######################################################################
# https://api.xeggex.com/api/v2/market/getlist
# Example: getlist

function getlist {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.xeggex.com/api/v2/market/getlist" -H "accept: application/json" | jq -r '.[]? | "\(.symbol): \(.quantityDecimals) \(.spreadPercentNumber)"'
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.xeggex.com/api/v2/market/getlist" -H "accept: application/json" | jq -r '.[]? | "\(.symbol): \(.quantityDecimals) \(.spreadPercentNumber)"'
  fi
}

# getbyticker ##################################################################
# https://api.xeggex.com/api/v2/asset/getbyticker
# Example: getbyticker BTC

function getbyticker {
  SYMBOL="$1"
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -X GET "https://api.xeggex.com/api/v2/asset/getbyticker/$SYMBOL" -H "accept: application/json" | jq -r
  else
    timeout "${API_TIMEOUT:?}" curl -X GET "https://api.xeggex.com/api/v2/asset/getbyticker/$SYMBOL" -H "accept: application/json" | jq -r
  fi
}

# END
