#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# returnAccount ################################################################
# https://stakecube.io/api/v2/user/account
# Return account balances for all currencies. Permission required: Return Account

function returnAccount {
  API_ENDPOINT="https://stakecube.io/api/v2/user/account"
  API_COUNTER_FILE="${LOG_DIR:?}/leeloo/nonce.count"
  # check if the counter file exists
  if [ -f "$API_COUNTER_FILE" ]; then
    # read the counter value from the file
    API_NONCE_COUNTER=$(cat "$API_COUNTER_FILE")
    # validate the counter value
    if ! [[ "$API_NONCE_COUNTER" =~ ^[0-9]+$ ]]; then
      # counter file contains an invalid value, set a default starting value
      API_NONCE_COUNTER=1
    fi
  else
    # counter file doesn't exit, continue
    API_NONCE_COUNTER=1
  fi
  # counter file zero, continue
  if [[ -z "$API_NONCE_COUNTER" ]]; then
    API_NONCE_COUNTER=1
  fi
  # append counter to the timestamp
  API_NONCE=$(date +%s%N)-${API_NONCE_COUNTER}
  DATA="nonce=${API_NONCE}"
  SIGNATURE=$(echo -n "${DATA}" | openssl dgst -sha256 -hmac "${API_STAKECUBE_SECRET}" | awk '{print $NF}')
  URL="${API_ENDPOINT}?${DATA}&signature=${SIGNATURE}"
  curl -s -H "X-API-KEY: ${API_STAKECUBE_KEY}" "${URL}"
  # increment the nonce counter for the next request
  ((API_NONCE_COUNTER++))
  # write the updated counter value back to the file
  echo "$API_NONCE_COUNTER" >"$API_COUNTER_FILE"
}

# END
