#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# setup_order ##################################################################

function setup_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# setup_limit_order ############################################################

function setup_limit_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  PRICE=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# last_log #####################################################################

function last_log {
  display_result() {
    dialog --title "Log Message: $(wc -l "${LOG_DIR:?}"/leeloo/broker.log)" \
      --no-collapse \
      --tailbox "$RESULT" 30 110
  }
  RESULT="${LOG_DIR:?}/leeloo/broker.log"
  display_result 2>/dev/null
}
