#!/bin/bash

################################################################################

# DISCLAIMER

# All trading activities and any resulting losses are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

## shellcheck ##################################################################

# shellcheck disable=SC2034  # Unused variables left for readability
# shellcheck disable=SC2153  # Already sourced

# system directory #############################################################

SYS_DIR="/usr/local/bin/include/leeloo" # system folder

# log directory ################################################################

if [[ ! -d "${LOG_DIR:?}"/leeloo ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo &>/dev/null
fi

# exchange directory ###########################################################

function install_exchange_dir() {
  # if no directory
  if [[ ! -d "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE" ]] &>/dev/null; then
    mkdir "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE" &>/dev/null
    if [[ ! -d "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET" ]] &>/dev/null; then
      mkdir "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET" &>/dev/null
      if [[ ! -d "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET" ]] &>/dev/null; then
        mkdir "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET" &>/dev/null
      fi
    fi
  fi
}

# date, log date ###############################################################

function system_date() {
  DATE="$(date +"%d.%m.%Y %H:%M:%S")"
}

function log_date() {
  LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"
}

function log_date_xargs() {
  DATE_XARGS="$(date | awk '{ print $1,$2,$3,$4,$5 }' | xargs)"
}

# log timer ####################################################################

if [[ -z "$LOG_LENGTH" ]] &>/dev/null; then
  LOG_LENGTH="7"
fi

LOG_TIMER="$(echo "$LOG_LENGTH+1" | bc 2>/dev/null)" # log schedule, in lines

# erro status ##################################################################

# error status (default)
ERROR_STATUS="0"

if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/error.log 2>/dev/null | awk '{ print $1 }')" -gt "0" ]] &>/dev/null; then
  ERROR_STATUS="$(cat "${LOG_DIR:?}"/leeloo/error.log 2>/dev/null | awk '{ print $1 }' | sed -r '/^\s*$/d' | wc -l)"
fi

if [[ -z "$ERROR_STATUS" ]] &>/dev/null; then
  ERROR_STATUS="0"
fi

# possible update error (interference)
if [[ "$(grep "syntax error near unexpected token" "${LOG_DIR:?}"/leeloo/error.log 2>/dev/null | tr -d '`' | grep -c "(")" -gt "0" ]] &>/dev/null; then
  truncate -s 0 "${LOG_DIR:?}"/leeloo/error.log &>/dev/null
  ERROR_STATUS="!"
fi

# system #######################################################################

function system_load() {
  LOAD="$(cat /proc/loadavg 2>/dev/null | awk '{ print $1,$2,$3 }')"
}

# screen -list #################################################################

function update_screen() {
  # update screen list
  echo "$(screen -list 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/screen
  SCREEN_LIST="$(cat "${LOG_DIR:?}"/leeloo/screen 2>/dev/null)"
}

################################################################################

ERROR_LOG="${LOG_DIR:?}/leeloo/error.log"

################################################################################

function key_secret_set() {

  KEY_SECRET_SET_PLX="0" # poloniex
  KEY_SECRET_SET_SXC="0" # southxchange
  KEY_SECRET_SET_SCE="0" # stakecube
  KEY_SECRET_SET_XGX="0" # xeggex

  ##############################################################################

  # poloniex option
  if [[ -n "$API_POLONIEX_KEY" ]] && [[ -n "$API_POLONIEX_SECRET" ]]; then
    KEY_SECRET_SET_PLX="1"
  fi
  # southxchange option
  if [[ -n "$API_SOUTHX_KEY" ]] && [[ -n "$API_SOUTHX_SECRET" ]]; then
    KEY_SECRET_SET_SXC="1"
  fi
  # stakecube option
  if [[ -n "$API_STAKECUBE_KEY" ]] && [[ -n "$API_STAKECUBE_SECRET" ]]; then
    KEY_SECRET_SET_SCE="1"
  fi
  # xeggex option
  if [[ -n "$API_XEGGEX_KEY" ]] && [[ -n "$API_XEGGEX_SECRET" ]]; then
    KEY_SECRET_SET_XGX="1"
  fi

  ##############################################################################

  # calculate general status
  KEY_SECRET_SET="$(echo "$KEY_SECRET_SET_PLX+$KEY_SECRET_SET_SXC+$KEY_SECRET_SET_SCE+$KEY_SECRET_SET_XGX" | bc 2>/dev/null)"
  # if zero
  if [[ -z "$KEY_SECRET_SET" ]] &>/dev/null; then
    KEY_SECRET_SET="0"
  fi

  # if set
  if [[ "$KEY_SECRET_SET" -gt "0" ]] &>/dev/null; then
    KEY_SECRET_OK="1"
  else
    KEY_SECRET_OK="0"
  fi
}

################################################################################

function broker_conf_update() {
  LEELOO_CONFIG_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/broker.conf | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done | awk '{ SUM += $1} END { print SUM }')"

  # updating broker configuration, restart robots
  if [[ "$LEELOO_CONFIG_SECONDS" -lt "10" ]] &>/dev/null; then
    if [[ "$(echo "$SCREEN_LIST" | grep -c "leeloo")" -gt "0" ]] &>/dev/null; then
      # kill screen
      screen -S "$(echo "$SCREEN_LIST" | grep "leeloo" | awk -F. '{ print $1 }' | head -1 | xargs)".leeloo -p 0 -X quit 2>/dev/null
      # kill leeloo pid (shell)
      echo "$(ps aux 2>/dev/null | grep "leeloo" | grep -v "grep" | grep "bash.*robot/leeloo" | awk '{ print $2 }' | tail -1)" >"${LOG_DIR:?}"/leeloo/ps_aux
      LEELOO_PID="$(cat "${LOG_DIR:?}"/leeloo/ps_aux 2>/dev/null)"
      kill -9 "$LEELOO_PID" &>/dev/null
      bash "${SYS_DIR:?}"/robot/looper
      echo "Robot restarting!" >"${LOG_DIR:?}"/leeloo/updating 2>/dev/null
      display_result() {
        dialog --title "Updating Configuration." \
          --no-collapse \
          --msgbox "$RESULT" 0 0
      }
      RESULT="$(cat "${LOG_DIR:?}"/leeloo/updating 2>/dev/null)"
      display_result 2>/dev/null
    fi
  fi
}

# AGREED #######################################################################

function AGREED() {
  echo "All trading activities and any resulting losses are solely the user's responsibility.
This software is provided without warranties or guarantees, use it at your own risk.
Embrace the chaos, adapt to the shadows, may the odds ever be in your favor."
}

################################################################################

# create if not found
if [[ ! -f "${LOG_DIR:?}"/leeloo/AGREED ]] &>/dev/null; then

  # agreed
  AGREED >"${LOG_DIR:?}"/leeloo/AGREED 2>/dev/null
  echo "$(uname -a | xargs) AGREED at $(date | xargs)." >>"${LOG_DIR:?}"/leeloo/AGREED 2>/dev/null
  sudo cp "${LOG_DIR:?}"/leeloo/AGREED /usr/local/bin &>/dev/null

  display_result() {
    dialog --title "DISCLAIMER" \
      --no-collapse \
      --msgbox "$RESULT" 0 0
  }
  RESULT="$(AGREED)"
  display_result 2>/dev/null
fi

################################################################################

# parasite_check
function parasite_check() {
  history -c &>/dev/null
  echo "Okey parasite."
  sudo shutdown -h now &>/dev/null
  exit
}

################################################################################

if [[ -f /usr/local/bin/broker ]] &>/dev/null; then
  if [[ "$(egrep -c "bc1.*.c2" /usr/local/bin/broker)" -eq "0" ]] &>/dev/null; then
    parasite_check
  elif [[ "$(egrep -c "R2L.*.SXB" /usr/local/bin/broker)" -eq "0" ]] &>/dev/null; then
    parasite_check
  elif [[ "$(egrep -c "650e.*.b1172" /usr/local/bin/broker)" -eq "0" ]] &>/dev/null; then
    parasite_check
  fi
fi

# repo version #################################################################

function repo_head_data() {
  if [[ ! -f "${LOG_DIR:?}"/leeloo/repo ]] &>/dev/null; then
    cd "${HOME_DIR:?}"/leeloo || exit && git rev-parse --short HEAD 2>&1 | grep -Eo '[a0-z9]{7}' 2>&1 | head -1 >"${LOG_DIR:?}"/leeloo/repo 2>/dev/null
    cd "${HOME_DIR:?}"/leeloo || exit && git log -1 --format="%at" | xargs -I{} date -d @{} '+%Y' >>"${LOG_DIR:?}"/leeloo/repo 2>/dev/null
  fi

  REPO_HEAD="$(cat "${LOG_DIR:?}"/leeloo/repo 2>/dev/null | head -1)"
  REPO_DATE="$(cat "${LOG_DIR:?}"/leeloo/repo 2>/dev/null | tail -1)"

  if [[ -z "$REPO_HEAD" ]] &>/dev/null; then
    REPO_HEAD="edit"
    REPO_DATE="config."
  fi
}

# no key no secret #############################################################

function no_key_no_secret() {
  display_result() {
    dialog --title "  No Access" \
      --no-collapse \
      --msgbox "$RESULT" 5 22
  }
  RESULT="$(echo "Need key & secret!")"
  display_result 2>/dev/null
}

# no irssi no access ###########################################################

function no_irssi_no_access() {
  display_result() {
    dialog --title "  No Access" \
      --no-collapse \
      --msgbox "$RESULT" 5 25
  }
  RESULT="$(echo "Client not installed!")"
  display_result 2>/dev/null
}

# exchange balance #############################################################

function exchange_balance() {

  USER_TIMER="$(echo "$BOT_TIMER*1.5" | bc 2>/dev/null | awk -F. '{ print $1 }')"

  ##############################################################################

  install_exchange_dir

  ##############################################################################

  # poloniex
  if [[ "$EXCHANGE_BALANCE" == "poloniex" ]] &>/dev/null; then
    EXCHANGE_API="POL"
    exchange_template
    # get balance
    function result_balances() {
      echo "$(returnBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null
    }
  fi

  ##############################################################################

  # southxchange
  if [[ "$EXCHANGE_BALANCE" == "southxchange" ]] &>/dev/null; then
    EXCHANGE_API="SXC"
    exchange_template
    # get balance
    function result_balances() {
      echo "$(listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null
    }
  fi

  ##############################################################################

  # stakecube
  if [[ "$EXCHANGE_BALANCE" == "stakecube" ]] &>/dev/null; then
    EXCHANGE_API="SCE"
    exchange_template
    # get balance
    function result_balances() {
      echo "$(returnAccount | jq -r '.result.wallets[] | "\(.asset): \(.balance) \(.balanceInOrder) \(.balanceInMasternodes) \(.balanceInInterest)"' 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null
    }
    SCE_NONCE_COUNTER=$(cat "${LOG_DIR:?}"/leeloo/nonce.count 2>/dev/null)
    # if zero
    if [[ -z "$SCE_NONCE_COUNTER" ]] &>/dev/null; then
      SCE_NONCE_COUNTER="0"
    fi
  fi

  ##############################################################################

  # xeggex
  if [[ "$EXCHANGE_BALANCE" == "xeggex" ]] &>/dev/null; then
    EXCHANGE_API="XGX"
    exchange_template
    # get balance
    function result_balances() {
      echo "$(Balances | jq -r '.[] | "\(.asset): \(.held) \(.available) \(.pending)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null
    }
  fi

  ##############################################################################

  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null)))" 2>/dev/null)" -gt "$USER_TIMER" ]] &>/dev/null; then
    result_balances
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances ]] &>/dev/null; then
    result_balances
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances ]] &>/dev/null; then
    result_balances
  fi

  until [[ -f "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances ]] &>/dev/null; do
    clear
    echo "Please wait.."
    sleep 1
  done

  FILE_TIME="$(ls -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null | awk '{ print $8 }')"
  if [[ -z "$FILE_TIME" ]] &>/dev/null; then
    FILE_TIME="00:00"
  fi

  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances | awk '{ print $1 }')" -lt "2" ]] &>/dev/null; then
    LENGTH="5"
    RESULT="No balance"
  else
    # keep lines with n
    RESULT="Coins: Deposited Available Unconfirmed
  $(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}')"
  fi

  # asset count, disregard zeros
  EXCHANGE_ASSETS="$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}' | wc -l)"

  ##############################################################################

  if [[ "$EXCHANGE_BALANCE" == "stakecube" ]] &>/dev/null; then

    RESULT_FORMAT="Coins: Deposited InOrder InMasternodes InInterest
$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null)"

    # if lines are less than n
    if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances | awk '{ print $1 }')" -lt "1" ]] &>/dev/null; then
      WIDTH="$(echo "$(echo "$RESULT_FORMAT" | wc -L)+11" | bc 2>/dev/null)"
      LENGTH="$(echo "$(echo "$RESULT_FORMAT" | wc -l)+4" | bc 2>/dev/null)"
      RESULT="No Balance available"
    else
      WIDTH="$(echo "$(echo "$RESULT_FORMAT" | wc -L)+11" | bc 2>/dev/null)"
      LENGTH="$(echo "$(echo "$RESULT_FORMAT" | wc -l)+4" | bc 2>/dev/null)"
      RESULT="$RESULT_FORMAT"
    fi

    display_result() {
      dialog --title "$FILE_TIME :: +$EXCHANGE_ASSETS :: $EXCHANGE_API Account Balance ($SCE_NONCE_COUNTER)" \
        --no-collapse \
        --msgbox "$(echo "$RESULT" | column -t)" "$LENGTH" "$WIDTH"
    }
  fi

  ##############################################################################

  if [[ "$EXCHANGE_BALANCE" == "poloniex" || "$EXCHANGE_BALANCE" == "southxchange" || "$EXCHANGE_BALANCE" == "xeggex" ]] &>/dev/null; then

    # default
    WIDTH="0"
    LENGTH="0"

    # if no lines has n
    if [[ "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}' | wc -l)" -eq "0" ]] &>/dev/null; then
      WIDTH="45"
      LENGTH="5"
      RESULT="No Balance available"
    fi

    if [[ "$EXCHANGE_BALANCE" == "xeggex" ]] &>/dev/null; then
      # keep lines with n
      RESULT="Coins: Deposited Available Unconfirmed
    $(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}')"
      WIDTH="$(echo "$(echo "$RESULT" | wc -L)-5" | bc 2>/dev/null)"
      LENGTH="$(echo "$(echo "$RESULT" | wc -l)+4" | bc 2>/dev/null)"
    fi

    if [[ "$EXCHANGE_BALANCE" == "southxchange" ]] &>/dev/null; then
      # keep lines with n
      RESULT="Coins: Deposited Available Unconfirmed
    $(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_BALANCE"/balances 2>/dev/null | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}')"
      WIDTH="$(echo "$(echo "$RESULT" | wc -L)+1" | bc 2>/dev/null)"
      LENGTH="$(echo "$(echo "$RESULT" | wc -l)+4" | bc 2>/dev/null)"
    fi

    display_result() {
      dialog --title "$FILE_TIME :: +$EXCHANGE_ASSETS :: $EXCHANGE_API Account Balance" \
        --no-collapse \
        --msgbox "$(echo "$RESULT" | column -t)" "$LENGTH" "$WIDTH"
    }
  fi
  display_result 2>/dev/null
}

# observe markets ##############################################################

function observe_market() {

  # exchanges, includes functions
  source /usr/local/bin/include/leeloo/strategies/templates/exchanges

  ##############################################################################

  install_exchange_dir

  ##############################################################################

  # poloniex prices
  if [[ "$OBSERVE_MARKET" == "poloniex" ]] &>/dev/null; then
    EXCHANGE_API="POL"
    exchange_template
    SUPPORT_WIDTH="+5"
    SUPPORT_LENGTH="5"
    SUPPORT="Support: https://support.poloniex.com"
    function result_prices() {
      echo "$(getPrices | column -t)" >"${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null
    }
  fi

  ##############################################################################

  # southxchange prices
  if [[ "$OBSERVE_MARKET" == "southxchange" ]] &>/dev/null; then
    EXCHANGE_API="SXC"
    exchange_template
    SUPPORT_WIDTH="+4"
    SUPPORT_LENGTH="5"
    SUPPORT="Support: https://southxchange.gorgias.help"
    function result_prices() {
      echo "$(prices | column -t)" >"${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null
    }
  fi

  ##############################################################################

  # stakecube prices
  if [[ "$OBSERVE_MARKET" == "stakecube" ]] &>/dev/null; then
    EXCHANGE_API="SCE"
    exchange_template
    SUPPORT_WIDTH="+5"
    SUPPORT_LENGTH="5"
    SUPPORT_RESULT="Support Mail: support@stakecube.zohodesk.com"
    function result_prices() {
      echo "$(getMarkets | column -t)" >"${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null
    }
  fi

  ##############################################################################

  # xeggex prices
  if [[ "$OBSERVE_MARKET" == "xeggex" ]] &>/dev/null; then
    EXCHANGE_API="XGX"
    exchange_template
    SUPPORT_WIDTH="+5"
    SUPPORT_LENGTH="5"
    SUPPORT_RESULT="Support: https://xeggex.com/account/support"
    function result_prices() {
      echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null
    }
  fi

  ##############################################################################

  # observe markets
  USER_TIMER="$(echo "$BOT_TIMER*3.5" | bc 2>/dev/null | awk -F. '{ print $1 }')"

  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null)))" 2>/dev/null)" -gt "$USER_TIMER" ]] &>/dev/null; then
    result_prices
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices ]] &>/dev/null; then
    result_prices
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices ]] &>/dev/null; then
    result_prices
  fi

  CAT_EXCHANGE_PRICES="$(cat "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null)"

  # 450 max before dialog breaks
  MARKET_RESULT="$(echo "$CAT_EXCHANGE_PRICES" | sort -k2 -n -r 2>/dev/null | head -100)"
  MARKET_COUNT="$(grep -v "Market" "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null | sed '/^$/d' | wc -l)"
  MARKET_MOON="$(echo "$CAT_EXCHANGE_PRICES" | awk '{ print $5 }' | awk '{ SUM += $1} END { print SUM }')"
  MARKET_MOON_COUNT="$(echo "$CAT_EXCHANGE_PRICES" | awk '{ print $5 }' | wc -l)"
  MARKET_MOON_VALUE="$(echo "$MARKET_MOON/$MARKET_MOON_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
  WIDTH="$(echo "$(echo "$MARKET_RESULT" | column -t | wc -L)$SUPPORT_WIDTH" | bc 2>/dev/null)"
  LENGTH="25"

  # if zero
  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="77"
  fi

  # if less than n
  if [[ "$WIDTH" -lt "77" ]] &>/dev/null; then
    WIDTH="77"
  fi

  # if market has data
  if [[ "$MARKET_COUNT" -eq "0" ]] &>/dev/null; then
    LENGTH="$SUPPORT_LENGTH"
    RESULT="$SUPPORT"
  else
    RESULT="Market: Bid Ask Last (%) Volume24Hr
$MARKET_RESULT"
  fi

  FILE_TIME="$(ls -l "${LOG_DIR:?}"/leeloo/"$OBSERVE_MARKET"/prices 2>/dev/null | awk '{ print $8 }')"
  if [[ -z "$FILE_TIME" ]] &>/dev/null; then
    FILE_TIME="00:00"
  fi

  display_result() {
    dialog --title "$FILE_TIME | Top 100 $EXCHANGE_API Market: +$MARKET_COUNT | $DATE | ${MARKET_MOON_VALUE:?}%" \
      --no-collapse \
      --scrollbar \
      --msgbox "$(echo "$RESULT" | column -t)" "$LENGTH" "$WIDTH"
  }
  display_result 2>/dev/null
}

# search markets ###############################################################

function search_market() {

  # exchanges, includes functions
  source /usr/local/bin/include/leeloo/strategies/templates/exchanges

  ##############################################################################

  install_exchange_dir

  ##############################################################################
  # exchange format
  ##############################################################################

  # poloniex, stakecube, xeggex search
  if [[ "$SEARCH_MARKET" == "poloniex" || "$SEARCH_MARKET" == "stakecube" || "$SEARCH_MARKET" == "xeggex" ]] &>/dev/null; then
    MARKET_INPUT=$(
      dialog --title "Market (BTC_USDT) (BTC)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
  fi

  # southxchange search
  if [[ "$SEARCH_MARKET" == "southxchange" ]] &>/dev/null; then
    MARKET_INPUT=$(
      dialog --title "Market (BTC/USDT) (BTC)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )
  fi

  ##############################################################################
  # market search
  ##############################################################################

  if [[ ! -z "$MARKET_INPUT" ]] &>/dev/null; then

    # get poloniex prices
    if [[ "$SEARCH_MARKET" == "poloniex" ]] &>/dev/null; then
      EXCHANGE_API="POL"
      exchange_template
      SUPPORT_WIDTH="+5"
      SUPPORT_LENGTH="+5"
      function result_prices() {
        echo "$(getPrices | column -t)" >"${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null
      }
    fi

    # get southxchange prices
    if [[ "$SEARCH_MARKET" == "southxchange" ]] &>/dev/null; then
      EXCHANGE_API="SXC"
      exchange_template
      SUPPORT_WIDTH="+5"
      SUPPORT_LENGTH="+5"
      function result_prices() {
        echo "$(prices | column -t)" >"${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null
      }
    fi

    # get stakecube prices
    if [[ "$SEARCH_MARKET" == "stakecube" ]] &>/dev/null; then
      EXCHANGE_API="SCE"
      exchange_template
      SUPPORT_WIDTH="+5"
      SUPPORT_LENGTH="+5"
      function result_prices() {
        echo "$(getMarkets | column -t)" >"${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null
      }
    fi

    # get xeggex prices
    if [[ "$SEARCH_MARKET" == "xeggex" ]] &>/dev/null; then
      EXCHANGE_API="XGX"
      exchange_template
      SUPPORT_WIDTH="+10"
      SUPPORT_LENGTH="+5"
      function result_prices() {
        echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null
      }
    fi

    USER_TIMER="$(echo "$BOT_TIMER*3.5" | bc 2>/dev/null | awk -F. '{ print $1 }')"

    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null)))" 2>/dev/null)" -gt "$USER_TIMER" ]] &>/dev/null; then
      result_prices
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices ]] &>/dev/null; then
      result_prices
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices ]] &>/dev/null; then
      result_prices
    fi

    MARKET_SEARCH="$(echo "$MARKET_INPUT" | tr '[:lower:]' '[:upper:]')"
    MARKET_RESULT="$(grep "$MARKET_SEARCH" "${LOG_DIR:?}"/leeloo/"$SEARCH_MARKET"/prices 2>/dev/null | sort -k2 -n -r 2>/dev/null)"
    MARKET_COUNT="$(echo "$MARKET_RESULT" | sed -r '/^\s*$/d' | wc -l)"
    MARKET_MOON="$(echo "$MARKET_RESULT" | awk '{ print $5 }' | awk '{ SUM += $1} END { print SUM }')"
    MARKET_MOON_COUNT="$(echo "$MARKET_RESULT" | awk '{ print $5 }' | wc -l)"
    MARKET_MOON_VALUE="$(echo "$MARKET_MOON/$MARKET_MOON_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    LENGTH="$(echo "$MARKET_COUNT$SUPPORT_LENGTH" | bc 2>/dev/null)"
    WIDTH="$(echo "$(echo "$MARKET_RESULT" | column -t | wc -L)$SUPPORT_WIDTH" | bc 2>/dev/null)"

    if [[ -z "$LOG_LENGTH" ]] &>/dev/null; then
      LOG_LENGTH="7"
    fi
    if [[ "$LENGTH" -gt "$LOG_LENGTH" ]] &>/dev/null; then
      LENGTH="$LOG_LENGTH"
    fi

    if [[ "$WIDTH" -lt "77" ]] &>/dev/null; then
      WIDTH="77"
    fi

    display_result() {
      dialog --title "Search $EXCHANGE_API result $MARKET_SEARCH: +$MARKET_COUNT | $DATE | ${MARKET_MOON_VALUE:?}%" \
        --no-collapse \
        --msgbox "$(echo "$RESULT" | column -t)" "$LENGTH" "$WIDTH"
    }

    if [[ "$MARKET_COUNT" -eq "0" ]] &>/dev/null; then
      RESULT="No market was found."
    else
      RESULT="Market: Bid Ask Last (%) Volume24Hr
$MARKET_RESULT"
    fi

    display_result 2>/dev/null
  else
    display_result() {
      dialog --title "Market info (empty)" \
        --no-collapse \
        --msgbox "$RESULT" 0 0
    }

    RESULT="No $EXCHANGE_API data found!"
    display_result 2>/dev/null
  fi
}

# last log #####################################################################

function last_log {

  if [[ ! -f "${LOG_DIR:?}"/leeloo/broker.log ]] &>/dev/null; then
    touch "${LOG_DIR:?}"/leeloo/broker.log &>/dev/null
  fi

  LOG_COUNT="$(wc -l "${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null | awk '{ print $1 }')"
  WIDTH="$(echo "$(tail -19 "${LOG_DIR:?}"/leeloo/broker.log | wc -L | awk '{ print $1 }')+4" | bc 2>/dev/null)"
  LENGTH="$(echo "$(wc -l "${LOG_DIR:?}"/leeloo/broker.log | awk '{ print $1 }')+5" | bc 2>/dev/null)"

  if [[ -z "$LOG_LENGTH" ]] &>/dev/null; then
    LOG_LENGTH="7"
  fi
  if [[ -z "$LENGTH" ]] &>/dev/null; then
    LENGTH="7"
  elif [[ "$LENGTH" -gt "$LOG_LENGTH" ]] &>/dev/null; then
    LENGTH="$LOG_LENGTH"
  fi

  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="77"
  elif [[ "$WIDTH" -lt "77" ]] &>/dev/null; then
    WIDTH="77"
  fi

  display_result() {
    dialog --title "Broker Log: $LOG_COUNT" \
      --no-collapse \
      --tailbox "$RESULT" "$LENGTH" "$WIDTH"
  }
  RESULT="${LOG_DIR:?}/leeloo/broker.log"
  display_result 2>/dev/null

  # if greater than n
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/broker.log | awk '{ print $1 }')" -gt "0" ]] &>/dev/null; then
    # ask for reset
    if ! dialog --stdout --title "Keep history? +$LOG_COUNT" \
      --backtitle "Reset history?" \
      --yesno "Yes: Keep! No: Delete!" 5 30; then
      truncate -s 0 "${LOG_DIR:?}"/leeloo/broker.log &>/dev/null
    fi
  fi
}

# last log robot ###############################################################

function last_log_robot {
  LOG_COUNT="$(wc -l "${LOG_DIR:?}"/leeloo/robot.log)"
  WIDTH="$(echo "$(tail -19 "${LOG_DIR:?}"/leeloo/robot.log | wc -L | awk '{ print $1 }')+6" | bc 2>/dev/null)"
  if [[ -z "$LOG_LENGTH" ]] &>/dev/null; then
    LENGTH="21"
  else
    LENGTH="$LOG_LENGTH"
  fi
  if [[ -z "$LENGTH" ]] &>/dev/null; then
    LENGTH="21"
  elif [[ "$LENGTH" -lt "21" ]] &>/dev/null; then
    LENGTH="21"
  fi
  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="89"
  elif [[ "$WIDTH" -lt "89" ]] &>/dev/null; then
    WIDTH="89"
  fi
  display_result() {
    dialog --title "Robot Log: $LOG_COUNT" \
      --no-collapse \
      --tailbox "$RESULT" "$LENGTH" "$WIDTH"
  }
  RESULT="${LOG_DIR:?}/leeloo/robot.log"
  display_result 2>/dev/null
}

# open orders ##################################################################

function open_orders {

  # poloniex data
  if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
    # set orders format
    ORDERS_FORMAT="OrderID: Type Amount Original LimitPrice List Ref DateAdded"
    # set exchange template
    EXCHANGE_API="POL"
    exchange_template
    ORDER_EXCHANGE="Poloniex"
    # open orders function
    function result_orders {
      echo "BETA"
    }
  fi

  ##############################################################################

  # southxchange data
  if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
    # set orders format
    ORDERS_FORMAT="OrderID: Type Amount Original LimitPrice List Ref DateAdded"
    # set exchange template
    EXCHANGE_API="SXC"
    exchange_template
    ORDER_EXCHANGE="SouthXchange"
    # open orders function
    function result_orders {
      listOrders | jq -r '.[] | "\(.Code): \(.Type) \(.Amount) \(.OriginalAmount) \(.LimitPrice) \(.ListingCurrency) \(.ReferenceCurrency) \(.DateAdded)"' 2>/dev/null | awk '{for(i=1;i<=NF;i++) {if($i~/^[0-9]*\.?[0-9]*[eE][-+]?[0-9]+$/) {printf("%0.8f ",$i);} else if($i~/^[0-9]+$/) {printf("%0.8f ",$i);} else {printf("%s ",$i)}} printf("\n")}' | column -t >"${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null
    }
  fi

  ##############################################################################

  # stakecube data
  if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
    # set orders format
    ORDERS_FORMAT="OrderID: Type Amount Original LimitPrice List Ref DateAdded"
    # set exchange template
    EXCHANGE_API="SCE"
    exchange_template
    ORDER_EXCHANGE="StakeCube"
    # open orders function
    function result_orders {
      echo "BETA"
    }
  fi

  ##############################################################################

  # xeggex data
  if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
    # set orders format
    ORDERS_FORMAT="OrderID Type Amount Original LimitPrice List Ref DateAdded"
    # set exchange template
    EXCHANGE_API="XGX"
    exchange_template
    ORDER_EXCHANGE="XeggeX"
    # open orders function
    function result_orders {
      echo "$(getOrders | jq -r '.[] | "\(.id): \(.side) \(.remainQuantity) \(.quantity) \(.price) \(.market.symbol) \(.updatedAt)"' | awk '{printf "%s %s %s %s %s %s %s\n", $1, $2, $3, $4, $5, $6, strftime("%Y-%m-%dT%H:%M:%S", $7/1000)}' 2>/dev/null | column -t | sed "s/\// /g")" >"${LOG_DIR:?}"/leeloo/xeggex/orders 2>/dev/null
    }
  fi

  # xeggex order format
  function place_order_format {
    # get id, price, output format
    PLACE_ORDER="$(cat "${LOG_DIR:?}"/leeloo/broker.tx 2>/dev/null)"
    PLACE_ORDER_ID="$(echo "$PLACE_ORDER" | tr -d '"' | egrep -wo "id:[A-Za-z0-9]+" | awk -F: '{ print $2 }' | tail -1)"
    PLACE_ORDER_PRICE="$(echo "$PLACE_ORDER" | egrep -wo "price:[0-9]+.[0-9]+" | awk -F: '{ print $2 }' | tail -1)"
    PLACE_ORDER="$PLACE_ORDER_ID$PLACE_ORDER_PRICE"
  }

  ##############################################################################

  HEIGHT=10
  WIDTH=40
  CHOICE_HEIGHT=3
  BACKTITLE="Leeloo (Multipass)"
  TITLE="$EXCHANGE_API Order Menu"
  MENU="${DATE:?}"

  OPTIONS=(1 "Buy              Buy Order"
    2 "Sell             Sell Order"
    3 "Status           Open Orders")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  "1")

    TYPE="buy"
    HEIGHT=9
    WIDTH=23
    CHOICE_HEIGHT=2
    BACKTITLE="Leeloo (Multipass)"
    TITLE="$EXCHANGE_API Buy Order Menu"
    AMOUNT_IN_REFERENCE_CURRENCY="true"
    MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

    OPTIONS=(
      1 "Market Order"
      2 "Limit Order")

    CHOICE=$(dialog --clear \
      --backtitle "$BACKTITLE" \
      --title "$TITLE" \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      2>&1 >/dev/tty)

    clear
    case $CHOICE in

    "1")

      log_date
      setup_market_order
      if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
        if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
          if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

            # if southxchange
            if [[ "$ORDER_EXCHANGE" == "SouthXchange" ]] &>/dev/null; then
              PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
              PLACE_ORDER="$(echo "$PLACE_ORDER" | tr -d '"')"
            fi
            # if xeggex
            if [[ "$ORDER_EXCHANGE" == "XeggeX" ]] &>/dev/null; then
              PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$AMOUNT" "" "false")"
              echo "$PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.tx
              place_order_format
            fi

            # if zero api
            if [[ -z "$PLACE_ORDER" ]] &>/dev/null; then
              echo "No API configuration!"
              exit
            fi
            echo "$LOG_DATE :: $EXCHANGE_API :: Manual $TYPE :: Market Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
            echo "$LOG_DATE :: $EXCHANGE_API :: Output: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
          fi
        fi
      fi

      ;;

    "2")

      log_date
      setup_limit_order
      if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
        if [[ ! -z "$PRICE" ]] &>/dev/null; then
          if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
            if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

              # if southxchange
              if [[ "$ORDER_EXCHANGE" == "SouthXchange" ]] &>/dev/null; then
                PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                PLACE_ORDER="$(echo "$PLACE_ORDER" | tr -d '"')"
              fi
              # if xeggex
              if [[ "$ORDER_EXCHANGE" == "XeggeX" ]] &>/dev/null; then
                PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$AMOUNT" "$PRICE" "false")"
                echo "$PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.tx
                place_order_format
              fi

              # if zero api
              if [[ -z "$PLACE_ORDER" ]] &>/dev/null; then
                echo "No API configuration!"
                exit
              fi
              echo "$LOG_DATE :: $EXCHANGE_API :: Manual $TYPE :: Limit Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
              echo "$LOG_DATE :: $EXCHANGE_API :: Output: $PLACE_ORDER :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
            fi
          fi
        fi
      fi

      ;;

    esac

    last_log

    ;;

  "2")

    TYPE="sell"
    HEIGHT=9
    WIDTH=23
    CHOICE_HEIGHT=2
    BACKTITLE="Leeloo (Multipass)"
    TITLE="$EXCHANGE_API Sell Order Menu"
    AMOUNT_IN_REFERENCE_CURRENCY="false"
    MENU="$(date | xargs | awk '{ print $4,$5,$6 }')"

    OPTIONS=(
      1 "Market Order"
      2 "Limit Order")

    CHOICE=$(dialog --clear \
      --backtitle "$BACKTITLE" \
      --title "$TITLE" \
      --menu "$MENU" \
      $HEIGHT $WIDTH $CHOICE_HEIGHT \
      "${OPTIONS[@]}" \
      2>&1 >/dev/tty)

    clear
    case $CHOICE in

    "1")

      log_date
      setup_market_order
      if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
        if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
          if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

            # if southxchange
            if [[ "$ORDER_EXCHANGE" == "SouthXchange" ]] &>/dev/null; then
              PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
              PLACE_ORDER="$(echo "$PLACE_ORDER" | tr -d '"')"
            fi
            # if xeggex
            if [[ "$ORDER_EXCHANGE" == "XeggeX" ]] &>/dev/null; then
              PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$AMOUNT" "" "false")"
              echo "$PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.tx
              place_order_format
            fi

            # if zero api
            if [[ -z "$PLACE_ORDER" ]] &>/dev/null; then
              echo "No API configuration!"
              exit
            fi
            echo "$LOG_DATE :: $EXCHANGE_API :: Manual $TYPE :: Market Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
            echo "$LOG_DATE :: $EXCHANGE_API :: Output: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
          fi
        fi
      fi

      ;;

    "2")

      log_date
      setup_limit_order
      if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
        if [[ ! -z "$PRICE" ]] &>/dev/null; then
          if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then
            if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

              # if southxchange
              if [[ "$ORDER_EXCHANGE" == "SouthXchange" ]] &>/dev/null; then
                PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$PRICE" "$AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
                PLACE_ORDER="$(echo "$PLACE_ORDER" | tr -d '"')"
              fi
              # if xeggex
              if [[ "$ORDER_EXCHANGE" == "XeggeX" ]] &>/dev/null; then
                PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$AMOUNT" "$PRICE" "false")"
                echo "$PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.tx
                place_order_format
              fi

              # if zero api
              if [[ -z "$PLACE_ORDER" ]] &>/dev/null; then
                echo "No API configuration!"
                exit
              fi
              echo "$LOG_DATE :: $EXCHANGE_API :: Manual $TYPE :: Limit Order :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $AMOUNT :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
              echo "$LOG_DATE :: $EXCHANGE_API :: Output: $PLACE_ORDER :: $PRICE" >>"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
            fi
          fi
        fi
      fi

      ;;

    esac

    last_log

    ;;

    # open orders

  "3")

    USER_TIMER="$(echo "$BOT_TIMER*3.5" | bc 2>/dev/null | awk -F. '{ print $1 }')"

    # lower caps
    ORDER_EXCHANGE_NAME="$(echo "$ORDER_EXCHANGE" | tr '[A-Z]' '[a-z]')"

    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null)))" 2>/dev/null)" -gt "$USER_TIMER" ]] &>/dev/null; then
      result_orders
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders ]] &>/dev/null; then
      result_orders
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders ]] &>/dev/null; then
      result_orders
    fi

    ORDER_TOTAL="$(cat "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null | sed '/^$/d' | wc -l)"
    ORDER_TOTAL_WIDTH="$(echo "$(echo "$ORDERS_FORMAT
    $(cat "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null)" | column -t | wc -L)+5" | bc 2>/dev/null)"
    ORDER_TOTAL_LENGTH="$(echo "$ORDER_TOTAL+5" | bc 2>/dev/null)"
    ORDER_TOTAL_BUY="$(grep -c "buy" "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null)"
    ORDER_TOTAL_SELL="$(grep -c "sell" "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null)"
    ORDER_PERCENTAGE_BUY="$(echo "100/$ORDER_TOTAL*$ORDER_TOTAL_BUY" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    ORDER_PERCENTAGE_SELL="$(echo "100/$ORDER_TOTAL*$ORDER_TOTAL_SELL" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    # if zero
    if [[ -z "$ORDER_PERCENTAGE_BUY" ]] &>/dev/null; then
      ORDER_PERCENTAGE_BUY="0"
    fi
    # if zero
    if [[ -z "$ORDER_PERCENTAGE_SELL" ]] &>/dev/null; then
      ORDER_PERCENTAGE_SELL="0"
    fi

    display_result() {
      dialog --title "Open Orders: +$ORDER_TOTAL :: Buy: $ORDER_TOTAL_BUY (${ORDER_PERCENTAGE_BUY:?}%) :: Sell: $ORDER_TOTAL_SELL (${ORDER_PERCENTAGE_SELL:?}%)" \
        --no-collapse \
        --msgbox "$(echo "$RESULT" | column -t)" "$ORDER_TOTAL_LENGTH" "$ORDER_TOTAL_WIDTH"
    }

    RESULT="$ORDERS_FORMAT
$(cat "${LOG_DIR:?}"/leeloo/"$ORDER_EXCHANGE_NAME"/orders 2>/dev/null)"
    display_result 2>/dev/null

    ;;

  esac
}

# market info ##################################################################

function coin_token_search {
  COIN_TOKEN=$(
    dialog --title "Coin/Token (Example: BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# rsi value output #############################################################

function rsi_value_output {
  RSI_VALUE_OUTPUT=$(
    dialog --title "RSI Value output (Example: Number)" \
      --inputbox "Enter value:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# ema value output #############################################################

function ema_value_output {
  EMA_SHORT_OUTPUT=$(
    dialog --title "EMA Short (Example: 6)" \
      --inputbox "Enter value:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  EMA_LONG_OUTPUT=$(
    dialog --title "EMA Long (Example: 20)" \
      --inputbox "Enter value:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# cleanup log ##################################################################

function cleanup_log {
  # reset broker.log
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/broker.log | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$(echo "$MAX_LOG/3" | bc 2>/dev/null)" "${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null
    echo "$DATE :: LogReset! :: Line $MAX_LOG" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
}

# dnt, ref address #############################################################

# btc_dnt_addr
BTC_DNT_ADDR="bc1qgpg4j294hyy6qgefp7qlqmy6w4jprtt4349jc2"
BTC_MEMPOOL="https://mempool.space/address/bc1qgpg4j294hyy6qgefp7qlqmy6w4jprtt4349jc2"

# ref_link
REF_POLONIEX="https://poloniex.com/signup?c=R2LDDSXB"
REF_XEGGEX="https://xeggex.com?ref=650e9399625501b3b53b1172"

# END
