#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

# search market ################################################################

function search {
  MARKET_INPUT=$(
    dialog --title "Market (BTC/USDT) (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# setup_market_order ###########################################################

function setup_market_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# setup_limit_order ############################################################

function setup_limit_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  LISTING_CURRENCY_PRICE="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $4 }' | head -1)"
  REFERENCE_CURRENCY_PRICE="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $4 }' | head -1)"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  PRICE=$(
    dialog --title "Price $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter price:
$LISTING_CURRENCY_PRICE $REFERENCE_CURRENCY_PRICE" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# last_log #####################################################################

function last_log {
  echo "$(cat "${LOG_DIR:?}"/leeloo/broker.log 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/broker.log
  LOG_COUNT="$(wc -l "${LOG_DIR:?}"/leeloo/broker.log)"
  WIDTH="$(echo "$(tail -25 "${LOG_DIR:?}"/leeloo/broker.log | wc -L | awk '{ print $1 }')+7" | bc 2>/dev/null)"
  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="100"
  elif [[ "$WIDTH" -lt "25" ]] &>/dev/null; then
    WIDTH="25"
  fi
  display_result() {
    dialog --title "Broker Log: $LOG_COUNT" \
      --no-collapse \
      --tailbox "$RESULT" 25 "$WIDTH"
  }
  RESULT="${LOG_DIR:?}/leeloo/broker.log"
  display_result 2>/dev/null
}

# last_log_robot ###############################################################

function last_log_robot {
  echo "$(cat "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot.log
  LOG_COUNT="$(wc -l "${LOG_DIR:?}"/leeloo/robot.log)"
  WIDTH="$(echo "$(tail -50 "${LOG_DIR:?}"/leeloo/robot.log | wc -L | awk '{ print $1 }')+7" | bc 2>/dev/null)"
  if [[ -z "$WIDTH" ]] &>/dev/null; then
    WIDTH="100"
  elif [[ "$WIDTH" -lt "25" ]] &>/dev/null; then
    WIDTH="25"
  fi
  display_result() {
    dialog --title "Robot Log: $LOG_COUNT" \
      --no-collapse \
      --tailbox "$RESULT" 25 "$WIDTH"
  }
  RESULT="${LOG_DIR:?}/leeloo/robot.log"
  display_result 2>/dev/null
}

# cleanup_log ##################################################################

function cleanup_log {
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/debug.log | awk '{ print $1 }')" -gt "4320" ]] &>/dev/null; then
    echo "$(tail -512 "${LOG_DIR:?}"/leeloo/debug.log 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/debug.log
  else
    echo "$(cat "${LOG_DIR:?}"/leeloo/debug.log 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/debug.log
  fi
}

# cleanup_log_robot ############################################################

function cleanup_log_robot {
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/robot.log | awk '{ print $1 }')" -gt "4320" ]] &>/dev/null; then
    echo "$(tail -512 "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot.log
  else
    echo "$(cat "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot.log
  fi
}

# END
