#!/bin/bash

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

# system directory #############################################################

SYS_DIR="/usr/local/bin/include/leeloo" # system folder

################################################################################

EXCHANGE_DIR_NAME="$GRAPH_EXCHANGE"

################################################################################

# create reference list based on exchange
GRAPH_REFERENCE_LIST="$(egrep -w "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices 2>/dev/null | egrep -o "_[A-Z,0-9]+" | tr -d '_' | awk '!a[$0]++')" /tmp/leeloo/"$EXCHANGE_DIR_NAME"/balances | awk '$2 != 0 || $3 != 0 || $4 != 0' | awk '{ print $1 }' | tr -d ':')"

# if data
if [[ -n "$GRAPH_REFERENCE_LIST" ]] &>/dev/null; then
  # keep data
  echo "$GRAPH_REFERENCE_LIST" >"${SYS_DIR:?}"/robot/"$EXCHANGE_DIR_NAME".reference
fi

################################################################################

SCREEN_LIST="$(cat "${LOG_DIR:?}"/leeloo/screen 2>/dev/null)"

if [[ "$GRAPH_TIME" == "0" || -z "$GRAPH_TIME" ]] &>/dev/null; then
  if [[ "$(echo "$SCREEN_LIST" | grep "leeloo" | wc -l)" -eq "1" ]] &>/dev/null; then

    LEELOO_PID="$(echo "$SCREEN_LIST" | grep "leeloo" | awk -F. '{ print $1 }' | xargs)"
    LEELOO_TIME=$(ps -p $LEELOO_PID -o etimes=)

    # time format
    GRAPH_TIME="$(echo "$LEELOO_TIME/1440" | bc 2>/dev/null)d"

    # if zero
    if [[ -z "$GRAPH_TIME" ]] &>/dev/null; then
      GRAPH_TIME="1d"
    fi
  fi
fi

################################################################################

# iterate over active references
for GRAPH_REFERENCE_CURRENCY in $GRAPH_REFERENCE_LIST; do
  GRAPH_DB_PATH="${SYS_DIR:?}/robot/${EXCHANGE_DIR_NAME:?}_${GRAPH_REFERENCE_CURRENCY}.rrd"
  GRAPH_PNG_PATH="/var/www/html/${GRAPH_REFERENCE_CURRENCY}.png"

  # create graph based on found reference accounts with balance
  if [ ! -f "${GRAPH_DB_PATH}" ]; then
    printf '%b' '%s Status() rrdtoolStats() Creating %s.rrd! %s<>%s\n' "$(date "+%Y-%m-%d %H:%M:%S")" "${GRAPH_REFERENCE_CURRENCY}" >>"${LOG_DIR:?}"/leeloo/graph.log 2>&1
    rrdtool create "${GRAPH_DB_PATH}" \
      --step=60 \
      DS:deposited:GAUGE:300:U:U \
      DS:available:GAUGE:300:U:U \
      DS:unconfirmed:GAUGE:300:U:U \
      RRA:AVERAGE:0.5:1:1051200
  fi

  ##############################################################################

  # update databases
  rrdtool update "$GRAPH_DB_PATH" N:"$(grep -w "$GRAPH_REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances 2>/dev/null | awk '{ print $2, $3, $4 }' | awk '{ printf "%.9f:%.9f:%.9f\n", $1, $2, $3 }')" 2>/dev/null

  ##############################################################################

  # reference balance
  rrdtool graph "${GRAPH_PNG_PATH}" \
    -w 400 -h 150 -a PNG \
    --slope-mode \
    --vertical-label "${GRAPH_REFERENCE_CURRENCY} Balance" \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:deposited="${GRAPH_DB_PATH}":deposited:MAX \
    DEF:available="${GRAPH_DB_PATH}":available:MAX \
    DEF:unconfirmed="${GRAPH_DB_PATH}":unconfirmed:MAX \
    CDEF:total=deposited,available,unconfirmed,+,+ \
    GPRINT:deposited:LAST:"Deposited\: %.9lf" \
    GPRINT:available:LAST:"Available\: %.9lf" \
    GPRINT:unconfirmed:LAST:"Unconfirmed\: %.9lf" \
    GPRINT:total:LAST:"Total\: %.9lf" \
    LINE1:deposited#45DC63:"Deposited" \
    LINE2:available#FFE000:"Available" \
    LINE3:unconfirmed#FF5100:"Unconfirmed" \
    LINE4:total#0000FF:"Total"
done

################################################################################

# start generating index.php
cat >/var/www/html/"$EXCHANGE_DIR_NAME".php <<'EOF'
<div id="content" align="center">
<?php
  header("refresh: 120;");
  // Background color (dark blue)
  echo "<body style='background-color:2D3037'>";
  // Graphs
EOF

for GRAPH_REFERENCE_CURRENCY in $GRAPH_REFERENCE_LIST; do
  GRAPH_PNG_PATH="${GRAPH_REFERENCE_CURRENCY}.png"
  # Echo the dynamically generated PHP code for the loop
  echo "  echo '<img src=\"$GRAPH_PNG_PATH\" alt=\"$GRAPH_REFERENCE_CURRENCY Balance\" />';" >>/var/www/html/"$EXCHANGE_DIR_NAME".php
done

# Close the PHP block
echo "?>" >>/var/www/html/"$EXCHANGE_DIR_NAME".php

# END
