#!/bin/bash

################################################################################

export LC_NUMERIC=en_US.UTF-8

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

# system directory #############################################################

SYS_DIR="/usr/local/bin/include/leeloo" # system folder

################################################################################

EXCHANGE_DIR_NAME="$GRAPH_EXCHANGE"

################################################################################

# exchange balances
WCL_BALANCES="$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances 2>/dev/null | awk '{ print $1 }')"
WCL_PRICES="$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices 2>/dev/null | awk '{ print $1 }')"
WCL_ORDERS="$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null | awk '{ print $1 }')"

# check balances, prices
if [[ "$WCL_BALANCES" -gt "1" && "$WCL_PRICES" -gt "1" && "$WCL_ORDERS" -gt "1" ]] &>/dev/null; then

  ##############################################################################

  # if xeggex
  if [[ "$EXCHANGE_DIR_NAME" == "xeggex" ]] &>/dev/null; then
    # create reference list based on exchange
    GRAPH_REFERENCE_LIST="$(egrep -w "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices 2>/dev/null | egrep -o "_[A-Z,0-9]+" | tr -d '_' | awk '!a[$0]++')" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances | awk '$2 != 0 || $3 != 0 || $4 != 0' | awk '{ print $1 }' | tr -d ':')"
    # orders by exchange
    GRAPH_ORDERS_EXCHANGE="XGX"
  fi

  ##############################################################################

  # if southxchange
  if [[ "$EXCHANGE_DIR_NAME" == "southxchange" ]] &>/dev/null; then
    # create reference list based on exchange
    GRAPH_REFERENCE_LIST="$(egrep -w "$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices 2>/dev/null | egrep -o "/[A-Z,0-9]+" | tr -d '/' | awk '!a[$0]++')" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances | awk '$2 != 0 || $3 != 0 || $4 != 0' | awk '{ print $1 }' | tr -d ':')"
    # orders by exchange
    GRAPH_ORDERS_EXCHANGE="SXC"
  fi

  ##############################################################################

  # if data
  if [[ -n "$GRAPH_REFERENCE_LIST" ]] &>/dev/null; then
    # keep reference data
    echo "$GRAPH_REFERENCE_LIST" >"${SYS_DIR:?}"/robot/"$EXCHANGE_DIR_NAME".reference
    # keep reference data logical (png graphs)
    comm -23 <(ls /var/www/html/"$EXCHANGE_DIR_NAME"*.png | sort) <(cat "${SYS_DIR:?}"/robot/"$EXCHANGE_DIR_NAME".reference | sort) | xargs -I {} rm {}
  fi

  ##############################################################################

  SCREEN_LIST="$(cat "${LOG_DIR:?}"/leeloo/screen 2>/dev/null)"

  if [[ "$GRAPH_TIME" == "0" ]] &>/dev/null; then
    if [[ "$(echo "$SCREEN_LIST" | grep "leeloo" | wc -l)" -eq "1" ]] &>/dev/null; then
      LEELOO_PID="$(echo "$SCREEN_LIST" | grep "leeloo" | awk -F. '{ print $1 }' | xargs)"
      LEELOO_TIME=$(ps -p $LEELOO_PID -o etimes=)
      # calculate hours (rounded up to the nearest hour)
      GRAPH_TIME_HOURS="$(echo "($LEELOO_TIME + 3599) / 3600" | bc)"
      GRAPH_TIME="${GRAPH_TIME_HOURS}h"
    fi
  fi
  # if still zero or empty
  if [[ -z "$GRAPH_TIME" ]] &>/dev/null; then
    GRAPH_TIME="1h"
  fi

  # if southxchange
  if [[ "$EXCHANGE_DIR_NAME" == "southxchange" ]] &>/dev/null; then
    EXCHANGE_NAME="SouthXchange"
    HEIGHT="150"
  fi

  # if xeggex
  if [[ "$EXCHANGE_DIR_NAME" == "xeggex" ]] &>/dev/null; then
    EXCHANGE_NAME="XeggeX"
    HEIGHT="164"
  fi

  ##############################################################################

  # iterate over active references
  for GRAPH_REFERENCE_CURRENCY in $GRAPH_REFERENCE_LIST; do

    # path references png
    GRAPH_DB_PATH="${SYS_DIR:?}/robot/${EXCHANGE_DIR_NAME:?}_${GRAPH_REFERENCE_CURRENCY}.rrd"
    GRAPH_PNG_PATH="/var/www/html/${EXCHANGE_DIR_NAME:?}_${GRAPH_REFERENCE_CURRENCY}.png"

    # path orders png
    GRAPH_DB_ORDERS_PATH="${SYS_DIR:?}/robot/${EXCHANGE_DIR_NAME:?}_orders.rrd"
    GRAPH_PNG_ORDERS_PATH="/var/www/html/${EXCHANGE_DIR_NAME:?}_orders.png"

    # if zero
    if [[ -z "$GRAPH_DATA" ]] &>/dev/null; then
      GRAPH_DATA="525600" # 1 year with 1-minute interval
    fi

    ############################################################################
    # graph exchange orders buy and sell count
    ############################################################################

    # create graph based on exchange orders
    if [ ! -f "${GRAPH_DB_ORDERS_PATH}" ]; then
      printf '%b' '%s Status() rrdtoolStats() Creating "'"${EXCHANGE_DIR_NAME:?}_orders"'".rrd! <>\n' "$(date "+%Y-%m-%d %H:%M:%S")" "Orders" >>"${LOG_DIR:?}"/leeloo/graph.log 2>&1
      rrdtool create "${GRAPH_DB_ORDERS_PATH}" \
        --step=60 \
        DS:buy:GAUGE:300:U:U \
        DS:sell:GAUGE:300:U:U \
        RRA:AVERAGE:0.5:1:"$GRAPH_DATA" # ruled by configuration
    fi

    # update order databases
    rrdtool update "$GRAPH_DB_ORDERS_PATH" N:"$(grep -c "buy" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null || true)":"$(grep -c "sell" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/orders 2>/dev/null || true)" 2>/dev/null

    ############################################################################
    # graph reference accounts with balance
    ############################################################################

    # create graph based on found reference accounts with balance
    if [ ! -f "${GRAPH_DB_PATH}" ]; then
      printf '%b' '%s Status() rrdtoolStats() Creating "'"${EXCHANGE_DIR_NAME:?}_${GRAPH_REFERENCE_CURRENCY}"'".rrd! <>\n' "$(date "+%Y-%m-%d %H:%M:%S")" "${GRAPH_REFERENCE_CURRENCY}" >>"${LOG_DIR:?}"/leeloo/graph.log 2>&1
      rrdtool create "${GRAPH_DB_PATH}" \
        --step=60 \
        DS:deposited:GAUGE:300:U:U \
        DS:available:GAUGE:300:U:U \
        DS:unconfirmed:GAUGE:300:U:U \
        RRA:AVERAGE:0.5:1:"$GRAPH_DATA" # ruled by configuration
    fi

    # update reference databases
    rrdtool update "$GRAPH_DB_PATH" N:"$(grep -w "$GRAPH_REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances 2>/dev/null | awk '{ printf "%.9f:%.9f:%.9f\n", $2, $3, $4 }')" 2>/dev/null

    ############################################################################

    # if xeggex
    if [[ "$EXCHANGE_DIR_NAME" == "xeggex" ]] &>/dev/null; then
      # reference balance
      rrdtool graph "${GRAPH_PNG_PATH}" \
        -w 400 -h 150 -a PNG \
        --slope-mode \
        --vertical-label "${GRAPH_REFERENCE_CURRENCY} Balance" \
        --color BACK#565875 \
        --color FONT#FFFFFF \
        --color CANVAS#42445F \
        --color GRID#565875 \
        --color FRAME#565875 \
        --color SHADEA#565875 \
        --color SHADEB#565875 \
        --font DEFAULT:8:"$LC_NUMERIC" \
        --end now --start end-"${GRAPH_TIME:?}" \
        DEF:deposited="${GRAPH_DB_PATH}":deposited:MAX \
        DEF:available="${GRAPH_DB_PATH}":available:MAX \
        DEF:unconfirmed="${GRAPH_DB_PATH}":unconfirmed:MAX \
        CDEF:total=deposited,available,unconfirmed,+,+ \
        LINE1:deposited#2970D6:" Deposited $GRAPH_REFERENCE_CURRENCY    " \
        GPRINT:deposited:LAST:"%.9lf\n" \
        LINE2:available#85bb65:" Available $GRAPH_REFERENCE_CURRENCY     " \
        GPRINT:available:LAST:"%.9lf\n" \
        LINE1:unconfirmed#EA7575:" Unconfirmed $GRAPH_REFERENCE_CURRENCY" \
        GPRINT:unconfirmed:LAST:"%.9lf\n" \
        LINE2:total#BFDACF:" Total $GRAPH_REFERENCE_CURRENCY           " \
        GPRINT:total:LAST:"%.9lf\n"
    fi

    ############################################################################

    # if southxchange
    if [[ "$EXCHANGE_DIR_NAME" == "southxchange" ]] &>/dev/null; then
      # reference balance
      rrdtool graph "${GRAPH_PNG_PATH}" \
        -w 400 -h 150 -a PNG \
        --slope-mode \
        --vertical-label "${GRAPH_REFERENCE_CURRENCY} Balance" \
        --color BACK#565875 \
        --color FONT#FFFFFF \
        --color CANVAS#42445F \
        --color GRID#565875 \
        --color FRAME#565875 \
        --color SHADEA#565875 \
        --color SHADEB#565875 \
        --font DEFAULT:8:"$LC_NUMERIC" \
        --end now --start end-"${GRAPH_TIME:?}" \
        DEF:deposited="${GRAPH_DB_PATH}":deposited:MAX \
        DEF:available="${GRAPH_DB_PATH}":available:MAX \
        DEF:unconfirmed="${GRAPH_DB_PATH}":unconfirmed:MAX \
        LINE1:deposited#BFDACF:" $GRAPH_REFERENCE_CURRENCY Deposited  " \
        GPRINT:deposited:LAST:"%.9lf\n" \
        LINE2:available#85bb65:" $GRAPH_REFERENCE_CURRENCY Available  " \
        GPRINT:available:LAST:"%.9lf\n" \
        LINE1:unconfirmed#EA7575:" $GRAPH_REFERENCE_CURRENCY Unconfirmed" \
        GPRINT:unconfirmed:LAST:"%.9lf\n"
    fi
  done

  ##############################################################################

  rrdtool graph "${GRAPH_PNG_ORDERS_PATH}" \
    -w 400 -h "$HEIGHT" -a PNG \
    --slope-mode \
    --vertical-label "${EXCHANGE_NAME} Orders" \
    --color BACK#565875 \
    --color FONT#FFFFFF \
    --color CANVAS#42445F \
    --color GRID#565875 \
    --color FRAME#565875 \
    --color SHADEA#565875 \
    --color SHADEB#565875 \
    --font DEFAULT:8:"$LC_NUMERIC" \
    --end now --start end-"${GRAPH_TIME:?}" \
    DEF:buy="${GRAPH_DB_ORDERS_PATH}":buy:MAX \
    DEF:sell="${GRAPH_DB_ORDERS_PATH}":sell:MAX \
    CDEF:total=buy,sell,+ \
    LINE1:buy#FA8A8A:" $EXCHANGE_NAME Buy   " \
    GPRINT:buy:LAST:"%.0lf\n" \
    LINE1:sell#6EBB65:" $EXCHANGE_NAME Sell  " \
    GPRINT:sell:LAST:"%.0lf\n" \
    LINE2:total#BFDACF:" $EXCHANGE_NAME Total " \
    GPRINT:total:LAST:"%.0lf\n"

  ##############################################################################

  # start generating exchange_dir_name.php
  cat >/var/www/html/"$EXCHANGE_DIR_NAME".php <<EOF
<div id="content" align="center">
<?php
  header("refresh: 120;");
  // Background color (dark blue)
  echo "<body style='background-color:2D3037'>";
  // Graphs
EOF

  # generate exchange orders at the beginning
  GRAPH_PNG_ORDERS_PATH="${EXCHANGE_DIR_NAME:?}_orders.png"
  echo "  echo '<img src=\"${GRAPH_PNG_ORDERS_PATH:?}\" alt=\"${EXCHANGE_DIR_NAME} Orders\" />';" >>/var/www/html/"$EXCHANGE_DIR_NAME".php

  # generate rest of reference balances
  for GRAPH_REFERENCE_CURRENCY in $GRAPH_REFERENCE_LIST; do
    GRAPH_PNG_PATH="${EXCHANGE_DIR_NAME:?}_${GRAPH_REFERENCE_CURRENCY}.png"
    # echo the dynamically generated PHP code for the loop
    echo "  echo '<img src=\"$GRAPH_PNG_PATH\" alt=\"$GRAPH_REFERENCE_CURRENCY Balance\" />';" >>/var/www/html/"$EXCHANGE_DIR_NAME".php
  done

  # exchange orders
  echo "$(grep "$GRAPH_ORDERS_EXCHANGE" "${SYS_DIR:?}"/robot/orders.view 2>/dev/null)" >"${SYS_DIR:?}"/robot/orders_"$EXCHANGE_DIR_NAME".graphs

  # generate last orders
  cat >>/var/www/html/"$EXCHANGE_DIR_NAME".php <<EOF
  // display last orders from the file with a limit of 100 orders
  \$ordersFilePath = '${SYS_DIR:?}/robot/orders_${EXCHANGE_DIR_NAME}.graphs';
  \$ordersContent = shell_exec('column -t ' . escapeshellarg(\$ordersFilePath));
  \$ordersLines = array_reverse(explode("\n", \$ordersContent)); // reverse the order

  // set the font size and style for the entire row
  \$rowFontSize = $GRAPH_FONT_SIZE; // adjust the font size for the entire row
  \$rowFontWeight = '$GRAPH_FONT_WEIGHT'; // adjust the font weight for the entire row
  \$rowColor = '$GRAPH_FONT_COLOR'; // set the text color to white
  \$limit = $GRAPH_ORDERS_LENGTH; // set the limit for the number of orders to display

  // counter for the number of orders displayed
  \$orderCount = 0;

  // start a container table for the columnar layout
  echo '<table class="columnar-layout" style="font-size: ' . \$rowFontSize . 'px; font-weight: ' . \$rowFontWeight . '; color: ' . \$rowColor . ';">' . PHP_EOL;
  foreach (\$ordersLines as \$orderLine) {
      // Stop if the limit is reached
      if (\$orderCount >= \$limit) {
          break;
      }
      // increment the counter
      \$orderCount++;
      // split the order into parts using the double colon (::) as a delimiter
      \$orderParts = preg_split('/\s+/', \$orderLine);
      // start a table row for each order line
      echo '    <tr class="order-line">' . PHP_EOL;
      // create a table cell for each part
      foreach (\$orderParts as \$part) {
          echo '        <td class="order-part">' . trim(\$part) . '</td>' . PHP_EOL;
      }
      // end the table row for each order line
      echo '    </tr>' . PHP_EOL;
  }
  // end the container table for the columnar layout
  echo '</table>' . PHP_EOL;
EOF

  # close the php block
  echo "?>" >>/var/www/html/"$EXCHANGE_DIR_NAME".php
fi

# END
