#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf

# directories ##################################################################

if [[ ! -d /usr/local/bin/include/leeloo ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo &>/dev/null
fi

if [[ ! -d /usr/local/bin/include/leeloo/robot ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo/robot &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/indicators ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/indicators &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/southxchange ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/southxchange &>/dev/null
fi

# files ########################################################################

sudo cp "${HOME_DIR:?}"/leeloo/broker /usr/local/bin/broker
sudo chmod +x /usr/local/bin/broker
sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/broker

cp -a "${HOME_DIR:?}"/leeloo/include/indicators/ "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/strategies/ "$SYS_DIR" &>/dev/null

# update strategies
for BST_UPDATES in "$SYS_DIR"/robot/bst.*.strategy; do
  cat "${HOME_DIR:?}"/leeloo/include/strategies/buy_sell_strategy >"$BST_UPDATES"
done
for EMA_UPDATES in "$SYS_DIR"/robot/ema.*.strategy; do
  cat "${HOME_DIR:?}"/leeloo/include/strategies/ema_strategy >"$EMA_UPDATES"
done

cat "${HOME_DIR:?}"/leeloo/include/strategies/buy_sell_strategy >"$SYS_DIR"/robot/bst.*.strategy
cat "${HOME_DIR:?}"/leeloo/include/strategies/ema_strategy >"$SYS_DIR"/robot/ema.*.strategy

cp "${HOME_DIR:?}"/leeloo/include/functions "$SYS_DIR" &>/dev/null
cp "${HOME_DIR:?}"/leeloo/include/install "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/robot/ "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/api/ "$SYS_DIR" &>/dev/null

# END
