#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf

# directories ##################################################################

if ! [ -x "$(command -v dialog)" ] &>/dev/null; then
  sudo apt-get install dialog
fi

if ! [ -x "$(command -v tor)" ] &>/dev/null; then
  sudo apt-get install tor
fi

if ! [ -x "$(command -v bc)" ] &>/dev/null; then
  sudo apt-get install bc
fi

if [[ ! -d /usr/local/bin/include/leeloo ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo &>/dev/null
fi

if [[ ! -d /usr/local/bin/include/leeloo/robot ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo/robot &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/indicators ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/indicators &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/southxchange ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/southxchange &>/dev/null
fi

# files ########################################################################

sudo cp "${HOME_DIR:?}"/leeloo/broker /usr/local/bin/broker
sudo chmod +x /usr/local/bin/broker
sudo chown "$(whoami)":"$(whoami)" /usr/local/bin/broker

cp -a "${HOME_DIR:?}"/leeloo/include/indicators/ "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/strategies/ "$SYS_DIR" &>/dev/null

# if configuration exist, continue
if [[ "$(echo "$(ls -l "$SYS_DIR"/robot/)" | egrep "bst.*.config" | wc -l)" -gt "0" ]] &>/dev/null; then
  # update buy and sell strategy
  for BST_UPDATES in "$SYS_DIR"/robot/bst.*.strategy; do
    cat "${HOME_DIR:?}"/leeloo/include/strategies/buy_sell_strategy >"$BST_UPDATES"
  done
fi

# if configuration exist, continue
if [[ "$(echo "$(ls -l "$SYS_DIR"/robot/)" | egrep "ema.*.config" | wc -l)" -gt "0" ]] &>/dev/null; then
  # update EMA strategy
  for EMA_UPDATES in "$SYS_DIR"/robot/ema.*.strategy; do
    cat "${HOME_DIR:?}"/leeloo/include/strategies/ema_strategy >"$EMA_UPDATES"
  done
fi

# if configuration exist, continue
if [[ "$(echo "$(ls -l "$SYS_DIR"/robot/)" | egrep "snp.*.config" | wc -l)" -gt "0" ]] &>/dev/null; then
  # update Sniper strategy
  for SNP_UPDATES in "$SYS_DIR"/robot/snp.*.strategy; do
    cat "${HOME_DIR:?}"/leeloo/include/strategies/snp_strategy >"$SNP_UPDATES"
  done
fi

cp "${HOME_DIR:?}"/leeloo/include/functions "$SYS_DIR" &>/dev/null
cp "${HOME_DIR:?}"/leeloo/include/install "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/robot/ "$SYS_DIR" &>/dev/null
cp -a "${HOME_DIR:?}"/leeloo/include/api/ "$SYS_DIR" &>/dev/null

# END
