#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf

# directories ##################################################################

if [[ ! -d /usr/local/bin/include/leeloo ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo &>/dev/null
fi

if [[ ! -d /usr/local/bin/include/leeloo/robot ]] &>/dev/null; then
  mkdir /usr/local/bin/include/leeloo/robot &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/indicators ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/indicators &>/dev/null
fi

if [[ ! -d "${LOG_DIR:?}"/leeloo/southxchange ]] &>/dev/null; then
  mkdir "${LOG_DIR:?}"/leeloo/southxchange &>/dev/null
fi

# files ########################################################################

if [[ ! -f "$SYS_DIR"/Installed ]] &>/dev/null; then
  cp -a "${HOME_DIR:?}"/leeloo/include/indicators/ "$SYS_DIR" &>/dev/null
  cp -a "${HOME_DIR:?}"/leeloo/include/strategies/ "$SYS_DIR" &>/dev/null
  cp "${HOME_DIR:?}"/leeloo/include/functions "$SYS_DIR" &>/dev/null
  cp -a "${HOME_DIR:?}"/leeloo/include/robot/ "$SYS_DIR" &>/dev/null
  cp -a "${HOME_DIR:?}"/leeloo/include/api/ "$SYS_DIR" &>/dev/null
  echo "$(date | xargs)" >"$SYS_DIR"/Installed
fi

# END
