#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

WHOAMI="$(whoami)"

################################################################################

function irssi_first_run() {
  # first time startup
  if [[ ! -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then
    echo "Installing configuration, please wait.."
    sleep 1
    clear
    timeout 1 irssi &
    pidof irssi &>/dev/null
  fi
  # sleep so loc above works.
  sleep 1

  # update default irssi settings, log connections successfully made
  if [[ -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then
    if [[ "$(grep "Bearish" /home/"$WHOAMI"/.irssi/config 2>/dev/null | wc -l)" -eq "0" ]] &>/dev/null; then

      # get config size by lines
      CONFIG_SIZE="$(wc -l /home/"$WHOAMI"/.irssi/config 2>/dev/null | awk '{ print $1 }')"

      # disregard n last lines from config
      echo "$(head -"$(echo "$CONFIG_SIZE-4" | bc 2>/dev/null)" /home/"$WHOAMI"/.irssi/config)" >/home/"$WHOAMI"/.irssi/config 2>/dev/null

      # add new lines to config
      # log all minus public and private
      cat >>/home/"$WHOAMI"/.irssi/config 2>/dev/null <<'EOF'
settings = {
core = {
real_name = "Bearish";
user_name = "Bullish";
};
"fe-text" = { actlist_sort = "refnum"; };
"fe-common/core" = {
  autolog = "yes";
  autolog_path = ".irssi/irclogs/$tag/$0.log";
  autolog_level = "ALL -PUBLIC -PRIVATE";
  };
};
EOF
    fi
  fi
}

################################################################################

# start irc chat
function irc_chat() {
  # get irc server list
  if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.servers ]] &>/dev/null; then
    echo "Downloading IRC server list.."
    # proxy configuration = true
    if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
      # with proxy
      curl -s --proxy socks5h://localhost:9050 https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null
    else
      curl -s https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null
    fi
  fi

  ##############################################################################

  # missing directory, continue
  if [[ ! -d /home/"$WHOAMI"/.irssi/irclogs/ ]] &>/dev/null; then
    mkdir /home/"$WHOAMI"/.irssi/irclogs/ &>/dev/null
  fi

  # missing file, continue
  if [[ ! -f /home/"$WHOAMI"/.irssi/irc.servers ]] &>/dev/null; then
    cat "${LOG_DIR:?}"/leeloo/irc.servers | egrep '[.]' | awk '!a[$0]++' | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null
  fi

  ##############################################################################

  # proxy configuration = true
  if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
    PROXY_CONFIG_STATUS="Enabled"
  else
    PROXY_CONFIG_STATUS="Disabled"
  fi

  ##############################################################################

  # irssi status
  if [[ "$(pidof irssi 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    IRSSI_COM_STATUS="Online"
  else
    IRSSI_COM_STATUS="Offline"
  fi
  # tor status
  if [[ "$(pidof tor 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    PROXY_COM_STATUS="Online"
  else
    PROXY_COM_STATUS="Offline"
  fi

  ##############################################################################

  # get irssi version
  if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.client ]] &>/dev/null; then
    echo "$(irssi -v 2>/dev/null)" | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.client 2>/dev/null
  fi
  IRSSI_CLIENT="$(cat "${LOG_DIR:?}"/leeloo/irc.client 2>/dev/null | xargs | awk '{ print $1,$2 }' | sed '/^$/d')"

  # zero, continue
  if [[ ! -s "${LOG_DIR:?}"/leeloo/irc.client ]] &>/dev/null; then
    IRSSI_CLIENT="Not installed"
  fi

  # get tor version
  if [[ ! -f "${LOG_DIR:?}"/leeloo/tor.client ]] &>/dev/null; then
    echo "$(tor --version 2>/dev/null)" | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/tor.client 2>/dev/null
  fi

  # zero, continue
  PROXY_CLIENT="$(cat "${LOG_DIR:?}"/leeloo/tor.client 2>/dev/null | xargs | sed '/^$/d')"
  if [[ ! -s "${LOG_DIR:?}"/leeloo/tor.client ]] &>/dev/null; then
    PROXY_CLIENT="Not installed"
  fi

  # banned on connect ##########################################################

  cat /home/"$WHOAMI"/.irssi/irclogs/*/* 2>/dev/null | egrep "Banned|banned|Ban|ban" | awk -F! '{ print $2 }' | awk '{ print $1 }' >/home/"$WHOAMI"/.irssi/irc.banned

  ##############################################################################

  # check if irc.connect file exists, create it if not
  if [[ ! -f /home/"$WHOAMI"/.irssi/irc.connect ]] &>/dev/null; then
    touch /home/"$WHOAMI"/.irssi/irc.connect &>/dev/null
  fi

  # list files in irclogs directory and extract their names
  ls -l /home/"$WHOAMI"/.irssi/irclogs/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }' | sed 's/.*\s//' >/home/"$WHOAMI"/.irssi/irclogs.tmp

  # iterate over the log file names and check if they exist in the connections file
  while read -r LOG_FILE; do
    MATCH=$(grep -F "$LOG_FILE" /home/"$WHOAMI"/.irssi/connections 2>/dev/null)
    if [[ -n "$MATCH" ]] &>/dev/null; then
      echo "$MATCH" >>/home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null
    fi
  done </home/"$WHOAMI"/.irssi/irclogs.tmp

  # remove temporary file
  rm /home/"$WHOAMI"/.irssi/irclogs.tmp

  # Get the last connected server from connections file
  IRSSI_CONNECTED="$(tail -n 1 /home/"$WHOAMI"/.irssi/connections 2>/dev/null)"

  # List files in irclog directory and extract the names of those that contain the last connected server
  ls -l /home/"$WHOAMI"/.irssi/irclog/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }' | grep "$IRSSI_CONNECTED" >"${LOG_DIR:?}"/leeloo/irc.tmp

  # Count the number of lines in irc.servers file and use it to extract the last n lines from irc.disconnect file
  DISCONNECT_TIMER="$(wc -l "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null | awk '{ print $1 }')"
  if [[ "$(grep -c "$IRSSI_CONNECTED" "${LOG_DIR:?}"/leeloo/irc.tmp 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    # If the server is not found in the list, append the last connected server to the irc.disconnect file
    echo "$IRSSI_CONNECTED" >>/home/"$WHOAMI"/.irssi/irc.disconnect
    # Remove duplicate and empty lines from irc.disconnect file
    tail -"$DISCONNECT_TIMER" /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null | awk '!a[$0]++' | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.disconnect.tmp
    mv /home/"$WHOAMI"/.irssi/irc.disconnect.tmp /home/"$WHOAMI"/.irssi/irc.disconnect
  fi

  # chat menu ##################################################################

  HEIGHT=15
  WIDTH=43
  CHOICE_HEIGHT=7
  BACKTITLE="Leeloo (Multipass)"
  TITLE="IRC Chat"
  MENU="Multipass $DATE
Client: $IRSSI_COM_STATUS Proxy: $PROXY_COM_STATUS"

  OPTIONS=(1 "Chat             Connect/irssi"
    2 "Servers          IRC Servers"
    3 "Status           IRC Status"
    4 "Install          Install client"
    5 "Remove           Remove client"
    6 "Config           Configuration"
    7 "Reset            Reset Client")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  # irc chat ###################################################################

  "1")

    # zero server configuration set, continue
    if [[ -z "$IRSSI_SERVER" ]] &>/dev/null; then

      ##########################################################################

      # disregard connected servers
      if [[ "$(wc -l /home/"$WHOAMI"/.irssi/irc.connect | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then
        echo "$(cat /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null | egrep '[.]' | awk -F. '{ print $2 }')" >"${LOG_DIR:?}"/c.tmp 2>/dev/null
        echo "$(grep -vf "${LOG_DIR:?}"/c.tmp "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null)" >/home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null
        rm "${LOG_DIR:?}"/c.tmp &>/dev/null
      fi

      ##########################################################################

      # disregard disconnected servers
      if [[ "$(wc -l /home/"$WHOAMI"/.irssi/irc.disconnect | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then
        echo "$(cat /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null | egrep '[.]' | awk -F. '{ print $2 }')" >"${LOG_DIR:?}"/dc.tmp 2>/dev/null
        echo "$(grep -vf "${LOG_DIR:?}"/dc.tmp "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null)" >/home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null
        rm "${LOG_DIR:?}"/dc.tmp &>/dev/null
      fi

      ##########################################################################
      # random server, port list ###############################################
      ##########################################################################

      # irc servers, remove duplicates, empty lines
      IRSSI_IRC_SERVERS="$(cat /home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null | egrep '[.]' | sort | awk '!a[$0]++' | sed '/^$/d')"

      # pick random server list
      RANDOM_SERVER_LIST=$((((RANDOM % 2) + 1)))

      if [[ "$RANDOM_SERVER_LIST" -eq "1" ]] &>/dev/null; then
        # random irc server
        IRSSI_RANDOM_SERVER="$(echo "$IRSSI_IRC_SERVERS" | sort -R | head -1)"
      else
        # disconnect timer
        IRSSI_RANDOM_TIMER="$(wc -l "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null | awk '{ print $1 }')"
        # random irc.connect server
        IRSSI_IRC_CONNECT_SERVER="$(tail -"$IRSSI_RANDOM_TIMER" /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null | sort -R | head -1)"
        IRSSI_RANDOM_SERVER="$(echo "$IRSSI_IRC_CONNECT_SERVER" | awk '{ print $1 }')"
        IRSSI_PORT="$(echo "$IRSSI_IRC_CONNECT_SERVER" | awk '{ print $2 }')"
      fi

      # disregard banned ports combined with server ############################

      if grep -q "$IRSSI_RANDOM_SERVER" /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null; then
        # port is banned
        BANNED=$(grep "$IRSSI_RANDOM_SERVER" /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null | awk '{ print $2 }' | sed '/^$/d' | xargs)
        echo "$BANNED" >/home/"$WHOAMI"/.irssi/irc.ports
      fi

      # random irc ports
      IRSSI_PORT_LIST=(6661 6662 6663 6664 6665 6666 6667 6668 6669 6697 7000 7001 8000)
      VALID_PORTS=()

      for PORT in "${IRSSI_PORT_LIST[@]}"; do
        if ! echo "$BANNED" | grep -qw "$PORT" &>/dev/null; then
          VALID_PORTS+=("$PORT")
        fi
      done

      if [[ ${#VALID_PORTS[@]} -eq 0 ]] &>/dev/null; then
        # all ports are banned, exit with error
        display_result() {
          dialog --title "IRC ports are banned: $IRSSI_RANDOM_SERVER" \
            --no-collapse \
            --msgbox "$RESULT" 5 40
        }
        RESULT="$(echo "All IRC ports are banned for server!")"
        display_result 2>/dev/null
      else
        IRSSI_INDEX=$((RANDOM % ${#VALID_PORTS[@]}))
        IRSSI_RANDOM_PORT="${VALID_PORTS[$IRSSI_INDEX]}"
      fi
    fi

    ############################################################################
    # random server, port after calculations ###################################
    ############################################################################

    # random server
    IRSSI_SERVER="$IRSSI_RANDOM_SERVER"

    # zero, random port
    if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
      IRSSI_PORT="$IRSSI_RANDOM_PORT"
    fi

    # no irc configuration is set ##############################################

    # irc servers
    IRSSI_IRC_SERVERS_RAW="$(cat "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null)"

    # zero, default random nickname
    if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
      IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
    fi
    # zero, default random server
    if [[ -z "$IRSSI_SERVER" ]] &>/dev/null; then
      IRSSI_SERVER="$(echo "$IRSSI_IRC_SERVERS_RAW" | sort -R | head -1)"
    fi
    # zero, default port
    if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
      IRSSI_PORT="6667"
    fi

    # result before connection #################################################

    display_result() {
      dialog --title "IRC Chat (irssi)" \
        --no-collapse \
        --msgbox "$RESULT" 13 "$(echo "$(echo "$RESULT" | wc -L)+6" | bc 2>/dev/null)"
    }

    RESULT="$(echo "IRC Client...: $IRSSI_CLIENT
Status.......: $IRSSI_COM_STATUS
Server.......: $IRSSI_SERVER
Port.........: $IRSSI_PORT
Nick.........: $IRSSI_NICKNAME
Proxy Client.: $PROXY_CLIENT
Status.......: $PROXY_COM_STATUS
Config.......: $PROXY_CONFIG_STATUS
COMMANDS.....: /help")"
    display_result 2>/dev/null

    # confirm start ############################################################

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      WIDTH="$(echo "$(echo "$IRSSI_SERVER" | wc -L)+18" | bc 2>/dev/null)"
      if [[ "$WIDTH" -lt "30" ]] &>/dev/null; then
        WIDTH="30"
      fi
      if dialog --stdout --title "Connect to $IRSSI_SERVER?" \
        --backtitle "Connecting $IRSSI_SERVER $IRSSI_PORT" \
        --yesno "Yes: Connect!, No: irssi" 5 "$WIDTH"; then

        clear
        irssi_first_run

        # proxy configuration = true
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then

          # get connection info
          echo "$IRSSI_SERVER $IRSSI_PORT" >/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # start irssi
          torify irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
          clear
        else

          # get connection info
          echo "$IRSSI_SERVER $IRSSI_PORT" >/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # start irssi
          irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
          clear
        fi

        # normal start #########################################################

      else
        # proxy configuration = true
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
          torify irssi
          clear
        else
          irssi
          clear
        fi
      fi
      clear
    else
      no_irssi_no_access
    fi

    ;;

    # irc servers ##############################################################

  "2")

    nano "${LOG_DIR:?}"/leeloo/irc.servers

    ;;

    # chat information #########################################################

  "3")

    # server list
    IRSSI_SERVER_LIST="$(wc -l "${LOG_DIR:?}"/leeloo/irc.servers 2>/dev/null | awk '{ print $1 }')"
    IRSSI_SERVER_LIST_FILTERED="$(wc -l /home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null | awk '{ print $1 }')"
    IRSSI_SERVER_LIST_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_LIST*$IRSSI_SERVER_LIST_FILTERED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    IRSSI_CONNECTED_TOTAL="$(wc -l /home/"$WHOAMI"/.irssi/irc.connect | awk '{ print $1 }')"
    IRSSI_CONNECTED_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_LIST*$IRSSI_CONNECTED_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    IRSSI_DISCONNECT_TOTAL="$(wc -l /home/"$WHOAMI"/.irssi/irc.disconnect | awk '{ print $1 }')"
    IRSSI_DISCONNECT_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_LIST*$IRSSI_DISCONNECT_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    IRSSI_BANNED_TOTAL="$(wc -l /home/"$WHOAMI"/.irssi/irc.banned | awk '{ print $1 }')"
    IRSSI_BANNED_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_LIST*$IRSSI_BANNED_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    if [[ -z "$IRSSI_SERVER_LIST" ]] &>/dev/null; then
      IRSSI_SERVER_LIST="0"
    fi
    if [[ -z "$IRSSI_SERVER_LIST_FILTERED" ]] &>/dev/null; then
      IRSSI_SERVER_LIST_FILTERED="0"
    fi
    if [[ -z "$IRSSI_SERVER_LIST_FILTERED_PERCENTAGE" ]] &>/dev/null; then
      IRSSI_SERVER_LIST_FILTERED_PERCENTAGE="0"
    fi
    if [[ "$(echo "$IRSSI_SERVER_LIST_FILTERED_PERCENTAGE" | awk -F. '{ print $1 }')" -eq "100" ]] &>/dev/null; then
      IRSSI_SERVER_LIST_FILTERED_PERCENTAGE="100"
    fi

    display_result() {
      dialog --title "IRC Chat information" \
        --no-collapse \
        --msgbox "$RESULT" 13 "$(echo "$(echo "$RESULT" | wc -L)+6" | bc 2>/dev/null)"
    }

    RESULT="IRC Client...: $IRSSI_CLIENT $IRSSI_VERSION
IRC Status...: $IRSSI_COM_STATUS
IRC Servers..: $IRSSI_SERVER_LIST
Banned.......: $IRSSI_BANNED_TOTAL (${IRSSI_BANNED_FILTERED_PERCENTAGE:?}%)
Connected....: $IRSSI_CONNECTED_TOTAL (${IRSSI_CONNECTED_FILTERED_PERCENTAGE:?}%)
Disconnect...: $IRSSI_DISCONNECT_TOTAL (${IRSSI_DISCONNECT_FILTERED_PERCENTAGE:?}%)
IRC Servers..: $IRSSI_SERVER_LIST_FILTERED (${IRSSI_SERVER_LIST_FILTERED_PERCENTAGE:?}%) *
Proxy Client.: $PROXY_CLIENT $PROXY_VERSION
Proxy Status.: $PROXY_COM_STATUS $PROXY_CONFIG_STATUS"
    display_result 2>/dev/null

    ;;

    # install client ###########################################################

  "4")

    if dialog --stdout --title "Install IRC Client?" \
      --backtitle "Install client" \
      --yesno "Yes: Install!, No: Quit" 5 30; then
      clear
      sudo apt-get install irssi -y
      rm "${LOG_DIR:?}"/leeloo/irc.client &>/dev/null
      irssi_first_run
      read -r -p "Press Enter to continue" </dev/tty
      echo
    fi

    ;;

    # remove client ############################################################

  "5")

    if dialog --stdout --title "Remove IRC Client?" \
      --backtitle "Remove client" \
      --yesno "Yes: Remove!, No: Quit" 5 30; then
      clear
      sudo apt-get purge --auto-remove irssi -y
      # remove irc.client, config, default.theme
      rm "${LOG_DIR:?}"/leeloo/irc.client &>/dev/null
      rm -R /home/"$WHOAMI"/.irssi &>/dev/null
      read -r -p "Press Enter to continue" </dev/tty
      echo
    fi

    ;;

    # irssi configuration ######################################################

  "6")

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      nano /home/"$WHOAMI"/.irssi/config
    else
      no_irssi_no_access
    fi

    ;;

    ############################################################################

  "7")

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      if dialog --stdout --title "Reset IRC configuration?" \
        --backtitle "Configuration reset" \
        --yesno "Yes: Reset!, No: Quit" 5 30; then
        clear
        # remove config, default.theme, version, servers
        if dialog --stdout --title "Reset IRC Servers?" \
          --backtitle "Server list reset" \
          --yesno "Yes: Reset!, No: Quit" 5 30; then
          rm -R "${LOG_DIR:?}"/leeloo/irc.* &>/dev/null
        fi
        rm -R /home/"$WHOAMI"/.irssi/* &>/dev/null
        irssi_first_run
        exit
      fi
    else
      no_irssi_no_access
    fi

    ;;

    ############################################################################

  esac
  # kill irssi process after exit
  if [[ "$(pidof irssi 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    kill -9 "$(pidof irssi 2>/dev/null)" &>/dev/null
  fi
}

# END
