#!/bin/bash

WHOAMI="$(whoami)"

################################################################################

function irssi_first_run() {
  # first time startup
  if [[ ! -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then
    clear
    echo "Installing configuration, please wait.."
    sleep 1
    timeout 1 irssi &
    pidof irssi &>/dev/null
  fi
  sleep 1
  # update default irssi settings, log connections successfully made
  if [[ -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then
    if [[ "$(grep "Bearish" /home/"$WHOAMI"/.irssi/config 2>/dev/null | wc -l)" -eq "0" ]] &>/dev/null; then
      # get config size by lines
      CONFIG_SIZE="$(wc -l /home/"$WHOAMI"/.irssi/config 2>/dev/null | awk '{ print $1 }')"
      # disregard n last lines from config
      echo "$(head -"$(echo "$CONFIG_SIZE-4" | bc 2>/dev/null)" /home/"$WHOAMI"/.irssi/config)" >/home/"$WHOAMI"/.irssi/config 2>/dev/null

      # add new lines to config
      cat >>/home/"$WHOAMI"/.irssi/config 2>/dev/null <<'EOF'
settings = {
core = {
real_name = "Bearish";
user_name = "Bullish";
};
"fe-text" = { actlist_sort = "refnum"; };
"fe-common/core" = {
  autolog = "yes";
  autolog_path = ".irssi/irclogs/$tag/$0.log";
  autolog_level = "ALL -PUBLIC -PRIVATE";
  };
};
EOF
    fi
  fi
}

################################################################################

function irc_chat() {
  # get irc server list
  if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.servers ]] &>/dev/null; then
    if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
      curl -s --proxy socks5h://localhost:9050 https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers
    else
      curl -s https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/irc.servers
    fi
  fi

  ##############################################################################

  # connection status
  if [[ "$(pidof irssi | wc -l)" -gt "0" ]] &>/dev/null; then
    IRSSI_COM_STATUS="Online"
  else
    IRSSI_COM_STATUS="Offline"
  fi
  if [[ "$(pidof tor | wc -l)" -gt "0" ]] &>/dev/null; then
    PROXY_COM_STATUS="Online"
  else
    PROXY_COM_STATUS="Offline"
  fi

  ##############################################################################

  # get version
  if [[ ! -f "${LOG_DIR:?}"/leeloo/irc.client ]] &>/dev/null; then
    echo "$(irssi -v 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/irc.client
  fi
  if [[ ! -f "${LOG_DIR:?}"/leeloo/tor.client ]] &>/dev/null; then
    echo "$(tor --version 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/tor.client
  fi

  # get raw data
  IRSSI_RAW="$(cat "${LOG_DIR:?}"/leeloo/irc.client 2>/dev/null)"
  PROXY_RAW="$(cat "${LOG_DIR:?}"/leeloo/tor.client 2>/dev/null)"

  # zero, continue
  if [[ -z "$IRSSI_RAW" ]] &>/dev/null; then
    IRSSI_RAW="?"
  fi
  if [[ -z "$PROXY_RAW" ]] &>/dev/null; then
    PROXY_RAW="?"
  fi

  # irssi data
  IRSSI_NAME="$(echo "$IRSSI_RAW" 2>/dev/null | awk '{ print $1 }')"
  IRSSI_VERSION="$(echo "$IRSSI_RAW" 2>/dev/null | awk '{ print $2 }' | xargs)"

  # zero, continue
  if [[ -z "$IRSSI_NAME" ]] &>/dev/null; then
    IRSSI_NAME="?"
  fi
  if [[ -z "$IRSSI_VERSION" ]] &>/dev/null; then
    IRSSI_VERSION="?"
  fi

  # proxy data
  PROXY_NAME="$(echo "$PROXY_RAW" 2>/dev/null | awk '{ print $1 }')"
  PROXY_VERSION="$(echo "$PROXY_RAW" 2>/dev/null | awk '{ print $3 }' | xargs)"

  # zero, continue
  if [[ -z "$PROXY_NAME" ]] &>/dev/null; then
    PROXY_NAME="?"
  fi
  if [[ -z "$PROXY_VERSION" ]] &>/dev/null; then
    PROXY_VERSION="?"
  fi

  ##############################################################################

  # proxy config
  if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
    PROXY_CONFIG_STATUS="Enabled"
  else
    PROXY_CONFIG_STATUS="Disabled"
  fi

  HEIGHT=15
  WIDTH=45
  CHOICE_HEIGHT=7
  BACKTITLE="Leeloo (Multipass)"
  TITLE="IRC Chat"
  MENU="Multipass $DATE
Client: $IRSSI_COM_STATUS Proxy: $PROXY_COM_STATUS"

  OPTIONS=(1 "Chat             Autoconnect/irssi"
    2 "Servers          IRC Server list"
    3 "Information      IRC Status"
    4 "Install          Install client"
    5 "Remove           Remove client"
    6 "Config           Configuration"
    7 "Reset            Reset Client")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  ##############################################################################

  "1")

    # irc chat
    display_result() {
      dialog --title "IRC Chat (irssi)" \
        --no-collapse \
        --msgbox "$RESULT" 15 "$(echo "$(echo "$RESULT" | wc -L)+6" | bc)"
    }

    # if empty, trigger something
    if [[ -z "$IRSSI_SERVER" ]] &>/dev/null; then
      TRIGGER_SERVER="1"
    fi

    # triggered, continue
    if [[ "$TRIGGER_SERVER" -gt "0" ]] &>/dev/null; then

      # create random connection ###############################################

      # disregard irc.servers with working
      IRSSI_IRC_SERVERS="$(grep -vf /home/"$WHOAMI"/.irssi/working "${LOG_DIR:?}"/leeloo/irc.servers)"
      echo "$IRSSI_IRC_SERVERS" >/home/"$WHOAMI"/.irssi/irc.servers

      # disregard irc.servers with non_working
      IRSSI_IRC_SERVERS="$(grep -vf /home/"$WHOAMI"/.irssi/non_working /home/"$WHOAMI"/.irssi/irc.servers)"
      echo "$IRSSI_IRC_SERVERS" >/home/"$WHOAMI"/.irssi/irc.servers

      # conectable
      IRSSI_P2P_WORKING="$(ls -l /home/"$WHOAMI"/.irssi/irclogs/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }')"
      echo "$IRSSI_P2P_WORKING" >/home/"$WHOAMI"/.irssi/working

      # difficult connections
      IRSSI_NON_WORKING="$(grep -vf /home/"$WHOAMI"/.irssi/working /home/"$WHOAMI"/.irssi/connections)"
      echo "$(echo "$IRSSI_NON_WORKING" | awk '{ print $2 }')" >/home/"$WHOAMI"/.irssi/non_working

      # random irc server
      IRSSI_SERVER="$(echo "$IRSSI_IRC_SERVERS" | sort -R | head -1)"

      # disregard banned ports combined with server
      BANNED="none" # code this!

      # random irc ports
      IRSSI_PORTS=(6661 6662 6663 6664 6665 6666 6667 6668 6669 6697 7000 8000)
      VALID_PORTS=()
      for PORT in "${IRSSI_PORTS[@]}"; do
        if ! [[ "$PORT" =~ $BANNED ]] &>/dev/null; then
          VALID_PORTS+=("$PORT")
        fi
      done
      IRSSI_INDEX=$((RANDOM % ${#VALID_PORTS[@]}))

      ##########################################################################

      # random port
      if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
        IRSSI_PORT="${IRSSI_PORTS[$IRSSI_INDEX]}"
      fi

      # random nickname
      if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
        IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
      fi
    fi

    # default port
    if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
      IRSSI_PORT="6667"
    fi
    # default random nickname
    if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
      IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
    fi

    RESULT="$(echo "IRC Client...: $IRSSI_NAME
Version......: $IRSSI_VERSION
Status.......: $IRSSI_COM_STATUS
Server.......: $IRSSI_SERVER
Port.........: $IRSSI_PORT
Nick.........: $IRSSI_NICKNAME
Proxy Client.: $PROXY_NAME
Version......: $PROXY_VERSION
Status.......: $PROXY_COM_STATUS
Config.......: $PROXY_CONFIG_STATUS
COMMANDS.....: /help")"
    display_result 2>/dev/null

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      if dialog --stdout --title "Connect to $IRSSI_SERVER?" \
        --backtitle "Connecting $IRSSI_SERVER $IRSSI_PORT" \
        --yesno "Yes: Connect!, No: irssi" 5 "$(echo "$(echo "$IRSSI_SERVER" | wc -L)+18" | bc 2>/dev/null)"; then

        irssi_first_run
        COM_CONFIG="$(echo "$(wc -l "${LOG_DIR:?}"/leeloo/irc.servers | awk '{ print $1 }')/2" | bc 2>/dev/null)"

        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then

          # get connection info
          echo "torify $IRSSI_SERVER $IRSSI_PORT" >>/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # remove duplicates
          echo "$(tail -"$COM_CONFIG" /home/"$WHOAMI"/.irssi/connections 2>/dev/null | sort | awk '!a[$0]++')" >/home/"$WHOAMI"/.irssi/connections
          # start irssi
          torify irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
        else

          # get connection info
          echo "public $IRSSI_SERVER $IRSSI_PORT" >>/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # remove duplicates
          echo "$(tail -"$COM_CONFIG" /home/"$WHOAMI"/.irssi/connections 2>/dev/null | sort | awk '!a[$0]++')" >/home/"$WHOAMI"/.irssi/connections
          # start irssi
          irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
        fi

      else
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
          torify irssi
        else
          irssi
        fi
      fi
    else
      no_irssi_no_access
    fi

    ;;

    ############################################################################

  "2")

    nano "${LOG_DIR:?}"/leeloo/irc.servers

    ;;

    ############################################################################

  "3")

    display_result() {
      dialog --title "IRC Chat information" \
        --no-collapse \
        --msgbox "$RESULT" 9 "$(echo "$(echo "$RESULT" | wc -L)+6" | bc)"
    }

    RESULT="IRC Client...: $IRSSI_NAME $IRSSI_VERSION
IRC Status...: $IRSSI_COM_STATUS
IRC Servers..: $(wc -l "${LOG_DIR:?}"/leeloo/irc.servers | awk '{ print $1 }')
Proxy Client.: $PROXY_NAME $PROXY_VERSION
Proxy Status.: $PROXY_COM_STATUS $PROXY_CONFIG_STATUS"
    display_result 2>/dev/null

    ;;

    ############################################################################

  "4")

    if dialog --stdout --title "Install IRC Client?" \
      --backtitle "Install client" \
      --yesno "Yes: Install!, No: Quit" 5 30; then
      clear
      sudo apt-get install irssi -y
      rm "${LOG_DIR:?}"/leeloo/irc.client &>/dev/null
      irssi_first_run
      read -r -p "Press Enter to continue" </dev/tty
      echo
    fi

    ;;

    ############################################################################

  "5")

    if dialog --stdout --title "Remove IRC Client?" \
      --backtitle "Remove client" \
      --yesno "Yes: Remove!, No: Quit" 5 30; then
      clear
      sudo apt-get purge --auto-remove irssi -y
      # remove irc.client, config, default.theme
      rm "${LOG_DIR:?}"/leeloo/irc.client &>/dev/null
      rm -R /home/"$WHOAMI"/.irssi &>/dev/null
      read -r -p "Press Enter to continue" </dev/tty
      echo
    fi

    ;;

    ############################################################################

  "6")

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      nano /home/"$WHOAMI"/.irssi/config
    else
      no_irssi_no_access
    fi

    ;;

    ############################################################################

  "7")

    if [ -x "$(command -v irssi)" ] &>/dev/null; then
      if dialog --stdout --title "Remove IRC config?" \
        --backtitle "Remove config" \
        --yesno "Yes: Remove!, No: Quit" 5 30; then
        # remove config, default.theme
        rm -R /home/"$WHOAMI"/.irssi/* &>/dev/null
        irssi_first_run
        clear
        exit
      fi
    else
      no_irssi_no_access
    fi

    ;;

  esac
  # kill irssi process
  if [[ "$(pidof irssi 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    kill -9 "$(pidof irssi 2>/dev/null)" &>/dev/null
  fi
}

# END
