#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

WHOAMI="$(whoami)"

################################################################################

if [ -x "$(command -v irssi)" ] &>/dev/null; then
  if [[ ! -d "${LOG_DIR:?}"/leeloo/chat ]] &>/dev/null; then
    echo "Installing /chat, please wait.."
    mkdir "${LOG_DIR:?}"/leeloo/chat &>/dev/null
    sleep 1
  fi
  if [[ ! -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then
    echo "Installing /.irssi, please wait.."
    mkdir /home/"$WHOAMI"/.irssi &>/dev/null
    sleep 1
  fi
fi

################################################################################

# disregard non irc servers
NOT_A_SERVER=".CAIRC|tor|tor-exit|-exit|discord.gg|.int|.html|.php|.pdf|.ip|.IP"

################################################################################

function irssi_first_run() {
  # first time startup
  if [[ ! -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then

    echo "Installing configuration, please wait.."
    sleep 1
    clear
    timeout 1 irssi &
    pidof irssi &>/dev/null
  fi
  # sleep so loc above works.
  sleep 1

  # update default irssi settings, log connections successfully made
  if [[ -f /home/"$WHOAMI"/.irssi/config ]] &>/dev/null; then
    if [[ "$(grep "Bearish" /home/"$WHOAMI"/.irssi/config 2>/dev/null | wc -l)" -eq "0" ]] &>/dev/null; then

      # get config size by lines
      CONFIG_SIZE="$(wc -l /home/"$WHOAMI"/.irssi/config 2>/dev/null | awk '{ print $1 }')"

      # disregard n last lines from config
      echo "$(head -"$(echo "$CONFIG_SIZE-4" | bc 2>/dev/null)" /home/"$WHOAMI"/.irssi/config)" >/home/"$WHOAMI"/.irssi/config 2>/dev/null

      # add new lines to config
      # log all minus public and private
      cat >>/home/"$WHOAMI"/.irssi/config 2>/dev/null <<'EOF'
settings = {
core = {
real_name = "Bearish";
user_name = "Bullish";
};
"fe-text" = { actlist_sort = "refnum"; };
"fe-common/core" = {
  autolog = "yes";
  autolog_path = ".irssi/irclogs/$tag/$0.log";
  autolog_level = "ALL -PUBLIC -PRIVATE";
  };
};
EOF
    fi
  fi
}

################################################################################

function irssi_files() {
  IRSSI_IRC_DISCONNECT="$(cat /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null | sed '/^$/d' | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b")"
  IRSSI_IRC_SERVERS="$(cat "${LOG_DIR:?}"/leeloo/chat/irc.servers 2>/dev/null | sed '/^$/d' | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b")"
  IRSSI_IRC_CONNECT="$(cat /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null | sed '/^$/d' | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b")"
  IRSSI_IRC_CONNECT_PORT="$(cat /home/"$WHOAMI"/.irssi/irc.connect_port 2>/dev/null | sed '/^$/d')"
  IRSSI_IRC_WELCOME="$(cat /home/"$WHOAMI"/.irssi/irc.welcome 2>/dev/null | sed '/^$/d' | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b")"
  IRSSI_IRC_BANNED="$(cat /home/"$WHOAMI"/.irssi/irc.banned 2>/dev/null | sed '/^$/d' | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b")"
  IRSSI_IRC_IRCLOGS="$(ls -l /home/"$WHOAMI"/.irssi/irclogs/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }' | sed 's/.*\s//' | sed '/^$/d')"
}

################################################################################

# start irc client
function irc_client() {
  # get irc server list
  if [[ ! -f "${LOG_DIR:?}"/leeloo/chat/irc.servers ]] &>/dev/null; then
    echo "Downloading IRC server list.."
    # proxy configuration = true
    if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
      # with proxy
      curl -s --proxy socks5h://localhost:9050 https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/chat/irc.servers 2>/dev/null
    else
      curl -s https://www.mirc.com/servers.ini | tr -t ':' ' ' | awk '{ print $3 }' | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/chat/irc.servers 2>/dev/null
    fi
  fi

  ##############################################################################

  function proxy_configuration() {
    # proxy configuration = true
    if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
      PROXY_CONFIG_STATUS="Enabled"
    else
      PROXY_CONFIG_STATUS="Disabled"
    fi
  }

  ##############################################################################

  function irssi_status() {
    # irssi status
    if [[ ! -f "${LOG_DIR:?}"/leeloo/chat/pid.irssi ]] &>/dev/null; then
      echo "0" >"${LOG_DIR:?}"/leeloo/chat/pid.irssi 2>/dev/null
    fi
    FILE_TIME_MAX="${BOT_TIMER:?}"
    FILE_TIME="$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/chat/pid.irssi 2>/dev/null)))" 2>/dev/null)"

    # update file
    if [[ "$FILE_TIME" -gt "$FILE_TIME_MAX" ]] &>/dev/null; then
      echo "$(pidof irssi 2>/dev/null | wc -l)" >"${LOG_DIR:?}"/leeloo/chat/pid.irssi 2>/dev/null
    fi

    if [[ "$(cat "${LOG_DIR:?}"/leeloo/chat/pid.irssi 2>/dev/null)" -gt "0" ]] &>/dev/null; then
      IRSSI_COM_STATUS="Online"
    else
      IRSSI_COM_STATUS="Offline"
    fi
  }

  function tor_status() {
    # tor status
    if [[ ! -f "${LOG_DIR:?}"/leeloo/chat/pid.tor ]] &>/dev/null; then
      echo "0" >"${LOG_DIR:?}"/leeloo/chat/pid.tor 2>/dev/null
    fi
    FILE_TIME_MAX="${BOT_TIMER:?}"
    FILE_TIME="$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/chat/pid.tor 2>/dev/null)))" 2>/dev/null)"

    # update file
    if [[ "$FILE_TIME" -gt "$FILE_TIME_MAX" ]] &>/dev/null; then
      echo "$(pidof tor 2>/dev/null | wc -l)" >"${LOG_DIR:?}"/leeloo/chat/pid.tor 2>/dev/null
    fi

    if [[ "$(cat "${LOG_DIR:?}"/leeloo/chat/pid.tor 2>/dev/null)" -gt "0" ]] &>/dev/null; then
      PROXY_COM_STATUS="Online"
    else
      PROXY_COM_STATUS="Offline"
    fi
  }

  ##############################################################################

  function irssi_version() {
    # get irssi version
    if [[ ! -f "${LOG_DIR:?}"/leeloo/chat/irc.client ]] &>/dev/null; then
      echo "$(irssi -v 2>/dev/null)" | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/chat/irc.client 2>/dev/null
    fi
    IRSSI_CLIENT="$(cat "${LOG_DIR:?}"/leeloo/chat/irc.client 2>/dev/null | xargs | sed '/^$/d' | awk '{ print $1,$2 }')"
    # zero, continue
    if [[ ! -s "${LOG_DIR:?}"/leeloo/chat/irc.client ]] &>/dev/null; then
      IRSSI_CLIENT="Not installed"
    fi
  }

  function tor_version() {
    # get tor version
    if [[ ! -f "${LOG_DIR:?}"/leeloo/chat/tor.client ]] &>/dev/null; then
      echo "$(tor --version 2>/dev/null)" | sed '/^$/d' >"${LOG_DIR:?}"/leeloo/chat/tor.client 2>/dev/null
    fi
    # zero, continue
    PROXY_CLIENT="$(cat "${LOG_DIR:?}"/leeloo/chat/tor.client 2>/dev/null | xargs | sed '/^$/d' | awk '{ print $1,$NF }')"
    if [[ ! -s "${LOG_DIR:?}"/leeloo/chat/tor.client ]] &>/dev/null; then
      PROXY_CLIENT="Not installed"
    fi
  }

  ##############################################################################

  function welcome_banned() {
    if [[ -d /home/"$WHOAMI"/.irssi/irclogs/ ]] &>/dev/null; then
      # welcome on connect
      WELCOME_STRING="Welcome|has joined"
      if [[ "$(cat /home/"$WHOAMI"/.irssi/irclogs/*/* 2>/dev/null | egrep -c "$WELCOME_STRING")" -gt "0" ]] &>/dev/null; then
        echo "$(cat /home/"$WHOAMI"/.irssi/irclogs/*/* 2>/dev/null | egrep "$WELCOME_STRING" | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b" | egrep -v "$NOT_A_SERVER" | awk '!a[$0]++' | sed '/^$/d')" >/home/"$WHOAMI"/.irssi/irc.welcome 2>/dev/null
      fi
      # banned on connect
      BANNED_STRING="Banned|banned|Ban|ban|You are not welcome"
      if [[ "$(cat /home/"$WHOAMI"/.irssi/irclogs/*/* 2>/dev/null | egrep -c "$BANNED_STRING")" -gt "0" ]] &>/dev/null; then
        echo "$(cat /home/"$WHOAMI"/.irssi/irclogs/*/* 2>/dev/null | egrep "$BANNED_STRING" | grep -Eo "\\b[a-zA-Z0-9][a-zA-Z0-9.-]*\\.[a-zA-Z]{2,}( [0-9]+)?\\b" | egrep -v "$NOT_A_SERVER" | awk '!a[$0]++' | sed '/^$/d')" >/home/"$WHOAMI"/.irssi/irc.banned 2>/dev/null
      fi
    fi
  }

  ##############################################################################

  function irc_connect() {
    # check if irc.connect file exists, create it if not
    if [[ ! -f /home/"$WHOAMI"/.irssi/irc.connect ]] &>/dev/null; then
      touch /home/"$WHOAMI"/.irssi/irc.connect &>/dev/null
    fi

    # list files in irclogs directory and extract their names
    if [[ -d /home/"$WHOAMI"/.irssi/irclogs/ ]] &>/dev/null; then
      ls -l /home/"$WHOAMI"/.irssi/irclogs/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }' | sed 's/.*\s//' >/home/"$WHOAMI"/.irssi/irclogs.tmp 2>/dev/null

      # iterate over the log file names and check if they exist in the connections file
      while read -r LOG_FILE; do
        MATCH=$(grep -F "$LOG_FILE" /home/"$WHOAMI"/.irssi/connections 2>/dev/null)
        if [[ -n "$MATCH" ]] &>/dev/null; then
          # without port
          echo "$MATCH" >>/home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null
          echo "$(cat /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null | egrep -v "$NOT_A_SERVER" | awk '{ print $1 }' | sed -r '/^\s*$/d' | sort | awk '!a[$0]++' | sed -r '/^.{,2}$/d')" >/home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null
          # with port
          echo "$MATCH" >>/home/"$WHOAMI"/.irssi/irc.connect_port 2>/dev/null
          echo "$(cat /home/"$WHOAMI"/.irssi/irc.connect_port 2>/dev/null | egrep -v "$NOT_A_SERVER" | sed -r '/^\s*$/d' | sort | awk '!a[$1]++' | sed -r '/^.{,2}$/d')" >/home/"$WHOAMI"/.irssi/irc.connect_port 2>/dev/null
        fi
      done </home/"$WHOAMI"/.irssi/irclogs.tmp 2>/dev/null

      # remove temporary file
      rm /home/"$WHOAMI"/.irssi/irclogs.tmp 2>/dev/null
    fi
  }

  ##############################################################################

  function irc_disconnect() {
    # check if irc.disconnect file exists, create it if not
    if [[ ! -f /home/"$WHOAMI"/.irssi/irc.disconnect ]] &>/dev/null; then
      touch /home/"$WHOAMI"/.irssi/irc.disconnect &>/dev/null
    fi

    # get the last connected server from connections file
    IRSSI_CONNECTED="$(tail -n 1 /home/"$WHOAMI"/.irssi/connections 2>/dev/null)"

    # list files in irclog directory and extract the names of those that contain the last connected server
    ls -l /home/"$WHOAMI"/.irssi/irclog/ 2>/dev/null | egrep -v "total [0-9]+" | awk '{ print $NF }' | grep "$IRSSI_CONNECTED" >"${LOG_DIR:?}"/leeloo/chat/irc.tmp 2>/dev/null

    if [[ "$(grep -c "$IRSSI_CONNECTED" "${LOG_DIR:?}"/leeloo/chat/irc.tmp 2>/dev/null)" -eq "0" ]] &>/dev/null; then
      # if the server is not found in the list, append the last connected server to the irc.disconnect file
      echo "$IRSSI_CONNECTED" 2>/dev/null >>/home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null

      # remove duplicates and empty lines from irc.disconnect file
      sort /home/"$WHOAMI"/.irssi/irc.disconnect 2>/dev/null | awk '!a[$0]++' | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.disconnect.tmp 2>/dev/null
      mv /home/"$WHOAMI"/.irssi/irc.disconnect.tmp /home/"$WHOAMI"/.irssi/irc.disconnect &>/dev/null
    fi

    # remove temporary file
    rm "${LOG_DIR:?}"/leeloo/chat/irc.tmp &>/dev/null
  }

  ##############################################################################

  # configuration
  IRSSI_SERVER_STATUS="$(egrep "IRSSI_SERVER=" "${SYS_DIR:?}"/broker.conf 2>/dev/null | tr -d '"' | egrep "IRSSI_SERVER=[aA0-zZ9]+" | awk -F= '{ print $2 }' | sed '/^$/d' | wc -l)"
  IRSSI_PORT_STATUS="$(egrep "IRSSI_PORT=" "${SYS_DIR:?}"/broker.conf 2>/dev/null | tr -d '"' | egrep "IRSSI_PORT=[0-9]+" | awk -F= '{ print $2 }' | sed '/^$/d' | wc -l)"

  ##############################################################################

  function random_server() {

    echo "$IRSSI_IRC_SERVERS" | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.servers
    echo "$IRSSI_IRC_IRCLOGS" | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.irclogs
    echo "$IRSSI_IRC_WELCOME" | sed '/^$/d' >/home/"$WHOAMI"/.irssi/irc.welcome

    ############################################################################

    # irc.irclogs
    function irssi_servers_irclogs() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_IRCLOGS" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -11 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_LIST="irc.irclogs"
    }

    # irc.banned
    function irssi_servers_banned() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_BANNED" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -21 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_LIST="irc.banned"
    }

    # irc.welcome
    function irssi_servers_welcome() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_WELCOME" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -21 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_LIST="irc.welcome"
    }

    # irc.connect
    function irssi_servers_connect() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_CONNECT" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -21 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_LIST="irc.connect"
    }

    # irc.connect
    function irssi_servers_connect_port() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_CONNECT_PORT" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -21 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_PORT="$(echo $IRSSI_RANDOM_PORT)"
      IRSSI_LIST="irc.connect_port"
    }

    # irc.servers
    function irssi_servers_list() {
      # disregard with not_a_server, words less than n
      IRSSI_RANDOM_DATA="$(echo "$IRSSI_IRC_SERVERS" | egrep -v "$NOT_A_SERVER" | sed -r '/^.{,2}$/d' | sort -R | head -21 | sort -R | head -1)"
      IRSSI_RANDOM_HOST="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $1 }')"
      IRSSI_RANDOM_PORT="$(echo "$IRSSI_RANDOM_DATA" | awk '{ print $2 }')"
      IRSSI_SERVER="$(echo "$IRSSI_RANDOM_HOST")"
      IRSSI_LIST="irc.servers"
    }

    ############################################################################

    function no_list() {
      if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null)" -gt "0" ]] &>/dev/null; then
        irssi_servers_list
      else
        IRSSI_LIST="irc.random"
        IRSSI_RANDOM_LENGTH=$((((RANDOM % 12) + 4)))
        IRSSI_SERVER="$(tr -dc '0a-z9' </dev/urandom 2>/dev/null | head -c "$IRSSI_RANDOM_LENGTH" | rev)"
      fi
    }

    ############################################################################

    # zero server configuration set, continue
    if [[ "$IRSSI_SERVER_STATUS" -eq "0" ]] &>/dev/null; then
      # pick random server list
      RANDOM_SERVER_LIST=$((((RANDOM % 7) + 1)))

      # random 1 (irc.servers)
      if [[ "$RANDOM_SERVER_LIST" -eq "1" ]] &>/dev/null; then
        no_list
      elif [[ "$RANDOM_SERVER_LIST" -eq "2" ]] &>/dev/null; then
        # random 2 (irc.connect_port) should work
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.connect_port 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          irssi_servers_connect_port
        else
          no_list
        fi
      elif [[ "$RANDOM_SERVER_LIST" -eq "3" ]] &>/dev/null; then
        # random 3 (irc.connect)
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          irssi_servers_connect
        else
          no_list
        fi
      elif [[ "$RANDOM_SERVER_LIST" -eq "4" ]] &>/dev/null; then
        # random 4 (irc.welcome)
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.welcome 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          irssi_servers_welcome
        else
          no_list
        fi
      elif [[ "$RANDOM_SERVER_LIST" -eq "5" ]] &>/dev/null; then
        # random 5 (irc.banned)
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.banned 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          irssi_servers_banned
        else
          no_list
        fi
      elif [[ "$RANDOM_SERVER_LIST" -eq "6" ]] &>/dev/null; then
        # random 6 (irc.irclogs)
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.irclogs 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          irssi_servers_irclogs
        else
          no_list
        fi
      elif [[ "$RANDOM_SERVER_LIST" -eq "7" ]] &>/dev/null; then
        # random 7 (irc.servers) again
        if [[ "$(egrep -c "[Aa0-Zz9]" /home/"$WHOAMI"/.irssi/irc.servers 2>/dev/null)" -gt "0" ]] &>/dev/null; then
          no_list
        fi
      fi

    else
      # configuration is set
      IRSSI_RANDOM_HOST="$IRSSI_SERVER"
    fi
  }

  ##############################################################################

  function random_port() {
    # read the contents of irc.disconnect file
    BANNED_PORTS=$(echo "$IRSSI_IRC_DISCONNECT")
    # random IRC ports
    IRSSI_PORT_LIST=(6661 6662 6663 6664 6665 6666 6667 6668 6669 6670 6671 6672 6677 6697 7000 7001 7158 7667 8000)
    VALID_PORTS=()
    for PORT in "${IRSSI_PORT_LIST[@]}"; do
      # check if the combination of server and port is not banned
      if ! echo "$BANNED_PORTS" | grep -qw "$IRSSI_RANDOM_HOST $PORT"; then
        VALID_PORTS+=("$PORT")
      fi
    done
    if [[ ${#VALID_PORTS[@]} -eq 0 ]]; then
      IRSSI_PORTS_ALL_BANNED="!"
      IRSSI_PORT="$(echo "${IRSSI_PORT_LIST[@]}" | tr ' ' '\n' | sort -R | head -1)"
    else
      # choose a random port from the valid ports
      IRSSI_INDEX=$((RANDOM % ${#VALID_PORTS[@]}))
      IRSSI_PORT="${VALID_PORTS[$IRSSI_INDEX]}"
    fi
    # first time connection
    if [[ "$(echo "$IRSSI_IRC_DISCONNECT" | grep "$IRSSI_RANDOM_HOST" | grep -c "6667")" -eq "0" ]] &>/dev/null; then
      IRSSI_PORT="6667"
    fi
  }

  # chat menu ##################################################################

  irssi_status
  tor_status

  HEIGHT=15
  WIDTH=43
  CHOICE_HEIGHT=7
  BACKTITLE="Leeloo (Multipass)"
  TITLE="IRC Menu"
  MENU="Multipass $DATE
Client: $IRSSI_COM_STATUS Proxy: $PROXY_COM_STATUS"

  OPTIONS=(1 "Chat             Connect/irssi"
    2 "Servers          IRC Servers"
    3 "Status           IRC Status"
    4 "Install          Install client"
    5 "Remove           Remove client"
    6 "Config           Configuration"
    7 "Reset            Reset Client")

  CHOICE=$(dialog --clear \
    --backtitle "$BACKTITLE" \
    --title "$TITLE" \
    --menu "$MENU" \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

  clear
  case $CHOICE in

  # irc client #################################################################

  "1")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then

      irssi_files

      proxy_configuration

      irssi_status
      tor_status

      irssi_version
      tor_version

      irc_connect
      irc_disconnect

      welcome_banned

      ##########################################################################
      # random server
      ##########################################################################

      random_server

      ##########################################################################
      # no port is set
      ##########################################################################

      # zero, default port
      if [[ -z "$IRSSI_PORT" ]] &>/dev/null; then
        IRSSI_PORT="6667"
      fi

      ##########################################################################
      # random port
      ##########################################################################

      if [[ ! "$RANDOM_SERVER_LIST" -eq "2" ]] &>/dev/null; then
        random_port
      fi

      ##########################################################################
      # no server is set
      ##########################################################################

      # zero, default random server
      if [[ -z "$IRSSI_SERVER" ]] &>/dev/null; then
        IRSSI_SERVER="$(echo "$IRSSI_IRC_SERVERS" | sort -R | head -1)"
      fi

      ##########################################################################
      # port is set
      ##########################################################################

      # port configuration set, continue
      if [[ "$IRSSI_PORT_STATUS" -eq "1" ]] &>/dev/null; then
        IRSSI_PORT="$IRSSI_PORT"
      fi

      ##########################################################################
      # no nickname is set
      ##########################################################################

      # zero, default random nickname
      if [[ -z "$IRSSI_NICKNAME" ]] &>/dev/null; then
        IRSSI_NICKNAME="$(tr -dc '0A-Z9' </dev/urandom 2>/dev/null | head -c 8 | rev)"
      fi

      ##########################################################################
      # setup before connection
      ##########################################################################

      display_result() {
        dialog --title "IRC Client (irssi)" \
          --no-collapse \
          --msgbox "$RESULT" 14 "$(echo "$(echo "$RESULT" | wc -L)+5" | bc 2>/dev/null)"
      }

      RESULT="$(echo "IRC.Client...:  $IRSSI_CLIENT
IRC.Status...:  $IRSSI_COM_STATUS
IRC.Server...:  $IRSSI_SERVER
IRC.List.....:  $IRSSI_LIST
IRC.Port.....:  ${IRSSI_PORT:?} $IRSSI_PORTS_ALL_BANNED
Nickname.....:  $IRSSI_NICKNAME
Proxy.Client.:  $PROXY_CLIENT
Proxy.Status.:  $PROXY_COM_STATUS
Config.......:  $PROXY_CONFIG_STATUS
COMMANDS.....:  /help")"
      display_result 2>/dev/null

      # confirm start ##########################################################

      WIDTH="$(echo "$(echo "$IRSSI_SERVER" | wc -L)+18" | bc 2>/dev/null)"
      if [[ "$WIDTH" -lt "30" ]] &>/dev/null; then
        WIDTH="30"
      fi
      if dialog --stdout --title "Connect to $IRSSI_SERVER?" \
        --backtitle "Connecting $IRSSI_SERVER $IRSSI_PORT" \
        --yesno "Yes: Connect!, No: irssi" 5 "$WIDTH"; then

        clear
        irssi_first_run

        # proxy configuration = true
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then

          # get connection info
          echo "$IRSSI_SERVER $IRSSI_PORT" >/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # start irssi
          torify irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
          clear
        else

          # get connection info
          echo "$IRSSI_SERVER $IRSSI_PORT" >/home/"$WHOAMI"/.irssi/connections 2>/dev/null
          # start irssi
          irssi -c "$IRSSI_SERVER" -p "$IRSSI_PORT" -n "$IRSSI_NICKNAME"
          clear
        fi

        # normal start #########################################################

      else
        # proxy configuration = true
        if [[ "$PROXY_CHAT_API" == "true" ]] &>/dev/null; then
          torify irssi
          clear
        else
          irssi
          clear
        fi
      fi
      clear
    else
      no_irssi_no_access
    fi

    ;;

    # irc servers ##############################################################

  "2")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then
      nano "${LOG_DIR:?}"/leeloo/chat/irc.servers
    else
      no_irssi_no_access
    fi

    ;;

    # chat information #########################################################

  "3")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then

      irssi_files

      proxy_configuration

      irssi_status
      tor_status

      irssi_version
      tor_version

      irc_connect
      irc_disconnect

      welcome_banned

      ##########################################################################

      # potential new irc servers from irc.connect
      if [[ -f /home/"$WHOAMI"/.irssi/irc.connect ]] &>/dev/null; then
        IRSSI_NEW_CONNECT="$(echo "$(grep -vf /home/"$WHOAMI"/.irssi/irc.servers /home/"$WHOAMI"/.irssi/irc.connect 2>/dev/null)" | egrep -c "[Aa0-Zz9]" 2>/dev/null)"
      fi
      if [[ -z "$IRSSI_NEW_CONNECT" ]] &>/dev/null; then
        IRSSI_NEW_CONNECT="0"
      fi

      # potential new irc servers from irc.welcome
      if [[ -f /home/"$WHOAMI"/.irssi/irc.welcome ]] &>/dev/null; then
        IRSSI_NEW_WELCOME="$(echo "$(grep -vf /home/"$WHOAMI"/.irssi/irc.servers /home/"$WHOAMI"/.irssi/irc.welcome 2>/dev/null)" | egrep -c "[Aa0-Zz9]" 2>/dev/null)"
      fi
      if [[ -z "$IRSSI_NEW_WELCOME" ]] &>/dev/null; then
        IRSSI_NEW_WELCOME="0"
      fi

      # potential new irc servers from irc.irclogs
      if [[ -f /home/"$WHOAMI"/.irssi/irc.irclogs ]] &>/dev/null; then
        IRSSI_NEW_IRCLOGS="$(echo "$(grep -vf /home/"$WHOAMI"/.irssi/irc.servers /home/"$WHOAMI"/.irssi/irc.irclogs 2>/dev/null)" | egrep -c "[Aa0-Zz9]" 2>/dev/null)"
      fi
      if [[ -z "$IRSSI_NEW_IRCLOGS" ]] &>/dev/null; then
        IRSSI_NEW_IRCLOGS="0"
      fi

      ##########################################################################

      # total ports
      IRSSI_TOTAL_PORTS="19"

      # servers total
      IRSSI_SERVER_TOTAL="$(echo "$IRSSI_IRC_SERVERS" | sed '/^$/d' | wc -l)"

      # servers total + potential new
      IRSSI_SERVER_TOTAL="$(echo "$IRSSI_SERVER_TOTAL+$IRSSI_NEW_CONNECT+$IRSSI_NEW_WELCOME+$IRSSI_NEW_IRCLOGS" | bc 2>/dev/null)"
      if [[ -z "$IRSSI_SERVER_TOTAL" ]] &>/dev/null; then
        IRSSI_SERVER_TOTAL="0"
      fi

      # total servers * ports
      IRSSI_SERVER_WITH_PORTS=$(echo "$IRSSI_SERVER_TOTAL*$IRSSI_TOTAL_PORTS" | sed '/^$/d' | bc 2>/dev/null)
      if [[ -z "$IRSSI_SERVER_WITH_PORTS" ]] &>/dev/null; then
        IRSSI_SERVER_WITH_PORTS="0"
      fi

      # connected total
      IRSSI_CONNECTED_TOTAL="$(echo "$IRSSI_IRC_CONNECT" | sed '/^$/d' | wc -l)"
      if [[ -z "$IRSSI_CONNECTED_TOTAL" ]] &>/dev/null; then
        IRSSI_CONNECTED_TOTAL="0"
      fi
      IRSSI_CONNECTED_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_WITH_PORTS*$IRSSI_CONNECTED_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
      if [[ -z "$IRSSI_CONNECTED_FILTERED_PERCENTAGE" ]] &>/dev/null; then
        IRSSI_CONNECTED_FILTERED_PERCENTAGE="0"
      fi

      # disconnect total
      IRSSI_DISCONNECT_TOTAL="$(echo "$IRSSI_IRC_DISCONNECT" | sed '/^$/d' | wc -l)"
      if [[ -z "$IRSSI_DISCONNECT_TOTAL" ]] &>/dev/null; then
        IRSSI_DISCONNECT_TOTAL="0"
      fi
      IRSSI_DISCONNECT_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_WITH_PORTS*$IRSSI_DISCONNECT_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
      if [[ -z "$IRSSI_DISCONNECT_FILTERED_PERCENTAGE" ]] &>/dev/null; then
        IRSSI_DISCONNECT_FILTERED_PERCENTAGE="0"
      fi

      # banned total
      IRSSI_BANNED_TOTAL="$(echo "$IRSSI_IRC_BANNED" | sed '/^$/d' | wc -l)"
      if [[ -z "$IRSSI_BANNED_TOTAL" ]] &>/dev/null; then
        IRSSI_BANNED_TOTAL="0"
      fi
      IRSSI_BANNED_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_WITH_PORTS*$IRSSI_BANNED_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
      if [[ -z "$IRSSI_BANNED_FILTERED_PERCENTAGE" ]] &>/dev/null; then
        IRSSI_BANNED_FILTERED_PERCENTAGE="0"
      fi

      # welcome total
      IRSSI_WELCOME_TOTAL="$(echo "$IRSSI_IRC_WELCOME" | sed '/^$/d' | wc -l)"
      if [[ -z "$IRSSI_WELCOME_TOTAL" ]] &>/dev/null; then
        IRSSI_WELCOME_TOTAL="0"
      fi
      IRSSI_WELCOME_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_WITH_PORTS*$IRSSI_WELCOME_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
      if [[ -z "$IRSSI_WELCOME_FILTERED_PERCENTAGE" ]] &>/dev/null; then
        IRSSI_WELCOME_FILTERED_PERCENTAGE="0"
      fi

      # irclogs total
      IRSSI_IRCLOGS_TOTAL="$(echo "$IRSSI_IRC_IRCLOGS" | sed '/^$/d' | wc -l)"
      if [[ -z "$IRSSI_IRCLOGS_TOTAL" ]] &>/dev/null; then
        IRSSI_IRCLOGS_TOTAL="0"
      fi
      IRSSI_IRCLOGS_FILTERED_PERCENTAGE="$(echo "100/$IRSSI_SERVER_WITH_PORTS*$IRSSI_IRCLOGS_TOTAL" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"
      if [[ -z "$IRSSI_IRCLOGS_FILTERED_PERCENTAGE" ]] &>/dev/null; then
        IRSSI_IRCLOGS_FILTERED_PERCENTAGE="0"
      fi

      display_result() {
        dialog --title "IRC Chat information" \
          --no-collapse \
          --msgbox "$(echo "$RESULT" | column -t)" 14 "$(echo "$(echo "$RESULT" | wc -L)+13" | bc 2>/dev/null)"
      }

      RESULT="IRC.Client...: $IRSSI_CLIENT
IRC.Status...: $IRSSI_COM_STATUS
IRC.Servers..: $IRSSI_SERVER_TOTAL:$IRSSI_TOTAL_PORTS/$IRSSI_SERVER_WITH_PORTS
irclogs......: $IRSSI_IRCLOGS_TOTAL ${IRSSI_IRCLOGS_FILTERED_PERCENTAGE:?}%
Welcome......: $IRSSI_WELCOME_TOTAL ${IRSSI_WELCOME_FILTERED_PERCENTAGE:?}%
Banned.......: $IRSSI_BANNED_TOTAL ${IRSSI_BANNED_FILTERED_PERCENTAGE:?}%
Connected....: $IRSSI_CONNECTED_TOTAL ${IRSSI_CONNECTED_FILTERED_PERCENTAGE:?}%
Disconnect...: $IRSSI_DISCONNECT_TOTAL ${IRSSI_DISCONNECT_FILTERED_PERCENTAGE:?}%
Proxy.Client.: $PROXY_CLIENT
Proxy.Status.: $PROXY_COM_STATUS $PROXY_CONFIG_STATUS"
      display_result 2>/dev/null
    else
      no_irssi_no_access
    fi

    ;;

    # install client ###########################################################

  "4")

    if dialog --stdout --title "Install IRC Client?" \
      --backtitle "Install client" \
      --yesno "Yes: Install!, No: Quit" 5 30; then
      clear
      sudo apt-get install irssi -y
      rm "${LOG_DIR:?}"/leeloo/chat/irc.client &>/dev/null
      read -r -p "Press Enter to continue" </dev/tty
      echo
    fi

    ;;

    # remove client ############################################################

  "5")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then
      if dialog --stdout --title "Remove IRC Client?" \
        --backtitle "Remove client" \
        --yesno "Yes: Remove!, No: Quit" 5 30; then
        clear
        sudo apt-get purge --auto-remove irssi -y
        # remove irc.client, config, default.theme
        rm "${LOG_DIR:?}"/leeloo/chat/irc.client &>/dev/null
        rm -R /home/"$WHOAMI"/.irssi &>/dev/null
        read -r -p "Press Enter to continue" </dev/tty
        echo
      fi
    else
      no_irssi_no_access
    fi

    ;;

    # irssi configuration ######################################################

  "6")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then
      nano /home/"$WHOAMI"/.irssi/config
    else
      no_irssi_no_access
    fi

    ;;

    # reset configuration ######################################################

  "7")

    if [[ -d /home/"$WHOAMI"/.irssi ]] &>/dev/null; then
      if dialog --stdout --title "Reset IRC configuration?" \
        --backtitle "Configuration reset" \
        --yesno "Yes: Reset!, No: Quit" 5 30; then
        clear
        # remove config, default.theme, version, servers
        if dialog --stdout --title "Reset IRC Servers?" \
          --backtitle "Server list reset" \
          --yesno "Yes: Reset!, No: Quit" 5 30; then
          rm -R "${LOG_DIR:?}"/leeloo/chat/irc.servers &>/dev/null
        fi
        rm -R /home/"$WHOAMI"/.irssi/* &>/dev/null
        rm -R "${LOG_DIR:?}"/leeloo/chat/irc.client &>/dev/null
        rm -R "${LOG_DIR:?}"/leeloo/chat/tor.client &>/dev/null
        rm -R "${LOG_DIR:?}"/leeloo/chat/pid.* &>/dev/null
        irssi_first_run
        exit
      fi
    else
      no_irssi_no_access
    fi

    ;;

    ############################################################################

  esac
  # kill irssi process after exit
  if [[ "$(pidof irssi 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    kill -9 "$(pidof irssi 2>/dev/null)" &>/dev/null
  fi
}

# END
