#!/bin/bash

# tickers ######################################################################
# https://api.xeggex.com/api/v2/tickers
# Example: tickers

function tickers {
  if [[ "$PROXY_PUBLIC_API" == "true" ]] &>/dev/null; then
    timeout "${API_TIMEOUT:?}" torify curl -s -X GET "https://api.kraken.com/0/public/Ticker" -H "accept: application/json" | jq -r '.result | to_entries[] | "\(.key): \(.value.b[0]) \(.value.a[0]) \(.value.c[0]) \(.value.p[1]) \(.value.v[1])"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}' 2>/dev/null
  else
    timeout "${API_TIMEOUT:?}" curl -s -X GET "https://api.kraken.com/0/public/Ticker" -H "accept: application/json" | jq -r '.result | to_entries[] | "\(.key): \(.value.b[0]) \(.value.a[0]) \(.value.c[0]) \(.value.p[1]) \(.value.v[1])"' | awk 'BEGIN{OFS="\t"} {for(i=2;i<=NF;i++){if($i ~ /^[0-9]+(\.[0-9]+)?$/){if($i < 1){$i=sprintf("%.9f",$i)}else{$i=sprintf("%.2f",$i)}}} print}' 2>/dev/null
  fi
}

# END
