#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# loop
for (( ; ; )); do

  cleanup_log

  ##############################################################################

  # get balance
  result_balance
  sleep 1

  ##############################################################################

  # get orders
  result_orders
  sleep 1

  ##############################################################################

  # get market
  result_market

  ##############################################################################

  if [[ ! -f "${SYS_DIR:?}"/robot/pool ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/pool &>/dev/null
  fi

  # update pool
  echo "Strategy Currency Amount Cost Result Age" >"${SYS_DIR:?}"/robot/pool

  ##############################################################################

  # run all strategies installed
  for f in "${SYS_DIR:?}"/robot/*.strategy; do
    bash "$f"
  done

  ##############################################################################

  # combine all logs, sort by date
  echo "$(sort -t '.' -k 1.3n -k 1.1,1.2n -k 2 "${LOG_DIR:?}"/leeloo/robot.*.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot.log

  ##############################################################################

  sleep "$(echo "$BOT_TIMER-2" | bc 2>/dev/null)"
done

# END
