#!/bin/bash

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# loop
for (( ; ; )); do

  ##############################################################################

  account_private_api
  account_public_api

  ##############################################################################

  cleanup_log

  ##############################################################################

  # get active bots
  LEELOO_RUNNING_BOTS="$(cat "${LOG_DIR:?}"/leeloo/robots 2>/dev/null)"
  # bot timer api
  BOT_TIMER_API="$(echo "$BOT_TIMER-5" | bc 2>/dev/null)"
  # if zero
  if [[ "$BOT_TIMER_API" -lt "5" ]] &>/dev/null; then
    BOT_TIMER_API="5"
  fi

  ##############################################################################
  # poloniex
  ##############################################################################

  # bots running
  if [[ "$(echo "$LEELOO_RUNNING_BOTS" | grep -c "POL")" -gt "0" ]] &>/dev/null; then
    # get poloniex prices
    function result_prices() {
      echo "$(getPrices 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/poloniex/prices 2>/dev/null
    }
    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/poloniex/prices 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER_API" ]] &>/dev/null; then
      result_prices
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/poloniex/prices ]] &>/dev/null; then
      result_prices
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/poloniex/prices ]] &>/dev/null; then
      result_prices
    fi
  fi

  ##############################################################################
  # xeggex
  ##############################################################################

  # bots running
  if [[ "$(echo "$LEELOO_RUNNING_BOTS" | grep -c "XGX")" -gt "0" ]] &>/dev/null; then
    # get xeggex balance
    function result_balances() {
      echo "$(Balances | jq -r '.[] | "\(.asset): \(.held) \(.available) \(.pending)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null
    }
    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER_API" ]] &>/dev/null; then
      result_balances
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/xeggex/balances ]] &>/dev/null; then
      result_balances
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/xeggex/balances ]] &>/dev/null; then
      result_balances
    fi
    sleep 1
  fi

  ##############################################################################

  # bots running
  if [[ "$(echo "$LEELOO_RUNNING_BOTS" | grep -c "XGX")" -gt "0" ]] &>/dev/null; then
    # get xeggex orders
    function result_orders() {
      echo "$(getOrders | jq -r '.[] | "\(.id): \(.side) \(.remainQuantity) \(.quantity) \(.price) \(.market.symbol) \(.updatedAt)"' | awk '{printf "%s %s %s %s %s %s %s\n", $1, $2, $3, $4, $5, $6, strftime("%Y-%m-%dT%H:%M:%S", $7/1000)}' 2>/dev/null | column -t | sed "s/\// /g" | tac)" >"${LOG_DIR:?}"/leeloo/xeggex/orders 2>/dev/null
    }
    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/xeggex/orders 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER_API" ]] &>/dev/null; then
      result_orders
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/xeggex/orders ]] &>/dev/null; then
      result_orders
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/xeggex/orders ]] &>/dev/null; then
      result_orders
    fi
    sleep 1
  fi

  ##############################################################################

  # bots running
  if [[ "$(echo "$LEELOO_RUNNING_BOTS" | grep -c "XGX")" -gt "0" ]] &>/dev/null; then
    # get xeggex prices
    function result_prices() {
      echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null
    }
    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER_API" ]] &>/dev/null; then
      result_prices
      # update data if missing
    elif [[ ! -f "${LOG_DIR:?}"/leeloo/xeggex/prices ]] &>/dev/null; then
      result_prices
      # update data if empty
    elif [[ ! -s "${LOG_DIR:?}"/leeloo/xeggex/prices ]] &>/dev/null; then
      result_prices
    fi
  fi

  ##############################################################################
  # strategy pool & fetch, sort logs
  ##############################################################################

  if [[ ! -f "${SYS_DIR:?}"/robot/pool ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/pool &>/dev/null
  fi

  # update pool
  echo "Exchange Strategy Currency Amount Cost Result Age" >"${SYS_DIR:?}"/robot/pool 2>/dev/null

  ##############################################################################

  # run all shell strategies installed
  for f in "${SYS_DIR:?}"/robot/*.strategy; do

    # error log file
    STRATEGY_LOG_FILE="${LOG_DIR:?}/leeloo/error.log"
    LAST_ERROR=""

    # execute the script and log only the error lines
    {
      # run strategies
      while IFS= read -r line; do
        if echo "$line" | grep -Ei "error|exit status|command not found|syntax error|not found|is empty|permission denied|= ''|\${[A-Za-z0-9_]*}|unbound variable|\$()" >/dev/null; then
          echo "$line"
          LAST_ERROR="$line"
        fi
      done < <(bash "$f" 2>&1) > >(grep -Ei "error|exit status|command not found|syntax error|not found|is empty|permission denied|= ''|\${[A-Za-z0-9_]*}|unbound variable|\$()" >>"$STRATEGY_LOG_FILE")
    }

    # check the exit status of the script
    if [ $? -ne 0 ]; then
      echo "Error occurred while running $f. Check $STRATEGY_LOG_FILE for details." >>"$STRATEGY_LOG_FILE"
      echo "Last error: $LAST_ERROR" >>"$STRATEGY_LOG_FILE"
    fi
  done

  ##############################################################################

  # filter out specific
  LO_FILTER="$(cat "${SYS_DIR:?}"/lo_filter 2>/dev/null)"

  # if zero
  if [[ -z "$LO_FILTER" ]] &>/dev/null; then
    LO_FILTER=": NULL :"
  fi

  ##############################################################################

  # sort all logs by date, remove duplicates, remove empty lines, remove lines with less than n
  echo "$(sort -t ':' -k 1.8,1.21n -k 1.4,1.5n -k 1.1,1.2n "${LOG_DIR:?}"/leeloo/robot.*.log 2>/dev/null | uniq | sed '/^$/d' | awk 'NF >= 6')" >"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  # apply filters
  echo "$(cat "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null | grep -v "${LO_FILTER[@]}")" >"${LOG_DIR:?}"/leeloo/robot.log

  ##############################################################################

  # sort all orders by date, remove duplicates, remove empty lines
  echo "$(sort -t ':' -k 1.8,1.21n -k 1.4,1.5n -k 1.1,1.2n "${SYS_DIR:?}"/robot/*.orders 2>/dev/null | uniq | sed '/^$/d')" >"${SYS_DIR:?}"/robot/orders 2>/dev/null
  # apply filters
  echo "$(cat "${SYS_DIR:?}"/robot/orders 2>/dev/null | grep -v "${LO_FILTER[@]}")" >"${SYS_DIR:?}"/robot/orders

  ##############################################################################

  # create a copy of orders (history)
  cp "${SYS_DIR:?}"/robot/orders "${SYS_DIR:?}"/robot/orders.view &>/dev/null

  # create a copy of pool (positions)
  cat "${SYS_DIR:?}"/robot/pool >"${SYS_DIR:?}"/robot/pool.view 2>/dev/null
  # include dip strategies (positions)
  cat "${SYS_DIR:?}"/robot/*.pool >>"${SYS_DIR:?}"/robot/pool.view 2>/dev/null

  # cleanup pool.view
  echo "$(cat "${SYS_DIR:?}"/robot/pool.view 2>/dev/null | awk '!a[$3]++' | column -t)" >"${SYS_DIR:?}"/robot/pool.view

  ##############################################################################

  # ruled by configuration
  sleep "$BOT_TIMER"
done

# END
