#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/sMcD

source /usr/local/bin/include/leeloo/functions

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# poloniex api
source /usr/local/bin/include/leeloo/api/poloniex/private_API
source /usr/local/bin/include/leeloo/api/poloniex/public_API

# loop
for (( ; ; )); do

  ##############################################################################

  cleanup_log

  ##############################################################################

  # get balance
  function result_balances() {
    echo "$(listBalances 2>/dev/null | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  }
  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER" ]] &>/dev/null; then
    result_balances
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_balances
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/balances ]] &>/dev/null; then
    result_balances
  fi
  sleep 1

  ##############################################################################

  # get orders
  function result_orders() {
    echo "$(listOrders 2>/dev/null | jq -r '.[] | "\(.Code): \(.Type) \(.Amount) \(.OriginalAmount) \(.LimitPrice) \(.ListingCurrency) \(.ReferenceCurrency) \(.DateAdded)"' 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null
  }
  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER" ]] &>/dev/null; then
    result_orders
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/orders ]] &>/dev/null; then
    result_orders
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/orders ]] &>/dev/null; then
    result_orders
  fi
  sleep 1

  ##############################################################################

  # get poloniex prices
  function result_prices() {
    echo "$(getPrices 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/poloniex/prices 2>/dev/null
  }
  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/poloniex/prices 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER" ]] &>/dev/null; then
    result_prices
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/poloniex/prices ]] &>/dev/null; then
    result_prices
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/poloniex/prices ]] &>/dev/null; then
    result_prices
  fi

  ##############################################################################

  # get southxchange prices
  function result_prices() {
    echo "$(prices 2>/dev/null | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null
  }
  # update data every n seconds
  if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null)))" 2>/dev/null)" -gt "$BOT_TIMER" ]] &>/dev/null; then
    result_prices
    # update data if missing
  elif [[ ! -f "${LOG_DIR:?}"/leeloo/southxchange/prices ]] &>/dev/null; then
    result_prices
    # update data if empty
  elif [[ ! -s "${LOG_DIR:?}"/leeloo/southxchange/prices ]] &>/dev/null; then
    result_prices
  fi

  ##############################################################################

  if [[ ! -f "${SYS_DIR:?}"/robot/pool ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/pool &>/dev/null
  fi

  # update pool
  echo "Strategy Currency Amount Cost Result Age" >"${SYS_DIR:?}"/robot/pool 2>/dev/null

  ##############################################################################

  # run all shell strategies installed
  for f in "${SYS_DIR:?}"/robot/*.strategy; do
    bash "$f"
  done

  ##############################################################################

  # sort all logs by date, remove duplicates, remove empty lines
  echo "$(sort -t '/' -k 2.3,2.4n -k 2.1,2.2n "${LOG_DIR:?}"/leeloo/robot.*.log 2>/dev/null | awk '!a[$0]++' | sed '/^$/d')" >"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null

  ##############################################################################

  # remove duplicates, remove empty lines
  echo "$(cat "${SYS_DIR:?}"/robot/*.orders 2>/dev/null | sort -t '/' -k 2.3,2.4n -k 2.1,2.2n | awk '!a[$0]++' | sed '/^$/d')" >"${SYS_DIR:?}"/robot/orders 2>/dev/null

  ##############################################################################

  sleep "$BOT_TIMER"
done

# END
