#!/bin/bash

# set the locale to "C" to use a decimal point as the separator
export LC_NUMERIC=C

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# functions
source /usr/local/bin/include/leeloo/functions

################################################################################

log_date

################################################################################

update_screen

################################################################################

# start screen session if not found
if [[ "$(echo "$SCREEN_LIST" | grep "leeloo" | wc -l)" -eq "0" ]] &>/dev/null; then

  # create a new screen session with logging enabled
  screen -dmSL leeloo -Logfile "$LOG_DIR/leeloo/screen.log"

  # start the leeloo command in the screen session
  screen -S leeloo -p 0 -X stuff "bash ${SYS_DIR}/robot/leeloo >> "$LOG_DIR/leeloo/leeloo.log" 2>&1"$'\n'

  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/leeloo.log 2>/dev/null | awk '{ print $1 }')" ]] &>/dev/null; then
    echo "$(tail -1024 "${LOG_DIR:?}"/leeloo/leeloo.log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/leeloo.log
  fi

  echo "$LOG_DATE : KEK : KEK : Starting robots!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  exit
fi

################################################################################

# nothing is happening for n seconds, while something needs to be happening
if [[ "$(echo "$SCREEN_LIST" | grep "leeloo" 2>/dev/null | wc -l)" -eq "1" ]] &>/dev/null; then

  # the age of all logs measured in seconds
  ROBOT_LOG_AGE_SECONDS="$(stat -c '%Y' "${LOG_DIR:?}"/leeloo/robot.*.log | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done | awk '{ SUM += $1} END { print SUM }')"
  # log file count
  ROBOT_LOG_COUNT="$(ls -l "${LOG_DIR:?}"/leeloo/robot.*.log 2>/dev/null | wc -l)"
  # calculate average seconds
  ROBOT_LOG_AVERAGE="$(echo "$ROBOT_LOG_AGE_SECONDS/$ROBOT_LOG_COUNT" | bc 2>/dev/null)"
  # calculate minutes
  ROBOT_LOG_AGE_MINUTES="$(echo "$ROBOT_LOG_AVERAGE/60" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
  # robot log max age
  ROBOT_LOG_MAX_AGE="300"

  # keep data
  echo "$ROBOT_LOG_AVERAGE" >"${LOG_DIR:?}"/leeloo/robot_average
  echo "$ROBOT_LOG_MAX_AGE" >"${LOG_DIR:?}"/leeloo/robot_max_age

  if [[ "$ROBOT_LOG_AVERAGE" -gt "$ROBOT_LOG_MAX_AGE" ]] &>/dev/null; then

    echo "$LOG_DATE : KEK : KEK : Failing robots! $ROBOT_LOG_AGE_MINUTES minutes behind.." >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null

    # kill leeloo pid (shell)
    echo "$(ps aux 2>/dev/null | grep "leeloo" | awk '{ print $2 }' | xargs)" >"${LOG_DIR:?}"/leeloo/ps_aux
    LEELOO_PID="$(cat "${LOG_DIR:?}"/leeloo/ps_aux 2>/dev/null)"
    kill -9 "$LEELOO_PID" &>/dev/null
    # kill screen
    screen -S "$(echo "$SCREEN_LIST" | grep "leeloo" | awk -F. '{ print $1 }' | head -1 | xargs)".leeloo -p 0 -X quit &>/dev/null
    sleep 1

    echo "$LOG_DATE : KEK : KEK : Stopping robots!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
    sleep 1

    if [[ "$(echo "$SCREEN_LIST" | grep "leeloo" 2>/dev/null | wc -l)" -eq "1" ]] &>/dev/null; then
      echo "$LOG_DATE : KEK : KEK : Still running! Killall screen!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
      killall screen &>/dev/null

      # start looper
      bash "${SYS_DIR:?}"/robot/looper
    fi
  fi
fi

# southxchange #################################################################

# get active robot
SXC_ROBOT_API="$(grep -c "SXC" "${LOG_DIR:?}"/leeloo/robots)"

if [[ -z "$SXC_ROBOT_API" ]] &>/dev/null; then
  SXC_ROBOT_API="0"
fi

# active robot, continue
if [[ "$SXC_ROBOT_API" -gt "0" ]] &>/dev/null; then
  if [[ "$(egrep -c "[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    echo "$LOG_DATE : SXC : KEK : Balances is empty!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  fi
  if [[ "$(egrep -c "[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    echo "$LOG_DATE : SXC : KEK : Orders is empty!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  fi
  if [[ "$(egrep -c "[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    echo "$LOG_DATE : SXC : KEK : Prices is empty!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  fi
fi

# stakecube ####################################################################

# get active robot
SCE_ROBOT_API="$(grep -c "SCE" "${LOG_DIR:?}"/leeloo/robots 2>/dev/null)"

if [[ -z "$SCE_ROBOT_API" ]] &>/dev/null; then
  SCE_ROBOT_API="0"
fi

# active robot, continue
if [[ "$SCE_ROBOT_API" -gt "0" ]] &>/dev/null; then
  if [[ "$(egrep -c "[0-9]+" "${LOG_DIR:?}"/leeloo/stakecube/balances 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    echo "$LOG_DATE : SCE : KEK : Balances is empty!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  fi
  if [[ "$(egrep -c "[0-9]+" "${LOG_DIR:?}"/leeloo/stakecube/prices 2>/dev/null)" -eq "0" ]] &>/dev/null; then
    echo "$LOG_DATE : SCE : KEK : Prices is empty!" >>"${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null
  fi
fi

################################################################################

# END
