#!/bin/bash

source /usr/local/bin/include/leeloo/broker.conf 2>/dev/null

if [[ "$(screen -list | grep "leeloo" | wc -l)" -eq "0" ]] &>/dev/null; then
  # create new screen session
  screen -dmS leeloo &>/dev/null
  # start robot
  screen -S leeloo -X -p 0 stuff $'bash '"${SYS_DIR:?}"'/robot/leeloo\n'
fi

# END
