#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################

function exchange_template() {

  # always public, poloniex, southxchange, stakecube api
  source /usr/local/bin/include/leeloo/api/poloniex/public_API 2>/dev/null
  source /usr/local/bin/include/leeloo/api/southxchange/public_API 2>/dev/null
  source /usr/local/bin/include/leeloo/api/stakecube/public_API 2>/dev/null
  # stakecube, southxchange, poloniex templates
  source /usr/local/bin/include/leeloo/strategies/templates/stakecube 2>/dev/null
  source /usr/local/bin/include/leeloo/strategies/templates/southxchange 2>/dev/null
  source /usr/local/bin/include/leeloo/strategies/templates/poloniex 2>/dev/null

  ##############################################################################

  # poloniex template
  if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/poloniex ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    fi
    # poloniex api
    source /usr/local/bin/include/leeloo/api/poloniex/private_API
  fi

  ##############################################################################

  # southxchange template
  if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/southxchange ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    fi
    # southxchange api
    source /usr/local/bin/include/leeloo/api/southxchange/private_API
  fi

  ##############################################################################

  # stakecube template
  if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/stakecube ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    fi
    # stakecube api
    source /usr/local/bin/include/leeloo/api/stakecube/private_API
  fi

  ##############################################################################

  if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
    EXCHANGE_API="No config!"
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    exit
  fi
}

################################################################################

# END
