#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

source /usr/local/bin/include/leeloo/functions

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################

# run private, public api with broker

# private api
function account_private_api() {
  # poloniex, southxchange, stakecube private api
  source /usr/local/bin/include/leeloo/api/poloniex/private_API
  source /usr/local/bin/include/leeloo/api/southxchange/private_API
  source /usr/local/bin/include/leeloo/api/stakecube/private_API
}
# public api
function account_public_api() {
  # poloniex, southxchange, stakecube public api
  source /usr/local/bin/include/leeloo/api/poloniex/public_API
  source /usr/local/bin/include/leeloo/api/southxchange/public_API
  source /usr/local/bin/include/leeloo/api/stakecube/public_API
}

################################################################################

function exchange_template() {

  # if broker is using this
  if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
    EXCHANGE_API="BROKER"
  fi

  ##############################################################################

  # poloniex template
  if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then

    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/poloniex ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/poloniex
    fi

    # poloniex api
    source /usr/local/bin/include/leeloo/api/poloniex/private_API
    source /usr/local/bin/include/leeloo/api/poloniex/public_API
  fi

  ##############################################################################

  # southxchange template
  if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then

    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/southxchange ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/southxchange
    fi

    # southxchange api
    source /usr/local/bin/include/leeloo/api/southxchange/private_API
    source /usr/local/bin/include/leeloo/api/southxchange/public_API
  fi

  ##############################################################################

  # stakecube template
  if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then

    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/stakecube ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/stakecube
    fi

    # stakecube api
    source /usr/local/bin/include/leeloo/api/stakecube/private_API
    source /usr/local/bin/include/leeloo/api/stakecube/public_API
  fi

  ##############################################################################

  if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
    EXCHANGE_API="No config!"
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    exit
  fi
}

# setup manual market order - southxchange #####################################

function setup_market_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )

  LISTING_CURRENCY="$(echo "$LISTING_CURRENCY" | tr '[:lower:]' '[:upper:]')"
  REFERENCE_CURRENCY="$(echo "$REFERENCE_CURRENCY" | tr '[:lower:]' '[:upper:]')"

  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

# setup manual limit order - southxchange ######################################

function setup_limit_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  REFERENCE_CURRENCY=$(
    dialog --title "Reference Currency (USDT)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )

  LISTING_CURRENCY="$(echo "$LISTING_CURRENCY" | tr '[:lower:]' '[:upper:]')"
  REFERENCE_CURRENCY="$(echo "$REFERENCE_CURRENCY" | tr '[:lower:]' '[:upper:]')"

  LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  LISTING_CURRENCY_PRICE="$LISTING_CURRENCY: $(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $4 }' | head -1)"
  REFERENCE_CURRENCY_PRICE="$REFERENCE_CURRENCY: $(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $4 }' | head -1)"

  AMOUNT=$(
    dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
  PRICE=$(
    dialog --title "Price $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
      --inputbox "Enter price:
$LISTING_CURRENCY_PRICE $REFERENCE_CURRENCY_PRICE" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )
}

################################################################################

# END
