#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# functions
source /usr/local/bin/include/leeloo/functions

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################

install_exchange_dir

################################################################################

# not less than n
if [[ "$BOT_TIMER" -lt "30" || -z "$BOT_TIMER" ]] &>/dev/null; then
  BOT_TIMER="30"
fi

################################################################################

# run private, public api with broker

# private api
function account_private_api() {
  # poloniex, stakecube private api
  source /usr/local/bin/include/leeloo/api/poloniex/private_API
  source /usr/local/bin/include/leeloo/api/stakecube/private_API
  source /usr/local/bin/include/leeloo/api/xeggex/private_API
  source /usr/local/bin/include/leeloo/api/nonkyc/private_API
}
# public api
function account_public_api() {
  # poloniex, stakecube public api
  source /usr/local/bin/include/leeloo/api/poloniex/public_API
  source /usr/local/bin/include/leeloo/api/stakecube/public_API
  source /usr/local/bin/include/leeloo/api/xeggex/public_API
  source /usr/local/bin/include/leeloo/api/nonkyc/public_API
}

################################################################################

# strategy error log
LOG_ERROR="${LOG_DIR:?}/leeloo/error.log"

################################################################################

# report robot count
ROBOT_COUNT="$(echo "$(ls -l "${LOG_DIR:?}"/leeloo/robot.*.log 2>/dev/null)" | wc -l)"

################################################################################

function exchange_template() {

  # if broker is using this
  if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
    EXCHANGE_API="BROKER"
  fi

  ##############################################################################

  # poloniex template
  if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
    EXCHANGE_OUTPUT_NAME="Poloniex"
    EXCHANGE_DIR_NAME="poloniex"
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/poloniex ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      EXCHANGE_DIR_NAME="null"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/poloniex
    fi
    # poloniex api
    source /usr/local/bin/include/leeloo/api/poloniex/private_API
    source /usr/local/bin/include/leeloo/api/poloniex/public_API
  fi

  ##############################################################################

  # stakecube template
  if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
    EXCHANGE_OUTPUT_NAME="StakeCube"
    EXCHANGE_DIR_NAME="stakecube"
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/stakecube ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      EXCHANGE_DIR_NAME="null"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/stakecube
    fi
    # stakecube api
    source /usr/local/bin/include/leeloo/api/stakecube/private_API
    source /usr/local/bin/include/leeloo/api/stakecube/public_API
  fi

  ##############################################################################

  # xeggex template
  if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
    EXCHANGE_OUTPUT_NAME="XeggeX"
    EXCHANGE_DIR_NAME="xeggex"
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/xeggex ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      EXCHANGE_DIR_NAME="null"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/xeggex
    fi
    # xeggex api
    source /usr/local/bin/include/leeloo/api/xeggex/private_API
    source /usr/local/bin/include/leeloo/api/xeggex/public_API
  fi

  ##############################################################################

  # nonkyc template
  if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
    EXCHANGE_OUTPUT_NAME="nonkyc"
    EXCHANGE_DIR_NAME="nonkyc"
    if [[ ! -f /usr/local/bin/include/leeloo/strategies/templates/nonkyc ]] &>/dev/null; then
      EXCHANGE_API="Nothing"
      EXCHANGE_DIR_NAME="null"
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No template found!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      exit
    else
      source /usr/local/bin/include/leeloo/strategies/templates/nonkyc
    fi
    # nonkyc api
    source /usr/local/bin/include/leeloo/api/nonkyc/private_API
    source /usr/local/bin/include/leeloo/api/nonkyc/public_API
  fi

  ##############################################################################

  if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
    EXCHANGE_API="No config!"
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    exit
  fi
}

################################################################################

# END
