#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

################################################################################

# report active bot
if [[ ! "$(grep -c "SXC" "${LOG_DIR:?}"/leeloo/robots 2>/dev/null)" -gt "0" ]] &>/dev/null; then
  echo "SXC Running bots @ $(date | xargs)" >"${LOG_DIR:?}"/leeloo/robots
fi

################################################################################

function sxc_backup_balances() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/balances "${LOG_DIR:?}"/leeloo/southxchange/balances.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/balances.bkp "${LOG_DIR:?}"/leeloo/southxchange/balances &>/dev/null
  fi
}

################################################################################

function sxc_backup_prices() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/prices | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/prices "${LOG_DIR:?}"/leeloo/southxchange/prices.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/prices | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/prices.bkp "${LOG_DIR:?}"/leeloo/southxchange/prices &>/dev/null
  fi
}

################################################################################

function sxc_backup_orders() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/orders | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/orders "${LOG_DIR:?}"/leeloo/southxchange/orders.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/orders | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/southxchange/orders.bkp "${LOG_DIR:?}"/leeloo/southxchange/orders &>/dev/null
  fi
}

################################################################################

function listing_data() {

  # backup balances, prices
  sxc_backup_balances
  sxc_backup_prices

  # get available listing data
  LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_UNCONFIRMED_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $4 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
  LISTING_PRICE_ASK="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $3 }')"
  LISTING_PRICE_LAST="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $4 }')"
  LISTING_AMOUNT_VALUED="$(echo "$LISTING_AMOUNT*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_UNCONFIRMED_VALUED="$(echo "$LISTING_UNCONFIRMED_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$LISTING_AVAILABLE_BALANCE" ]] &>/dev/null; then
    LISTING_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT" ]] &>/dev/null; then
    LISTING_AMOUNT="0.00000000"
  fi
  if [[ -z "$LISTING_PRICE" ]] &>/dev/null; then
    LISTING_PRICE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT_VALUED" ]] &>/dev/null; then
    LISTING_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_AVAILABLE_VALUED" ]] &>/dev/null; then
    LISTING_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function reference_data() {

  # backup balances, prices
  sxc_backup_balances
  sxc_backup_prices

  # get available reference data
  REFERENCE_AVAILABLE_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_UNCONFIRMED_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $4 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
  REFERENCE_PRICE_ASK="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $3 }')"
  REFERENCE_PRICE_LAST="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $4 }')"
  REFERENCE_AMOUNT_VALUED="$(echo "$REFERENCE_AMOUNT/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_UNCONFIRMED_VALUED="$(echo "$REFERENCE_UNCONFIRMED_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$REFERENCE_AVAILABLE_BALANCE" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT" ]] &>/dev/null; then
    REFERENCE_AMOUNT="0.00000000"
  fi
  if [[ -z "$REFERENCE_PRICE" ]] &>/dev/null; then
    REFERENCE_PRICE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT_VALUED" ]] &>/dev/null; then
    REFERENCE_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_AVAILABLE_VALUED" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function listing_total_value() {
  # calculate total values
  LISTING_TOTAL="$(echo "$LISTING_AVAILABLE_BALANCE+$LISTING_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_TOTAL_VALUED="$(echo "$LISTING_AVAILABLE_VALUED+$LISTING_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
}

################################################################################

function reference_total_value() {
  # calculate total values
  REFERENCE_TOTAL="$(echo "$REFERENCE_AVAILABLE_BALANCE+$REFERENCE_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_TOTAL_VALUED="$(echo "$REFERENCE_AVAILABLE_VALUED+$REFERENCE_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
}

################################################################################

function listing_allocated() {
  # total listing allocated
  LISTING_ALLOCATED_REAL="$(echo "100/$REFERENCE_TOTAL*$LISTING_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$LISTING_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="100"
  fi
  if [[ -z "$LISTING_ALLOCATED_REAL" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="0.00"
  fi
}

################################################################################

function reference_allocated() {
  # total reference allocated
  REFERENCE_ALLOCATED_REAL="$(echo "100/$LISTING_TOTAL*$REFERENCE_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$REFERENCE_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="100"
  fi
  if [[ -z "$REFERENCE_ALLOCATED_REAL" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="0.00"
  fi
}

################################################################################

function last_tx() {
  # last tx
  TX_ID_LAST="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null | egrep -o "[0-9]+")"
  # zero, continue
  if [[ -z "$TX_ID_LAST" ]] &>/dev/null; then
    TX_ID_LAST="null"
  fi
}

################################################################################

function cost_price() {
  # update balances, prices after last order
  echo "$(listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
  echo "$(prices | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null

  # backup balances, prices
  sxc_backup_balances
  sxc_backup_prices

  LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ ! -z "$LISTING_PRICE" ]] &>/dev/null; then
    # listing
    echo "$LISTING_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null
    echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null

    # listing output
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating cost! $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
}

################################################################################

function tx_id {
  echo "$(echo "$PLACE_ORDER" | tr -d '"')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null
}

################################################################################

function incoming_listing() {

  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming &>/dev/null
  fi

  # create list from listing unconfirmed balance
  echo "$LISTING_UNCONFIRMED_BALANCE" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null
  # keep n lines
  echo "$(tail -10 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null

  # last lines are different, continue
  LIST_INCOMING="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null)"
  # last n lines above
  LIST_INCOMING_ABOVE="$(echo "$LIST_INCOMING" | tail -2 | head -1 | tr -d '.' | sed 's/^0*//')"
  # last n lines below
  LIST_INCOMING_BELOW="$(echo "$LIST_INCOMING" | tail -2 | tail -1 | tr -d '.' | sed 's/^0*//')"

  # lines are different, continue
  if [[ ! "$LIST_INCOMING_ABOVE" -eq "$LIST_INCOMING_BELOW" ]] &>/dev/null; then
    # make sure last change is a negative
    if [[ "$LIST_INCOMING_ABOVE" -gt "$LIST_INCOMING_BELOW" ]] &>/dev/null; then

      # update balances, prices after last order
      echo "$(listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
      echo "$(prices | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null

      # backup balances, prices
      sxc_backup_balances
      sxc_backup_prices

      LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
      LISTING_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
      LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

      if [[ ! -z "$LISTING_PRICE" ]] &>/dev/null; then
        # listing
        echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null

        # listing output
        echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating price! $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi

  # incoming listing
  if [[ "$(echo "$LISTING_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep " :: Inc :: " | wc -l)" -lt "1" ]] &>/dev/null; then
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Inc :: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi
}

################################################################################

function incoming_reference() {

  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming &>/dev/null
  fi

  # create list from reference unconfirmed balance
  echo "$REFERENCE_UNCONFIRMED_BALANCE" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null
  # keep n lines
  echo "$(tail -10 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null

  # last lines are different, continue
  REF_INCOMING="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null)"
  # last n lines above
  REF_INCOMING_ABOVE="$(echo "$REF_INCOMING" | tail -2 | head -1 | tr -d '.' | sed 's/^0*//')"
  # last n lines below
  REF_INCOMING_BELOW="$(echo "$REF_INCOMING" | tail -2 | tail -1 | tr -d '.' | sed 's/^0*//')"

  # lines are different, continue
  if [[ ! "$REF_INCOMING_ABOVE" -eq "$REF_INCOMING_BELOW" ]] &>/dev/null; then
    # make sure last change is a negative
    if [[ "$REF_INCOMING_ABOVE" -gt "$REF_INCOMING_BELOW" ]] &>/dev/null; then

      # update balances, prices after last order
      echo "$(listBalances | jq -r '.[] | "\(.Currency): \(.Deposited) \(.Available) \(.Unconfirmed)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null
      echo "$(prices | column -t)" >"${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null

      # backup balances, prices
      sxc_backup_balances
      sxc_backup_prices

      REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
      REFERENCE_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
      REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE*$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

      if [[ ! -z "$REFERENCE_PRICE" ]] &>/dev/null; then
        # reference
        echo "$REFERENCE_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null

        # reference output
        echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating price! $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi

  # incoming reference
  if [[ "$(echo "$REFERENCE_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep " :: Inc :: " | wc -l)" -lt "1" ]] &>/dev/null; then
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Inc :: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi
}

################################################################################

function signal_age() {
  # hours into seconds
  SIGNAL_AGE_SECONDS="$(echo "$SIGNAL_AGE*3600" | bc 2>/dev/null)"

  # signal age file
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "IDLING :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr/${SIGNAL_AGE_SECONDS:?}sec :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi
}

function signal_age_buying() {
  # signal age
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "Buying :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi
  # get signal order age (seconds)
  SIGNAL_ORDER_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
}

function signal_age_selling() {
  # signal age
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "Selling :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi
  # get signal order age (seconds)
  SIGNAL_ORDER_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
}

################################################################################

function open_positions() {

  # backup balances, prices
  sxc_backup_balances
  sxc_backup_prices

  LISTING_OPEN_CURRENCY="$LISTING_CURRENCY/$REFERENCE_CURRENCY"
  LISTING_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
  LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_OPEN_AMOUNT="$LISTING_AVAILABLE_BALANCE"

  if [[ -z "$LISTING_OPEN_AMOUNT" ]] &>/dev/null; then
    LISTING_OPEN_AMOUNT="0.00000000"
  fi

  ##############################################################################

  REFERENCE_OPEN_CURRENCY="$LISTING_CURRENCY/$REFERENCE_CURRENCY"
  REFERENCE_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
  REFERENCE_AVAILABLE_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE*$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_OPEN_AMOUNT="$REFERENCE_AVAILABLE_BALANCE"

  if [[ -z "$REFERENCE_OPEN_AMOUNT" ]] &>/dev/null; then
    REFERENCE_OPEN_AMOUNT="0.00000000"
  fi

  ##############################################################################

  # make sure prices, balances exist, continue
  if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null)" -gt "0" ]] &>/dev/null; then
    if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)" -gt "0" ]] &>/dev/null; then

      # listing price null, continue
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null)" -eq "0" ]] &>/dev/null; then
        echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null
      fi
      # listing cost null, continue
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null)" -eq "0" ]] &>/dev/null; then
        echo "$LISTING_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null
      fi

      ##########################################################################

      # reference price null, continue
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null)" -eq "0" ]] &>/dev/null; then
        echo "$REFERENCE_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null
      fi
      # reference cost null, continue
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_cost 2>/dev/null)" -eq "0" ]] &>/dev/null; then
        echo "$REFERENCE_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_cost 2>/dev/null
      fi
    fi
  fi

  ##############################################################################

  LISTING_OPEN_PRICE="$(cat "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null)"
  LISTING_OPEN_BALANCE="$(cat "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null)"

  if [[ -z "$LISTING_OPEN_PRICE" ]] &>/dev/null; then
    LISTING_OPEN_PRICE="0.00000000"
  fi
  if [[ -z "$LISTING_OPEN_BALANCE" ]] &>/dev/null; then
    LISTING_OPEN_BALANCE="0.00000000"
  fi

  ##############################################################################

  LISTING_OPEN_RESULT="$(echo "$(echo "100/$LISTING_OPEN_PRICE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')-100" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ -z "$LISTING_OPEN_RESULT" ]] &>/dev/null; then
    LISTING_OPEN_RESULT="0.00"
  fi

  ##############################################################################

  # listing age (seconds)
  if [[ -f "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price ]] &>/dev/null; then
    LISTING_OPEN_AMOUNT_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    if [[ -z "$LISTING_OPEN_AMOUNT_SECONDS" ]] &>/dev/null; then
      LISTING_OPEN_AMOUNT_SECONDS="0"
    fi
    LISTING_OPEN_AMOUNT_AGE=$(printf '%dh:%dm:%ds\n' $(("$LISTING_OPEN_AMOUNT_SECONDS/3600")) $(("$LISTING_OPEN_AMOUNT_SECONDS%3600/60")) $(("$LISTING_OPEN_AMOUNT_SECONDS%60")))
  fi

  ##############################################################################

  # reference age (seconds)
  if [[ -f "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price ]] &>/dev/null; then
    REFERENCE_OPEN_AMOUNT_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    if [[ -z "$REFERENCE_OPEN_AMOUNT_SECONDS" ]] &>/dev/null; then
      REFERENCE_OPEN_AMOUNT_SECONDS="0"
    fi
    REFERENCE_OPEN_AMOUNT_AGE=$(printf '%dh:%dm:%ds\n' $(("$REFERENCE_OPEN_AMOUNT_SECONDS/3600")) $(("$REFERENCE_OPEN_AMOUNT_SECONDS%3600/60")) $(("$REFERENCE_OPEN_AMOUNT_SECONDS%60")))
  fi

  ##############################################################################

  # make sure prices, balances exist, continue
  if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null)" -gt "0" ]] &>/dev/null; then
    if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null)" -gt "0" ]] &>/dev/null; then

      # is this an open position?
      if [[ "$(echo "$LISTING_OPEN_AMOUNT" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
        # currency amount cost result age
        echo "$STRATEGY_TYPE $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${SYS_DIR:?}"/robot/pool 2>/dev/null
        echo "$(cat "${SYS_DIR:?}"/robot/pool 2>/dev/null | column -t)" >"${SYS_DIR:?}"/robot/pool 2>/dev/null
      else
        rm "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".* &>/dev/null
      fi
    fi
  fi
}

################################################################################

function rogue_profit() {
  # rogue profit using rsi

  ROGUE_TIMER_NOW="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  ROGUE_TIMER="3600"      # n seconds (default: 3600 seconds/1 hour cooldown)
  ROGUE_HOURS="14"        # n hours of data (default: 14 hours)
  ROGUE_AMOUNT="0.009225" # n % to be used (default: 0.009225)
  ROGUE_MAX_DAY="4"       # n trades a day (default: 4)
  ROGUE_RSI="14"          # relative strength index (default: 14)

  ##############################################################################

  # missing, continue
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue &>/dev/null
  fi

  ##############################################################################

  # get_rsi n
  function rogue_data() {
    echo "L $LISTING_CURRENCY $(get_rsi "$ROGUE_RSI" "$LISTING_CURRENCY")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
    sleep 1
    echo "R $REFERENCE_CURRENCY $(get_rsi "$ROGUE_RSI" "$REFERENCE_CURRENCY")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
  }

  ##############################################################################

  function rogue_stealth() {
    if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth ]] &>/dev/null; then
      echo "Lurking in the Shadows.." >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null
      sleep 1
    fi
    STEALTH_TIME_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    STEALTH_TIME=$(printf '%dh:%dm:%ds\n' $(("$STEALTH_TIME_SECONDS/3600")) $(("$STEALTH_TIME_SECONDS%3600/60")) $(("$STEALTH_TIME_SECONDS%60")))
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Stealth mode $STEALTH_TIME" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  }

  ##############################################################################

  function rogue_vanish() {
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Rogue used Vanishing Powder!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    sleep 1
    # vanish the vanishing line
    echo "$(cat "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -v "Vanishing")" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  }

  ##############################################################################

  function rogue_buying() {
    # n% amount
    REFERENCE_AMOUNT="$(echo "$ROGUE_AMOUNT*$REFERENCE_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cheap Shot successfully! $REFERENCE_AMOUNT @ $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_market "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "true")"
      rogue_vanish
    elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_limit "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "true")"
      rogue_vanish
    fi
  }

  ##############################################################################

  function rogue_selling() {
    # n% amount
    REFERENCE_AMOUNT="$(echo "$ROGUE_AMOUNT*$REFERENCE_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    LISTING_AMOUNT="$(echo "$ROGUE_AMOUNT*$LISTING_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Pick Pocket successfully! $LISTING_AMOUNT @ $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_market "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "false")"
      rogue_vanish
    elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_limit "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "false")"
      rogue_vanish
    fi
  }

  ##############################################################################

  function rogue_clean_lines() {
    # keep n lines
    echo "$(tail -"$(echo "$ROGUE_HOURS*2" | bc -l 2>/dev/null)" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
  }

  ##############################################################################

  if [[ "$ROGUE_PROFIT" -eq "1" ]] &>/dev/null; then

    # update data every n seconds
    if [[ "$ROGUE_TIMER_NOW" -gt "$ROGUE_TIMER" ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
      # update data if missing
    elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
      # update data if empty
    elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
    fi

    ############################################################################

    # line count
    ROGUE_LINES="$(wc -l "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $1 }')"
    ROGUE_COUNT="$(echo "$ROGUE_LINES/2" | bc 2>/dev/null)"
    ROGUE_DAYS="$(echo "$ROGUE_COUNT/24" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    # backup prices
    sxc_backup_prices

    # listing
    LISTING_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
    ROGUE_LISTING_PRICE="$LISTING_PRICE"
    ROGUE_LISTING_PRICE_OLD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | awk '{ print $3 }' | tail -1)"

    if [[ -z "$ROGUE_LISTING_PRICE_OLD" ]] &>/dev/null; then
      ROGUE_LISTING_PRICE_OLD="0"
    fi

    ROGUE_LISTING_PRICE_DIFF="$(echo "100/$ROGUE_LISTING_PRICE_OLD*$ROGUE_LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    if [[ -z "$ROGUE_LISTING_PRICE_DIFF" ]] &>/dev/null; then
      ROGUE_LISTING_PRICE_DIFF="0"
    fi

    ROGUE_LISTING_NOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | tail -1 | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_LISTING_HIGH="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_LISTING_LOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.4f\n", $1 }')"

    # rsi can not be empty/zero, regardless
    if [[ -z "$ROGUE_LISTING_NOW" ]] &>/dev/null; then
      ROGUE_LISTING_NOW="50.1111"
    fi
    if [[ -z "$ROGUE_LISTING_HIGH" ]] &>/dev/null; then
      ROGUE_LISTING_HIGH="50.1111"
    fi
    if [[ -z "$ROGUE_LISTING_LOW" ]] &>/dev/null; then
      ROGUE_LISTING_LOW="50.1111"
    fi
    if [[ "$ROGUE_LISTING_NOW" -eq "0" ]] &>/dev/null; then
      ROGUE_LISTING_NOW="50.1111"
    fi
    if [[ "$ROGUE_LISTING_HIGH" -eq "0" ]] &>/dev/null; then
      ROGUE_LISTING_HIGH="50.1111"
    fi
    if [[ "$ROGUE_LISTING_LOW" -eq "0" ]] &>/dev/null; then
      ROGUE_LISTING_LOW="50.1111"
    fi

    ROGUE_LISTING_DIFF="$(echo "$ROGUE_LISTING_HIGH-$ROGUE_LISTING_LOW" | bc -l 2>/dev/null | tr -d '-' | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_LISTING_TOTAL="$(echo "$ROGUE_LISTING_NOW+$ROGUE_LISTING_HIGH+$ROGUE_LISTING_LOW" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    ROGUE_LISTING_AVERAGE="$(echo "$ROGUE_LISTING_TOTAL/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

    ############################################################################

    # set idle
    ROGUE_LISTING_X_CALCULATE="$ROGUE_LISTING_TOTAL"

    # overbought
    if [[ "$(echo "$ROGUE_LISTING_NOW" | awk -F. '{ print $1 }')" -gt "60" ]] &>/dev/null; then
      # positive
      ROGUE_LISTING_X_CALCULATE="$(echo "$ROGUE_LISTING_TOTAL+$ROGUE_LISTING_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    fi

    # oversold
    if [[ "$(echo "$ROGUE_LISTING_NOW" | awk -F. '{ print $1 }')" -lt "40" ]] &>/dev/null; then
      # negative
      ROGUE_LISTING_X_CALCULATE="$(echo "$ROGUE_LISTING_TOTAL-$ROGUE_LISTING_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    fi

    ############################################################################

    ROGUE_LISTING_RPI="$(echo "$ROGUE_LISTING_X_CALCULATE/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

    # keep at idle if zero
    if [[ -z "$ROGUE_LISTING_RPI" ]] &>/dev/null; then
      ROGUE_LISTING_RPI="0"
    fi

    ############################################################################

    # x_factor, ruled by 60/40
    ROGUE_LISTING_DIFF_PERCENTAGE="$(echo "100/$ROGUE_LISTING_AVERAGE*$ROGUE_LISTING_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    if [[ -z "$ROGUE_LISTING_DIFF_PERCENTAGE" ]] &>/dev/null; then
      ROGUE_LISTING_DIFF_PERCENTAGE="0"
    fi

    # reference
    REFERENCE_PRICE="$(grep -w "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/prices | awk '{ print $2 }')"
    ROGUE_REFERENCE_PRICE="$REFERENCE_PRICE"
    ROGUE_REFERENCE_PRICE_OLD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | awk '{ print $5 }' | tail -1)"

    if [[ -z "$ROGUE_REFERENCE_PRICE_OLD" ]] &>/dev/null; then
      ROGUE_REFERENCE_PRICE_OLD="0"
    fi

    ROGUE_REFERENCE_PRICE_DIFF="$(echo "100/$ROGUE_REFERENCE_PRICE_OLD*$ROGUE_REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    if [[ -z "$ROGUE_REFERENCE_PRICE_DIFF" ]] &>/dev/null; then
      ROGUE_REFERENCE_PRICE_DIFF="0"
    fi

    ROGUE_REFERENCE_NOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | tail -1 | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_REFERENCE_HIGH="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_REFERENCE_LOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_REFERENCE_DIFF="$(echo "$ROGUE_REFERENCE_HIGH-$ROGUE_REFERENCE_LOW" | bc -l 2>/dev/null | tr -d '-' | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_REFERENCE_TOTAL="$(echo "$ROGUE_REFERENCE_NOW+$ROGUE_REFERENCE_HIGH+$ROGUE_REFERENCE_LOW" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    ROGUE_REFERENCE_AVERAGE="$(echo "$ROGUE_REFERENCE_TOTAL/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

    ############################################################################

    # set idle
    ROGUE_REFERENCE_X_CALCULATE="$ROGUE_REFERENCE_TOTAL"

    # overbought
    if [[ "$(echo "$ROGUE_REFERENCE_NOW" | awk -F. '{ print $1 }')" -gt "60" ]] &>/dev/null; then
      # positive
      ROGUE_REFERENCE_X_CALCULATE="$(echo "$ROGUE_REFERENCE_TOTAL+$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    fi

    # oversold
    if [[ "$(echo "$ROGUE_REFERENCE_NOW" | awk -F. '{ print $1 }')" -lt "40" ]] &>/dev/null; then
      # negative
      ROGUE_REFERENCE_X_CALCULATE="$(echo "$ROGUE_REFERENCE_TOTAL-$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
    fi

    ############################################################################

    ROGUE_REFERENCE_RPI="$(echo "$ROGUE_REFERENCE_X_CALCULATE/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

    # keep at idle if zero
    if [[ -z "$ROGUE_REFERENCE_RPI" ]] &>/dev/null; then
      ROGUE_REFERENCE_RPI="0"
    fi

    ############################################################################

    ROGUE_REFERENCE_DIFF_PERCENTAGE="$(echo "100/$ROGUE_REFERENCE_AVERAGE*$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    if [[ -z "$ROGUE_REFERENCE_DIFF_PERCENTAGE" ]] &>/dev/null; then
      ROGUE_REFERENCE_DIFF_PERCENTAGE="0"
    fi

    ############################################################################

    ROGUE_SYNCED_PERCENTAGE="$(echo "100/$ROGUE_HOURS*$ROGUE_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    if [[ -z "$ROGUE_SYNCED_PERCENTAGE" ]] &>/dev/null; then
      ROGUE_SYNCED_PERCENTAGE="0"
    fi

    ############################################################################

    ROGUE_UPDATE_PERCENTAGE="$(echo "100/$ROGUE_TIMER*$ROGUE_TIMER_NOW" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    if [[ -z "$ROGUE_UPDATE_PERCENTAGE" ]] &>/dev/null; then
      ROGUE_UPDATE_PERCENTAGE="0"
    fi

    ############################################################################

    ROGUE_BOUGHT="$(grep -c "BOUGHT" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status)"
    ROGUE_SOLD="$(grep -c "SOLD" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status)"

    ############################################################################

    # call shot
    if [[ "$(echo "$ROGUE_SYNCED_PERCENTAGE" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
      ROGUE_SYNCED_PERCENTAGE="100"
    fi

    ############################################################################

    ROGUE_LISTING_RPI_NR="$(echo "$ROGUE_LISTING_RPI" | awk '{ printf "%.4f\n", $1 }')"
    ROGUE_REFERENCE_RPI_NR="$(echo "$ROGUE_REFERENCE_RPI" | awk '{ printf "%.4f\n", $1 }')"

    if [[ -z "$ROGUE_LISTING_RPI_NR" ]] &>/dev/null; then
      # if zero, keep it idling
      ROGUE_LISTING_RPI_NR="50.1111"
    fi

    if [[ -z "$ROGUE_REFERENCE_RPI_NR" ]] &>/dev/null; then
      # if zero, keep it idling
      ROGUE_REFERENCE_RPI_NR="50.1111"
    fi

    ############################################################################

    # if zero, idle
    if [[ "$(echo "$ROGUE_LISTING_DIFF_PERCENTAGE" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
      ROGUE_LISTING_RPI="IDLE"
    fi

    # if zero, idle
    if [[ "$(echo "$ROGUE_REFERENCE_DIFF_PERCENTAGE" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
      ROGUE_REFERENCE_RPI="IDLE"
    fi

    ############################################################################

    echo "Update    $ROGUE_TIMER_NOW/${ROGUE_TIMER:?}s ${ROGUE_UPDATE_PERCENTAGE:?}% (${ROGUE_SYNCED_PERCENTAGE:?}%)
Lines     $ROGUE_LINES/${ROGUE_COUNT:?}h/${ROGUE_DAYS:?}d
RSI       $ROGUE_RSI

L_PRICE   $ROGUE_LISTING_PRICE Diff: ${ROGUE_LISTING_PRICE_DIFF:?}%
L_NOW     $ROGUE_LISTING_NOW
L_HIGHEST $ROGUE_LISTING_HIGH
L_LOWEST  $ROGUE_LISTING_LOW
L_AVERAGE $ROGUE_LISTING_AVERAGE
L_DIFF    $ROGUE_LISTING_DIFF ${ROGUE_LISTING_DIFF_PERCENTAGE:?}%
RPI       $ROGUE_LISTING_RPI ($ROGUE_LISTING_RPI_NR)

R_PRICE   $ROGUE_REFERENCE_PRICE Diff: ${ROGUE_REFERENCE_PRICE_DIFF:?}%
R_NOW     $ROGUE_REFERENCE_NOW
R_HIGHEST $ROGUE_REFERENCE_HIGH
R_LOWEST  $ROGUE_REFERENCE_LOW
R_AVERAGE $ROGUE_REFERENCE_AVERAGE
R_DIFF    $ROGUE_REFERENCE_DIFF ${ROGUE_REFERENCE_DIFF_PERCENTAGE:?}%
RPI       $ROGUE_REFERENCE_RPI ($ROGUE_REFERENCE_RPI_NR)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rsi 2>/dev/null

    ############################################################################

    function rogue_shadow_output() {
      echo "Lurking in the Shadows.." >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null
    }

    ############################################################################

    if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] &>/dev/null; then
      touch >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status &>/dev/null
    fi

    ############################################################################

    TYPE="sell"

    MARKET_RGP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
    MARKET_RGP_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
    MARKET_RGP_STATUS_SOLD="SOLD @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)"

    # wait on call shot
    if [[ "$(echo "$ROGUE_SYNCED_PERCENTAGE" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then

      # rogue_selling config n% of allocated n%
      if [[ "$(echo "$ROGUE_LISTING_RPI_NR" | awk -F. '{ print $1 }')" -gt "70" ]] &>/dev/null; then
        # overbought, pick pocket at top!
        if [[ "$(tail -"$ROGUE_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "SOLD")" -lt "$ROGUE_MAX_DAY" ]] &>/dev/null; then
          tx_id
          cost_price
          rogue_selling
          rogue_shadow_output
          echo "$MARKET_RGP_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          echo "$MARKET_RGP_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          echo "$MARKET_RGP_STATUS_SOLD" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
        fi
      fi

      ##########################################################################

      TYPE="buy"

      MARKET_RGP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
      MARKET_RGP_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
      MARKET_RGP_STATUS_BOUGHT="BOUGHT @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)"

      # rogue_buying config n% of allocated n%
      if [[ "$(echo "$ROGUE_LISTING_RPI_NR" | awk -F. '{ print $1 }')" -lt "30" ]] &>/dev/null; then
        # oversold, cheap shot at bottom!
        if [[ "$(tail -"$ROGUE_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "BOUGHT")" -lt "$ROGUE_MAX_DAY" ]] &>/dev/null; then
          tx_id
          cost_price
          rogue_buying
          rogue_shadow_output
          echo "$MARKET_RGP_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          echo "$MARKET_RGP_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          echo "$MARKET_RGP_STATUS_BOUGHT" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
        fi
      fi
    fi

    ############################################################################

    # reset status at midnight
    if [[ "$(date '+%H:%M' | egrep "00:00" | wc -l)" -eq "1" ]] &>/dev/null; then
      echo "IDLE @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
    fi
  fi
}

################################################################################

function save_orders() {
  TRADE_TIMER="60"
  if [[ ! -f "${SYS_DIR:?}"/robot/orders ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/orders &>/dev/null
    TRADE_TIMER="0"
    sleep 1
  fi
  TRADE_HISTORY_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/orders 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  if [[ "$TRADE_HISTORY_SECONDS" -gt "$TRADE_TIMER" ]] &>/dev/null; then
    # keep orders, remove empty lines
    TRADE_HISTORY="$(cat "${SYS_DIR:?}"/robot/*.orders 2>/dev/null | sed '/^$/d')"
    echo "$TRADE_HISTORY" >>"${SYS_DIR:?}"/robot/orders 2>/dev/null
  fi
}

################################################################################

function last_orders {
  # keep n lines
  if [[ "$(wc -l "${SYS_DIR:?}"/robot/orders | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$(echo "$MAX_LOG/3" | bc 2>/dev/null)" "${SYS_DIR:?}"/robot/orders 2>/dev/null)" >"${SYS_DIR:?}"/robot/orders 2>/dev/null
  fi
}

################################################################################

function robot_Log_cleanup() {
  NEW_LOG="$(echo "$MAX_LOG/3" | bc 2>/dev/null)"
  # keep n lines
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$NEW_LOG" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    echo "$LOG_DATE :: LogReset :: Line $MAX_LOG > $NEW_LOG" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  else
    echo "$(cat "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
}

################################################################################

# END
