#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# StakeCube template - 2023

################################################################################

# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# END
