#!/bin/bash

################################################################################

# XeggeX template - 2023

################################################################################

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges
# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

################################################################################

account_private_api
account_public_api

################################################################################

log_date

################################################################################

# report active bot
if [[ ! "$(grep -c "XGX" "${LOG_DIR:?}"/leeloo/robots 2>/dev/null || true)" -gt "0" ]] &>/dev/null; then
  if [[ "$(echo "$(ls -l "${SYS_DIR:?}"/robot/)" | egrep -c "XGX.*.strategy" || true)" -gt "0" ]] &>/dev/null; then
    echo "XGX Running bots @ $(date | xargs)" >>"${LOG_DIR:?}"/leeloo/robots
  fi
fi

# remove duplicates
echo "$(cat "${LOG_DIR:?}"/leeloo/robots 2>/dev/null | awk '!a[$1]++')" >"${LOG_DIR:?}"/leeloo/robots

################################################################################

function backup_balances() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}' | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/balances "${LOG_DIR:?}"/leeloo/xeggex/balances.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{for(i=2;i<=NF;i++) if($i>0) {print; break}}' | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/balances.bkp "${LOG_DIR:?}"/leeloo/xeggex/balances &>/dev/null
  fi
}

################################################################################

function backup_prices() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/prices | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/prices "${LOG_DIR:?}"/leeloo/xeggex/prices.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/prices | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/prices.bkp "${LOG_DIR:?}"/leeloo/xeggex/prices &>/dev/null
  fi
}

################################################################################

function backup_orders() {
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/orders | wc -l)" -gt "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/orders "${LOG_DIR:?}"/leeloo/xeggex/orders.bkp &>/dev/null
  fi
  if [[ "$(egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/orders | wc -l)" -eq "0" ]] &>/dev/null; then
    cp "${LOG_DIR:?}"/leeloo/xeggex/orders.bkp "${LOG_DIR:?}"/leeloo/xeggex/orders &>/dev/null
  fi
}

################################################################################

function insufficient_funds {
  NO_FUNDS="$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null || true)"
  # if no funds
  if [[ "$NO_FUNDS" -gt "0" ]] &>/dev/null; then
    # cleanup null
    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null
    # listing output
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Insufficient funds! $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    # keep record of insufficient funds
    echo "$REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY" >"${LOG_DIR:?}"/leeloo/xeggex/insufficient_$BASENAME_STRATEGY
  fi

  # insufficient limit
  INSUFFICIENT_LIMIT="$(cat "${LOG_DIR:?}"/leeloo/xeggex/insufficient_$BASENAME_STRATEGY 2>/dev/null | awk '{ print $2 }' | tr -d '.' | sed 's/^0*//')"

  # if zero
  if [[ -z "$INSUFFICIENT_LIMIT" ]] &>/dev/null; then
    INSUFFICIENT_LIMIT="0"
  fi

  # if greater than limit
  if [[ "$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -gt "$INSUFFICIENT_LIMIT" ]] &>/dev/null; then
    # limit is broken (trade)
    NO_FUNDS="0"
  else
    # not greater (wait)
    NO_FUNDS="1"
  fi
}

################################################################################

function delisted() {
  # check if delisted_xeggex file exists, create it if not
  if [[ ! -f "${SYS_DIR:?}/delisted_xeggex" ]] &>/dev/null; then
    touch "${SYS_DIR:?}/delisted_xeggex"
  fi

  # define file paths
  PRICES_FILE="${LOG_DIR:?}/leeloo/xeggex/prices"
  DELISTED_FILE="${SYS_DIR:?}/delisted_xeggex"

  # check if there are delisted markets
  if [[ -s "$DELISTED_FILE" ]] &>/dev/null; then
    # loop through the delisted markets and remove them from the prices file
    while IFS= read -r MARKET; do
      # remove the market in both formats
      sed -i "/${MARKET//\//\\/}/d" "$PRICES_FILE"
    done <"$DELISTED_FILE"
  fi
}

################################################################################

function listing_data() {

  # get available listing data
  LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_UNCONFIRMED_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $4 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
  LISTING_PRICE_ASK="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $3 }')"
  LISTING_PRICE_LAST="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $4 }')"
  LISTING_AMOUNT_VALUED="$(echo "$LISTING_AMOUNT*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_UNCONFIRMED_VALUED="$(echo "$LISTING_UNCONFIRMED_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$LISTING_AVAILABLE_BALANCE" ]] &>/dev/null; then
    LISTING_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT" ]] &>/dev/null; then
    LISTING_AMOUNT="0.00000000"
  fi
  if [[ -z "$LISTING_PRICE" ]] &>/dev/null; then
    LISTING_PRICE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT_VALUED" ]] &>/dev/null; then
    LISTING_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_AVAILABLE_VALUED" ]] &>/dev/null; then
    LISTING_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function reference_data() {

  # get available reference data
  REFERENCE_AVAILABLE_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_UNCONFIRMED_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $4 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
  REFERENCE_PRICE_ASK="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $3 }')"
  REFERENCE_PRICE_LAST="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $4 }')"
  REFERENCE_AMOUNT_VALUED="$(echo "$REFERENCE_AMOUNT/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_UNCONFIRMED_VALUED="$(echo "$REFERENCE_UNCONFIRMED_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$REFERENCE_AVAILABLE_BALANCE" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT" ]] &>/dev/null; then
    REFERENCE_AMOUNT="0.00000000"
  fi
  if [[ -z "$REFERENCE_PRICE" ]] &>/dev/null; then
    REFERENCE_PRICE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT_VALUED" ]] &>/dev/null; then
    REFERENCE_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_AVAILABLE_VALUED" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function listing_total_value() {
  # calculate total values
  LISTING_TOTAL="$(echo "$LISTING_AVAILABLE_BALANCE+$LISTING_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_TOTAL_VALUED="$(echo "$LISTING_AVAILABLE_VALUED+$LISTING_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
}

################################################################################

function reference_total_value() {
  # calculate total values
  REFERENCE_TOTAL="$(echo "$REFERENCE_AVAILABLE_BALANCE+$REFERENCE_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_TOTAL_VALUED="$(echo "$REFERENCE_AVAILABLE_VALUED+$REFERENCE_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
}

################################################################################

function listing_allocated() {
  # total listing allocated
  LISTING_ALLOCATED_REAL="$(echo "100/$REFERENCE_TOTAL*$LISTING_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
  # total listing allocated raw
  LISTING_ALLOCATED_REAL_RAW="$(echo "100/$REFERENCE_TOTAL*$LISTING_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$LISTING_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="100"
  fi
  if [[ -z "$LISTING_ALLOCATED_REAL" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="0.00"
  fi
  if [[ -z "$LISTING_ALLOCATED_REAL_RAW" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL_RAW="0.00"
  fi
}

################################################################################

function reference_allocated() {
  # total reference allocated
  REFERENCE_ALLOCATED_REAL="$(echo "100/$LISTING_TOTAL*$REFERENCE_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
  # total reference allocated raw
  REFERENCE_ALLOCATED_REAL_RAW="$(echo "100/$LISTING_TOTAL*$REFERENCE_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$REFERENCE_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="100"
  fi
  if [[ -z "$REFERENCE_ALLOCATED_REAL" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="0.00"
  fi
  if [[ -z "$REFERENCE_ALLOCATED_REAL_RAW" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL_RAW="0.00"
  fi
}

################################################################################

function listing_balance_check {
  # listing balance check (without decimal)
  LISTING_AVAILABLE_BALANCE_NR="$(echo "$LISTING_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')"
}

################################################################################

function reference_balance_check {
  # reference balance check (without decimal)
  REFERENCE_AVAILABLE_BALANCE_NR="$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')"
}

################################################################################

function tx_id {
  # if not found
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid
  fi

  echo "$(echo "$PLACE_ORDER" | tr -d '{"}')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid

  # last txid (raw)
  TX_ID_LAST_RAW="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null)"

  # if txid exist
  if [[ "$(echo "$TX_ID_LAST_RAW" | egrep -c "id:[A-Za-z0-9]+" || true)" -gt "0" ]] &>/dev/null; then
    # update txid
    echo "$(echo "$TX_ID_LAST_RAW" | egrep -wo "id:[A-Za-z0-9]+" | awk -F: '{ print $2 }')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid
  fi

  # search for words ###########################################################
  TX_ID_NULL_WORDS="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null | wc -w)"
  # search for symbols other than normal txid
  TX_ID_NULL_SYMBOLS="$(grep -oE '[^a-fA-F0-9]' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid | wc -w)"

  # if several words is found, if symbols is found
  if [[ "$TX_ID_NULL_WORDS" -gt "1" || "$TX_ID_NULL_SYMBOLS" -gt "0" ]] &>/dev/null; then
    # update null
    echo "$LOG_DATE : $LISTING_CURRENCY/$REFERENCE_CURRENCY : $TX_ID_LAST_RAW" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null
  fi ###########################################################################

  # cleanup null
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null 2>/dev/null | egrep -v "id:[A-Za-z0-9]+" | sed '/^$/d')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null
  # cleanup txid
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null | egrep -v "error|null" | sed '/^$/d')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid

  # last txid
  TX_ID_LAST="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null)"

  # if zero
  if [[ -z "$TX_ID_LAST" || "$(echo "$TX_ID_LAST" | sed '/^$/d' | wc -l)" -eq "0" ]] &>/dev/null; then
    TX_ID_LAST="null"
  fi
}

################################################################################

function tx_id_age {
  # get txid age (seconds)
  TX_ID_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

  # if zero
  if [[ -z "$TX_ID_AGE_SECONDS" ]] &>/dev/null; then
    TX_ID_AGE_SECONDS="0"
  fi

  # txid age format
  TX_ID_AGE=$(printf '%dh:%dm:%ds\n' $(("$TX_ID_AGE_SECONDS/3600")) $(("$TX_ID_AGE_SECONDS%3600/60")) $(("$TX_ID_AGE_SECONDS%60")))
  # calculate txid days
  TX_ID_AGE_DAYS=$(echo "$TX_ID_AGE_SECONDS/86400" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')
}

################################################################################

function cost_price() {
  # update balances, prices after last order
  echo "$(Balances | jq -r '.[] | "\(.asset): \(.held) \(.available) \(.pending)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null
  echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null

  # backup balances, prices
  backup_balances
  backup_prices

  LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ ! -z "$LISTING_PRICE" ]] &>/dev/null; then
    # listing
    echo "$LISTING_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null
    echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null

    # listing output
    echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating cost! $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
}

################################################################################

function incoming_listing() {

  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming &>/dev/null
  fi

  if [[ -z "$LISTING_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_BALANCE="0.000000000"
  fi

  # create list from listing unconfirmed balance
  echo "$LISTING_UNCONFIRMED_BALANCE" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null
  # keep n lines
  echo "$(tail -10 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null

  # last lines are different
  LIST_INCOMING="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".list_incoming 2>/dev/null)"
  # last n lines above
  LIST_INCOMING_ABOVE="$(echo "$LIST_INCOMING" | tail -2 | head -1 | tr -d '.' | sed 's/^0*//')"
  # last n lines below
  LIST_INCOMING_BELOW="$(echo "$LIST_INCOMING" | tail -2 | tail -1 | tr -d '.' | sed 's/^0*//')"

  # lines are different
  if [[ ! "$LIST_INCOMING_ABOVE" -eq "$LIST_INCOMING_BELOW" ]] &>/dev/null; then
    # make sure last change is a negative
    if [[ "$LIST_INCOMING_ABOVE" -gt "$LIST_INCOMING_BELOW" ]] &>/dev/null; then

      # update balances, prices after last order
      echo "$(Balances | jq -r '.[] | "\(.asset): \(.held) \(.available) \(.pending)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null
      echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null

      # backup balances, prices
      backup_balances
      backup_prices

      LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
      LISTING_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
      LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

      if [[ ! -z "$LISTING_PRICE" ]] &>/dev/null; then
        # listing
        echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null

        # listing output
        echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating price! $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi

  # incoming listing
  if [[ "$(echo "$LISTING_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep " :: Inc :: " | wc -l)" -lt "1" ]] &>/dev/null; then
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Inc :: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi
}

################################################################################

function incoming_reference() {

  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming &>/dev/null
  fi

  if [[ -z "$REFERENCE_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_BALANCE="0.000000000"
  fi

  # create list from reference unconfirmed balance
  echo "$REFERENCE_UNCONFIRMED_BALANCE" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null
  # keep n lines
  echo "$(tail -10 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null

  # last lines are different
  REF_INCOMING="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ref_incoming 2>/dev/null)"
  # last n lines above
  REF_INCOMING_ABOVE="$(echo "$REF_INCOMING" | tail -2 | head -1 | tr -d '.' | sed 's/^0*//')"
  # last n lines below
  REF_INCOMING_BELOW="$(echo "$REF_INCOMING" | tail -2 | tail -1 | tr -d '.' | sed 's/^0*//')"

  # lines are different
  if [[ ! "$REF_INCOMING_ABOVE" -eq "$REF_INCOMING_BELOW" ]] &>/dev/null; then
    # make sure last change is a negative
    if [[ "$REF_INCOMING_ABOVE" -gt "$REF_INCOMING_BELOW" ]] &>/dev/null; then

      # update balances, prices after last order
      echo "$(Balances | jq -r '.[] | "\(.asset): \(.held) \(.available) \(.pending)"' 2>/dev/null | awk '{printf "%s %.8f %.8f %.8f\n", $1, $2, $3, $4}' | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null
      echo "$(tickers | column -t)" >"${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null

      # backup balances, prices
      backup_balances
      backup_prices

      REFERENCE_AVAILABLE_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
      REFERENCE_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
      REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE*$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

      if [[ ! -z "$REFERENCE_PRICE" ]] &>/dev/null; then
        # reference
        echo "$REFERENCE_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null

        # reference output
        echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Updating price! $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi

  # incoming reference
  if [[ "$(echo "$REFERENCE_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep " :: Inc :: " | wc -l)" -lt "1" ]] &>/dev/null; then
      echo "$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Inc :: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi
}

################################################################################

function signal_age() {
  # hours into seconds
  SIGNAL_AGE_SECONDS="$(echo "$SIGNAL_AGE*3600" | bc 2>/dev/null)"

  # signal age file
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "IDLING :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr/${SIGNAL_AGE_SECONDS:?}sec :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi

  # get signal order age (seconds)
  SIGNAL_ORDER_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
}

function signal_age_buying() {
  # signal age
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "Buying :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi
  # get signal order age (seconds)
  SIGNAL_ORDER_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
}

function signal_age_selling() {
  # signal age
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order ]] &>/dev/null; then
    echo "Selling :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${SIGNAL_AGE:?}hr :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null
  fi
  # get signal order age (seconds)
  SIGNAL_ORDER_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
}

################################################################################

function open_positions() {

  LISTING_OPEN_CURRENCY="$LISTING_CURRENCY/$REFERENCE_CURRENCY"
  LISTING_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
  LISTING_AVAILABLE_BALANCE="$(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  LISTING_OPEN_AMOUNT="$LISTING_AVAILABLE_BALANCE"

  if [[ -z "$LISTING_OPEN_AMOUNT" ]] &>/dev/null; then
    LISTING_OPEN_AMOUNT="0.00000000"
  fi

  ##############################################################################

  REFERENCE_OPEN_CURRENCY="$LISTING_CURRENCY/$REFERENCE_CURRENCY"
  REFERENCE_PRICE="$(grep -w "${LISTING_CURRENCY:?}_${REFERENCE_CURRENCY:?}" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $2 }')"
  REFERENCE_AVAILABLE_BALANCE="$(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE*$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  REFERENCE_OPEN_AMOUNT="$REFERENCE_AVAILABLE_BALANCE"

  if [[ -z "$REFERENCE_OPEN_AMOUNT" ]] &>/dev/null; then
    REFERENCE_OPEN_AMOUNT="0.00000000"
  fi

  ##############################################################################

  # make sure prices, balances exist
  if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null || true)" -gt "0" ]] &>/dev/null; then
    if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null || true)" -gt "0" ]] &>/dev/null; then

      # listing price null
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
        echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null
      fi
      # listing cost null
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
        echo "$LISTING_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null
      fi

      ##########################################################################

      # reference price null
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
        echo "$REFERENCE_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null
      fi
      # reference cost null
      if [[ "$(egrep -c "[0-9]+.[0-9]+" "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_cost 2>/dev/null || true)" -eq "0" ]] &>/dev/null; then
        echo "$REFERENCE_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_cost 2>/dev/null
      fi
    fi
  fi

  ##############################################################################

  LISTING_OPEN_PRICE="$(cat "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null | head -1)"
  LISTING_OPEN_BALANCE="$(cat "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_cost 2>/dev/null | head -1)"

  if [[ -z "$LISTING_OPEN_PRICE" ]] &>/dev/null; then
    LISTING_OPEN_PRICE="0.00000000"
  fi
  if [[ -z "$LISTING_OPEN_BALANCE" ]] &>/dev/null; then
    LISTING_OPEN_BALANCE="0.00000000"
  fi

  ##############################################################################

  LISTING_OPEN_RESULT="$(echo "$(echo "100/$LISTING_OPEN_PRICE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')-100" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ -z "$LISTING_OPEN_RESULT" ]] &>/dev/null; then
    LISTING_OPEN_RESULT="0.00"
  fi

  ##############################################################################

  # listing age (seconds)
  if [[ -f "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price ]] &>/dev/null; then
    LISTING_OPEN_AMOUNT_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".list_price 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    if [[ -z "$LISTING_OPEN_AMOUNT_SECONDS" ]] &>/dev/null; then
      LISTING_OPEN_AMOUNT_SECONDS="0"
    fi
    LISTING_OPEN_AMOUNT_AGE=$(printf '%dh:%dm:%ds\n' $(("$LISTING_OPEN_AMOUNT_SECONDS/3600")) $(("$LISTING_OPEN_AMOUNT_SECONDS%3600/60")) $(("$LISTING_OPEN_AMOUNT_SECONDS%60")))
  fi

  ##############################################################################

  # reference age (seconds)
  if [[ -f "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price ]] &>/dev/null; then
    REFERENCE_OPEN_AMOUNT_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".ref_price 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    if [[ -z "$REFERENCE_OPEN_AMOUNT_SECONDS" ]] &>/dev/null; then
      REFERENCE_OPEN_AMOUNT_SECONDS="0"
    fi
    REFERENCE_OPEN_AMOUNT_AGE=$(printf '%dh:%dm:%ds\n' $(("$REFERENCE_OPEN_AMOUNT_SECONDS/3600")) $(("$REFERENCE_OPEN_AMOUNT_SECONDS%3600/60")) $(("$REFERENCE_OPEN_AMOUNT_SECONDS%60")))
  fi

  ##############################################################################

  # make sure prices, balances exist
  if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/prices 2>/dev/null || true)" -gt "0" ]] &>/dev/null; then
    if [[ "$(egrep -c "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/xeggex/balances 2>/dev/null || true)" -gt "0" ]] &>/dev/null; then

      # is this an open position?
      if [[ "$(echo "$LISTING_OPEN_AMOUNT" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
        # currency amount cost result age
        echo "$EXCHANGE_API $STRATEGY_TYPE $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${SYS_DIR:?}"/robot/pool 2>/dev/null
        echo "$(cat "${SYS_DIR:?}"/robot/pool 2>/dev/null | column -t)" >"${SYS_DIR:?}"/robot/pool 2>/dev/null
      else
        rm "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".* &>/dev/null
      fi
    fi
  fi
}

################################################################################

function save_orders() {
  TRADE_TIMER="60"
  if [[ ! -f "${SYS_DIR:?}"/robot/orders ]] &>/dev/null; then
    touch "${SYS_DIR:?}"/robot/orders &>/dev/null
    TRADE_TIMER="0"
    sleep 1
  fi
  TRADE_HISTORY_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/orders 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  if [[ "$TRADE_HISTORY_SECONDS" -gt "$TRADE_TIMER" ]] &>/dev/null; then
    # keep orders, remove empty lines
    TRADE_HISTORY="$(cat "${SYS_DIR:?}"/robot/*.orders 2>/dev/null | sed '/^$/d')"
    echo "$TRADE_HISTORY" >>"${SYS_DIR:?}"/robot/orders 2>/dev/null
  fi
}

################################################################################

function last_orders {
  # keep n lines
  if [[ "$(wc -l "${SYS_DIR:?}"/robot/orders | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$(echo "$MAX_LOG/3" | bc 2>/dev/null)" "${SYS_DIR:?}"/robot/orders 2>/dev/null)" >"${SYS_DIR:?}"/robot/orders 2>/dev/null
  fi
}

################################################################################

function robot_Log_cleanup() {
  NEW_LOG="$(echo "$MAX_LOG/3" | bc 2>/dev/null)"
  # keep n lines
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$NEW_LOG" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    echo "$LOG_DATE : LogReset : $MAX_LOG lines down to > $NEW_LOG lines." >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
}

# setup manual market order - ##################################################

function setup_market_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )

  if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

    REFERENCE_CURRENCY=$(
      dialog --title "Reference Currency (USDT)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )

    if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then

      # currency
      LISTING_CURRENCY="$(echo "$LISTING_CURRENCY" | tr '[:lower:]' '[:upper:]')"
      REFERENCE_CURRENCY="$(echo "$REFERENCE_CURRENCY" | tr '[:lower:]' '[:upper:]')"
      # amount
      LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }')"
      REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }')"

      AMOUNT=$(
        dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
          --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
          3>&1 1>&2 2>&3 3>&-
      )
    fi
  fi
}

# setup manual limit order #####################################################

function setup_limit_order {
  LISTING_CURRENCY=$(
    dialog --title "Listing Currency (BTC)" \
      --inputbox "Enter name:" 8 40 \
      3>&1 1>&2 2>&3 3>&-
  )

  if [[ ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then

    REFERENCE_CURRENCY=$(
      dialog --title "Reference Currency (USDT)" \
        --inputbox "Enter name:" 8 40 \
        3>&1 1>&2 2>&3 3>&-
    )

    if [[ ! -z "$REFERENCE_CURRENCY" ]] &>/dev/null; then

      # currency
      LISTING_CURRENCY="$(echo "$LISTING_CURRENCY" | tr '[:lower:]' '[:upper:]')"
      REFERENCE_CURRENCY="$(echo "$REFERENCE_CURRENCY" | tr '[:lower:]' '[:upper:]')"
      # amount
      LISTING_CURRENCY_AMOUNT="$LISTING_CURRENCY: $(grep -w "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }')"
      REFERENCE_CURRENCY_AMOUNT="$REFERENCE_CURRENCY: $(grep -w "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/balances | awk '{ print $3 }')"
      # listing/reference price
      LISTING_REFERENCE_CURRENCY_PRICE="$REFERENCE_CURRENCY: $(egrep -w "$LISTING_CURRENCY.$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/xeggex/prices | awk '{ print $4 }')"

      # ask amount
      AMOUNT=$(
        dialog --title "Amount $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
          --inputbox "Enter amount:
$LISTING_CURRENCY_AMOUNT $REFERENCE_CURRENCY_AMOUNT" 8 40 \
          3>&1 1>&2 2>&3 3>&-
      )

      # if not zero
      if [[ ! -z "$AMOUNT" ]] &>/dev/null; then
        # ask price
        PRICE=$(
          dialog --title "Price $LISTING_CURRENCY/$REFERENCE_CURRENCY" \
            --inputbox "Enter price:
$LISTING_CURRENCY: $AMOUNT $LISTING_REFERENCE_CURRENCY_PRICE" 8 40 \
            3>&1 1>&2 2>&3 3>&-
        )
      fi
    fi
  fi
}

################################################################################

# END
