#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# buy-sell strategy configuration (static)
################################################################################

STRATEGY_TYPE="BST"

# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# sell or buy order
TYPE="$(egrep "TYPE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# execute cooldown (days)
BST_COOLDOWN="$(egrep "BST_COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# cooldown until profit (0)
BST_TAKE_PROFIT="$(egrep "BST_TAKE_PROFIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference status
REFERENCE_STATUS="$(egrep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger  (execute when amount is reached)
LISTING_TRIGGER="$(egrep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger (execute when amount is reached)
REFERENCE_TRIGGER="$(egrep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################

listing_trigger
reference_trigger
total_trigger

################################################################################

# calculate days into seconds
COOLDOWN_SECONDS="$(echo "$BST_COOLDOWN*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"
CONFIG_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$COOLDOWN_SECONDS/3600")) $(("$COOLDOWN_SECONDS%3600/60")) $(("$COOLDOWN_SECONDS%60")))

# calculate seconds minus tx_time
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid ]] &>/dev/null; then
  touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid &>/dev/null
  COOLDOWN_SECONDS="0"
fi

TX_TIME="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

CALCULATE_SECONDS="$(echo "$COOLDOWN_SECONDS-$TX_TIME" | bc 2>/dev/null)"
if [[ "$(echo "$CALCULATE_SECONDS" | grep "-" | wc -l)" -eq "1" ]] &>/dev/null; then
  CALCULATE_SECONDS="0"
fi
ORDER_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$CALCULATE_SECONDS/3600")) $(("$CALCULATE_SECONDS%3600/60")) $(("$CALCULATE_SECONDS%60")))

################################################################################

# get data
echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

BST_Data..............: BST $TYPE
BST_Listing_Trigger...: $TRIGGER_L/$LISTING_TRIGGER
BST_Reference_Trigger.: $TRIGGER_R/$REFERENCE_TRIGGER
BST_Total_Trigger.....: $TOTAL_TRIGGER/1
BST_Cooldown..........: $ORDER_COOLDOWN/$CONFIG_COOLDOWN

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null

################################################################################

open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################

if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
  MARKET_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
  LIMIT_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"
elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
  MARKET_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
  LIMIT_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"
fi

MARKET_BST_POSITION="$LOG_DATE :: $TYPE :: $STRATEGY_TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
LIMIT_BST_POSITION="$MARKET_BST_POSITION"

COOLDOWN_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cooldown $ORDER_COOLDOWN"

################################################################################

if [[ -z "$COOLDOWN_SECONDS" ]] &>/dev/null; then
  COOLDOWN_SECONDS="0"
fi

if [[ -z "$TX_TIME" ]] &>/dev/null; then
  TX_TIME="0"
fi

if [[ "$(egrep "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid | wc -l)" -eq "0" ]] &>/dev/null; then
  COOLDOWN_SECONDS="0"
fi

################################################################################

if [[ "$BST_TAKE_PROFIT" == "1" ]] &>/dev/null; then

  # order position, without decimal
  BST_ORDER_POSITION="$(echo "$LISTING_OPEN_RESULT" | awk -F. '{ print $1 }' 2>/dev/null)"

  PROFIT_BST_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Waiting for profit :: ${LISTING_OPEN_RESULT:?}%"

  if [[ "$BST_ORDER_POSITION" -gt "0" ]] &>/dev/null; then
    COOLDOWN_SECONDS="0" # less
    TX_TIME="1"          # greater
    TOTAL_TRIGGER="1"    # trigger take profit
  fi
fi

################################################################################

if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
  # skip if allocated is less than n%
  ALLOCATED_REAL="$LISTING_ALLOCATED_REAL"
elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
  # skip if allocated is less than n%
  ALLOCATED_REAL="$REFERENCE_ALLOCATED_REAL"
fi

################################################################################

if [[ "$TX_TIME" -gt "$COOLDOWN_SECONDS" ]] &>/dev/null; then

  # trigger greater than zero, continue
  if [[ "$TOTAL_TRIGGER" -gt "0" ]] &>/dev/null; then
    # reference false
    if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        if [[ ! "$(echo "$ALLOCATED_REAL" | awk -F. '{ print $1 }')" -lt "1" ]] &>/dev/null; then

          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$MARKET_BST_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$MARKET_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null

          # limit
        elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

          # placeOrder limit ###################################################
          PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$LIMIT_BST_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$LIMIT_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        fi
      fi

      # reference true
    elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        if [[ ! "$(echo "$ALLOCATED_REAL" | awk -F. '{ print $1 }')" -lt "1" ]] &>/dev/null; then

          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$MARKET_BST_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$MARKET_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null

          # limit
        elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

          # placeOrder limit ###################################################
          PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$LIMIT_BST_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$LIMIT_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        fi
      fi
    fi
  fi
fi

################################################################################

if [[ ! "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null | egrep "Cooldown|Waiting for profit" | wc -l)" -gt "0" ]] &>/dev/null; then
  if [[ "$BST_TAKE_PROFIT" == "0" ]] &>/dev/null; then
    # cooldown output
    echo "$COOLDOWN_BST_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  else
    # profit output
    echo "$PROFIT_BST_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
fi

################################################################################

save_orders
last_orders

################################################################################

robot_Logs_by_date

################################################################################

# END
