#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# buy-sell strategy configuration (static)
################################################################################

STRATEGY_TYPE="BST"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# sell or buy order
TYPE="$(egrep "TYPE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# execute cooldown (days)
BST_COOLDOWN="$(egrep "BST_COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# cooldown or profit (0)
BST_TAKE_PROFIT="$(egrep "BST_TAKE_PROFIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# profit amount (default greater than 3%)
BST_PROFIT_AMOUNT="$(egrep "BST_PROFIT_AMOUNT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# spread limit (default less than 3%)
BST_SPREAD_LIMIT="$(egrep "BST_SPREAD_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference status
REFERENCE_STATUS="$(egrep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger  (execute when amount is reached)
LISTING_TRIGGER="$(egrep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger (execute when amount is reached)
REFERENCE_TRIGGER="$(egrep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx
txid_null             # txid null

################################################################################

LISTING_AVAILABLE_BALANCE_NR="$(echo "$LISTING_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')"
LISTING_TRIGGER_NR="$(echo "$LISTING_TRIGGER" | tr -d '.' | sed 's/^0*//')"

# listing trigger
if [[ "$(echo "$LISTING_TRIGGER" | egrep "[0-9]+" | tr -d '.' | sed 's/^0*//' | wc -l)" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then

  if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "$LISTING_TRIGGER_NR" ]] 2>>"${LOG_ERROR:?}"; then
    TRIGGER_L="1"
  else
    TRIGGER_L="0"
  fi
fi

if [[ -z "$TRIGGER_L" ]] &>/dev/null; then
  TRIGGER_L="0"
fi

################################################################################

REFERENCE_AVAILABLE_BALANCE_NR="$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')"
REFERENCE_TRIGGER_NR="$(echo "$REFERENCE_TRIGGER" | tr -d '.' | sed 's/^0*//')"

# reference trigger
if [[ "$(echo "$REFERENCE_TRIGGER" | egrep "[0-9]+" | tr -d '.' | sed 's/^0*//' | wc -l)" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then

  if [[ "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "$REFERENCE_TRIGGER_NR" ]] 2>>"${LOG_ERROR:?}"; then
    TRIGGER_R="1"
  else
    TRIGGER_R="0"
  fi
fi

if [[ -z "$TRIGGER_R" ]] &>/dev/null; then
  TRIGGER_R="0"
fi

################################################################################

# get total trigger
TOTAL_TRIGGER="$(echo "$TRIGGER_L+$TRIGGER_R" | bc 2>/dev/null)"
if [[ -z "$TOTAL_TRIGGER" ]] &>/dev/null; then
  TOTAL_TRIGGER="0"
fi

################################################################################

# calculate days into seconds
COOLDOWN_SECONDS="$(echo "$BST_COOLDOWN*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"
CONFIG_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$COOLDOWN_SECONDS/3600")) $(("$COOLDOWN_SECONDS%3600/60")) $(("$COOLDOWN_SECONDS%60")))

# calculate seconds minus tx_time
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid ]] 2>>"${LOG_ERROR:?}"; then
  touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>>"${LOG_ERROR:?}"
  COOLDOWN_SECONDS="0"
fi

TX_TIME="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>>"${LOG_ERROR:?}" | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

CALCULATE_SECONDS="$(echo "$COOLDOWN_SECONDS-$TX_TIME" | bc 2>/dev/null)"
if [[ "$(echo "$CALCULATE_SECONDS" | grep "-" | wc -l)" -eq "1" ]] 2>>"${LOG_ERROR:?}"; then
  CALCULATE_SECONDS="0"
fi
ORDER_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$CALCULATE_SECONDS/3600")) $(("$CALCULATE_SECONDS%3600/60")) $(("$CALCULATE_SECONDS%60")))

if [[ -z "$TX_ID_LAST" ]] &>/dev/null; then
  TX_ID_LAST="N/A"
fi

################################################################################

# get data
echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

BST_Data..............: BST $TYPE
BST_Listing_Trigger...: $TRIGGER_L/$LISTING_TRIGGER
BST_Reference_Trigger.: $TRIGGER_R/$REFERENCE_TRIGGER
BST_Total_Trigger.....: $TOTAL_TRIGGER/1
BST_Cooldown..........: $ORDER_COOLDOWN/$CONFIG_COOLDOWN

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST $TXID_AGE (${TXID_AGE_DAYS:?}d)" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>>"${LOG_ERROR:?}"

################################################################################

open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################

if [[ "$REFERENCE_STATUS" == "false" ]] 2>>"${LOG_ERROR:?}"; then
  MARKET_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
  LIMIT_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"
elif [[ "$REFERENCE_STATUS" == "true" ]] 2>>"${LOG_ERROR:?}"; then
  MARKET_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
  LIMIT_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"
fi

MARKET_BST_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $REFERENCE_OPEN_AMOUNT ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
LIMIT_BST_POSITION="$MARKET_BST_POSITION"

COOLDOWN_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cooldown $ORDER_COOLDOWN"

################################################################################

if [[ -z "$COOLDOWN_SECONDS" ]] &>/dev/null; then
  COOLDOWN_SECONDS="0"
fi

if [[ -z "$TX_TIME" ]] &>/dev/null; then
  TX_TIME="0"
fi

if [[ "$(egrep "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid | wc -l)" -eq "0" ]] 2>>"${LOG_ERROR:?}"; then
  COOLDOWN_SECONDS="0"
fi

################################################################################

# take profit enabled
if [[ "$BST_TAKE_PROFIT" == "1" ]] 2>>"${LOG_ERROR:?}"; then

  # disable normal trigger
  TX_TIME="0"

  # low (bid)
  BST_SPREAD_LOW="$LISTING_PRICE"
  # high (ask)
  BST_SPREAD_HIGH="$LISTING_PRICE_ASK"
  # get difference
  BST_SPREAD_DIFF="$(echo "$BST_SPREAD_HIGH-$BST_SPREAD_LOW" | bc -l 2>/dev/null)"
  # calculate percentage
  BST_DIFF_PERCENTAGE="$(echo "100/$LISTING_PRICE*$BST_SPREAD_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # bst spread without decimal (n%)
  BST_SPREAD="$(echo "$BST_DIFF_PERCENTAGE" | awk -F. '{ print $1 }')"
  # profit without decimal (n%)
  LISTING_OPEN_RESULT_OK="$(echo "$LISTING_OPEN_RESULT" | awk -F. '{ print $1 }')"

  if [[ -z "$BST_SPREAD" ]] &>/dev/null; then
    BST_SPREAD="0"
  fi
  if [[ -z "$BST_PROFIT_AMOUNT" ]] &>/dev/null; then
    BST_PROFIT_AMOUNT="0"
  fi

  SPREAD_OK="NO"
  PROFIT_OK="NO"

  # profit greater or equal than n%
  if [[ "$LISTING_OPEN_RESULT_OK" -ge "$BST_PROFIT_AMOUNT" ]] 2>>"${LOG_ERROR:?}"; then
    PROFIT_OK="OK"
  fi
  # spread less than n%
  if [[ "$BST_SPREAD" -lt "$BST_SPREAD_LIMIT" ]] 2>>"${LOG_ERROR:?}"; then
    SPREAD_OK="OK"
  fi

  # trigger everything
  if [[ "$PROFIT_OK" == "OK" ]] && [[ "$SPREAD_OK" == "OK" ]]; then
    COOLDOWN_SECONDS="0" # less
    TX_TIME="1"          # greater
    TOTAL_TRIGGER="1"    # trigger take profit
  fi
fi

# status, spread output with decimal (n%)
PROFIT_BST_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Result ${LISTING_OPEN_RESULT:?}->${BST_PROFIT_AMOUNT:?}% Spread ${BST_DIFF_PERCENTAGE:?}<-${BST_SPREAD_LIMIT:?}% - $PROFIT_OK/$SPREAD_OK"

################################################################################

ALLOCATED_REAL="0"

if [[ "$REFERENCE_STATUS" == "false" ]] 2>>"${LOG_ERROR:?}"; then
  AMOUNT_IN_REFERENCE_CURRENCY="false"
  # skip if allocated is less than n%
  ALLOCATED_REAL="$(echo "$LISTING_ALLOCATED_REAL" | awk -F. '{ print $1 }')"
elif [[ "$REFERENCE_STATUS" == "true" ]] 2>>"${LOG_ERROR:?}"; then
  AMOUNT_IN_REFERENCE_CURRENCY="true"
  # skip if allocated is less than n%
  ALLOCATED_REAL="$(echo "$REFERENCE_ALLOCATED_REAL" | awk -F. '{ print $1 }')"
fi

################################################################################

if [[ "$TX_TIME" -gt "$COOLDOWN_SECONDS" ]] 2>>"${LOG_ERROR:?}"; then

  # trigger greater than zero
  if [[ "$TOTAL_TRIGGER" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
    # reference false
    if [[ "$REFERENCE_STATUS" == "false" ]] 2>>"${LOG_ERROR:?}"; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
        # allocated limit
        if [[ "$ALLOCATED_REAL" -gt "1" ]] 2>>"${LOG_ERROR:?}"; then

          if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
            # placeOrder market ################################################
            PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
            ####################################################################
          fi

          echo "$MARKET_BST_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          tx_id
          cost_price
          echo "$MARKET_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # limit
        elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then

          if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
            # placeOrder limit #################################################
            PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
            ####################################################################
          fi

          echo "$LIMIT_BST_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          tx_id
          cost_price
          echo "$LIMIT_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
        fi
      fi

      # reference true
    elif [[ "$REFERENCE_STATUS" == "true" ]] 2>>"${LOG_ERROR:?}"; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
        # allocated limit
        if [[ "$ALLOCATED_REAL" -gt "1" ]] 2>>"${LOG_ERROR:?}"; then

          if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
            # placeOrder market ################################################
            PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
            ####################################################################
          fi

          echo "$MARKET_BST_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          tx_id
          cost_price
          echo "$MARKET_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # limit
        elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then

          if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
            # placeOrder limit #################################################
            PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
            ####################################################################
          fi

          echo "$LIMIT_BST_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          tx_id
          cost_price
          echo "$LIMIT_BST_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

          # remove duplicates
          echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
        fi
      fi
    fi
  fi
fi

################################################################################

if [[ ! "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log 2>>"${LOG_ERROR:?}" | egrep "Cooldown| :: Result " | wc -l)" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
  if [[ "$BST_TAKE_PROFIT" == "0" ]] 2>>"${LOG_ERROR:?}"; then
    # cooldown output
    echo "$COOLDOWN_BST_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
  else
    # profit output
    echo "$PROFIT_BST_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
  fi
fi

################################################################################

save_orders
last_orders
sxc_backup_orders

################################################################################

robot_Log_cleanup

################################################################################

# END
