#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# buy-sell strategy configuration
################################################################################

# type
TYPE="sell"              # sell or buy order
COOLDOWN="1"             # execute cooldown (days)
MARKET_LIMIT="market"    # market or limit order
REFERENCE_STATUS="false" # reference status

# listing
LISTING_CURRENCY=""     # listing currency
LISTING_TRIGGER=""      # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="100" # account allocated (100%)

# reference
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_TRIGGER=""      # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="100" # account allocated (100%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="BST$(basename "$0" | awk -F. '{ print $2 }')"
bash "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".strategy

# END
