#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# pool
source /usr/local/bin/include/leeloo/strategies/pool

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
STRATEGY_NAME="$(egrep "STRATEGY_NAME=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# buy-sell strategy configuration (static)
################################################################################

STRATEGY_TYPE="BST"

MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

TYPE="$(egrep "TYPE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                         # sell or buy order
COOLDOWN="$(egrep "COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                 # execute cooldown (days)
REFERENCE_STATUS="$(egrep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # reference status

# listing
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # listing currency
LISTING_TRIGGER="$(egrep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"     # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

# reference
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # reference currency
REFERENCE_TRIGGER="$(egrep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"     # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################
# S T R A T E G Y - T R I G G E R
################################################################################

listing_trigger
reference_trigger
total_trigger

################################################################################

# calculate days into seconds
COOLDOWN_SECONDS="$(echo "$COOLDOWN*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"
CONFIG_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$COOLDOWN_SECONDS/3600")) $(("$COOLDOWN_SECONDS%3600/60")) $(("$COOLDOWN_SECONDS%60")))

# calculate seconds minus tx_time
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid ]] &>/dev/null; then
  touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid &>/dev/null
  COOLDOWN_SECONDS="0"
fi

TX_TIME="$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null)))" 2>/dev/null)"

CALCULATE_SECONDS="$(echo "$COOLDOWN_SECONDS-$TX_TIME" | bc 2>/dev/null)"
if [[ "$(echo "$CALCULATE_SECONDS" | grep "-" | wc -l)" -eq "1" ]] &>/dev/null; then
  CALCULATE_SECONDS="0"
fi
ORDER_COOLDOWN=$(printf '%dh:%dm:%ds\n' $(("$CALCULATE_SECONDS/3600")) $(("$CALCULATE_SECONDS%3600/60")) $(("$CALCULATE_SECONDS%60")))

################################################################################

# get data
function result_bst() {
  echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY
BST_Data..............: BST $TYPE
Listing_Trigger.......: $TRIGGER_L/$LISTING_TRIGGER
Reference_Trigger.....: $TRIGGER_R/$REFERENCE_TRIGGER
Total_Trigger.........: $TOTAL_TRIGGER/1
Cooldown..............: $ORDER_COOLDOWN/$CONFIG_COOLDOWN
Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "Last_Order.txid.......:  $TX_ID_LAST
" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "- Last info" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "$(egrep "info.*Incoming" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | tail -1)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "- Executed" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  # get executed orders
  echo "$(egrep "sell.*h:|buy.*h:" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -v "Cooldown")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
  echo "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
}

################################################################################

BST_TIMER="$(echo "${BOT_TIMER:?}*1.25" | bc 2>/dev/null | awk -F. '{ print $1 }')" # BST data timer

# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null)))" 2>/dev/null)" -gt "$BST_TIMER" ]] &>/dev/null; then
  result_bst
  # update data if missing
elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_bst
  # update data if empty
elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_bst
fi

################################################################################
# O P E N - P O S I T I O N S
################################################################################

OPEN_STRATEGY="$STRATEGY_TYPE"
open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################

if [[ -z "$COOLDOWN_SECONDS" ]] &>/dev/null; then
  COOLDOWN_SECONDS="0"
fi

if [[ -z "$TX_TIME" ]] &>/dev/null; then
  TX_TIME="0"
fi

if [[ "$(egrep "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid | wc -l)" -eq "0" ]] &>/dev/null; then
  if [[ ! "$(grep " :: (0) No tx!" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | wc -l)" -gt "0" ]] &>/dev/null; then
    echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: (0) No tx!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  fi
  COOLDOWN_SECONDS="0"
fi

if [[ "$TX_TIME" -gt "$COOLDOWN_SECONDS" ]] &>/dev/null; then

  # trigger greater than zero, continue
  if [[ "$TOTAL_TRIGGER" -gt "0" ]] &>/dev/null; then
    # reference false
    if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        # placeOrder market ####################################################
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $LISTING_CURRENCY :: Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
        tx_id
        cost_price
        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log

        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

        # placeOrder limit #####################################################
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
        tx_id
        cost_price
        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log

      fi
    # reference true
    elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        # placeOrder market ####################################################
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $LISTING_CURRENCY :: Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
        tx_id
        cost_price
        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log

        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

        # placeOrder limit #####################################################
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
        tx_id
        cost_price
        echo "$LOG_DATE :: Strategy $STRATEGY_TYPE $TYPE :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log

      fi
    fi
  fi
else
  if [[ ! "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep "Cooldown" | wc -l)" -gt "0" ]] &>/dev/null; then
    echo "$LOG_DATE :: Strategy $STRATEGY_TYPE info :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cooldown $ORDER_COOLDOWN" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  fi
fi

################################################################################

# sort by date
echo "$(sort -k 1.5M -k 1.3n -k 1.4n -k 2n -k 3.1n -k 3.2n "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
  echo "$(tail -"$(echo "$MAX_LOG/3" | bc 2>/dev/null)" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  echo "$LOG_DATE :: LogReset :: Line $MAX_LOG" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
else
  echo "$(cat "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
fi

################################################################################

# END
