#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

DATE="$(date | xargs)"
# get strategy id.config
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"

################################################################################
# buy-sell strategy configuration (static)
################################################################################

# type
TYPE="$(grep "TYPE=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                         # sell or buy order
COOLDOWN="$(grep "COOLDOWN=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                 # execute cooldown (days)
MARKET_LIMIT="$(grep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"         # market or limit order
REFERENCE_STATUS="$(grep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # reference status

# listing
LISTING_CURRENCY="$(grep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # listing currency
LISTING_TRIGGER="$(grep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"     # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="$(grep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

# reference
REFERENCE_CURRENCY="$(grep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # reference currency
REFERENCE_TRIGGER="$(grep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }')"                                      # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="$(grep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

################################################################################
# listing and reference data
################################################################################

# listing trigger
if [[ "$(echo "$LISTING_TRIGGER" | egrep "[0-9]+")" ]] &>/dev/null; then

  # get available listing data
  LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
  LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

  if [[ "$(echo "$LISTING_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$LISTING_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    TRIGGER_L="1"
  else
    TRIGGER_L="0"
  fi
fi

# reference trigger
if [[ "$(echo "$REFERENCE_TRIGGER" | egrep "[0-9]+")" ]] &>/dev/null; then

  # get available reference data
  REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
  REFERENCE_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

  if [[ "$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$REFERENCE_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    TRIGGER_R="1"
  else
    TRIGGER_R="0"
  fi
fi

if [[ -z "$TRIGGER_L" ]] &>/dev/null; then
  TRIGGER_L="0"
fi
if [[ -z "$TRIGGER_R" ]] &>/dev/null; then
  TRIGGER_R="0"
fi

# get total trigger
TOTAL_TRIGGER="$(echo "$TRIGGER_L+$TRIGGER_R" | bc 2>/dev/null)"

if [[ -z "$TOTAL_TRIGGER" ]] &>/dev/null; then
  TOTAL_TRIGGER="0"
fi

################################################################################
# strategy
################################################################################

# calculate days into seconds
COOLDOWN_SECONDS="$(echo "$(grep "COOLDOWN=" "${SYS_DIR:?}"/robot/bst."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | egrep -o "[0-9]+.[0-9]+")*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"

if [[ ! -f "${SYS_DIR:?}"/robot/txid."$BASENAME_STRATEGY" ]] &>/dev/null; then
  touch "${SYS_DIR:?}"/robot/txid."$BASENAME_STRATEGY" &>/dev/null
  COOLDOWN_SECONDS="0"
fi

TX_TIME="$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/txid."$BASENAME_STRATEGY" 2>/dev/null)))" 2>/dev/null)"

if [[ -z "$COOLDOWN_SECONDS" ]] &>/dev/null; then
  COOLDOWN_SECONDS="0"
fi
if [[ -z "$TX_TIME" ]] &>/dev/null; then
  TX_TIME="0"
fi

if [[ "$TX_TIME" -gt "$COOLDOWN_SECONDS" ]] &>/dev/null; then

  function cooldown {
    echo "$PLACE_ORDER" >"${SYS_DIR:?}"/robot/txid."$BASENAME_STRATEGY"
  }

  # trigger greater than zero, continue
  if [[ "$TOTAL_TRIGGER" -gt "0" ]] &>/dev/null; then
    # reference false
    if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        cooldown
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        cooldown
      fi
    # reference true
    elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        cooldown
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        cooldown
      fi
    fi
  fi
else
  echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cooldown $TX_TIME/$COOLDOWN_SECONDS" >>"${LOG_DIR:?}"/leeloo/robot.log
fi

################################################################################

# END
