#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################
# buy-sell strategy configuration
################################################################################

# type
TYPE="sell"              # sell or buy order
COOLDOWN="1"             # execute cooldown (days)
MARKET_LIMIT="market"    # market or limit order
REFERENCE_STATUS="false" # reference status

# listing
LISTING_CURRENCY=""     # listing currency
LISTING_TRIGGER=""      # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="100" # account allocated (100%)

# reference
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_TRIGGER=""      # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="100" # account allocated (100%)

################################################################################

source /usr/local/bin/include/leeloo/broker.conf

# southxchange api
source include/api/southxchange/private_API
source include/api/southxchange/public_API

DATE="$(date | xargs)"

################################################################################
# listing and reference data
################################################################################

# listing trigger
if [[ "$(echo "$LISTING_TRIGGER" | egrep "[0-9]+")" ]] &>/dev/null; then

  # get available listing data
  LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
  LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

  if [[ "$(echo "$LISTING_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$LISTING_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    TRIGGER_L="1"
  else
    TRIGGER_L="0"
  fi
fi

# reference trigger
if [[ "$(echo "$REFERENCE_TRIGGER" | egrep "[0-9]+")" ]] &>/dev/null; then

  # get available reference data
  REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null)"
  REFERENCE_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

  if [[ "$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$REFERENCE_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    TRIGGER_R="1"
  else
    TRIGGER_R="0"
  fi
fi

if [[ -z "$TRIGGER_L" ]] &>/dev/null; then
  TRIGGER_L="0"
fi
if [[ -z "$TRIGGER_R" ]] &>/dev/null; then
  TRIGGER_R="0"
fi

# get total trigger
TOTAL_TRIGGER="$(echo "$TRIGGER_L+$TRIGGER_R" | bc 2>/dev/null)"

if [[ -z "$TOTAL_TRIGGER" ]] &>/dev/null; then
  TOTAL_TRIGGER="0"
fi

################################################################################
# strategy
################################################################################

# calculate days into seconds
COOLDOWN_DAYS="$(echo "$COOLDOWN*86400" | bc 2>/dev/null)"
COOLDOWN_BST="$(echo "$(($(date +%s) - $(date +%s -r "${LOG_DIR:?}"/leeloo/cd_bst 2>/dev/null)))" 2>/dev/null)"

if [[ ! -f "${LOG_DIR:?}"/leeloo/cd_bst ]] &>/dev/null; then
  touch "${LOG_DIR:?}"/leeloo/cd_bst &>/dev/null
fi

if [[ "$COOLDOWN_BST" -gt "$COOLDOWN_DAYS" ]] &>/dev/null; then
  rm "${LOG_DIR:?}"/leeloo/cd_bst &>/dev/null
fi

if [[ ! -f "${LOG_DIR:?}"/leeloo/cd_bst ]] &>/dev/null; then
  # trigger greater than zero, continue
  if [[ "$TOTAL_TRIGGER" -gt "0" ]] &>/dev/null; then
    # reference false
    if [[ "$REFERENCE_STATUS" == "false" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
      fi
    # reference true
    elif [[ "$REFERENCE_STATUS" == "true" ]] &>/dev/null; then
      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
      fi
    fi
    # cooldown
    echo "$DATE" >"${LOG_DIR:?}"/leeloo/cd_bst
  fi
fi

################################################################################

# END
