#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# custom strategy configuration
################################################################################

TYPE="sell"               # sell or buy order
CST_COOLDOWN="1"          # execute cooldown (days)
MARKET_LIMIT="market"     # market or limit order
REFERENCE_STATUS="false"  # reference status
LISTING_CURRENCY=""       # listing currency
LISTING_TRIGGER=""        # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="100"   # account allocated (100%)
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_TRIGGER=""      # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="100" # account allocated (100%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
