#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/sMcD

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# custom strategy configuration (static)
################################################################################

STRATEGY_TYPE="CST"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# sell or buy order
TYPE="$(egrep "TYPE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# execute cooldown (days)
CST_COOLDOWN="$(egrep "CST_COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference status
REFERENCE_STATUS="$(egrep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger  (execute when amount is reached)
LISTING_TRIGGER="$(egrep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing trigger (execute when amount is reached)
REFERENCE_TRIGGER="$(egrep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# trategy templates
################################################################################

# poloniex template
if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/poloniex
fi
# southxchange template
if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/southxchange
fi
# stakecube template
if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/stakecube
fi

if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
  echo "$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  exit
fi

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################

open_positions

################################################################################

CST_CHANGE_ME="$LOG_DATE :: $BASENAME_STRATEGY :: No lines of code found! ::"

################################################################################

# CODE #

################################################################################

echo "$CST_CHANGE_ME" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

################################################################################

incoming_listing
incoming_reference

################################################################################

save_orders
last_orders
sxc_backup_orders

################################################################################

robot_Log_cleanup

################################################################################

# END
