#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
STRATEGY_NAME="$(egrep "STRATEGY_NAME=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# custom strategy configuration (static)
################################################################################

STRATEGY_TYPE="CST"

MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

TYPE="$(egrep "TYPE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                         # sell or buy order
COOLDOWN="$(egrep "COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                 # execute cooldown (days)
REFERENCE_STATUS="$(egrep "REFERENCE_STATUS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # reference status

# listing
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # listing currency
LISTING_TRIGGER="$(egrep "LISTING_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"     # listing trigger  (execute when amount is reached)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

# reference
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # reference currency
REFERENCE_TRIGGER="$(egrep "REFERENCE_TRIGGER=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"     # listing trigger (execute when amount is reached)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (100%)

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################
# C U S T O M - A N Y T H I N G
################################################################################

# code

# END
