#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# dip strategy configuration
################################################################################

# SXC southxchange template
# XGX xeggex template

################################################################################

EXCHANGE_API=""        # exchange api (template)
DIP_MIN_DIP="5"        # minimum dip percentage
DIP_MAX_DIP="50"       # maximum dip percentage
DIP_MIN_SPREAD="10"    # minimum spread percentage
DIP_MAX_SPREAD="50"    # maximum spread percentage
DIP_MIN_VOLUME="0.5"   # minimum volume
DIP_MIN_MOVEMENT="0"   # minimum price movement
DIP_MARKETS="BTC"      # main market
DIP_MARGIN="1"         # order margin
DIP_DCA="false"        # dca (default false) 100=100%
DIP_ALL_IN="0"         # use reference as targets
DIP_ALLOCATED="1"      # dip allocated (1% of balance)
DIP_MAX_ORDERS="10"    # max open orders
DIP_MAX_AGE="600"      # dip max age (default 600 seconds)
DIP_DISREGARD_BOTS="1" # disregard other markets run by other bots
DIP_OLD_ORDER_MAX="7"  # max buy order age (days)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
