#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# dip strategy configuration
################################################################################

# XGX xeggex template

################################################################################

EXCHANGE_API=""        # exchange api (template)
DIP_MIN_DIP="1"        # minimum dip percentage (slightly higher for added caution)
DIP_MAX_DIP="80"       # maximum dip percentage (adjust based on market conditions)
DIP_MIN_SPREAD="3"     # minimum spread percentage (lower for higher liquidity)
DIP_MAX_SPREAD="80"    # maximum spread percentage (be cautious in volatile markets)
DIP_MIN_VOLUME="1"     # minimum volume (higher for liquidity)
DIP_MIN_MOVEMENT="0"   # minimum price movement (filter out minor fluctuations)
DIP_RSI_LIMIT="34"     # relative strength index limit (when below limit, buy)
DIP_MARKETS="USDT"     # choose available market (USDT, BTC, LTC, DOGE, ETH)
DIP_MARGIN="1"         # order margin (slightly higher for added leverage)
DIP_DCA="100"          # dollar cost averaging (DCA) percentage (half allocation for DCA)
DIP_ALL_IN="0"         # do not use the reference as targets (maintain independent strategy)
DIP_ALLOCATED="0.1"    # dip allocated (allocate 3% of the balance)
DIP_MAX_ORDERS="100"   # maximum open orders (manage exposure)
DIP_MAX_AGE="180"      # dip max age (react faster to changing market conditions)
DIP_DISREGARD_BOTS="1" # disregard other markets run by other bots (focus on own strategy)
DIP_MAX_BUY_AGE="1"    # max buy order age (days) before reconsideration
DIP_MAX_SELL_AGE="2"   # max sell order age (days) before reconsideration
DIP_EXTRA_LOGS="false" # extra dip logs (extra information)
DIP_PAUSE_MARKETS="24" # pause failing markets (24 markets)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
