#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# dip strategy configuration (static) BETA (embrace chaos)
################################################################################

STRATEGY_TYPE="DIP"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# minimum dip percentage (default 5%)
DIP_MIN_DIP="$(egrep "DIP_MIN_DIP=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# minimum spread percentage (default 10%)
DIP_MIN_SPREAD="$(egrep "DIP_MIN_SPREAD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# minimum volume percentage (default 0.5%)
DIP_MIN_VOLUME="$(egrep "DIP_MIN_VOLUME=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# markets to consider
DIP_MARKETS="$(egrep "DIP_MARKETS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk '{ print $1 }' | awk -F= '{ print $2 }' | tr -d '"#')"
# dip allocated (1% of balance)
DIP_ALLOCATED="$(egrep "DIP_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# max open orders (default 10)
DIP_MAX_ORDERS="$(egrep "DIP_MAX_ORDERS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# dip margin (default 1)
DIP_MARGIN="$(egrep "DIP_MARGIN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# dip max age (default 600 seconds)
DIP_MAX_AGE="$(egrep "DIP_MAX_AGE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# disregard other markets run by other bots
DIP_DISREGARD_BOTS="$(egrep "DIP_DISREGARD_BOTS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################

last_tx
delisted

################################################################################

# amount to buy sell
function amount_to_buy_sell() {
  # account allocated (n%)
  REFERENCE_ALLOCATED="$DIP_ALLOCATED"
  # configuration not set, use n%
  if [[ -z "$REFERENCE_ALLOCATED" ]] &>/dev/null; then
    REFERENCE_ALLOCATED="1" # n%
  fi
  # calculate dip allocated (configuration)
  REFERENCE_ALLOCATED="$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)"

  # reference balance (available)
  REFERENCE_BALANCE="$(grep -w "\<$REFERENCE_CURRENCY:" "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }' | head -1)"
  # listing balance (available)
  LISTING_BALANCE="$(grep -w "\<$LISTING_CURRENCY:" "${LOG_DIR:?}"/leeloo/southxchange/balances 2>/dev/null | awk '{ print $3 }' | awk '{ printf "%.9f\n", $1 }' | head -1)"

  if [[ -z "$REFERENCE_BALANCE" ]] &>/dev/null; then
    REFERENCE_BALANCE="0.000000000"
  fi
  if [[ -z "$LISTING_BALANCE" ]] &>/dev/null; then
    LISTING_BALANCE="0.000000000"
  fi

  # calculate dip margin
  DIP_MARGIN="$(echo "$DIP_MARGIN/1000000000" | bc -l 2>/dev/null)"
  # price margin (default 1 = 0.000000001), buy with margin (positive)
  DIP_TARGET_BID="$(echo "$DIP_TARGET_BID+$DIP_MARGIN" | bc -l 2>/dev/null)"
  # price margin (default 1 = 0.000000001), sell with margin (negative)
  DIP_TARGET_ASK="$(echo "$DIP_TARGET_ASK-$DIP_MARGIN" | bc -l 2>/dev/null)"

  # amount for buy (reference)
  DIP_BUY_AMOUNT_REFERENCE="$(echo "$REFERENCE_ALLOCATED*$REFERENCE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to buy (listing)
  DIP_BUY_AMOUNT_LISTING="$(echo "$DIP_BUY_AMOUNT_REFERENCE/$DIP_TARGET_BID" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to get (reference)
  DIP_GET_AMOUNT_REFERENCE="$(echo "$DIP_BUY_AMOUNT_LISTING*$DIP_TARGET_ASK" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to profit (reference)
  DIP_GET_AMOUNT_PROFIT="$(echo "$DIP_GET_AMOUNT_REFERENCE-$DIP_BUY_AMOUNT_REFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to profit (reference percentage)
  DIP_GET_PERCENTAGE_PROFIT="$(echo "100/$DIP_GET_AMOUNT_REFERENCE*$DIP_GET_AMOUNT_PROFIT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
}

################################################################################

# target data for both target and active
function target_data() {

  # use latest target
  if [[ "$TARGET_ACTIVE" == "TARGET" ]] &>/dev/null; then
    DIP_TARGET_FILE_OUTPUT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target 2>/dev/null | head -1)"

    # use active list
  elif [[ "$TARGET_ACTIVE" == "ACTIVE" ]] &>/dev/null; then
    DIP_TARGET_FILE_OUTPUT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | shuf | head -1)"
  fi

  ##############################################################################

  # target count (data)
  DIP_TARGET_COUNT="$(echo "$DIP_TARGET_FILE_OUTPUT" | sed '/^$/d' | wc -l)"

  # target symbol
  DIP_TARGET_SYMBOL="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $1 }' | tr -d ':')"
  # listing (target from above)
  LISTING_CURRENCY="$(echo "$DIP_TARGET_SYMBOL" | awk -F/ '{ print $1 }')"
  # reference (market from above)
  REFERENCE_CURRENCY="$(echo "$DIP_TARGET_SYMBOL" | awk -F/ '{ print $2 }')"

  # target bid
  DIP_TARGET_BID="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $4 }')"
  # target ask
  DIP_TARGET_ASK="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $7 }')"
  # target last
  DIP_TARGET_LAST="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $10 }')"
  # target dip
  DIP_TARGET_DIP="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $13 }')"
  # target spread
  DIP_TARGET_SPREAD="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $16 }')"
  # target price movement
  DIP_TARGET_PRICE_MOVEMENT="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $20 }')"
  # target volume
  DIP_TARGET_VOLUME="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $23 }')"

  amount_to_buy_sell

  # target amount to buy and sell (listing)
  DIP_TARGET_AMOUNT="$(echo "$DIP_TARGET_FILE_OUTPUT" | awk '{ print $26 }' | awk '{ printf "%.9f\n", $1 }')"
}

################################################################################

# remove zero positions (amount to buy is zero)
DIP_ZERO_POSITION="$(egrep "Amount: 0.000000000" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active | awk '{ print $1 }' | tr -d ':' | shuf | head -1)"

if [[ -n "$DIP_ZERO_POSITION" ]] &>/dev/null; then
  # remove old (active) order
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$DIP_ZERO_POSITION")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
  # log target output
  DIP_ZERO_POSITION_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Removing :: Zero order (no amount) $DIP_ZERO_POSITION"
  echo "$DIP_ZERO_POSITION_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
  # auto delist market
  echo "$DIP_ZERO_POSITION" >>"${SYS_DIR:?}"/delisted_southxchange
  # remove duplicates
  echo "$(cat "${SYS_DIR:?}"/delisted_southxchange 2>/dev/null | awk '!a[$0]++')" | sort >"${SYS_DIR:?}"/delisted_southxchange
fi

################################################################################
# market prices
################################################################################

# create price.dip file, disregard markets with equal bid & ask
cat "${LOG_DIR:?}"/leeloo/southxchange/prices 2>/dev/null | awk '{if ($2 != $3) print}' >"${LOG_DIR:?}"/leeloo/southxchange/prices.dip

################################################################################

# disregard already active bots (orders)
if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active)" -gt "0" ]] &>/dev/null; then

  RANDOM_CLEARED_MARKET=$((((RANDOM % 2) + 1)))

  if [[ "$RANDOM_CLEARED_MARKET" == "1" ]] &>/dev/null; then
    # set the paths for the files
    PRICES_FILE="${LOG_DIR}/leeloo/southxchange/prices.dip"
    # extract the active markets from the active file
    ALREADY_ACTIVE_BOTS="$(egrep -o "[A-Z]+/[A-Z]+|[0-9]+/[0-9]+|[A-Z]+[0-9]+/[A-Z]+[0-9]+|[0-9]+[A-Z]+/[0-9]+[A-Z]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active)"
    # filter out markets with found data
    grep -vf <(echo "$ALREADY_ACTIVE_BOTS") "$PRICES_FILE" >"${PRICES_FILE}.temp"
    # replace the original prices file with the filtered version
    mv "${PRICES_FILE}.temp" "$PRICES_FILE"
  fi
fi

# disregard already running bots (strategies)
if [[ "$DIP_DISREGARD_BOTS" == "1" ]] &>/dev/null; then
  # set the paths for the files
  ROBOT_LOG="${LOG_DIR}/leeloo/robot.log"
  PRICES_FILE="${LOG_DIR}/leeloo/southxchange/prices.dip"
  # extract the running markets from the robot.log file
  ALREADY_RUNNING_BOTS=$(tail -100 "$ROBOT_LOG" 2>/dev/null | awk '!/All|DIP/ {print $7}' | awk '!a[$0]++' | egrep -o "[A-Z]+/[A-Z]+|[0-9]+/[0-9]+|[A-Z]+[0-9]+/[A-Z]+[0-9]+|[0-9]+[A-Z]+/[0-9]+[A-Z]+")
  # filter out markets with found data
  grep -vf <(echo "$ALREADY_RUNNING_BOTS") "$PRICES_FILE" >"${PRICES_FILE}.temp"
  # replace the original prices file with the filtered version
  mv "${PRICES_FILE}.temp" "$PRICES_FILE"
fi

################################################################################

# prices file output
DIP_PRICES_FILE_OUTPUT="$(cat "${LOG_DIR:?}/leeloo/southxchange/prices.dip" 2>/dev/null)"
# total market count
DIP_PRICES_FILE_COUNT="$(echo "$DIP_PRICES_FILE_OUTPUT" | wc -l)"

# config not set, do random markets (all reference markets)
if [[ -z "$DIP_MARKETS" ]] &>/dev/null; then
  # dip markets (random)
  DIP_MARKETS="$(echo "$DIP_PRICES_FILE_OUTPUT" | awk -F/ '{ print $2 }' | awk '{ print $1 }' | awk '!a[$1]++' | tr -d ':' | shuf | head -1)"
fi

# use good old bitcoin if still zero
if [[ -z "$DIP_MARKETS" ]] &>/dev/null; then
  DIP_MARKETS="BTC"
fi

# create specific dip_markets list
echo "$(echo "$DIP_PRICES_FILE_OUTPUT" | grep "/$DIP_MARKETS" 2>/dev/null)" >"${LOG_DIR:?}/leeloo/southxchange/prices.$DIP_MARKETS" 2>/dev/null

################################################################################

# prices file output
DIP_ACTIVE_FILE_OUTPUT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null)"
# total active count
DIP_ACTIVE_FILE_COUNT="$(echo "$DIP_ACTIVE_FILE_OUTPUT" | sed '/^$/d' | wc -l)"

# total active dip
DIP_ACTIVE_FILE_DIP="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | awk '{ print $13 }' | awk '{ SUM += $1} END { print SUM }')"
# calculate average dip
DIP_ACTIVE_FILE_AVERAGE_DIP="$(echo "$DIP_ACTIVE_FILE_DIP/$DIP_ACTIVE_FILE_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

if [[ -z "$DIP_ACTIVE_FILE_AVERAGE_DIP" ]] &>/dev/null; then
  DIP_ACTIVE_FILE_AVERAGE_DIP="0"
fi

# total active spread
DIP_ACTIVE_FILE_SPREAD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | awk '{ print $16 }' | awk '{ SUM += $1} END { print SUM }')"
# calculate average spread
DIP_ACTIVE_FILE_AVERAGE_SPREAD="$(echo "$DIP_ACTIVE_FILE_SPREAD/$DIP_ACTIVE_FILE_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

if [[ -z "$DIP_ACTIVE_FILE_COUNT" ]] &>/dev/null; then
  DIP_ACTIVE_FILE_COUNT="0"
fi
if [[ -z "$DIP_ACTIVE_FILE_AVERAGE_SPREAD" ]] &>/dev/null; then
  DIP_ACTIVE_FILE_AVERAGE_SPREAD="0"
fi

# specific prices count
DIP_PRICES_FILE_COUNT="$(echo "$DIP_PRICES_FILE_OUTPUT" | grep -c "/$DIP_MARKETS" 2>/dev/null)"

# log prices output
DIP_PRICES_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : All/$DIP_MARKETS :: Search: $DIP_PRICES_FILE_COUNT Active: $DIP_ACTIVE_FILE_COUNT Dip: ${DIP_ACTIVE_FILE_AVERAGE_DIP:?}% Spread: ${DIP_ACTIVE_FILE_AVERAGE_SPREAD:?}%"
echo "$DIP_PRICES_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

################################################################################
# search market for a target
################################################################################

# prices file path
DIP_PRICES_FILE="${LOG_DIR:?}/leeloo/southxchange/prices.$DIP_MARKETS"

################################################################################

if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market ]] &>/dev/null; then
  touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market &>/dev/null
fi

################################################################################

# variables for potential buy recommendation (default)
POTENTIAL_BUY_SYMBOL=""
POTENTIAL_BUY_BID="0"
POTENTIAL_BUY_ASK="0"

################################################################################

# market file age
DIP_MARKET_FILE_AGE="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

if [[ -z "$DIP_MARKET_FILE_AGE" ]] &>/dev/null; then
  DIP_MARKET_FILE_AGE="0"
fi

################################################################################

# file age greater than max age
if [[ "$DIP_MARKET_FILE_AGE" -gt "$DIP_MAX_AGE" ]] &>/dev/null; then

  # reset market file
  if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market 2>/dev/null | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then
    truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market &>/dev/null
  fi

  ##############################################################################

  # read the file line by line
  while IFS= read -r line; do
    # extract relevant information from the line
    SYMBOL=$(echo "$line" | awk '{print $1}')
    BID=$(echo "$line" | awk '{print $2}')
    ASK=$(echo "$line" | awk '{print $3}')
    LAST=$(echo "$line" | awk '{print $4}')
    DIP=$(echo "$line" | awk '{print $5}' | sed 's/%//')
    VOLUME_PERCENTAGE=$(echo "$line" | awk '{print $6}' | sed 's/%//')
    # if the symbol matches the specified market and if the spread, dip, and volume meet the criteria
    if [[ "$SYMBOL" == *"$DIP_MARKETS"* ]] && (($(echo "$DIP < -$DIP_MIN_DIP" | bc -l 2>/dev/null))) && (($(echo "$VOLUME_PERCENTAGE > $DIP_MIN_VOLUME" | bc -l 2>/dev/null))); then
      if [[ $BID != "0" ]] && [[ $BID != "0.000000000" ]]; then
        # spread
        SPREAD=$(bc -l <<<"scale=2; ($ASK - $BID) / $BID * 100" 2>/dev/null | awk '{ printf "%.2f\n", $1 }')
        if (($(echo "$SPREAD > $DIP_MIN_SPREAD" | bc -l))); then
          # price movement ("Thats a good potential! --80s broker, New York)
          PRICE_MOVEMENT=$(bc -l <<<"scale=2; ($LAST - $BID) / $BID * 100" 2>/dev/null | awk '{ printf "%.2f\n", $1 }')
          # volume percentage (configuration)
          VOLUME_PERCENTAGE="$(echo "$VOLUME_PERCENTAGE" | awk '{ printf "%.2f\n", $1 }')"
          # create market file
          echo "$SYMBOL | Bid: $BID | Ask: $ASK | Dip: $DIP% | Spread: $SPREAD% | Price Movement: $PRICE_MOVEMENT% | Volume: $VOLUME_PERCENTAGE" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market
          # if the symbol meets the potential buy criteria
          if (($(echo "$PRICE_MOVEMENT > 0" | bc -l 2>/dev/null))); then
            if (($(echo "$BID < $POTENTIAL_BUY_BID" | bc -l 2>/dev/null))) || [[ -z "$POTENTIAL_BUY_SYMBOL" ]]; then
              # potential symbol, bid, ask, last
              POTENTIAL_BUY_SYMBOL="$SYMBOL"
              POTENTIAL_BUY_BID="$BID"
              POTENTIAL_BUY_ASK="$ASK"
              POTENTIAL_BUY_LAST="$LAST"
              # create target file
              POTENTIAL_TARGET_FOUND="$POTENTIAL_BUY_SYMBOL | Bid: $POTENTIAL_BUY_BID | Ask: $POTENTIAL_BUY_ASK | Last: $POTENTIAL_BUY_LAST | Dip: $DIP% | Spread: $SPREAD% | Price Movement: $PRICE_MOVEMENT% | Volume: $VOLUME_PERCENTAGE"
              echo "$POTENTIAL_TARGET_FOUND" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target
            fi
          fi
        fi
      fi
    fi
  done <"$DIP_PRICES_FILE" 2>/dev/null

  ##############################################################################

  # target data
  TARGET_ACTIVE="TARGET"
  target_data

  # target found
  if [[ -n "$POTENTIAL_BUY_SYMBOL" ]] &>/dev/null; then

    # update target
    if [[ "$(egrep -c "[0-9]+" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target)" -gt "0" ]] &>/dev/null; then

      # order status
      if [[ "$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/orders | grep -c "$LISTING_CURRENCY")" -gt "0" ]] &>/dev/null; then
        # keep old amount (listing)
        DIP_BUY_AMOUNT_LISTING="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active | awk '{ print $26 }' | awk '{ printf "%.9f\n", $1 }')"
      fi

      # if active order already exist
      if [[ "$(grep -c "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active)" -gt "0" ]] &>/dev/null; then
        # remove old (active) order
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
      fi
      # create active file and add amount to buy at end
      echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target 2>/dev/null) | Amount: $DIP_BUY_AMOUNT_LISTING $LISTING_CURRENCY" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null
    fi

    # remove active duplicates (markets), empty lines, lines less than n
    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | awk '!a[$1]++' | sed '/^$/d' | sed -r '/^.{,100}$/d')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active

    # market count
    POTENTIAL_MARKET_COUNT="$(wc -l "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market | awk '{ print $1 }')"
    # total market spread
    POTENTIAL_MARKET_TOTAL_SPREAD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".market 2>/dev/null | awk '{ print $13 }' | awk '{ SUM += $1} END { print SUM }')"
    # average market spread
    POTENTIAL_MARKET_AVERAGE_SPREAD="$(echo "$POTENTIAL_MARKET_TOTAL_SPREAD/$POTENTIAL_MARKET_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    # update log date
    LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"
    # log target output
    DIP_MARKET_FOUND_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: Found: $POTENTIAL_MARKET_COUNT Market: $REFERENCE_CURRENCY Spread: ${POTENTIAL_MARKET_AVERAGE_SPREAD:?}%"
    echo "$DIP_MARKET_FOUND_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

    # target count greater than n
    if [[ "$DIP_TARGET_COUNT" -gt "0" ]] &>/dev/null; then
      # update log date
      LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"
      # log target output
      DIP_TARGET_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: Target: $LISTING_CURRENCY/$REFERENCE_CURRENCY Spread: ${DIP_TARGET_SPREAD:?} Profit: ${DIP_GET_PERCENTAGE_PROFIT:?}%"
      echo "$DIP_TARGET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi

    # balance check (without decimal)
    REFERENCE_BALANCE_CHECK="$(echo "$REFERENCE_BALANCE" | tr -d '.' | sed 's/^0*//')"

    # no buying power (no balance)
    if [[ "$REFERENCE_BALANCE_CHECK" -eq "0" ]] &>/dev/null; then
      # update log date
      LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"
      # log target output
      DIP_MARKET_FOUND_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: $REFERENCE_CURRENCY Has no balance!"
      echo "$DIP_MARKET_FOUND_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

      # remove active order
      if [[ ! -z "$REFERENCE_CURRENCY" && ! -z "$LISTING_CURRENCY" ]] &>/dev/null; then
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
      fi

      # log target output
      DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: Removing $LISTING_CURRENCY/$REFERENCE_CURRENCY order from pool."
      echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
      # reset sold file
      truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold &>/dev/null
    fi

    # order status
    if [[ "$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/orders | grep -c "$LISTING_CURRENCY")" -gt "0" ]] &>/dev/null; then

      # dip bought age
      DIP_BOUGHT_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".bought 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
      if [[ -z "$DIP_BOUGHT_FILE_AGE_SECONDS" ]] &>/dev/null; then
        DIP_BOUGHT_FILE_AGE_SECONDS="0"
      fi
      DIP_BOUGHT_FILE_AGE=$(printf '%dh:%dm:%ds\n' $(("$DIP_BOUGHT_FILE_AGE_SECONDS/3600")) $(("$DIP_BOUGHT_FILE_AGE_SECONDS%3600/60")) $(("$DIP_BOUGHT_FILE_AGE_SECONDS%60")))
      DIP_BOUGHT_FILE_AGE_DAYS="$(echo "$DIP_BOUGHT_FILE_AGE_SECONDS/86400" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

      # update log date
      LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"
      # log target output
      DIP_MARKET_FOUND_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: $LISTING_CURRENCY/$REFERENCE_CURRENCY Active: $DIP_BOUGHT_FILE_AGE $DIP_BOUGHT_FILE_AGE_DAYS days"
      echo "$DIP_MARKET_FOUND_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi
  fi

  ##############################################################################
  # setup buy order (limit)
  ##############################################################################

  # if any orders with reference, listing currency does not exist
  if [[ "$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/orders | grep -c "$LISTING_CURRENCY")" -eq "0" ]] &>/dev/null; then

    # max active orders, set by configuration
    if [[ "$DIP_ACTIVE_FILE_COUNT" -lt "$DIP_MAX_ORDERS" ]] &>/dev/null; then
      # has buying power (balance)
      if [[ "$(echo "$REFERENCE_BALANCE" | tr -d '.' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then

        # update log date
        LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

        # reset sold file
        truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold &>/dev/null

        # setup limit buy order ################################################
        placeOrder_limit "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$DIP_TARGET_BID" "$DIP_BUY_AMOUNT_REFERENCE" "true" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid
        ########################################################################

        # track amount being bought
        echo "Buying $DIP_BUY_AMOUNT_LISTING $LISTING_CURRENCY for ($DIP_BUY_AMOUNT_REFERENCE $REFERENCE_CURRENCY) @ $(echo "$DIP_TARGET_BID" | awk '{ printf "%.9f\n", $1 }') Price -> Quest: Selling @ $(echo "$DIP_TARGET_ASK" | awk '{ printf "%.9f\n", $1 }') Price for ($DIP_GET_AMOUNT_REFERENCE $REFERENCE_CURRENCY) Earning: $DIP_GET_AMOUNT_PROFIT $REFERENCE_CURRENCY ${DIP_GET_PERCENTAGE_PROFIT:?}%" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".bought
        # keep n lines
        echo "$(tail -10 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".bought)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".bought

        DIP_TARGET_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

        if [[ -z "$DIP_TARGET_FILE_AGE_SECONDS" ]] &>/dev/null; then
          DIP_TARGET_FILE_AGE_SECONDS="0"
        fi

        DIP_TARGET_FILE_AGE=$(printf '%dh:%dm:%ds\n' $(("$DIP_TARGET_FILE_AGE_SECONDS/3600")) $(("$DIP_TARGET_FILE_AGE_SECONDS%3600/60")) $(("$DIP_TARGET_FILE_AGE_SECONDS%60")))

        # buy output (trade history)
        DIP_LIMIT_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : buy :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $LISTING_BALANCE $REFERENCE_BALANCE ${DIP_GET_PERCENTAGE_PROFIT:?}% $DIP_TARGET_FILE_AGE"
        echo "$DIP_LIMIT_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

        # buy output (log)
        DIP_BUY_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : PlaceOrder :: Buying $DIP_BUY_AMOUNT_LISTING $LISTING_CURRENCY for $DIP_BUY_AMOUNT_REFERENCE $REFERENCE_CURRENCY"
        echo "$DIP_BUY_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

        # earning output (log)
        DIP_BUY_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: Profit: $DIP_GET_AMOUNT_PROFIT $REFERENCE_CURRENCY -> ${DIP_GET_PERCENTAGE_PROFIT:?}%"
        echo "$DIP_BUY_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
      fi
    else
      # max orders output
      DIP_MAX_ORDERS_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : MaxOrders :: Reached max open orders! ($DIP_ACTIVE_FILE_COUNT/$DIP_MAX_ORDERS)"
      echo "$DIP_MAX_ORDERS_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi
  fi
fi

################################################################################

# reset target file
if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target 2>/dev/null | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then
  truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".target &>/dev/null
fi

################################################################################
# setup sell order (limit)
################################################################################

# target data
TARGET_ACTIVE="ACTIVE"
target_data

# has active file any orders
if [[ "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | sed '/^$/d' | wc -l)" -gt "0" ]] &>/dev/null; then

  # create strategy directory
  if [[ ! -d "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY" ]] &>/dev/null; then
    mkdir "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY" &>/dev/null
  fi

  ##############################################################################

  # get total sum (confirmed sell)
  DIP_TOTAL_SOLD_SUM="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$DIP_TOTAL_SOLD_SUM" ]] &>/dev/null; then
    DIP_TOTAL_SOLD_SUM="0"
  fi

  # leftover sell amount
  DIP_LEFTOVER_SOLD="$(echo "$DIP_TARGET_AMOUNT-$DIP_TOTAL_SOLD_SUM" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  if [[ -z "$DIP_LEFTOVER_SOLD" ]] &>/dev/null; then
    DIP_LEFTOVER_SOLD="0"
  fi

  # leftover sell amount (without decimal)
  DIP_LEFTOVER_SOLD_CHECK="$(echo "$DIP_LEFTOVER_SOLD" | tr -d '.' | sed 's/^0*//')"
  # total sum (without decimal)
  DIP_TOTAL_SOLD_SUM_CHECK="$(echo "$DIP_TOTAL_SOLD_SUM" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"

  if [[ -z "$DIP_TOTAL_SOLD_SUM_CHECK" ]] &>/dev/null; then
    DIP_TOTAL_SOLD_SUM_CHECK="0"
  fi

  # listing balance (without decimal)
  DIP_LISTING_BALANCE_CHECK="$(echo "$LISTING_BALANCE" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"
  # target amount (without decimal)
  DIP_TARGET_BALANCE_CHECK="$(echo "$DIP_TARGET_AMOUNT" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"

  if [[ -z "$DIP_LISTING_BALANCE_CHECK" ]] &>/dev/null; then
    DIP_LISTING_BALANCE_CHECK="0"
  fi
  if [[ -z "$DIP_TARGET_BALANCE_CHECK" ]] &>/dev/null; then
    DIP_TARGET_BALANCE_CHECK="0"
  fi

  ##############################################################################

  # balance has selling power (available)
  if [[ "$DIP_LISTING_BALANCE_CHECK" -gt "0" ]] &>/dev/null; then
    # if total sum (sold) is less than target amount
    if [[ "$DIP_TOTAL_SOLD_SUM_CHECK" -lt "$DIP_TARGET_BALANCE_CHECK" ]] &>/dev/null; then

      ##########################################################################

      # if balance (available) are greater or equal to leftover
      if [[ "$DIP_LISTING_BALANCE_CHECK" -ge "$DIP_TARGET_BALANCE_CHECK" ]] &>/dev/null; then
        # sell target amount (available)
        LISTING_BALANCE="$DIP_TARGET_AMOUNT"
      fi

      ##########################################################################

      # if balance is less than leftover of target
      if [[ "$DIP_LISTING_BALANCE_CHECK" -lt "$DIP_LEFTOVER_SOLD_CHECK" ]] &>/dev/null; then
        # sell balance (available)
        LISTING_BALANCE="$LISTING_BALANCE"
        # if balance is greater than leftover of target
      else
        # sell leftover (available)
        LISTING_BALANCE="$DIP_LEFTOVER_SOLD"
      fi

      ##########################################################################

      # calculate percentage of order size
      DIP_LEFTOVER_SIZE=$(awk "BEGIN { result = 100 / $DIP_TARGET_AMOUNT * $LISTING_BALANCE; printf \"%.9f\", (result > 100 ? 100 : result) }")

      if (($(echo "$DIP_LEFTOVER_SIZE > 99.999999" | bc -l))) &>/dev/null; then
        DIP_LEFTOVER_SIZE="100"
      fi
      if [[ -z "$DIP_LEFTOVER_SIZE" ]] &>/dev/null; then
        DIP_LEFTOVER_SIZE="0"
      fi

      # re calculate get amount based on order size
      DIP_SELL_AMOUNT_REFERENCE="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_REFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
      DIP_SELL_AMOUNT_PROFIT="$(echo "$(echo "$DIP_LEFTOVER_SIZE/100" | bc -l 2>/dev/null)*$DIP_GET_AMOUNT_PROFIT" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

      ##########################################################################

      # update log date
      LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

      # setup limit sell order #################################################
      placeOrder_limit "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$DIP_TARGET_ASK" "$LISTING_BALANCE" "false" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid
      ##########################################################################

      # track amount being sold
      echo "$LISTING_BALANCE" | awk '{ printf "%.9f\n", $1 }' >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold

      # sell output (log)
      DIP_SELL_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : PlaceOrder :: Selling $LISTING_BALANCE $LISTING_CURRENCY for $DIP_SELL_AMOUNT_REFERENCE $REFERENCE_CURRENCY"
      echo "$DIP_SELL_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

      # size output (log)
      DIP_SELL_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : SizeOrder :: ${DIP_LEFTOVER_SIZE:?}% of the order."
      echo "$DIP_SELL_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

      # earning output (log)
      DIP_BUY_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Potential :: Profit: $DIP_SELL_AMOUNT_PROFIT $REFERENCE_CURRENCY -> ${DIP_GET_PERCENTAGE_PROFIT:?}%"
      echo "$DIP_BUY_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi
  fi
fi

################################################################################

# if no specific orders exists
if [[ "$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null | grep -c "$LISTING_CURRENCY")" -eq "0" ]] &>/dev/null; then

  # get total sum (confirmed sell)
  DIP_TOTAL_SOLD_SUM="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold 2>/dev/null | awk '{ SUM += $1} END { print SUM }' | awk '{ printf "%.9f\n", $1 }')"
  DIP_TOTAL_SOLD_SUM="$(echo "$DIP_TOTAL_SOLD_SUM" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"

  if [[ -z "$DIP_TOTAL_SOLD_SUM" ]] &>/dev/null; then
    DIP_TOTAL_SOLD_SUM="0"
  fi

  # target amount
  DIP_TARGET_BALANCE_CHECK="$(echo "$DIP_TARGET_AMOUNT" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"

  # if total sum greater or equal than target
  if [[ "$DIP_TOTAL_SOLD_SUM_CHECK" -ge "$DIP_TARGET_BALANCE_CHECK" ]] &>/dev/null; then
    # update log date
    LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

    # dip bought age
    DIP_BOUGHT_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"${LISTING_CURRENCY:?}"_"${REFERENCE_CURRENCY:?}".bought 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
    if [[ -z "$DIP_BOUGHT_FILE_AGE_SECONDS" ]] &>/dev/null; then
      DIP_BOUGHT_FILE_AGE_SECONDS="0"
    fi
    DIP_BOUGHT_FILE_AGE=$(printf '%dh:%dm:%ds\n' $(("$DIP_BOUGHT_FILE_AGE_SECONDS/3600")) $(("$DIP_BOUGHT_FILE_AGE_SECONDS%3600/60")) $(("$DIP_BOUGHT_FILE_AGE_SECONDS%60")))
    DIP_BOUGHT_FILE_AGE_DAYS="$(echo "$DIP_BOUGHT_FILE_AGE_SECONDS/86400" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

    # remove old (sold) order
    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active

    # cleanup output (log)
    DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Fulfilled :: Removing $LISTING_CURRENCY/$REFERENCE_CURRENCY order from pool. (sold)"
    echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

    # profit output (log)
    DIP_PROFIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : Fulfilled :: Profit: $DIP_GET_AMOUNT_PROFIT $REFERENCE_CURRENCY -> ${DIP_GET_PERCENTAGE_PROFIT:?}% after $DIP_BOUGHT_FILE_AGE $DIP_BOUGHT_FILE_AGE_DAYS days"
    echo "$DIP_PROFIT_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

    # sell output (trade history)
    DIP_LIMIT_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : sell :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $LISTING_BALANCE $REFERENCE_BALANCE ${DIP_GET_PERCENTAGE_PROFIT:?}% $DIP_BOUGHT_FILE_AGE"
    echo "$DIP_LIMIT_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
    # reset sold file
    truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold &>/dev/null
  fi
fi

################################################################################

# if active exist, but no orders
if [[ -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold ]] &>/dev/null; then
  # file age (seconds)
  DIP_SOLD_FILE_AGE_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  if [[ -z "$DIP_SOLD_FILE_AGE_SECONDS" ]] &>/dev/null; then
    DIP_SOLD_FILE_AGE_SECONDS="0"
  fi
  # if sold age (seconds) are greater than n
  if [[ "$DIP_SOLD_FILE_AGE_SECONDS" -gt "3600" ]] &>/dev/null; then
    # if specific market exist in active file
    if [[ "$(grep "$REFERENCE_CURRENCY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -c "$LISTING_CURRENCY")" -eq "1" ]] &>/dev/null; then
      # if specific market dont exist in orders file
      if [[ "$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/orders 2>/dev/null | grep "$LISTING_CURRENCY" | egrep -c "sell|buy")" -eq "0" ]] &>/dev/null; then
        # remove old order from active pool
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active 2>/dev/null | grep -v "$LISTING_CURRENCY/$REFERENCE_CURRENCY")" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".active
        DIP_CLEANUP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : LeftOvers :: Removing $LISTING_CURRENCY/$REFERENCE_CURRENCY order from pool. (old)"
        echo "$DIP_CLEANUP_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
        # reset sold file
        truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".sold &>/dev/null
      fi
    fi
  fi
fi

################################################################################
# open positions
################################################################################

DIP_OUTPUT_FILE="${SYS_DIR:?}/robot/pool"

# read the active list from the file
DIP_ACTIVE_LIST=$(cat "${SYS_DIR:?}/robot/${BASENAME_STRATEGY}.active" 2>/dev/null)

# function to extract values from the active list
extract_values() {
  CURRENCY=$1
  FIELD=$2
  VALUE=$(grep "$CURRENCY" <<<"$DIP_ACTIVE_LIST" | awk -F "| $FIELD: " '{print $2}' | awk '{print $1}')
  echo "$VALUE"
}

# function to calculate the age of the sold file
calculate_sold_file_age() {
  CURRENCY=$1
  FILE_PATH_BOUGHT="${SYS_DIR:?}/robot/$BASENAME_STRATEGY/${CURRENCY//\//_}.bought"
  FILE_PATH_SOLD="${SYS_DIR:?}/robot/$BASENAME_STRATEGY/${CURRENCY//\//_}.sold"
  if [[ -f "$FILE_PATH_BOUGHT" ]] &>/dev/null; then
    FILE_PATH="${SYS_DIR:?}/robot/$BASENAME_STRATEGY/${CURRENCY//\//_}.bought"
  fi
  if [[ -f "$FILE_PATH_SOLD" ]] &>/dev/null; then
    FILE_PATH="${SYS_DIR:?}/robot/$BASENAME_STRATEGY/${CURRENCY//\//_}.sold"
  fi
  if [[ -f "$FILE_PATH" ]] &>/dev/null; then
    LAST_EDIT=$(stat -c '%Y' "$FILE_PATH")
    AGE_SECONDS=$(($(date +%s) - $LAST_EDIT))
    if [[ -z "$AGE_SECONDS" ]] &>/dev/null; then
      AGE_SECONDS="0"
    fi
    printf '%dh:%dm:%ds\n' $((AGE_SECONDS / 3600)) $((AGE_SECONDS % 3600 / 60)) $((AGE_SECONDS % 60))
  else
    echo "N/A"
  fi
}

# values for each currency
while IFS= read -r line; do
  # currency
  CURRENCY=$(echo "$line" | awk -F ": " '{print $1}')
  # amount to buy (listing)
  AMOUNT=$(extract_values "$CURRENCY" "Amount")
  # order bid (reference)
  COST_BID=$(extract_values "$CURRENCY" "Bid")
  # order ask (reference)
  COST_ASK=$(extract_values "$CURRENCY" "Ask")
  # amount for buy (reference)
  COST_BUY=$(echo "$AMOUNT*$COST_BID" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')
  # amount to get (reference)
  RESULT_GET="$(echo "$AMOUNT*$COST_ASK" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to profit (reference)
  RESULT_DIFF="$(echo "$RESULT_GET-$COST_BUY" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"
  # amount to profit (reference percentage)
  RESULT_PROFIT="$(echo "100/$RESULT_GET*$RESULT_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
  # order age
  AGE=$(calculate_sold_file_age "$CURRENCY")

  # result output (positions)
  echo "$STRATEGY_TYPE $CURRENCY $AMOUNT $COST_BUY ${RESULT_PROFIT:?}% $AGE" >>"$DIP_OUTPUT_FILE"
done < <(grep -oE '^[^:]*' <<<"$DIP_ACTIVE_LIST")

# format output
column -t <"$DIP_OUTPUT_FILE" >"${DIP_OUTPUT_FILE}.tmp"
mv "${DIP_OUTPUT_FILE}.tmp" "$DIP_OUTPUT_FILE"

################################################################################

save_orders
last_orders
sxc_backup_orders

################################################################################

robot_Log_cleanup

################################################################################

# END
