#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# dusting strategy configuration (dynamic)
################################################################################

# XGX xeggex template
# NKY nonkyc template

################################################################################

EXCHANGE_API=""         # exchange api (template)
MARKET_LIMIT="market"   # market or limit order
REFERENCE_CURRENCY=""   # reference currency
LISTING_ALLOCATED="100" # account allocated (100%)
DST_PROFIT_LIMIT="10"   # dust trigger (execute when profit is reached)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
