#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# dusting strategy configuration (static)
################################################################################

STRATEGY_TYPE="DST"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# dust trigger (execute when profit is reached)
DST_PROFIT_LIMIT="$(egrep "DST_PROFIT_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################
# data
################################################################################

robot_log               # strategy log
listing_data            # get available listing data
reference_data          # get available reference data
listing_allocated       # total listing allocated
reference_allocated     # total reference allocated
listing_balance_check   # check for listing balance
reference_balance_check # check for reference balance
insufficient_funds      # check for available funds

################################################################################

open_positions

################################################################################

CST_CHANGE_ME="$LOG_DATE : $BASENAME_STRATEGY : No lines of code found!"

################################################################################

# CODE #

################################################################################

echo "$CST_CHANGE_ME" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

################################################################################

incoming_listing
incoming_reference

################################################################################

tx_id_data    # txid data
save_orders   # save orders
last_orders   # last orders
backup_orders # backup orders

################################################################################

robot_Log_cleanup

################################################################################

# END
