#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# dusting strategy configuration (dynamic)
################################################################################

# XGX xeggex template

################################################################################

EXCHANGE_API=""         # exchange api (template)
MARKET_LIMIT="market"   # market or limit order
REFERENCE_CURRENCY=""   # reference currency
LISTING_ALLOCATED="100" # account allocated (100%)
DST_PROFIT_LIMIT="10"   # dust trigger (execute when profit is reached)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
