#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# ema strategy configuration (dynamic)
################################################################################

# XGX xeggex template
# NKY nonkyc template

################################################################################

EXCHANGE_API=""          # exchange api (template)
MARKET_LIMIT="market"    # market or limit order
EMA_SHORT="10"           # EMA short (10)
EMA_LONG="20"            # EMA long (20)
EMA_FOMO="true"          # EMA Fear Of Missing Out (false)
ROGUE_PROFIT="0"         # RSI rogue profit (0)
ROGUE_AMOUNT="1"         # n % to be used (default 0.036918189 = 3.6918189)
ROGUE_BUYS="3"           # n trades after signal age (default 3)
SIGNAL_AGE="24"          # signal age (24h)
LISTING_CURRENCY=""      # listing currency
LISTING_ALLOCATED="90"   # account allocated (100%)
REFERENCE_CURRENCY=""    # reference currency
REFERENCE_ALLOCATED="90" # account allocated (100%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
