#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# indicators
source /usr/local/bin/include/leeloo/indicators/ema
source /usr/local/bin/include/leeloo/indicators/rsi_xgx
source /usr/local/bin/include/leeloo/indicators/rsi_nky

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# ema strategy configuration (static)
################################################################################

STRATEGY_TYPE="EMA"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# ema short
EMA_SHORT="$(egrep "EMA_SHORT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# ema long
EMA_LONG="$(egrep "EMA_LONG=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# ema fomo
EMA_FOMO="$(egrep "EMA_FOMO=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# rogue profit enable, disable
ROGUE_PROFIT="$(egrep "ROGUE_PROFIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# n % to be used (default: 0.036918189 = 3.6918189)
ROGUE_AMOUNT="$(egrep "ROGUE_AMOUNT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# n trades after signal age (default: 3)
ROGUE_BUYS="$(egrep "ROGUE_BUYS=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# signal age
SIGNAL_AGE="$(egrep "SIGNAL_AGE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################
# data
################################################################################

robot_log               # strategy log
signal_age              # signal age
tx_id_data              # txid data
trades_data             # trades data
listing_data            # get available listing data
reference_data          # get available reference data
listing_allocated       # total listing allocated
reference_allocated     # total reference allocated
listing_balance_check   # check for listing balance
reference_balance_check # check for reference balance
insufficient_funds      # check for available funds
listing_fomo            # listing fomo
reference_fomo          # reference fomo
decimal_market          # decimal market

################################################################################

function cancel_old_orders {
  # if any data
  if [[ -n "$LISTING_CURRENCY" && -n "$REFERENCE_CURRENCY" ]] &>/dev/null; then

    # if buy order
    if [[ "$TYPE" == "buy" ]] &>/dev/null; then
      # ema sell orders
      EMA_OLD_ORDERS="$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".orders 2>/dev/null | grep "sell" | awk -F: '{ print $1 }')"
    fi

    # if sell order
    if [[ "$TYPE" == "sell" ]] &>/dev/null; then
      # ema buy orders
      EMA_OLD_ORDERS="$(cat "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/"$LISTING_CURRENCY"_"$REFERENCE_CURRENCY".orders 2>/dev/null | grep "buy" | awk -F: '{ print $1 }')"
    fi

    # if any data
    if [[ -n "$EMA_OLD_ORDERS" ]] &>/dev/null; then
      # cancel old orders
      echo "$EMA_OLD_ORDERS" | while IFS= read -r ORDER_ID; do

        # if xeggex cancelorder
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # cancel ghost order
          cancelOrder "$ORDER_ID" 2>>"${LOG_ERROR:?}"
        fi

        # if nonkyc cancelorder
        if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
          # cancel ghost order
          cancelOrder_nky "$ORDER_ID" 2>>"${LOG_ERROR:?}"
        fi
      done
    fi
  fi
}

################################################################################

# if txid age greater than signal limit in hours (based on configuration)
if [[ "$(echo "$TX_ID_AGE_HOURS" | awk -F. '{ print $1 }')" -gt "$SIGNAL_AGE" ]] 2>>"${LOG_ERROR:?}"; then
  # reset status file
  truncate -s 0 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status &>/dev/null
fi

################################################################################

# get ema data
GET_EMA_DATA="$(get_ema "$EMA_SHORT" "$EMA_LONG" "$LISTING_CURRENCY")"
# create temp
echo "$GET_EMA_DATA" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ema.tmp
# get ema check
GET_EMA_CHECK="$(echo "$GET_EMA_DATA" | awk '{ print $3 }' | egrep -c "[0-9]+" || true)"

# if any data
if [[ "$GET_EMA_CHECK" -eq "1" ]] &>/dev/null; then
  # update ema
  mv "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ema.tmp "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ema
fi

# ema data
GET_EMA_DATA="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".ema 2>/dev/null)"

GET_EMA_SIGNAL="$(echo "$GET_EMA_DATA" | awk '{ print $1 }')"
GET_EMA_CONFIG="$(echo "$GET_EMA_DATA" | awk '{ print $NF }')"
GET_SHORT_DATA="$(echo "$GET_EMA_DATA" | awk '{ print $3 }')"
GET_LONG_DATA="$(echo "$GET_EMA_DATA" | awk '{ print $5 }')"
GET_DIFFERENCE="$(echo "$GET_SHORT_DATA-$GET_LONG_DATA" | bc -l 2>/dev/null)"
GET_PERCENTAGE="$(echo "100/$GET_SHORT_DATA*$GET_DIFFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"

# if zero
if [[ -z "$GET_PERCENTAGE" ]] &>/dev/null; then
  GET_PERCENTAGE="0"
fi

# if zero
if [[ -z "$TX_ID_LAST" ]] &>/dev/null; then
  TX_ID_LAST="N/A"
fi

################################################################################

# fomo data
if [[ "$EMA_FOMO" == "true" ]] &>/dev/null; then
  EMA_FOMO_DATA="Enabled"
else
  EMA_FOMO_DATA="Disabled"
fi

# if zero
if [[ -z "$LISTING_ALLOCATED_REAL_CHECK" ]] &>/dev/null; then
  LISTING_ALLOCATED_REAL_CHECK="N/A"
fi

# if zero
if [[ -z "$REFERENCE_ALLOCATED_REAL_CHECK" ]] &>/dev/null; then
  REFERENCE_ALLOCATED_REAL_CHECK="N/A"
fi

# if market
if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
  MARKET_LIMIT_DATA="Market"
fi

# if limit
if [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
  MARKET_LIMIT_DATA="Limit"
fi

# listing available balance (market decimal)
LISTING_AVAILABLE_BALANCE="$(echo "$LISTING_AVAILABLE_BALANCE" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
LISTING_UNCONFIRMED_BALANCE="$(echo "$LISTING_UNCONFIRMED_BALANCE" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
LISTING_AMOUNT="$(echo "$LISTING_AMOUNT" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"

REFERENCE_AMOUNT_FOMO="$(echo "$REFERENCE_AMOUNT_FOMO" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
LISTING_AMOUNT_FOMO="$(echo "$LISTING_AMOUNT_FOMO" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"

################################################################################

echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY
Order_Type............: $MARKET_LIMIT_DATA
Exchange..............: $EXCHANGE_OUTPUT_NAME $EXCHANGE_API
EMA_Data..............: $STRATEGY_TYPE $GET_EMA_CONFIG
EMA_Short.............: $GET_SHORT_DATA
EMA_Long..............: $GET_LONG_DATA
EMA_Signal............: $GET_EMA_SIGNAL
EMA_Cross_Age.........: ${SIGNAL_ORDER_AGE_HOURS:?}h - ${SIGNAL_ORDER_AGE_DAYS:?}d
EMA_Age_Limit.........: ${SIGNAL_AGE:?}h
EMA_Strength..........: ${GET_PERCENTAGE:?}%
EMA_FOMO..............: $EMA_FOMO_DATA
Listing_Value.........: $TOTAL_EMA_VALUE $REFERENCE_CURRENCY
Reference_Value.......: $TOTAL_EMA_AMOUNT $LISTING_CURRENCY
Price.................: $LISTING_PRICE $LISTING_CURRENCY
Average_Buy_Price.....: $AVERAGE_BUY_PRICE $REFERENCE_CURRENCY
Average_Sell_Price....: $AVERAGE_SELL_PRICE $REFERENCE_CURRENCY
Average_Buy_Amount....: $AVERAGE_BUY_AMOUNT $LISTING_CURRENCY
Average_Sell_Amount...: $AVERAGE_SELL_AMOUNT $LISTING_CURRENCY ${BOUGHT_SOLD_FULLFIMENT:?}%
Average_Profit_Loss...: ${LOSS_PROFIT_PERCENTAGE:?}%
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL_CHECK:?}%/${LISTING_ALLOCATED:?}% Diff: $REFERENCE_AMOUNT_FOMO $LISTING_CURRENCY ${LISTING_ALL_DIFF_CHECK:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY ($LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY)
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY ($LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY)
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY ($LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY)
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL_CHECK:?}%/${REFERENCE_ALLOCATED:?}% Diff: $LISTING_AMOUNT_FOMO $LISTING_CURRENCY ${REFERENCE_ALL_DIFF_CHECK:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY ($REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY)
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY ($REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY)
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY ($REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY)
Last_Order.txid.......: $TX_ID_LAST $TX_ID_AGE (${TX_ID_AGE_DAYS:?}d)" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>>"${LOG_ERROR:?}"

################################################################################

open_positions

################################################################################

BUY_LIMIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $REFERENCE_CURRENCY Limit $REFERENCE_PRICE $REFERENCE_AMOUNT"
SELL_LIMIT_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"

ORDER_SELL_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : sell :: $LISTING_OPEN_CURRENCY :: $REFERENCE_AVAILABLE_BALANCE $LISTING_AVAILABLE_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
ORDER_BUY_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : buy :: $LISTING_OPEN_CURRENCY :: $REFERENCE_AVAILABLE_BALANCE $LISTING_AVAILABLE_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"

################################################################################

incoming_listing
incoming_reference

################################################################################
# rogue profit using rsi
################################################################################

ROGUE_TIMER_NOW="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
ROGUE_STATUS_NOW="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

################################################################################
################################################################################

ROGUE_TIMER="3600"                                                                             # n seconds (default: 3600 seconds/1 hour cooldown)
ROGUE_HOURS="6"                                                                                # n hours of data (default: 6 hours)
ROGUE_AMOUNT="$(echo "$ROGUE_AMOUNT/100" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')" # n amount calculated in percentage

################################################################################
################################################################################

# if bullish signal
if [[ "$GET_EMA_SIGNAL" == "Bullish" ]] &>/dev/null; then
  # n% listing amount
  ROGUE_LISTING_AMOUNT="$(echo "$ROGUE_AMOUNT*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }' | head -1)"
fi

# if bearish signal
if [[ "$GET_EMA_SIGNAL" == "Bearish" ]] &>/dev/null; then
  # n% listing amount
  ROGUE_LISTING_AMOUNT="$(echo "$ROGUE_AMOUNT*$REFERENCE_AVAILABLE_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }' | head -1)"
fi

# minimum amount
EMA_MINIMUM_AMOUNT="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".null 2>/dev/null | grep "Minimum" | awk '{ print $NF }')"
# if rogue listing amount is less than minimum
if [[ "$EMA_MINIMUM_AMOUNT" > "$ROGUE_LISTING_AMOUNT" ]] &>/dev/null; then
  # use minimum
  ROGUE_LISTING_AMOUNT="$EMA_MINIMUM_AMOUNT"
fi

################################################################################

# missing
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
  touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue &>/dev/null
fi

################################################################################

# get_rsi n
function rsi_data() {

  # if xeggex rsi
  if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
    echo "L $LISTING_CURRENCY $(get_rsi_xgx "$LISTING_CURRENCY" "USDT")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
    sleep 1
    echo "R $REFERENCE_CURRENCY $(get_rsi_xgx "$REFERENCE_CURRENCY" "USDT")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
  fi

  # if nonkyc rsi
  if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
    echo "L $LISTING_CURRENCY $(get_rsi_nky "$LISTING_CURRENCY" "USDT")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
    sleep 1
    echo "R $REFERENCE_CURRENCY $(get_rsi_nky "$REFERENCE_CURRENCY" "USDT")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
  fi

}

################################################################################

function rogue_stealth() {
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth ]] &>/dev/null; then
    echo "Lurking in the Shadows.." >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null
    sleep 1
  fi

  STEALTH_TIME_SECONDS="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"
  STEALTH_TIME=$(printf '%dh:%dm:%ds\n' $(("$STEALTH_TIME_SECONDS/3600")) $(("$STEALTH_TIME_SECONDS%3600/60")) $(("$STEALTH_TIME_SECONDS%60")))
  STEALTH_TIME_H="$(("$STEALTH_TIME_SECONDS/3600"))"
  STEALTH_TIME_D="$(("$STEALTH_TIME_H/24"))"
  echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Stealth mode ${STEALTH_TIME_D:?}d (${STEALTH_TIME:?})" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
}

################################################################################
################################################################################

function rogue_buying() {

  # default
  MINIMUM_AMOUNT_REACHED="0"
  # amount check with decimal_market
  AMOUNT_DECIMAL_CHECK="$(echo "$ROGUE_LISTING_AMOUNT" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }' | tr -d '.' | sed 's/^0*//')"
  # if zero
  if [[ -z "$AMOUNT_DECIMAL_CHECK" ]] &>/dev/null; then
    # output minimum reached
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Minimum buy amount reached! $ROGUE_LISTING_AMOUNT $REFERENCE_CURRENCY @ $REFERENCE_PRICE $LISTING_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    # minimum amount reached, do not buy
    MINIMUM_AMOUNT_REACHED="1"
  fi

  ##############################################################################

  # if market order, if minimum amount not reached
  if [[ "$MARKET_LIMIT" == "market" && "$MINIMUM_AMOUNT_REACHED" == "0" ]] &>/dev/null; then

    ############################################################################
    ############################################################################

    # balance check
    if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
      # if insufficient funds from last order
      if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

        # buy output
        echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cheap Shot successfully! $ROGUE_LISTING_AMOUNT @ $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        ########################################################################

        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # createorder buy market #############################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "market" "$ROGUE_LISTING_AMOUNT" "" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY buy market $ROGUE_LISTING_AMOUNT '' false <--- Buying asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi

        # if nonkyc order
        if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
          # createorder buy market #############################################
          PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "market" "$ROGUE_LISTING_AMOUNT" "" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY buy market $ROGUE_LISTING_AMOUNT '' false <--- Buying asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi
      fi
    fi
    # if limit order, if minimum amount not reached
  elif [[ "$MARKET_LIMIT" == "limit" && "$MINIMUM_AMOUNT_REACHED" == "0" ]] &>/dev/null; then

    ############################################################################
    ############################################################################

    # balance check
    if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
      # if insufficient funds from last order
      if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # createorder buy limit ##############################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "limit" "$ROGUE_LISTING_AMOUNT" "$LISTING_PRICE" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY buy limit $ROGUE_LISTING_AMOUNT $LISTING_PRICE false <--- Buying asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi

        # if nonkyc order
        if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
          # createorder buy limit ##############################################
          PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "limit" "$ROGUE_LISTING_AMOUNT" "$LISTING_PRICE" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY buy limit $ROGUE_LISTING_AMOUNT $LISTING_PRICE false <--- Buying asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi
      fi
    fi
  fi
}

################################################################################

function rogue_selling() {

  # default
  MINIMUM_AMOUNT_REACHED="0"
  # amount check with decimal_market
  AMOUNT_DECIMAL_CHECK="$(echo "$ROGUE_LISTING_AMOUNT" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }' | tr -d '.' | sed 's/^0*//')"
  # if zero
  if [[ -z "$AMOUNT_DECIMAL_CHECK" ]] &>/dev/null; then
    # output minimum reached
    echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Minimum sell amount reached! $ROGUE_LISTING_AMOUNT $REFERENCE_CURRENCY @ $REFERENCE_PRICE $LISTING_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    # minimum amount reached, do not sell
    MINIMUM_AMOUNT_REACHED="1"
  fi

  ##############################################################################

  # if market order, if minimum amount not reached
  if [[ "$MARKET_LIMIT" == "market" && "$MINIMUM_AMOUNT_REACHED" == "0" ]] &>/dev/null; then

    ############################################################################
    ############################################################################

    # balance check
    if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
      # if insufficient funds from last order
      if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

        # sell output
        echo "$LOG_DATE : $EXCHANGE_API : RGP : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Pick Pocket successfully! $ROGUE_LISTING_AMOUNT @ $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        ########################################################################

        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # CreateOrder market #################################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "market" "$ROGUE_LISTING_AMOUNT" "" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell market $ROGUE_LISTING_AMOUNT '' false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi

        # if nonkyc order
        if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
          # CreateOrder market #################################################
          PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "market" "$ROGUE_LISTING_AMOUNT" "" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell market $ROGUE_LISTING_AMOUNT '' false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi
      fi
    fi
    # if limit order, if minimum amount not reached
  elif [[ "$MARKET_LIMIT" == "limit" && "$MINIMUM_AMOUNT_REACHED" == "0" ]] &>/dev/null; then

    ############################################################################
    ############################################################################

    # balance check
    if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
      # if insufficient funds from last order
      if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # createorder sell limit #############################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "limit" "$ROGUE_LISTING_AMOUNT" "$LISTING_PRICE" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell limit $ROGUE_LISTING_AMOUNT $LISTING_PRICE false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi

        # if nonkyc order
        if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
          # createorder sell limit #############################################
          PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "limit" "$ROGUE_LISTING_AMOUNT" "$LISTING_PRICE" "false")"
          # debug line #########################################################
          echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY sell limit $ROGUE_LISTING_AMOUNT $LISTING_PRICE false <--- Selling asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
          ######################################################################
        fi
      fi
    fi
  fi
}

################################################################################

function rogue_clean_lines() {
  # keep n lines
  echo "$(tail -"$(echo "$ROGUE_HOURS*2" | bc -l 2>/dev/null)" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null
}

################################################################################

if [[ "$ROGUE_PROFIT" -eq "1" ]] &>/dev/null; then

  # update data every n/100 seconds
  if [[ "$ROGUE_TIMER_NOW" -gt "$(echo "$ROGUE_TIMER/100" | bc 2>/dev/null)" ]] &>/dev/null; then
    rsi_data
  fi

  # update data every n seconds
  if [[ "$ROGUE_TIMER_NOW" -gt "$ROGUE_TIMER" ]] &>/dev/null; then
    rogue_stealth
    rogue_clean_lines
    # update data if missing
  elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
    rsi_data
    rogue_stealth
    rogue_clean_lines
    # update data if empty
  elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
    rsi_data
    rogue_stealth
    rogue_clean_lines
  fi

  ##############################################################################

  # line count
  ROGUE_LINES="$(wc -l "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $1 }')"
  ROGUE_COUNT="$(echo "$ROGUE_LINES/2" | bc 2>/dev/null)"
  ROGUE_DAYS="$(echo "$ROGUE_COUNT/24" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # backup prices
  backup_prices

  # rogue listing price
  ROGUE_LISTING_PRICE="$LISTING_PRICE"

  # rogue listing price old
  ROGUE_LISTING_PRICE_OLD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | awk '{ print $3 }' | tail -1)"

  # if zero
  if [[ -z "$ROGUE_LISTING_PRICE_OLD" ]] &>/dev/null; then
    ROGUE_LISTING_PRICE_OLD="0"
  fi

  ROGUE_LISTING_PRICE_DIFF="$(echo "100/$ROGUE_LISTING_PRICE_OLD*$ROGUE_LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_LISTING_PRICE_DIFF" ]] &>/dev/null; then
    ROGUE_LISTING_PRICE_DIFF="0"
  fi

  ROGUE_LISTING_NOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | grep -v "0.000000000" | awk '{ print $NF }' | tail -1 | awk '{ printf "%.4f\n", $1 }')"
  ROGUE_LISTING_HIGH="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | grep -v "0.000000000" | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.4f\n", $1 }')"
  ROGUE_LISTING_LOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | grep -v "0.000000000" | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.4f\n", $1 }')"

  # rsi can not be empty/zero, regardless

  # if zero
  if [[ -z "$ROGUE_LISTING_NOW" || "$(echo "$ROGUE_LISTING_NOW" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_LISTING_NOW="50.1111"
  fi

  # if zero
  if [[ -z "$ROGUE_LISTING_HIGH" || "$(echo "$ROGUE_LISTING_HIGH" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_LISTING_HIGH="50.1111"
  fi

  # if zero
  if [[ -z "$ROGUE_LISTING_LOW" || "$(echo "$ROGUE_LISTING_LOW" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_LISTING_LOW="50.1111"
  fi

  ROGUE_LISTING_DIFF="$(echo "$ROGUE_LISTING_HIGH-$ROGUE_LISTING_LOW" | bc -l 2>/dev/null | tr -d '-' | awk '{ printf "%.2f\n", $1 }')"
  ROGUE_LISTING_TOTAL="$(echo "$ROGUE_LISTING_NOW+$ROGUE_LISTING_HIGH+$ROGUE_LISTING_LOW" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  ROGUE_LISTING_AVERAGE="$(echo "$ROGUE_LISTING_TOTAL/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  ##############################################################################

  # set idle
  ROGUE_LISTING_RPI="50.1111"

  # overbought, greater than n
  if [[ "$(echo "$ROGUE_LISTING_NOW" | awk -F. '{ print $1 }')" -gt "50" ]] &>/dev/null; then
    # positive + half
    ROGUE_LISTING_RPI="$(echo "$ROGUE_LISTING_AVERAGE+$(echo "$ROGUE_LISTING_DIFF/3.69" | bc -l 2>/dev/null)" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  fi

  # oversold, less than n
  if [[ "$(echo "$ROGUE_LISTING_NOW" | awk -F. '{ print $1 }')" -lt "50" ]] &>/dev/null; then
    # negative - half
    ROGUE_LISTING_RPI="$(echo "$ROGUE_LISTING_AVERAGE-$(echo "$ROGUE_LISTING_DIFF/3.69" | bc -l 2>/dev/null)" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  fi

  ROGUE_LISTING_RPI="$(echo "$ROGUE_LISTING_RPI" | awk '{ printf "%.9f\n", $1 }')"

  # keep at idle if zero
  if [[ -z "$ROGUE_LISTING_RPI" ]] &>/dev/null; then
    ROGUE_LISTING_RPI="0"
  fi

  ##############################################################################

  ROGUE_LISTING_DIFF_PERCENTAGE="$(echo "100/$ROGUE_LISTING_AVERAGE*$ROGUE_LISTING_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_LISTING_DIFF_PERCENTAGE" ]] &>/dev/null; then
    ROGUE_LISTING_DIFF_PERCENTAGE="0"
  fi

  # reference
  ROGUE_REFERENCE_PRICE="$REFERENCE_PRICE"
  ROGUE_REFERENCE_PRICE_OLD="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | awk '{ print $5 }' | tail -1)"

  # if zero
  if [[ -z "$ROGUE_REFERENCE_PRICE_OLD" ]] &>/dev/null; then
    ROGUE_REFERENCE_PRICE_OLD="0"
  fi

  ROGUE_REFERENCE_PRICE_DIFF="$(echo "100/$ROGUE_REFERENCE_PRICE_OLD*$ROGUE_REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_REFERENCE_PRICE_DIFF" ]] &>/dev/null; then
    ROGUE_REFERENCE_PRICE_DIFF="0"
  fi

  ROGUE_REFERENCE_NOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | tail -1 | awk '{ printf "%.4f\n", $1 }')"
  ROGUE_REFERENCE_HIGH="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.4f\n", $1 }')"
  ROGUE_REFERENCE_LOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.4f\n", $1 }')"

  # rsi can not be empty/zero, regardless

  # if zero
  if [[ -z "$ROGUE_REFERENCE_NOW" || "$(echo "$ROGUE_REFERENCE_NOW" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_REFERENCE_NOW="50.1111"
  fi

  # if zero
  if [[ -z "$ROGUE_REFERENCE_HIGH" || "$(echo "$ROGUE_REFERENCE_HIGH" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_REFERENCE_HIGH="50.1111"
  fi

  # if zero
  if [[ -z "$ROGUE_REFERENCE_LOW" || "$(echo "$ROGUE_REFERENCE_LOW" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_REFERENCE_LOW="50.1111"
  fi

  ROGUE_REFERENCE_DIFF="$(echo "$ROGUE_REFERENCE_HIGH-$ROGUE_REFERENCE_LOW" | bc -l 2>/dev/null | tr -d '-' | awk '{ printf "%.2f\n", $1 }')"
  ROGUE_REFERENCE_TOTAL="$(echo "$ROGUE_REFERENCE_NOW+$ROGUE_REFERENCE_HIGH+$ROGUE_REFERENCE_LOW" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  ROGUE_REFERENCE_AVERAGE="$(echo "$ROGUE_REFERENCE_TOTAL/3" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  ##############################################################################

  # set idle
  ROGUE_REFERENCE_RPI="50.1111"

  # overbought, greater than n
  if [[ "$(echo "$ROGUE_REFERENCE_NOW" | awk -F. '{ print $1 }')" -gt "50" ]] &>/dev/null; then
    # positive
    ROGUE_REFERENCE_RPI="$(echo "$ROGUE_REFERENCE_AVERAGE+$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  fi

  ##############################################################################

  # oversold, greater than n
  if [[ "$(echo "$ROGUE_REFERENCE_NOW" | awk -F. '{ print $1 }')" -lt "50" ]] &>/dev/null; then
    # negative
    ROGUE_REFERENCE_RPI="$(echo "$ROGUE_REFERENCE_AVERAGE-$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.34f\n", $1 }')"
  fi

  ROGUE_REFERENCE_RPI="$(echo "$ROGUE_REFERENCE_RPI" | awk '{ printf "%.9f\n", $1 }')"

  # keep at idle if zero
  if [[ -z "$ROGUE_REFERENCE_RPI" ]] &>/dev/null; then
    ROGUE_REFERENCE_RPI="0"
  fi

  ##############################################################################

  ROGUE_REFERENCE_DIFF_PERCENTAGE="$(echo "100/$ROGUE_REFERENCE_AVERAGE*$ROGUE_REFERENCE_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_REFERENCE_DIFF_PERCENTAGE" ]] &>/dev/null; then
    ROGUE_REFERENCE_DIFF_PERCENTAGE="0"
  fi

  ##############################################################################

  ROGUE_SYNCED_PERCENTAGE="$(echo "100/$ROGUE_HOURS*$ROGUE_COUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_SYNCED_PERCENTAGE" ]] &>/dev/null; then
    ROGUE_SYNCED_PERCENTAGE="0"
  fi

  ##############################################################################

  ROGUE_UPDATE_PERCENTAGE="$(echo "100/$ROGUE_TIMER*$ROGUE_TIMER_NOW" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_UPDATE_PERCENTAGE" ]] &>/dev/null; then
    ROGUE_UPDATE_PERCENTAGE="0"
  fi

  ##############################################################################

  # call shot
  if [[ "$(echo "$ROGUE_SYNCED_PERCENTAGE" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    ROGUE_SYNCED_PERCENTAGE="100"
  fi

  ##############################################################################

  ROGUE_LISTING_RPI_NR="$(echo "$ROGUE_LISTING_RPI" | awk '{ printf "%.4f\n", $1 }')"
  ROGUE_REFERENCE_RPI_NR="$(echo "$ROGUE_REFERENCE_RPI" | awk '{ printf "%.4f\n", $1 }')"

  # if zero
  if [[ -z "$ROGUE_LISTING_RPI_NR" ]] &>/dev/null; then
    # if zero, keep it idling
    ROGUE_LISTING_RPI_NR="50.1111"
  fi

  # if zero
  if [[ -z "$ROGUE_REFERENCE_RPI_NR" ]] &>/dev/null; then
    # if zero, keep it idling
    ROGUE_REFERENCE_RPI_NR="50.1111"
  fi

  ##############################################################################

  # if zero, idle
  if [[ "$(echo "$ROGUE_LISTING_DIFF_PERCENTAGE" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_LISTING_RPI="IDLE"
  fi

  # if zero, idle
  if [[ "$(echo "$ROGUE_REFERENCE_DIFF_PERCENTAGE" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    ROGUE_REFERENCE_RPI="IDLE"
  fi

  ##############################################################################

  echo "Update    $ROGUE_TIMER_NOW/${ROGUE_TIMER:?}s ${ROGUE_UPDATE_PERCENTAGE:?}% (${ROGUE_SYNCED_PERCENTAGE:?}%)
Lines     $ROGUE_LINES/${ROGUE_COUNT:?}h/${ROGUE_DAYS:?}d
RSI       14

L_PRICE   $ROGUE_LISTING_PRICE Diff: ${ROGUE_LISTING_PRICE_DIFF:?}%
L_NOW     $ROGUE_LISTING_NOW
L_HIGHEST $ROGUE_LISTING_HIGH
L_LOWEST  $ROGUE_LISTING_LOW
L_AVERAGE $ROGUE_LISTING_AVERAGE
L_DIFF    $ROGUE_LISTING_DIFF ${ROGUE_LISTING_DIFF_PERCENTAGE:?}%
RPI       $ROGUE_LISTING_RPI ($ROGUE_LISTING_RPI_NR)

R_PRICE   $ROGUE_REFERENCE_PRICE Diff: ${ROGUE_REFERENCE_PRICE_DIFF:?}%
R_NOW     $ROGUE_REFERENCE_NOW
R_HIGHEST $ROGUE_REFERENCE_HIGH
R_LOWEST  $ROGUE_REFERENCE_LOW
R_AVERAGE $ROGUE_REFERENCE_AVERAGE
R_DIFF    $ROGUE_REFERENCE_DIFF ${ROGUE_REFERENCE_DIFF_PERCENTAGE:?}%
RPI       $ROGUE_REFERENCE_RPI ($ROGUE_REFERENCE_RPI_NR)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rsi 2>/dev/null

  ##############################################################################

  function rogue_shadow_output() {
    echo "Lurking in the Shadows.." >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".stealth 2>/dev/null
  }

  ##############################################################################

  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] &>/dev/null; then
    touch >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status &>/dev/null
  fi

  ##############################################################################

  TYPE="sell"

  MARKET_RGP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
  MARKET_RGP_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
  MARKET_RGP_STATUS_SOLD="SOLD @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)"

  # wait on call shot
  if [[ "$(echo "$ROGUE_SYNCED_PERCENTAGE" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then

    # rogue_selling config n% of allocated n%, if minimum amount not reached
    if [[ "$(echo "$ROGUE_LISTING_RPI_NR" | awk -F. '{ print $1 }')" -gt "70" ]] &>/dev/null; then
      # overbought, pick pocket at top!
      if [[ "$(tail -"$ROGUE_BUYS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "SOLD")" -lt "$ROGUE_BUYS" ]] &>/dev/null; then
        rogue_selling

        tx_id
        cost_price

        rogue_shadow_output
        echo "$MARKET_RGP_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$MARKET_RGP_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        echo "$MARKET_RGP_STATUS_SOLD" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
      fi
    fi

    ############################################################################

    TYPE="buy"

    MARKET_RGP_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Market $LISTING_AMOUNT"
    MARKET_RGP_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
    MARKET_RGP_STATUS_BOUGHT="BOUGHT @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)"

    # rogue_buying config n% of allocated n%, if minimum amount not reached
    if [[ "$(echo "$ROGUE_LISTING_RPI_NR" | awk -F. '{ print $1 }')" -lt "30" ]] &>/dev/null; then
      # oversold, cheap shot at bottom!
      if [[ "$(tail -"$ROGUE_BUYS" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "BOUGHT")" -lt "$ROGUE_BUYS" ]] &>/dev/null; then
        rogue_buying

        tx_id
        cost_price

        rogue_shadow_output
        echo "$MARKET_RGP_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$MARKET_RGP_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        echo "$MARKET_RGP_STATUS_BOUGHT" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
      fi
    fi
  fi

  ##############################################################################

  # reset status at midnight, greater than n
  if [[ "$(date '+%H:%M' | egrep "00:00" | wc -l)" -eq "1" || "$ROGUE_STATUS_NOW" -gt "86400" ]] &>/dev/null; then
    echo "IDLE @ $ROGUE_LISTING_PRICE / $ROGUE_REFERENCE_PRICE :: $(date | xargs)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
  fi
fi

################################################################################

# rogue profit indicator output
if [[ "$ROGUE_PROFIT" -eq "1" ]] 2>>"${LOG_ERROR:?}"; then
  ROGUE_PROFIT_INDICATOR="RPI $(echo "$ROGUE_LISTING_RPI" | awk '{ printf "%.0f\n", $1 }')/$(echo "$ROGUE_REFERENCE_RPI" | awk '{ printf "%.0f\n", $1 }')"
else
  ROGUE_PROFIT_INDICATOR=""
fi

################################################################################

# raw strategy.data
EMA_REAL_RAW="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>>"${LOG_ERROR:?}")"

# fetch ema values from strategy.data
EMA_REAL_SIGNAL="$(echo "$EMA_REAL_RAW" | grep -w "EMA_Signal" | awk '{ print $2 }')"
EMA_REAL_SHORT="$(echo "$EMA_REAL_RAW" | grep -w "EMA_Short" | awk '{ print $2 }')"
EMA_REAL_LONG="$(echo "$EMA_REAL_RAW" | grep -w "EMA_Long" | awk '{ print $2 }')"

# if any data
if [[ -n "$EMA_REAL_SHORT" && -n "$EMA_REAL_LONG" ]] 2>>"${LOG_ERROR:?}"; then
  # if not zero n
  if [[ ! "$EMA_REAL_SHORT" == "0.000000000" && ! "$EMA_REAL_LONG" == "0.000000000" ]] &>/dev/null; then
    # create signal line based on ema values
    echo "$EMA_REAL_SIGNAL :: $EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>>"${LOG_ERROR:?}"
  fi
fi

################################################################################

# if no data, only zeros, not sure n error
if [[ "$LISTING_PRICE" == "0.000000000" || -z "$LISTING_PRICE" ]] &>/dev/null; then
  # use last data point from logs
  LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null | egrep -o "[0-9]+.[0-9]+ Bullish|[0-9]+.[0-9]+ Bearish" | egrep "[0-9]+.[0-9]+" | grep -v "0.000000000" | awk '{ print $1 }' | awk '!a[$0]++' | tail -5 | sort -R | tail -1)"
fi

################################################################################

# keep n lines
echo "$(tail -21 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>>"${LOG_ERROR:?}"

# latest signal
EMA_REAL_SIGNAL="$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | awk '{ print $1 }')"

# if zero, skip
if [[ -z "$EMA_REAL_SIGNAL" ]] &>/dev/null; then
  EMA_REAL_SIGNAL="Idling"
fi

EMA_DIFFERENCE="$(echo "$EMA_REAL_SHORT-$EMA_REAL_LONG" | bc -l 2>/dev/null)"
EMA_PERCENTAGE="$(echo "100/$EMA_REAL_SHORT*$EMA_DIFFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"

# if zero
if [[ -z "$EMA_PERCENTAGE" ]] &>/dev/null; then
  EMA_PERCENTAGE="0"
fi

################################################################################
# B U L L I S H - S I G N A L
################################################################################

BULLISH_EMA_CROSS="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${REFERENCE_ALLOCATED:?}% : Bullish+Cross : Buy"
BULLISH_EMA_SIGNAL="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Trigger : Bullish+Signal : Buying $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_ALLOCATED_REAL_CHECK+$LISTING_ALL_DIFF_CHECK% > ${LISTING_ALLOCATED:?}%"
BULLISH_EMA_STATUS="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT / $EMA_REAL_LONG / ($LISTING_PRICE Bullish ${EMA_PERCENTAGE:?}%) ${ROGUE_PROFIT_INDICATOR:?}"

################################################################################

# if missing
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo ]] 2>/dev/null; then
  echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo
fi

# fomo signal
SIGNAL_FOMO="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>/dev/null)"

if [[ "$EMA_REAL_SIGNAL" == "Bullish" || "$EMA_REAL_SIGNAL" == "Bullish" && "$SIGNAL_FOMO" == "Bearish" ]] 2>>"${LOG_ERROR:?}"; then
  # if zero, skip log
  if [[ ! "$(echo "$EMA_REAL_SHORT" | awk -F. '{ print $1 }')" -eq "0" ]] 2>>"${LOG_ERROR:?}"; then
    if [[ ! "$(echo "$EMA_REAL_LONG" | awk -F. '{ print $1 }')" -eq "0" ]] 2>>"${LOG_ERROR:?}"; then
      # log bullish trend
      echo "$BULLISH_EMA_STATUS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi
  fi

  ##############################################################################
  # F O M O - B U Y
  ##############################################################################

  # check if balances, prices exist
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then
    if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then

      backup_balances

      # if fear of missing out is true
      if [[ "$EMA_FOMO" == "true" ]] &>/dev/null; then
        # if fomo signal is bearish while bullish
        if [[ "$SIGNAL_FOMO" == "Bearish" ]] &>/dev/null; then
          # ready to buy (signal age)
          if [[ "$SIGNAL_ORDER_AGE" -gt "$SIGNAL_AGE_SECONDS" ]] 2>>"${LOG_ERROR:?}"; then

            # if xeggex rsi
            if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
              # rsi bullish check
              RSI_BULLISH_CHECK="$(get_rsi_xgx "$LISTING_CURRENCY" "USDT" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if nonkyc rsi
            if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
              # rsi bullish check
              RSI_BULLISH_CHECK="$(get_rsi_nky "$LISTING_CURRENCY" "USDT" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if zero
            if [[ -z "$RSI_BULLISH_CHECK" ]] &>/dev/null; then
              RSI_BULLISH_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rsi 2>/dev/null | grep "L_NOW" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if not zero, has data
            if [[ ! -z "$RSI_BULLISH_CHECK" && -n "$RSI_BULLISH_CHECK" ]] &>/dev/null; then
              # if any data
              if [[ "$(echo "$RSI_BULLISH_CHECK" | egrep -c "[0-9]+" || true)" -gt "0" ]] &>/dev/null; then
                # rsi below bullish, above bearish
                if [[ "$RSI_BULLISH_CHECK" -lt "70" && "$RSI_BULLISH_CHECK" -gt "30" ]] &>/dev/null; then
                  # if valued (check)
                  if [[ "$LISTING_ALL_DIFF_CHECK" -gt "0" ]] &>/dev/null; then

                    # new listing amount (missing difference)
                    LISTING_AMOUNT="$(echo "$REFERENCE_AMOUNT_FOMO" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
                    # new bullish output
                    BULLISH_EMA_SIGNAL="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: FOMO : Bullish+Signal : Buying $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_ALLOCATED_REAL_CHECK+$LISTING_ALL_DIFF_CHECK% > ${LISTING_ALLOCATED:?}%"

                    # has value
                    if [[ "$(echo "$LISTING_AMOUNT" | tr -d '.' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
                      # if any data
                      if [[ -n "$LISTING_ALLOCATED_REAL_CHECK" && -n "$LISTING_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                        # is this bullish signal allocated correctly? (without decimal)
                        if [[ "$LISTING_ALLOCATED_REAL_CHECK" -lt "$LISTING_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                          # if not equal
                          if [[ ! "$LISTING_ALLOCATED_REAL_CHECK" -eq "$LISTING_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                            # trigger a buy for fear of missing out
                            echo "$BULLISH_EMA_SIGNAL" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
                            echo "Bearish :: 1$EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal
                            echo "Bullish :: $EMA_REAL_SHORT 1$EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal
                          fi
                        fi
                      fi
                    fi
                  fi
                fi
              fi
            fi
          fi
        fi
      fi
    fi
  fi

  ##############################################################################

  # is this a bullish cross?
  if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}" | egrep -c "Bullish+Cross|Bullish+Signal")" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then

    if [[ ! "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | tail -1 | awk '{ print $1 }')" ]] 2>>"${LOG_ERROR:?}"; then
      if [[ "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | grep -c "Bullish")" -eq "1" ]] 2>>"${LOG_ERROR:?}"; then

        ########################################################################

        signal_age_buying

        # buy order ############################################################

        TYPE="buy"
        DEBUG_TYPE="Buying"

        ########################################################################

        # ready to buy (signal age)
        if [[ "$SIGNAL_ORDER_AGE" -gt "$SIGNAL_AGE_SECONDS" ]] 2>>"${LOG_ERROR:?}"; then

          # if market order
          if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
            # balance check
            if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
              # if insufficient funds from last order
              if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

                # remove old signal_order
                rm "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                # if xeggex order
                if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
                  # createorder buy market #####################################
                  PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$LISTING_AMOUNT" "" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE market $LISTING_AMOUNT '' false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # if nonkyc order
                if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
                  # createorder buy market #####################################
                  PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$LISTING_AMOUNT" "" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE market $LISTING_AMOUNT '' false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # create fomo signal based on ema values
                echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                tx_id
                cost_price
                echo "$ORDER_BUY_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

                # remove duplicates
                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
              fi
            fi
            # if limit order
          elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then

            ####################################################################
            ####################################################################

            # balance check
            if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
              # if insufficient funds from last order
              if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

                # cancel old ema orders
                cancel_old_orders

                # if xeggex order
                if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
                  # createorder buy limit ######################################
                  PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$LISTING_AMOUNT" "$LISTING_PRICE" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE limit $LISTING_AMOUNT $LISTING_PRICE false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # if nonkyc order
                if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
                  # createorder buy limit ######################################
                  PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$LISTING_AMOUNT" "$LISTING_PRICE" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE limit $LISTING_AMOUNT $LISTING_PRICE false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # create fomo signal based on ema values
                echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                echo "$BUY_LIMIT_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
                tx_id
                cost_price
                echo "$ORDER_BUY_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

                # remove duplicates
                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
              fi
            fi
            echo "$BULLISH_EMA_CROSS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          fi
        fi
      fi
    fi
  fi
fi

################################################################################
# B E A R I S H - S I G N A L
################################################################################

BEARISH_EMA_CROSS="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ${LISTING_ALLOCATED:?}% : Bearish+Cross : Sell"
BEARISH_EMA_SIGNAL="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Trigger : Bearish+Signal : Selling $LISTING_AMOUNT $LISTING_CURRENCY $REFERENCE_ALLOCATED_REAL_CHECK+$REFERENCE_ALL_DIFF_CHECK% > ${REFERENCE_ALLOCATED:?}%"
BEARISH_EMA_STATUS="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT / $EMA_REAL_LONG / ($LISTING_PRICE Bearish ${EMA_PERCENTAGE:?}%) ${ROGUE_PROFIT_INDICATOR:?}"

################################################################################

# if missing
if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo ]] 2>/dev/null; then
  echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo
fi

# fomo signal
SIGNAL_FOMO="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>/dev/null)"

if [[ "$EMA_REAL_SIGNAL" == "Bearish" || "$EMA_REAL_SIGNAL" == "Bearish" && "$SIGNAL_FOMO" == "Bullish" ]] 2>>"${LOG_ERROR:?}"; then
  # if zero, skip log
  if [[ ! "$(echo "$EMA_REAL_SHORT" | awk -F. '{ print $1 }')" -eq "0" ]] 2>>"${LOG_ERROR:?}"; then
    if [[ ! "$(echo "$EMA_REAL_LONG" | awk -F. '{ print $1 }')" -eq "0" ]] 2>>"${LOG_ERROR:?}"; then
      # log bearish trend
      echo "$BEARISH_EMA_STATUS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    fi
  fi

  ##############################################################################
  # F O M O - S E L L
  ##############################################################################

  # check if balances, prices exist
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/balances | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then
    if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/"$EXCHANGE_DIR_NAME"/prices | awk '{ print $1 }')" -gt "1" ]] &>/dev/null; then

      backup_balances

      # if fear of missing out is true
      if [[ "$EMA_FOMO" == "true" ]] &>/dev/null; then
        # if fomo signal is bullish while bearish
        if [[ "$SIGNAL_FOMO" == "Bullish" ]] &>/dev/null; then
          # ready to sell (signal age)
          if [[ "$SIGNAL_ORDER_AGE" -gt "$SIGNAL_AGE_SECONDS" ]] 2>>"${LOG_ERROR:?}"; then

            # if xeggex rsi
            if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
              # rsi bullish check
              RSI_BULLISH_CHECK="$(get_rsi_xgx "$LISTING_CURRENCY" "USDT" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if nonkyc rsi
            if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
              # rsi bullish check
              RSI_BULLISH_CHECK="$(get_rsi_nky "$LISTING_CURRENCY" "USDT" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if zero
            if [[ -z "$RSI_BEARISH_CHECK" ]] &>/dev/null; then
              RSI_BEARISH_CHECK="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rsi 2>/dev/null | grep "L_NOW" | awk '{ print $NF }' | awk -F. '{ print $1 }')"
            fi

            # if not zero, has data
            if [[ ! -z "$RSI_BEARISH_CHECK" && -n "$RSI_BEARISH_CHECK" ]] &>/dev/null; then
              # if any data
              if [[ "$(echo "$RSI_BEARISH_CHECK" | egrep -c "[0-9]+" || true)" -gt "0" ]] &>/dev/null; then
                # rsi above bearish, below bullish
                if [[ "$RSI_BEARISH_CHECK" -gt "30" && "$RSI_BEARISH_CHECK" -lt "70" ]] &>/dev/null; then
                  # if valued (check)
                  if [[ "$REFERENCE_ALL_DIFF_CHECK" -gt "0" ]] &>/dev/null; then

                    # new listing amount (missing difference)
                    LISTING_AMOUNT="$(echo "$LISTING_AMOUNT_FOMO" | awk '{ printf "%." '$DECIMAL_LIMIT' "f\n", int($0 * 10^'$DECIMAL_LIMIT') / 10^'$DECIMAL_LIMIT' }')"
                    # new bearish output
                    BEARISH_EMA_SIGNAL="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: FOMO : Bearish+Signal : Selling $LISTING_AMOUNT $LISTING_CURRENCY $REFERENCE_ALLOCATED_REAL_CHECK+$REFERENCE_ALL_DIFF_CHECK% > ${REFERENCE_ALLOCATED:?}%"

                    # has value
                    if [[ "$(echo "$LISTING_AMOUNT" | tr -d '.' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
                      # if any data
                      if [[ -n "$REFERENCE_ALLOCATED_REAL_CHECK" && -n "$REFERENCE_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                        # is this bearish signal allocated correctly? (without decimal)
                        if [[ "$REFERENCE_ALLOCATED_REAL_CHECK" -lt "$REFERENCE_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                          # if not equal
                          if [[ ! "$REFERENCE_ALLOCATED_REAL_CHECK" -eq "$REFERENCE_ALLOCATED_CONFIG_CHECK" ]] &>/dev/null; then
                            # trigger a sell for fear of missing out
                            echo "$BEARISH_EMA_SIGNAL" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
                            echo "Bullish :: $EMA_REAL_SHORT 1$EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal
                            echo "Bearish :: 1$EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal
                          fi
                        fi
                      fi
                    fi
                  fi
                fi
              fi
            fi
          fi
        fi
      fi
    fi
  fi

  ##############################################################################

  # is this a bearish cross?
  if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}" | egrep -c "Bearish+Cross|Bearish+Signal")" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then

    if [[ ! "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | tail -1 | awk '{ print $1 }')" ]] 2>>"${LOG_ERROR:?}"; then
      if [[ "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | grep -c "Bearish")" -eq "1" ]] 2>>"${LOG_ERROR:?}"; then

        ########################################################################

        signal_age_selling

        # sell order ###########################################################

        TYPE="sell"
        DEBUG_TYPE="Selling"

        ########################################################################

        # ready to sell (signal age)
        if [[ "$SIGNAL_ORDER_AGE" -gt "$SIGNAL_AGE_SECONDS" ]] 2>>"${LOG_ERROR:?}"; then

          # if market order
          if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
            # balance check
            if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
              # if insufficient funds from last order
              if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

                # remove old signal_order
                rm "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_order 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                # if xeggex order
                if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
                  # createorder sell market ####################################
                  PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$LISTING_AMOUNT" "" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE market $LISTING_AMOUNT '' false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # if nonkyc order
                if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
                  # createorder sell market ####################################
                  PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "market" "$LISTING_AMOUNT" "" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE market $LISTING_AMOUNT '' false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # create fomo signal based on ema values
                echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                tx_id
                cost_price
                echo "$ORDER_SELL_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

                # remove duplicates
                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
              fi
            fi
            # if limit order
          elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then

            ####################################################################
            ####################################################################

            # balance check
            if [[ "$LISTING_AVAILABLE_BALANCE_NR" -gt "0" || "$REFERENCE_AVAILABLE_BALANCE_NR" -gt "0" ]] 2>>"${LOG_ERROR:?}"; then
              # if insufficient funds from last order
              if [[ "$NO_FUNDS" -eq "0" ]] &>/dev/null; then

                # cancel old ema orders
                cancel_old_orders

                # if xeggex order
                if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
                  # createorder sell limit #####################################
                  PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$LISTING_AMOUNT" "$LISTING_PRICE" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE limit $LISTING_AMOUNT $LISTING_PRICE false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # if nonkyc order
                if [[ "$EXCHANGE_API" == "NKY" ]] &>/dev/null; then
                  # createorder sell limit #####################################
                  PLACE_ORDER="$(CreateOrder_nky "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "$TYPE" "limit" "$LISTING_AMOUNT" "$LISTING_PRICE" "false")"
                  # debug line #################################################
                  echo "$LOG_DATE : DebugOrder '' $LISTING_CURRENCY/$REFERENCE_CURRENCY $TYPE limit $LISTING_AMOUNT $LISTING_PRICE false <--- $DEBUG_TYPE asset" >>"${LOG_DIR:?}"/leeloo/"$BASENAME_STRATEGY".debug
                  ##############################################################
                fi

                # create fomo signal based on ema values
                echo "$EMA_REAL_SIGNAL" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal_fomo 2>>"${LOG_ERROR:?}"

                ################################################################
                ################################################################

                echo "$SELL_LIMIT_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
                tx_id
                cost_price
                echo "$ORDER_SELL_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

                # remove duplicates
                echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
              fi
            fi
            echo "$BEARISH_EMA_CROSS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
          fi
        fi
      fi
    fi
  fi
fi

################################################################################

save_orders   # save orders
last_orders   # last orders
backup_orders # backup orders

################################################################################

robot_Log_cleanup

################################################################################

# END
