#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# ema strategy configuration
################################################################################

# POL poloniex template - SXC southxchange template - SCE stakecube template

################################################################################

EXCHANGE_API=""           # exchange api (template)
MARKET_LIMIT="market"     # market or limit order
EMA_SHORT="10"            # EMA short (10)
EMA_LONG="20"             # EMA long (20)
EMA_FOMO="false"          # EMA Fear Of Missing Out (false)
ROGUE_PROFIT="0"          # RSI rogue profit (0)
SIGNAL_AGE="24"           # signal age (24h)
LISTING_CURRENCY=""       # listing currency
LISTING_ALLOCATED="100"   # account allocated (100%)
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_ALLOCATED="100" # account allocated (100%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
