#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# indicators
source /usr/local/bin/include/leeloo/indicators/ema
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
STRATEGY_NAME="$(egrep "STRATEGY_NAME=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# ema strategy configuration (static)
################################################################################

STRATEGY_TYPE="EMA"

# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# ema short
EMA_SHORT="$(egrep "EMA_SHORT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# ema long
EMA_LONG="$(egrep "EMA_LONG=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# rogue profit enable, disable
ROGUE_PROFIT="$(egrep "ROGUE_PROFIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################
# S T R A T E G Y - S I G N A L
################################################################################

# get data
function result_ema() {
  GET_EMA_DATA="$(get_ema "$EMA_SHORT" "$EMA_LONG" "$LISTING_CURRENCY")"
  GET_EMA_SIGNAL="$(echo "$GET_EMA_DATA" | awk '{ print $1 }')"
  GET_EMA_CONFIG="$(echo "$GET_EMA_DATA" | awk '{ print $NF }')"
  GET_SHORT_DATA="$(echo "$GET_EMA_DATA" | awk '{ print $3 }')"
  GET_LONG_DATA="$(echo "$GET_EMA_DATA" | awk '{ print $5 }')"
  GET_DIFFERENCE="$(echo "$GET_SHORT_DATA-$GET_LONG_DATA" | bc -l 2>/dev/null)"
  GET_PERCENTAGE="$(echo "100/$GET_SHORT_DATA*$GET_DIFFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"

  if [[ -z "$GET_PERCENTAGE" ]] &>/dev/null; then
    GET_PERCENTAGE="0"
  fi

  echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

EMA_Data..............: $STRATEGY_TYPE $GET_EMA_CONFIG
EMA_Short.............: $GET_SHORT_DATA
EMA_Long..............: $GET_LONG_DATA
EMA_Signal............: $GET_EMA_SIGNAL
EMA_Strength..........: ${GET_PERCENTAGE:?}%

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
}

################################################################################

executed_orders

################################################################################

EMA_TIMER="$(echo "${BOT_TIMER:?}*3.69" | bc 2>/dev/null | awk -F. '{ print $1 }')" # EMA data timer

# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null)))" 2>/dev/null)" -gt "$EMA_TIMER" ]] &>/dev/null; then
  result_ema
  # update data if missing
elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_ema
  # update data if empty
elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_ema
fi

################################################################################
# O P E N - P O S I T I O N S
################################################################################

open_positions

################################################################################

BUY_MARKET_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_NAME :: $REFERENCE_CURRENCY Market $REFERENCE_AMOUNT"
SELL_MARKET_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_NAME :: $LISTING_CURRENCY :: Market $LISTING_AMOUNT"

BUY_LIMIT_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_NAME :: $REFERENCE_CURRENCY Limit $REFERENCE_PRICE $REFERENCE_AMOUNT"
SELL_LIMIT_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_NAME :: $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"

BUY_LIMIT_POSITION="$LOG_DATE :: Strategy $STRATEGY_NAME :: $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
SELL_LIMIT_POSITION="$BUY_LIMIT_POSITION"

BUY_MARKET_POSITION="$BUY_LIMIT_POSITION"
SELL_MARKET_POSITION="$BUY_LIMIT_POSITION"

################################################################################

incoming_listing
incoming_reference

################################################################################

rogue_profit

################################################################################

EMA_REAL_RAW="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null)"
EMA_REAL_STRATEGY="$(echo "$EMA_REAL_RAW" | grep "EMA_Data" | awk '{ print $2 }')"
EMA_REAL_SIGNAL="$(echo "$EMA_REAL_RAW" | grep "EMA_Signal" | awk '{ print $2 }')"
EMA_REAL_SHORT="$(echo "$EMA_REAL_RAW" | grep "EMA_Short" | awk '{ print $2 }')"
EMA_REAL_LONG="$(echo "$EMA_REAL_RAW" | grep "EMA_Long" | awk '{ print $2 }')"

# if zero, skip signal
if [[ ! "$(echo "$EMA_REAL_SHORT" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
  if [[ ! "$(echo "$EMA_REAL_LONG" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    echo "$EMA_REAL_SIGNAL :: $EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>/dev/null
  fi
fi

# keep n lines
echo "$(tail -21 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>/dev/null

# latest signal
EMA_REAL_SIGNAL="$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | awk '{ print $1 }')"

# if zero, skip
if [[ -z "$EMA_REAL_SIGNAL" ]] &>/dev/null; then
  EMA_REAL_SIGNAL="Idling"
fi

EMA_DIFFERENCE="$(echo "$EMA_REAL_SHORT-$EMA_REAL_LONG" | bc -l 2>/dev/null)"
EMA_PERCENTAGE="$(echo "100/$EMA_REAL_SHORT*$EMA_DIFFERENCE" | bc -l 2>/dev/null | awk '{ printf "%.4f\n", $1 }')"

if [[ -z "$EMA_PERCENTAGE" ]] &>/dev/null; then
  EMA_PERCENTAGE="0"
fi

################################################################################
# B U L L I S H - S I G N A L
################################################################################

BULLISH_EMA_CROSS="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: ${REFERENCE_ALLOCATED:?}% :: Bullish+Cross :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $TYPE"
BULLISH_EMA_STATUS="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT/$EMA_REAL_LONG Bullish ${EMA_PERCENTAGE:?}%"
BULLISH_EMA_RIDE="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: Joining the $EMA_REAL_SIGNAL ride!"

BEARISH_EMA_CROSS="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: ${LISTING_ALLOCATED:?}% :: Bearish+Cross :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $TYPE"
BEARISH_EMA_STATUS="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT/$EMA_REAL_LONG Bearish ${EMA_PERCENTAGE:?}%"
BEARISH_EMA_RIDE="$LOG_DATE :: Strategy $EMA_REAL_STRATEGY :: Leaving the $EMA_REAL_SIGNAL ride!"

################################################################################

if [[ "$EMA_REAL_SIGNAL" == "Bullish" ]] &>/dev/null; then

  # did the bot join the ride?
  ENJOYING_RIDE="$(grep -c "Bullish" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal)"
  if [[ "$ENJOYING_RIDE" -lt "2" ]] &>/dev/null; then
    if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -c "Joining")" -gt "0" ]] &>/dev/null; then
      echo "Buying :: $EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>/dev/null
      echo "$BULLISH_EMA_RIDE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi

  # if zero, skip log
  if [[ ! "$(echo "$EMA_REAL_SHORT" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    if [[ ! "$(echo "$EMA_REAL_LONG" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
      # log bullish trend
      echo "$BULLISH_EMA_STATUS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi

  ##############################################################################

  # is this a bullish cross?
  if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -c "Bullish+Cross")" -gt "0" ]] &>/dev/null; then

    if [[ ! "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | tail -1 | awk '{ print $1 }')" ]] &>/dev/null; then
      if [[ "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | grep -c "Bullish")" -eq "1" ]] &>/dev/null; then

        # buy order ############################################################

        TYPE="buy"
        AMOUNT_IN_REFERENCE_CURRENCY="true"

        if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$BUY_MARKET_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$BUY_MARKET_POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

          # placeOrder limit ###################################################
          PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$BUY_LIMIT_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$BUY_LIMIT_POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        fi
        echo "$BULLISH_EMA_CROSS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi
fi

################################################################################
# B E A R I S H - S I G N A L
################################################################################

if [[ "$EMA_REAL_SIGNAL" == "Bearish" ]] &>/dev/null; then

  # did the bot leave the ride?
  ENJOYING_RIDE="$(grep -c "Bearish" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal)"
  if [[ "$ENJOYING_RIDE" -lt "2" ]] &>/dev/null; then
    if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -c "Leaving")" -gt "0" ]] &>/dev/null; then
      echo "Selling :: $EMA_REAL_SHORT $EMA_REAL_LONG" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal 2>/dev/null
      echo "$BEARISH_EMA_RIDE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi

  # if zero, skip log
  if [[ ! "$(echo "$EMA_REAL_SHORT" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
    if [[ ! "$(echo "$EMA_REAL_LONG" | awk -F. '{ print $1 }')" -eq "0" ]] &>/dev/null; then
      # log bearish trend
      echo "$BEARISH_EMA_STATUS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi
  fi

  ##############################################################################

  # is this a bearish cross?
  if [[ ! "$(tail -10 "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -c "Bearish+Cross")" -gt "0" ]] &>/dev/null; then

    if [[ ! "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | tail -1 | awk '{ print $1 }')" ]] &>/dev/null; then
      if [[ "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".signal | grep -c "Bearish")" -eq "1" ]] &>/dev/null; then

        # sell order ###########################################################

        TYPE="sell"
        AMOUNT_IN_REFERENCE_CURRENCY="false"

        if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$SELL_MARKET_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$SELL_MARKET_POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

          # placeOrder limit ###################################################
          PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
          ######################################################################

          echo "$SELL_LIMIT_OUTPUT :: $TYPE :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
          tx_id
          cost_price
          echo "$SELL_LIMIT_POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

        fi
        echo "$BEARISH_EMA_CROSS" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
      fi
    fi
  fi
fi

################################################################################

save_orders

################################################################################

robot_Logs_by_date

################################################################################

# END
