#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/ema

DATE="$(date | xargs)"
# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"

################################################################################
# ema strategy configuration (static)
################################################################################

STRATEGY_TYPE="EMA"
MARKET_LIMIT="$(grep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order
EMA_SHORT="$(grep "EMA_SHORT=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"       # EMA short
EMA_LONG="$(grep "EMA_LONG=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"         # EMA long

# listing
LISTING_CURRENCY="$(grep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # listing currency
LISTING_ALLOCATED="$(grep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

# reference
REFERENCE_CURRENCY="$(grep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # reference currency
REFERENCE_ALLOCATED="$(grep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

################################################################################
# strategy
################################################################################

# get available listing data
LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

# get available reference data
REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
REFERENCE_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"

# keep data
function result_ema() {
  get_ema "$EMA_SHORT" "$EMA_LONG" "$LISTING_CURRENCY" >"${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".data 2>/dev/null
}
# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".data 2>/dev/null)))" 2>/dev/null)" -gt "90" ]] &>/dev/null; then
  result_ema
  # update data if missing
elif [[ ! -f "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_ema
  # update data if empty
elif [[ ! -s "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_ema
fi

EMA_REAL_RAW="$(cat "${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".data 2>/dev/null)"
EMA_REAL_SIGNAL="$(echo "$EMA_REAL_RAW" | awk '{ print $1 }')"
EMA_REAL_SHORT="$(echo "$EMA_REAL_RAW" | awk '{ print $5 }')"
EMA_REAL_LONG="$(echo "$EMA_REAL_RAW" | awk '{ print $8 }')"

if [[ "$EMA_REAL_SIGNAL" == "Bearish" ]] &>/dev/null; then
  BEAR_BULL="Bearish"
fi

if [[ "$EMA_REAL_SIGNAL" == "Bullish" ]] &>/dev/null; then
  BEAR_BULL="Bullish"
fi

echo "$BEAR_BULL :: $EMA_REAL_SHORT $EMA_REAL_LONG" >>"${LOG_DIR:?}"/leeloo/ema_signal
echo "$(tail -21 "${LOG_DIR:?}"/leeloo/ema_signal)" >"${LOG_DIR:?}"/leeloo/ema_signal

function tx_id {
  echo "$(echo "$PLACE_ORDER" | tr -d '"')" >"${SYS_DIR:?}"/robot/ema."$BASENAME_STRATEGY".txid
}

if [[ "$EMA_REAL_SIGNAL" == "Bullish" ]] &>/dev/null; then

  EMA_DIFFERENCE="$(echo "$EMA_REAL_SHORT-$EMA_REAL_LONG" | bc -l)"
  EMA_PERCENTAGE="$(echo "100/$EMA_REAL_SHORT*$EMA_DIFFERENCE" | bc -l | awk '{ printf "%.4f\n", $1 }')"

  # bullish trend?
  echo "$DATE :: Strategy $STRATEGY_TYPE $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT/$EMA_REAL_LONG Bullish ${EMA_PERCENTAGE:?}%" >>"${LOG_DIR:?}"/leeloo/robot.log

  # is this a bullish signal?
  if [[ ! "$(tail -2 "${LOG_DIR:?}"/leeloo/ema_signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${LOG_DIR:?}"/leeloo/ema_signal | tail -1 | awk '{ print $1 }')" ]] &>/dev/null; then
    if [[ "$(tail -1 "${LOG_DIR:?}"/leeloo/ema_signal | grep -c "Bullish")" -eq "1" ]] &>/dev/null; then

      # buy order ##############################################################

      TYPE="buy"
      REFERENCE_STATUS="false"

      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        tx_id
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        tx_id
      fi
      echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE :: Bullish+Cross :: $LISTING_CURRENCY/$REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot.log
    fi
  fi
fi

if [[ "$EMA_REAL_SIGNAL" == "Bearish" ]] &>/dev/null; then

  EMA_DIFFERENCE="$(echo "$EMA_REAL_SHORT-$EMA_REAL_LONG" | bc -l)"
  EMA_PERCENTAGE="$(echo "100/$EMA_REAL_SHORT*$EMA_DIFFERENCE" | bc -l | awk '{ printf "%.4f\n", $1 }')"

  # bearish trend?
  echo "$DATE :: Strategy $STRATEGY_TYPE $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $EMA_REAL_SHORT/$EMA_REAL_LONG Bearish ${EMA_PERCENTAGE:?}%" >>"${LOG_DIR:?}"/leeloo/robot.log

  # is this a bearish signal?
  if [[ ! "$(tail -2 "${LOG_DIR:?}"/leeloo/ema_signal | head -1 | awk '{ print $1 }')" == "$(tail -2 "${LOG_DIR:?}"/leeloo/ema_signal | tail -1 | awk '{ print $1 }')" ]] &>/dev/null; then
    if [[ "$(tail -1 "${LOG_DIR:?}"/leeloo/ema_signal | grep -c "Bearish")" -eq "1" ]] &>/dev/null; then

      # sell order #############################################################

      TYPE="sell"
      REFERENCE_STATUS="true"

      # market
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE $LISTING_CURRENCY Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        tx_id
        # limit
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE $LISTING_CURRENCY Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log
        tx_id
      fi
      echo "$DATE :: Strategy $STRATEGY_TYPE $TYPE :: Bearish+Cross :: $LISTING_CURRENCY/$REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot.log
    fi
  fi
fi

# END
