#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# lorentzian strategy configuration
################################################################################

# POL poloniex template - SXC southxchange template - SCE stakecube template

################################################################################

EXCHANGE_API=""           # exchange api (template)
MARKET_LIMIT="market"     # market or limit order
LISTING_CURRENCY=""       # listing currency
LISTING_ALLOCATED="100"   # account allocated (100%)
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_ALLOCATED="100" # account allocated (100%)
LZN_LAMBDA="0.015"        # width of the lorentzian distribution
LZN_BUY_THRESHOLD="0.8"   # buy threshold
LZN_SELL_THRESHOLD="0.3"  # sell threshold

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
