#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
STRATEGY_NAME="$(egrep "STRATEGY_NAME=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# lorentzian strategy configuration
################################################################################

STRATEGY_TYPE="LZN"

MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

# listing
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # listing currency
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

# reference
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # reference currency
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

# strategy parameters
LAMBDA="$(egrep "LAMBDA=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"                 # width of the lorentzian distribution
BUY_THRESHOLD="$(egrep "BUY_THRESHOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # buy threshold
SELL_THRESHOLD="$(egrep "SELL_THRESHOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # sell threshold

PAIR="$LISTING_CURRENCY/$REFERENCE_CURRENCY"

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################
# S T R A T E G Y - I N D I C A T O R
################################################################################

if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position ]] &>/dev/null; then
  LZN_POSITION="LONG"
  echo "$LZN_POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position
else
  LZN_POSITION="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position 2>/dev/null)"
  LZN_POSITION_VALUE=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".lc 2>/dev/null)
fi

################################################################################

# get data
function result_lzn() {
  # get listing, reference trades
  LZN_TRADES=$(trades "$LISTING_CURRENCY" "$REFERENCE_CURRENCY")
  echo "$LZN_TRADES" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".trades

  echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY
LZN_Data..............: $STRATEGY_TYPE
LZN_Position..........: $LZN_POSITION $LZN_POSITION_VALUE
Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "Last_Order.txid.......:  $TX_ID_LAST
" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "- Last info" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "$(egrep "info.*Incoming" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | tail -1)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  echo "- Executed" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
  # get executed orders
  echo "$(egrep "sell.*h:|buy.*h:" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -v "Cooldown")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
  echo "$(tail -1 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null
}

################################################################################

LZN_TIMER="$(echo "${BOT_TIMER:?}*3.33" | bc 2>/dev/null | awk -F. '{ print $1 }')"

# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null)))" 2>/dev/null)" -gt "$LZN_TIMER" ]] &>/dev/null; then
  result_lzn
  # update data if missing
elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_lzn
  # update data if empty
elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data ]] &>/dev/null; then
  result_lzn
fi

################################################################################
# O P E N - P O S I T I O N S
################################################################################

OPEN_STRATEGY="$STRATEGY_TYPE"
open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################
# L O R E N T Z I A N - I N D I C A T O R
################################################################################

POSITION="$(grep "LZN_Position" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data | awk '{ print $2 }')"

# define initial price and timestamp
PRICE=0
TIMESTAMP=0

# define function to calculate the lorentzian classification indicator
function lorentzian_classification {
  PRICE=$1
  LAMBDA=$2
  CLASSIFICATION=$(echo "scale=10; 1/(1 + (${PRICE}-${PRICE}*${PRICE})/(${LAMBDA}*${LAMBDA}))" | bc -l 2>/dev/null)
  echo ${CLASSIFICATION}
}

# retrieve last trade
TRADE=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".trades 2>/dev/null)
NEW_PRICE=$(echo "${TRADE}" | jq '.Price')
NEW_TIMESTAMP=$(echo "${TRADE}" | jq '.At')

# check if new trade has been executed
if (($(echo "${NEW_PRICE} != ${PRICE}" | bc -l 2>/dev/null))); then
  # calculate lorentzian classification indicator
  LC=$(lorentzian_classification "${NEW_PRICE}" "${LAMBDA}" | awk '{ printf "%.8f\n", $1 }')
  echo "$LC" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".lc

  # determine trading action
  if [[ "$(echo "${LC} > ${BUY_THRESHOLD}" | bc -l)" -eq 1 && "${POSITION}" == "NONE" ]]; then

    # hodl position
    POSITION="LONG"
    echo "$POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position

    # buy order ################################################################

    TYPE="buy"
    AMOUNT_IN_REFERENCE_CURRENCY="true"

    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

      # placeOrder market ######################################################
      PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
      ##########################################################################

      # place buy order
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: Placing buy order for ${PAIR} at ${NEW_PRICE}" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $TYPE $REFERENCE_CURRENCY Market $REFERENCE_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      tx_id
      cost_price
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

      # placeOrder limit #######################################################
      PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
      ##########################################################################

      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: Placing buy order for ${PAIR} at ${NEW_PRICE}" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $TYPE $REFERENCE_CURRENCY Limit $REFERENCE_PRICE $REFERENCE_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      tx_id
      cost_price
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    fi

    ############################################################################

    # update position and price
    POSITION="LONG"
    PRICE=${NEW_PRICE}
    TIMESTAMP=${NEW_TIMESTAMP}
    # determine trading action
  elif [[ "$(echo "${LC} < ${SELL_THRESHOLD}" | bc -l)" -eq 1 && "${POSITION}" == "LONG" ]]; then

    # hodl position
    POSITION="NONE"
    echo "$POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position

    # sell order ###############################################################

    TYPE="sell"
    AMOUNT_IN_REFERENCE_CURRENCY="false"

    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

      # placeOrder market ######################################################
      PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
      ##########################################################################

      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: Placing sell order for ${PAIR} at ${NEW_PRICE}" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $TYPE $LISTING_CURRENCY :: Market $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      tx_id
      cost_price
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log

    elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

      # placeOrder limit #######################################################
      PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
      ##########################################################################

      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: Placing sell order for ${PAIR} at ${NEW_PRICE}" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $TYPE $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
      tx_id
      cost_price
      echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    fi

    # update position and price
    POSITION="NONE"
    PRICE=${NEW_PRICE}
    TIMESTAMP=${NEW_TIMESTAMP}
  else
    echo "$LOG_DATE :: Strategy $STRATEGY_NAME :: $PAIR :: $LC :: Price ${NEW_PRICE} ${LISTING_OPEN_RESULT:?}% :: $POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  fi
fi

################################################################################

robot_Logs_by_date

################################################################################

# END
