#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/sMcD

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# lorentzian strategy configuration
################################################################################

STRATEGY_TYPE="LZN"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# width of the lorentzian distribution
LZN_LAMBDA="$(egrep "LZN_LAMBDA=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# buy threshold
LZN_BUY_THRESHOLD="$(egrep "LZN_BUY_THRESHOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# sell threshold
LZN_SELL_THRESHOLD="$(egrep "LZN_SELL_THRESHOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# trategy templates
################################################################################

# poloniex template
if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/poloniex
fi
# southxchange template
if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/southxchange
fi
# stakecube template
if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/stakecube
fi

if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
  echo "$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  exit
fi

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################

if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position ]] &>/dev/null; then
  LZN_POSITION="LONG"
  echo "$LZN_POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position 2>/dev/null
else
  LZN_POSITION="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position 2>/dev/null)"
  LZN_POSITION_VALUE=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".lc 2>/dev/null)
fi

################################################################################

# get listing, reference trades
LZN_TRADES=$(trades "$LISTING_CURRENCY" "$REFERENCE_CURRENCY")
echo "$LZN_TRADES" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".trades 2>/dev/null

# get data
echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

LZN_Data..............: $STRATEGY_TYPE
LZN_Position..........: $LZN_POSITION $LZN_POSITION_VALUE

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null

################################################################################

open_positions

################################################################################

# market output
BUY_MARKET_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $REFERENCE_CURRENCY Market $REFERENCE_AMOUNT"
SELL_MARKET_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY :: Market $LISTING_AMOUNT"
# limit output
BUY_LIMIT_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $REFERENCE_CURRENCY Limit $REFERENCE_PRICE $REFERENCE_AMOUNT"
SELL_LIMIT_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY :: Limit $LISTING_PRICE $LISTING_AMOUNT"
# position output
MARKET_LZN_POSITION="$LOG_DATE :: $TYPE :: $STRATEGY_TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
LIMIT_LZN_POSITION="$LOG_DATE :: $TYPE :: $STRATEGY_TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"

################################################################################

incoming_listing
incoming_reference

################################################################################
# L O R E N T Z I A N - I N D I C A T O R
################################################################################

POSITION="$(grep "LZN_Position" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data | awk '{ print $2 }')"

# define initial price and timestamp
PRICE=0
TIMESTAMP=0

# define function to calculate the lorentzian classification indicator
function lorentzian_classification {
  PRICE=$1
  LZN_LAMBDA=$2
  CLASSIFICATION=$(echo "scale=10; 1/(1 + (${PRICE}-${PRICE}*${PRICE})/(${LZN_LAMBDA}*${LZN_LAMBDA}))" | bc -l 2>/dev/null)
  echo ${CLASSIFICATION}
}

# retrieve last trade
TRADE=$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".trades 2>/dev/null)
# not zero, continue
if [[ ! -z "$TRADE" ]] &>/dev/null; then
  NEW_PRICE=$(echo "${TRADE}" | jq '.Price')
  NEW_TIMESTAMP=$(echo "${TRADE}" | jq '.At')

  # check if new trade has been executed
  if (($(echo "${NEW_PRICE} != ${PRICE}" | bc -l 2>/dev/null))); then
    # calculate lorentzian classification indicator
    LC=$(lorentzian_classification "${NEW_PRICE}" "${LZN_LAMBDA}" | awk '{ printf "%.10f\n", $1 }')
    LC_OUTPUT="$(echo "$LC" | awk '{ printf "%.9f\n", $1 }')"

    if [[ -z "$LC_OUTPUT" ]] &>/dev/null; then
      LC_OUTPUT="$(echo "0" | awk '{ printf "%.9f\n", $1 }')"
    fi

    echo "$LC" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".lc 2>/dev/null
  fi

  ##############################################################################

  STATUS_LZN_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $LC_OUTPUT :: ${LISTING_OPEN_RESULT:?}% :: $POSITION"
  BUY_LZN_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: Placing buy order for $LISTING_CURRENCY/$REFERENCE_CURRENCY at ${NEW_PRICE}"
  BOUGHT_LZN_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: Already bought, waiting. $LISTING_CURRENCY/$REFERENCE_CURRENCY at ${NEW_PRICE}"
  SELL_LZN_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: Placing sell order for $LISTING_CURRENCY/$REFERENCE_CURRENCY at ${NEW_PRICE}"
  SOLD_LZN_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: Already sold, waiting. $LISTING_CURRENCY/$REFERENCE_CURRENCY at ${NEW_PRICE}"

  ##############################################################################

  # determine trading action
  if [[ "$(echo "${LC} > ${LZN_BUY_THRESHOLD}" | bc -l)" -eq 1 && "${POSITION}" == "NONE" ]]; then

    # hodl position
    POSITION="LONG"
    echo "$POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position 2>/dev/null

    # buy order ################################################################

    # amount must be greater than zero
    if [[ "$(echo "$REFERENCE_AMOUNT" | tr -d '.' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then

      TYPE="buy"
      AMOUNT_IN_REFERENCE_CURRENCY="true"

      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        # placeOrder market ####################################################
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        # buy market order
        echo "$BUY_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$BUY_MARKET_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        tx_id
        cost_price
        echo "$MARKET_LZN_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        # remove duplicates
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null

      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

        # placeOrder limit #####################################################
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        # buy limit order
        echo "$BUY_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$BUY_LIMIT_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        tx_id
        cost_price
        echo "$LIMIT_LZN_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        # remove duplicates
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
      fi
    else
      echo "$BOUGHT_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi

    ############################################################################

    # update position and price
    POSITION="LONG"
    PRICE=${NEW_PRICE}
    TIMESTAMP=${NEW_TIMESTAMP}
    # determine trading action
  elif [[ "$(echo "${LC} < ${LZN_SELL_THRESHOLD}" | bc -l)" -eq 1 && "${POSITION}" == "LONG" ]]; then

    # hodl position
    POSITION="NONE"
    echo "$POSITION" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".position 2>/dev/null

    # sell order ###############################################################

    # amount must be greater than zero
    if [[ "$(echo "$LISTING_AMOUNT" | tr -d '.' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then

      TYPE="sell"
      AMOUNT_IN_REFERENCE_CURRENCY="false"

      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

        # placeOrder market ####################################################
        PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        # sell order
        echo "$SELL_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$SELL_MARKET_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        tx_id
        cost_price
        echo "$MARKET_LZN_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        # remove duplicates
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null

      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

        # placeOrder limit #####################################################
        PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
        ########################################################################

        # sell order
        echo "$SELL_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        echo "$SELL_LIMIT_OUTPUT :: $TYPE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
        tx_id
        cost_price
        echo "$LIMIT_LZN_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
        # remove duplicates
        echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
      fi
    else
      echo "$SOLD_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
    fi

    ############################################################################

    # update position and price
    POSITION="NONE"
    PRICE=${NEW_PRICE}
    TIMESTAMP=${NEW_TIMESTAMP}
  else
    echo "$STATUS_LZN_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  fi
fi

################################################################################

save_orders
last_orders
sxc_backup_orders

################################################################################

robot_Log_cleanup

################################################################################

# END
