#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# market chaser strategy configuration (static)
################################################################################

STRATEGY_TYPE="MCS"

# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################

# chase and hodl the type
REFERENCE_MCS_PRICE_BID="$(echo "$REFERENCE_PRICE" | tr -d '.' | sed 's/^0*//')"
REFERENCE_MCS_PRICE_ASK="$(echo "$REFERENCE_PRICE_ASK" | tr -d '.' | sed 's/^0*//')"
REFERENCE_MCS_PRICE_LAST="$(echo "$REFERENCE_PRICE_LAST" | tr -d '.' | sed 's/^0*//')"

################################################################################

if [[ "$REFERENCE_MCS_PRICE_LAST" == "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  MCS_POSITION_VALUE="[$REFERENCE_MCS_PRICE_LAST-$REFERENCE_MCS_PRICE_ASK]"
  MCS_POSITION_STATUS="OK"
fi

if [[ "$REFERENCE_MCS_PRICE_LAST" -lt "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  MCS_POSITION_VALUE="[$REFERENCE_MCS_PRICE_LAST>$REFERENCE_MCS_PRICE_ASK]"
  MCS_POSITION_STATUS="Moon!"
fi

if [[ "$REFERENCE_MCS_PRICE_LAST" -gt "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  MCS_POSITION_VALUE="[$REFERENCE_MCS_PRICE_LAST*$REFERENCE_MCS_PRICE_ASK]"
  MCS_POSITION_STATUS="Waiting"
fi

################################################################################

# get data
echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

MCS_Data..............: $STRATEGY_TYPE
MCS_Position..........: $MCS_POSITION_STATUS $MCS_POSITION_VALUE
MCS_Bid/Ask/Last......: $REFERENCE_MCS_PRICE_BID/$REFERENCE_MCS_PRICE_ASK/$REFERENCE_MCS_PRICE_LAST

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>/dev/null

################################################################################
# O P E N - P O S I T I O N S
################################################################################

open_positions

################################################################################

MARKET_MCS_EXECUTE="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Chasing Ask! $REFERENCE_MCS_PRICE_LAST > $REFERENCE_MCS_PRICE_ASK"
MARKET_MCS_POSITION="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"

################################################################################

# price is equal
if [[ "$REFERENCE_MCS_PRICE_LAST" == "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  MCS_STATUS="$MCS_POSITION_STATUS :: ${MCS_POSITION_VALUE:?}"
fi

################################################################################

if [[ "$REFERENCE_MCS_PRICE_LAST" -lt "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  # price is different
  MCS_STATUS="$MCS_POSITION_STATUS! :: ${MCS_POSITION_VALUE:?}"

  # listing market buy order
  AMOUNT_IN_REFERENCE_CURRENCY="false"
  TYPE="buy"

  # random order amount
  RANDOM_ORDER_NUMBER=$((((RANDOM % 369369369) + 1)))
  RANDOM_ORDER_NUMBER="$(echo "$RANDOM_ORDER_NUMBER/369369" | bc -l 2>/dev/null | awk '{ printf "%.18f\n", $1 }')"
  # new listing amount
  LISTING_AMOUNT="$(echo "$LISTING_AMOUNT+$RANDOM_ORDER_NUMBER" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

  # placeOrder market ##########################################################
  PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
  ##############################################################################

  echo "$MARKET_MCS_EXECUTE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  tx_id
  cost_price
  echo "$MARKET_MCS_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
  # remove duplicates
  echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>/dev/null
fi

################################################################################

if [[ "$REFERENCE_MCS_PRICE_LAST" -gt "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  MCS_STATUS="$MCS_POSITION_STATUS :: ${MCS_POSITION_VALUE:?}"
fi

################################################################################

MCS_MARKET_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $MCS_STATUS"

################################################################################

echo "$MCS_MARKET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

################################################################################

incoming_listing
incoming_reference

################################################################################

save_orders
last_orders

################################################################################

robot_Logs_by_date

################################################################################

# END
