#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# market chaser configuration
################################################################################

# POL poloniex template - SXC southxchange template - SCE stakecube template

################################################################################

EXCHANGE_API=""            # exchange api (template)
LISTING_CURRENCY=""        # listing currency
LISTING_ALLOCATED="0.01"   # account allocated (0.01%)
REFERENCE_CURRENCY=""      # reference currency
REFERENCE_ALLOCATED="0.01" # account allocated (0.01%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
