#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API
# strategy tools
source /usr/local/bin/include/leeloo/strategies/tools

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# market chaser strategy configuration (static)
################################################################################

STRATEGY_TYPE="MCS"

# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

# log_timer
LOG_TIMER="18"

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total values
reference_total_value # calculate total values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################
# S T R A T E G Y - T R I G G E R
################################################################################

# chase and hodl the type
REFERENCE_PRICE_LAST="$(echo "$REFERENCE_PRICE" | tr -d '.' | sed 's/^0*//')"
REFERENCE_PRICE_ASK="$(echo "$REFERENCE_PRICE_ASK" | tr -d '.' | sed 's/^0*//')"

################################################################################

MARKET_MCS_EXECUTE="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Chasing Ask! $REFERENCE_PRICE_LAST > $REFERENCE_PRICE_ASK"

################################################################################

# if ask is greater than last, continue
if [[ "$REFERENCE_PRICE_ASK" -gt "$REFERENCE_PRICE_LAST" ]] &>/dev/null; then
  # price is equal
  MCS_STATUS="Market price is ok."
else
  # price is different
  MCS_STATUS="Market price needs to moon!"
  # listing market buy order
  AMOUNT_IN_REFERENCE_CURRENCY="false"
  TYPE="buy"

  # placeOrder market ##########################################################
  PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"
  ##############################################################################

  echo "$MARKET_MCS_EXECUTE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  tx_id
  cost_price
fi

################################################################################

executed_orders

################################################################################
# O P E N - P O S I T I O N S
################################################################################

open_positions

################################################################################

MARKET_MCS_POSITION="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE :: $TYPE"

################################################################################

# if last is greater than ask, continue
if [[ "$REFERENCE_PRICE_LAST" -gt "$REFERENCE_PRICE_ASK" ]] &>/dev/null; then
  echo "$MARKET_MCS_POSITION" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
fi

################################################################################

MCS_MARKET_OUTPUT="$LOG_DATE :: Strategy $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $MCS_STATUS"

################################################################################

echo "$MCS_MARKET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

################################################################################

incoming_listing
incoming_reference

################################################################################

save_orders

################################################################################

robot_Logs_by_date

################################################################################

# END
