#!/bin/bash

# All trading activities and any resulting losses or profits are solely the user's responsibility.
# This software is provided without warranties or guarantees, use it at your own risk.
# Embrace the chaos, adapt to the shadows, may the odds ever be in your favor.

################################################################################

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# market chaser configuration (dynamic)
################################################################################

# XGX xeggex template

################################################################################

EXCHANGE_API=""         # exchange api (template)
LISTING_CURRENCY=""     # listing currency
LISTING_ALLOCATED="MIN" # account allocated (MIN) use MIN for minimum possible
REFERENCE_CURRENCY=""   # reference currency

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
