#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# market chaser strategy configuration (static)
################################################################################

STRATEGY_TYPE="MCS"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################
# data
################################################################################

last_tx               # last tx
listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated

################################################################################

# chase and hodl the type
REFERENCE_MCS_PRICE_BID="$(echo "$REFERENCE_PRICE" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"
REFERENCE_MCS_PRICE_ASK="$(echo "$REFERENCE_PRICE_ASK" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"
REFERENCE_MCS_PRICE_LAST="$(echo "$REFERENCE_PRICE_LAST" | awk '{ printf "%.9f\n", $1 }' | tr -d '.' | sed 's/^0*//')"

################################################################################

if [[ -z "$REFERENCE_MCS_PRICE_BID" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_BID="0"
fi
if [[ -z "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_ASK="0"
fi
if [[ -z "$REFERENCE_MCS_PRICE_LAST" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_LAST="0"
fi

################################################################################

# low (bid)
MCS_SPREAD_LOW="$REFERENCE_PRICE"
# high (ask)
MCS_SPREAD_HIGH="$REFERENCE_PRICE_ASK"
# get difference
MCS_SPREAD_DIFF="$(echo "$MCS_SPREAD_HIGH-$MCS_SPREAD_LOW" | bc -l 2>/dev/null)"
# calculate percentage
REFERENCE_MCS_SPREAD="$(echo "100/$REFERENCE_PRICE*$MCS_SPREAD_DIFF" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

if [[ -z "$REFERENCE_MCS_SPREAD" ]] &>/dev/null; then
  REFERENCE_MCS_SPREAD="0"
fi

################################################################################

if [[ "$REFERENCE_MCS_PRICE_LAST" == "$REFERENCE_MCS_PRICE_ASK" ]] 2>>"${LOG_ERROR:?}"; then
  MCS_POSITION_VALUE="$REFERENCE_MCS_PRICE_LAST-$REFERENCE_MCS_PRICE_ASK"
  MCS_POSITION_STATUS="OK"
fi

if [[ "$REFERENCE_MCS_PRICE_LAST" -lt "$REFERENCE_MCS_PRICE_ASK" ]] 2>>"${LOG_ERROR:?}"; then
  MCS_POSITION_VALUE="$REFERENCE_MCS_PRICE_LAST>$REFERENCE_MCS_PRICE_ASK"
  MCS_POSITION_STATUS="->"
fi

if [[ "$REFERENCE_MCS_PRICE_LAST" -gt "$REFERENCE_MCS_PRICE_ASK" ]] 2>>"${LOG_ERROR:?}"; then
  MCS_POSITION_VALUE="$REFERENCE_MCS_PRICE_LAST*$REFERENCE_MCS_PRICE_ASK"
  MCS_POSITION_STATUS="<>"
fi

################################################################################

MCS_STATUS="$MCS_POSITION_STATUS ${MCS_POSITION_VALUE:?}"

################################################################################

if [[ -z "$REFERENCE_MCS_PRICE_BID" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_BID="0"
  MCS_POSITION_STATUS="><"
fi
if [[ -z "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_ASK="0"
  MCS_POSITION_STATUS="><"
fi
if [[ -z "$REFERENCE_MCS_PRICE_LAST" ]] &>/dev/null; then
  REFERENCE_MCS_PRICE_LAST="0"
  MCS_POSITION_STATUS="><"
fi
if [[ -z "$TX_ID_LAST" ]] &>/dev/null; then
  TX_ID_LAST="N/A"
fi

################################################################################

# get data
echo "Market................: $LISTING_CURRENCY/$REFERENCE_CURRENCY

MCS_Data..............: $STRATEGY_TYPE
MCS_Position..........: $MCS_POSITION_STATUS $MCS_POSITION_VALUE
MCS_Bid/Ask/Last......: $REFERENCE_MCS_PRICE_BID/$REFERENCE_MCS_PRICE_ASK/$REFERENCE_MCS_PRICE_LAST

Price.................: $LISTING_PRICE $REFERENCE_CURRENCY
Listing_Allocated.....: ${LISTING_ALLOCATED_REAL:?}%/${LISTING_ALLOCATED:?}%
Listing_Amount........: $LISTING_AMOUNT $LISTING_CURRENCY $LISTING_AMOUNT_VALUED $REFERENCE_CURRENCY
Listing_Available.....: $LISTING_AVAILABLE_BALANCE $LISTING_CURRENCY $LISTING_AVAILABLE_VALUED $REFERENCE_CURRENCY
Listing_Unconfirmed...: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY
Reference_Allocated...: ${REFERENCE_ALLOCATED_REAL:?}%/${REFERENCE_ALLOCATED:?}%
Reference_Amount......: $REFERENCE_AMOUNT $REFERENCE_CURRENCY $REFERENCE_AMOUNT_VALUED $LISTING_CURRENCY
Reference_Available...: $REFERENCE_AVAILABLE_BALANCE $REFERENCE_CURRENCY $REFERENCE_AVAILABLE_VALUED $LISTING_CURRENCY
Reference_Unconfirmed.: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY
Last_Order.txid.......: $TX_ID_LAST $TXID_AGE (${TXID_AGE_DAYS:?}d)" | column -t >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".data 2>>"${LOG_ERROR:?}"

################################################################################

open_positions

################################################################################

# executing output
MARKET_MCS_EXECUTE="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Chasing Ask! $REFERENCE_MCS_PRICE_ASK"
# position output
MARKET_MCS_POSITION="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : buy :: $LISTING_OPEN_CURRENCY :: $LISTING_OPEN_AMOUNT $REFERENCE_OPEN_AMOUNT ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE"
# no balance output
MARKET_MCS_NO_BALANCE="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_OPEN_CURRENCY :: No balance $LISTING_AMOUNT-$REFERENCE_AMOUNT"

################################################################################

# skip if data is null
if [[ ! -z "$REFERENCE_MCS_PRICE_ASK" ]] &>/dev/null; then
  # last is less than ask
  if [[ "$REFERENCE_MCS_PRICE_LAST" -lt "$REFERENCE_MCS_PRICE_ASK" ]] 2>>"${LOG_ERROR:?}"; then

    # random order amount
    RANDOM_ORDER_NUMBER=$((((RANDOM % 369369369) + 1)))
    RANDOM_ORDER_NUMBER="$(echo "$RANDOM_ORDER_NUMBER/369369" | bc -l 2>/dev/null | awk '{ printf "%.18f\n", $1 }')"
    # new listing amount
    LISTING_AMOUNT="$(echo "$LISTING_AMOUNT+$RANDOM_ORDER_NUMBER" | bc -l 2>/dev/null | awk '{ printf "%.9f\n", $1 }')"

    ############################################################################
    ############################################################################

    # if southxchange order
    if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
      # placeOrder market ######################################################
      PLACE_ORDER="$(placeOrder_market "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "false")"
      ##########################################################################
    fi
    # if xeggex order
    if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
      # xeggex decimal
      LISTING_AMOUNT="$(echo "$LISTING_AMOUNT" | awk '{ printf "%.6f\n", $1 }')"
      # CreateOrder market #####################################################
      PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "market" "$LISTING_AMOUNT" "" "true")"
      ##########################################################################
    fi

    ############################################################################
    ############################################################################

    echo "$MARKET_MCS_EXECUTE :: buy" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"
    tx_id
    cost_price
    echo "$MARKET_MCS_POSITION" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"

    # remove duplicates
    echo "$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}" | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".orders 2>>"${LOG_ERROR:?}"
  fi
fi

################################################################################

MCS_MARKET_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $MCS_STATUS ${REFERENCE_MCS_SPREAD:?}%"

################################################################################

echo "$MCS_MARKET_OUTPUT" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

################################################################################

incoming_listing
incoming_reference

################################################################################

txid_null     # txid null
save_orders   # save orders
last_orders   # last orders
backup_orders # backup orders

################################################################################

robot_Log_cleanup

################################################################################

# END
