#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# exit strategy if any error
set -e

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf
# s & k
source /usr/local/bin/include/leeloo/sMcD
# exchanges, includes functions
source /usr/local/bin/include/leeloo/strategies/templates/exchanges

################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"

################################################################################

log_date

################################################################################
# rsi strategy configuration (static)
################################################################################

STRATEGY_TYPE="RSI"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# rsi value (n)
RSI_VALUE="$(egrep "RSI_VALUE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# above this is overbought
RSI_OVERBOUGHT="$(egrep "RSI_OVERBOUGHT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# above this is oversold
RSI_OVERSOLD="$(egrep "RSI_OVERSOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# cooldown hours (hours)
RSI_COOLDOWN="$(egrep "RSI_COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# max trades a day
RSI_MAX_DAY="$(egrep "RSI_MAX_DAY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# exchange template
################################################################################

exchange_template

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated

################################################################################

# get rsi value
RSI_VALUE_RAW_NOW="$(get_rsi "$RSI_VALUE" "$LISTING_CURRENCY")"
RSI_VALUE_NOW="$(echo "$RSI_VALUE_RAW_NOW" | awk '{ print $3 }')"
RSI_VALUE_STATUS_NOW="$(echo "$RSI_VALUE_RAW_NOW" | awk '{ print $1 }')"
RSI_TIMER="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>>"${LOG_ERROR:?}" | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

################################################################################

# calculate days into seconds
RSI_COOLDOWN_HOURS="$(echo "$RSI_COOLDOWN*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"
RSI_COOLDOWN_NOW="$(echo "$RSI_TIMER/3600" | bc 2>/dev/null)"

if [[ -z "$RSI_COOLDOWN_HOURS" ]] &>/dev/null; then
  RSI_COOLDOWN_HOURS="0"
fi

if [[ -z "$RSI_COOLDOWN_NOW" ]] &>/dev/null; then
  RSI_COOLDOWN_NOW="0"
fi

if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] 2>>"${LOG_ERROR:?}"; then
  RSI_COOLDOWN_HOURS="0"
fi

################################################################################

STATUS_RSI_OUTPUT="$LOG_DATE : $EXCHANGE_API : $STRATEGY_TYPE : $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $RSI_VALUE_NOW"

################################################################################

function rsi_timer_check() {
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] 2>>"${LOG_ERROR:?}"; then
    echo "IDLE @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>>"${LOG_ERROR:?}"
  fi
}

################################################################################

function rsi_buy_order() {
  echo "BOUGHT @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>>"${LOG_ERROR:?}"
}
function rsi_sell_order() {
  echo "SOLD @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>>"${LOG_ERROR:?}"
}

################################################################################

if [[ "$RSI_COOLDOWN_NOW" -gt "$RSI_COOLDOWN_HOURS" ]] 2>>"${LOG_ERROR:?}"; then
  if [[ "$(tail -"$RSI_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>>"${LOG_ERROR:?}" | grep -c "SOLD")" -lt "$RSI_MAX_DAY" ]] 2>>"${LOG_ERROR:?}"; then
    if [[ "$(echo "$RSI_VALUE_NOW" | awk -F. '{ print $1 }')" -gt "$RSI_OVERBOUGHT" ]] 2>>"${LOG_ERROR:?}"; then
      # overbought, sell
      if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
        rsi_timer_check

        ########################################################################
        ########################################################################

        # if southxchange order
        if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "false")"
          ######################################################################
        fi
        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # CreateOrder market #################################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "market" "$LISTING_AMOUNT" "" "false")"
          ######################################################################
        fi

        ########################################################################
        ########################################################################

        rsi_sell_order
        cost_price
      elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then
        rsi_timer_check

        ########################################################################
        ########################################################################

        # if southxchange order
        if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_limit "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "false")"
          ######################################################################
        fi
        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # CreateOrder limit ##################################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "sell" "limit" "$LISTING_AMOUNT" "$LISTING_PRICE" "false")"
          ######################################################################
        fi

        ########################################################################
        ########################################################################

        rsi_sell_order
        cost_price
      fi
    fi
  fi
fi

################################################################################

if [[ "$RSI_COOLDOWN_NOW" -gt "$RSI_COOLDOWN_HOURS" ]] 2>>"${LOG_ERROR:?}"; then
  if [[ "$(tail -"$RSI_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "BOUGHT")" -lt "$RSI_MAX_DAY" ]] 2>>"${LOG_ERROR:?}"; then
    if [[ "$(echo "$RSI_VALUE_NOW" | awk -F. '{ print $1 }')" -lt "$RSI_OVERSOLD" ]] 2>>"${LOG_ERROR:?}"; then
      # oversold, buy
      if [[ "$MARKET_LIMIT" == "market" ]] 2>>"${LOG_ERROR:?}"; then
        rsi_timer_check

        ########################################################################
        ########################################################################

        # if southxchange order
        if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_market "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "true")"
          ######################################################################
        fi
        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # CreateOrder market #################################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "market" "$REFERENCE_AMOUNT" "" "true")"
          ######################################################################
        fi

        ########################################################################
        ########################################################################

        rsi_buy_order
        cost_price
      elif [[ "$MARKET_LIMIT" == "limit" ]] 2>>"${LOG_ERROR:?}"; then
        rsi_timer_check

        ########################################################################
        ########################################################################

        # if southxchange order
        if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
          # placeOrder market ##################################################
          PLACE_ORDER="$(placeOrder_limit "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "true")"
          ######################################################################
        fi
        # if xeggex order
        if [[ "$EXCHANGE_API" == "XGX" ]] &>/dev/null; then
          # CreateOrder limit ##################################################
          PLACE_ORDER="$(CreateOrder "" "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "buy" "limit" "$REFERENCE_AMOUNT" "$REFERENCE_PRICE" "true")"
          ######################################################################
        fi

        ########################################################################
        ########################################################################

        rsi_buy_order
        cost_price
      fi
    fi
  fi
fi

################################################################################

echo "$STATUS_RSI_OUTPUT :: $RSI_VALUE_STATUS_NOW :: $RSI_COOLDOWN_NOW/${RSI_COOLDOWN_HOURS:?}h :: $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>>"${LOG_ERROR:?}"

################################################################################

open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################

last_tx       # last tx
txid_null     # txid null
save_orders   # save orders
last_orders   # last orders
backup_orders # backup orders

################################################################################

robot_Log_cleanup

################################################################################

# END
