#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# rsi strategy configuration
################################################################################

# POL poloniex template - SXC southxchange template - SCE stakecube template

################################################################################

EXCHANGE_API=""           # exchange api (template)
MARKET_LIMIT="market"     # market or limit order
LISTING_CURRENCY=""       # listing currency
LISTING_ALLOCATED="100"   # account allocated (100%)
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_ALLOCATED="100" # account allocated (100%)
RSI_VALUE="14"            # rsi value (14)
RSI_OVERBOUGHT="70"       # above this is overbought
RSI_OVERSOLD="30"         # above this is oversold
RSI_COOLDOWN="1"          # execute cooldown (days)
RSI_MAX_DAY="10"          # max trades a day (10)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
