#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/sMcD

# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
LOG_DATE="$(date +"%d/%m.%y-%H:%M:%S")"

################################################################################
# rsi strategy configuration (static)
################################################################################

STRATEGY_TYPE="RSI"

# exchange template
EXCHANGE_API="$(egrep "EXCHANGE_API=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# market or limit order
MARKET_LIMIT="$(egrep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# listing currency
LISTING_CURRENCY="$(egrep "LISTING_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
LISTING_ALLOCATED="$(egrep "LISTING_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# reference currency
REFERENCE_CURRENCY="$(egrep "REFERENCE_CURRENCY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# account allocated (n%)
REFERENCE_ALLOCATED="$(egrep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# rsi value (n)
RSI_VALUE="$(egrep "RSI_VALUE=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# above this is overbought
RSI_OVERBOUGHT="$(egrep "RSI_OVERBOUGHT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# above this is oversold
RSI_OVERSOLD="$(egrep "RSI_OVERSOLD=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# cooldown hours (hours)
RSI_COOLDOWN="$(egrep "RSI_COOLDOWN=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"
# max trades a day
RSI_MAX_DAY="$(egrep "RSI_MAX_DAY=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"

################################################################################
# strategy templates
################################################################################

# poloniex template
if [[ "$EXCHANGE_API" == "POL" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/poloniex
fi
# southxchange template
if [[ "$EXCHANGE_API" == "SXC" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/southxchange
fi
# stakecube template
if [[ "$EXCHANGE_API" == "SCE" ]] &>/dev/null; then
  source /usr/local/bin/include/leeloo/strategies/templates/stakecube
fi

if [[ -z "$EXCHANGE_API" ]] &>/dev/null; then
  echo "$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: No EXCHANGE_API= set in configuration!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null
  exit
fi

################################################################################
# data
################################################################################

listing_data          # get available listing data
reference_data        # get available reference data
listing_total_value   # calculate total listing values
reference_total_value # calculate total reference values
listing_allocated     # total listing allocated
reference_allocated   # total reference allocated
last_tx               # last tx

################################################################################

# get rsi value
RSI_VALUE_RAW_NOW="$(get_rsi "$RSI_VALUE" "$LISTING_CURRENCY")"
RSI_VALUE_NOW="$(echo "$RSI_VALUE_RAW_NOW" | awk '{ print $3 }')"
RSI_VALUE_STATUS_NOW="$(echo "$RSI_VALUE_RAW_NOW" | awk '{ print $1 }')"
RSI_TIMER="$(stat -c '%Y' "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | while read lastedit; do echo "$(($(date +%s) - $lastedit))"; done)"

################################################################################

# calculate days into seconds
RSI_COOLDOWN_HOURS="$(echo "$RSI_COOLDOWN*86400" | bc 2>/dev/null | awk -F. '{ print $1 }')"
RSI_COOLDOWN_NOW="$(echo "$RSI_TIMER/3600" | bc 2>/dev/null)"

if [[ -z "$RSI_COOLDOWN_HOURS" ]] &>/dev/null; then
  RSI_COOLDOWN_HOURS="0"
fi

if [[ -z "$RSI_COOLDOWN_NOW" ]] &>/dev/null; then
  RSI_COOLDOWN_NOW="0"
fi

if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] &>/dev/null; then
  RSI_COOLDOWN_HOURS="0"
fi

################################################################################

STATUS_RSI_OUTPUT="$LOG_DATE :: $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: $RSI_VALUE_NOW"

################################################################################

function rsi_timer_check() {
  if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status ]] &>/dev/null; then
    echo "IDLE @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
  fi
}

################################################################################

function rsi_buy_order() {
  echo "BOUGHT @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
}
function rsi_sell_order() {
  echo "SOLD @ $LISTING_PRICE / $REFERENCE_PRICE :: $(date | xargs)" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null
}

################################################################################

if [[ "$RSI_COOLDOWN_NOW" -gt "$RSI_COOLDOWN_HOURS" ]] &>/dev/null; then
  if [[ "$(tail -"$RSI_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status 2>/dev/null | grep -c "SOLD")" -lt "$RSI_MAX_DAY" ]] &>/dev/null; then
    if [[ "$(echo "$RSI_VALUE_NOW" | awk -F. '{ print $1 }')" -gt "$RSI_OVERBOUGHT" ]] &>/dev/null; then
      # overbought, sell
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        rsi_timer_check
        PLACE_ORDER="$(placeOrder_market "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "false")"
        rsi_sell_order
        cost_price
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        rsi_timer_check
        PLACE_ORDER="$(placeOrder_limit "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "false")"
        rsi_sell_order
        cost_price
      fi
    fi
  fi
fi

################################################################################

if [[ "$RSI_COOLDOWN_NOW" -gt "$RSI_COOLDOWN_HOURS" ]] &>/dev/null; then
  if [[ "$(tail -"$RSI_MAX_DAY" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".status | grep -c "BOUGHT")" -lt "$RSI_MAX_DAY" ]] &>/dev/null; then
    if [[ "$(echo "$RSI_VALUE_NOW" | awk -F. '{ print $1 }')" -lt "$RSI_OVERSOLD" ]] &>/dev/null; then
      # oversold, buy
      if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
        rsi_timer_check
        PLACE_ORDER="$(placeOrder_market "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "true")"
        rsi_buy_order
        cost_price
      elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then
        rsi_timer_check
        PLACE_ORDER="$(placeOrder_limit "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "true")"
        rsi_buy_order
        cost_price
      fi
    fi
  fi
fi

################################################################################

echo "$STATUS_RSI_OUTPUT :: $RSI_VALUE_STATUS_NOW :: $RSI_COOLDOWN_NOW/${RSI_COOLDOWN_HOURS:?}h :: $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null

################################################################################

open_positions

################################################################################

incoming_listing
incoming_reference

################################################################################

save_orders
last_orders
sxc_backup_orders

################################################################################

robot_Log_cleanup

################################################################################

# END
