#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# sell strategy configuration
################################################################################

STRATEGY_REFERENCE_STATUS="false" # reference status
STRATEGY_ORDER_TYPE="sell"        # market or limit order
# listing
STRATEGY_LISTING_CURRENCY=""     # listing currency
STRATEGY_LISTING_TRIGGER="1"     # listing trigger (amount)
STRATEGY_LISTING_ALLOCATED="100" # account allocated (100%)
# reference
STRATEGY_REFERENCE_CURRENCY="BTC"  # reference currency
STRATEGY_REFERENCE_TRIGGER="false" # listing trigger (amount)
STRATEGY_REFERENCE_ALLOCATED="100" # account allocated (100%)

################################################################################
# strategy
################################################################################

# get available listing balance
LISTING_AVAILABLE_BALANCE="$(grep "$STRATEGY_LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $2 }')"
STRATEGY_LISTING_AMOUNT="$(echo "$(echo "$STRATEGY_LISTING_ALLOCATED/100" | bc -l)*$LISTING_AVAILABLE_BALANCE" | bc -l)"

# get available reference balance
REFERENCE_AVAILABLE_BALANCE="$(grep "$STRATEGY_REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $2 }')"
STRATEGY_REFERENCE_AMOUNT="$(echo "$(echo "$STRATEGY_REFERENCE_ALLOCATED/100" | bc -l)*$REFERENCE_AVAILABLE_BALANCE" | bc -l)"

################################################################################

if [[ "$STRATEGY_REFERENCE_STATUS" == "false" ]] &>/dev/null; then
  # balance greater or equal against trigger value, continue
  if [[ "$(echo "$STRATEGY_LISTING_AMOUNT" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$STRATEGY_LISTING_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    # sell listing currency if triggered
    PLACE_ORDER="$(placeOrder_market "$STRATEGY_ORDER_TYPE" "$STRATEGY_LISTING_CURRENCY" "$STRATEGY_LISTING_AMOUNT" "$STRATEGY_REFERENCE_CURRENCY" "$STRATEGY_REFERENCE_AMOUNT")"
    echo "${DATE:?} :: Strategy $STRATEGY_ORDER_TYPE ::  Market Order :: $STRATEGY_LISTING_CURRENCY $STRATEGY_LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
  fi
fi

################################################################################

if [[ "$STRATEGY_REFERENCE_STATUS" == "true" ]] &>/dev/null; then
  # balance greater or equal against trigger value, continue
  if [[ "$(echo "$STRATEGY_REFERENCE_AMOUNT" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$STRATEGY_REFERENCE_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
    # sell reference currency if triggered
    PLACE_ORDER="$(placeOrder_market "$STRATEGY_ORDER_TYPE" "$STRATEGY_LISTING_CURRENCY" "$STRATEGY_REFERENCE_AMOUNT" "$STRATEGY_REFERENCE_CURRENCY" "$STRATEGY_LISTING_AMOUNT")"
    echo "${DATE:?} :: Strategy $STRATEGY_ORDER_TYPE ::  Market Order :: $STRATEGY_REFERENCE_CURRENCY $STRATEGY_REFERENCE_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/broker.log
  fi
fi

# END
