#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# snp strategy configuration
################################################################################

MARKET_LIMIT="market" # market or limit order

# hodl
HODL_CURRENCY="USDT" # hodl currency
HODL_ALLOCATED="10"  # account allocated (10%)

# coins
HODL_COINS="100" # amount of coins (100)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"
bash "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".strategy

# END
