#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

DATE="$(date | xargs)"
# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"

################################################################################
# snp strategy configuration (static)
################################################################################

STRATEGY_TYPE="Sniper"

# type
MARKET_LIMIT="$(grep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

# currency
HODL_CURRENCY="$(grep "HODL_CURRENCY=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # hodl currency
HODL_ALLOCATED="$(grep "HODL_ALLOCATED=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

# coins
HODL_COINS="$(grep "HODL_COINS=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

################################################################################
# strategy
################################################################################

function worst_drop {
  # get top n coins that have dropped significantly
  cat "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null | sort -k5 -n -r | grep "/$HODL_CURRENCY" | tail -"$HODL_COINS" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market
}

# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market 2>/dev/null)))" 2>/dev/null)" -gt "900" ]] &>/dev/null; then
  worst_drop
fi
# update data if missing
if [[ ! -f "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market ]] &>/dev/null; then
  worst_drop
fi
# update data if less than n lines
if [[ "$(wc -l "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market | awk '{ print $1 }')" -lt "3" ]] &>/dev/null; then
  worst_drop
fi

echo "$DATE :: Strategy $STRATEGY_TYPE :: Looking :: $HODL_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot.log

# target random coin from list
SNIPER_TARGET="$(sort -R "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market | head -1 | awk -F/ '{ print $1 }')"

get_rsi 14 "$SNIPER_TARGET" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target

SNIPER_STATUS="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target | awk '{ print $1 }')"
SNIPER_VALUE="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target | awk '{ print $5 }' | awk -F. '{ print $1 }')"
echo "$DATE :: Strategy $STRATEGY_TYPE :: Target $SNIPER_TARGET :: $SNIPER_STATUS $SNIPER_VALUE" >>"${LOG_DIR:?}"/leeloo/robot.log

# list of no data coins/tokens
if [[ "$SNIPER_VALUE" -eq "0" ]] &>/dev/null; then
  echo "$SNIPER_TARGET :: No data :: $SNIPER_VALUE" >>"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".nodata
  HODL_NODATA="$(echo "$HODL_COINS/3" | bc)"
  echo "$(tail -"$HODL_NODATA" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".nodata)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".nodata
fi

cat "${LOG_DIR:?}"/leeloo/robot.log 2>/dev/null | egrep -o "Sniper :: Target [aA0-zZ9]+ :: [aA0-zZ9]+" | awk '{ print $4,$6 }' >>"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe
echo "$(tail -"$HODL_COINS" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe 2>/dev/null | awk '!a[$0]++')" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe
# disregard no data coins/tokens
echo "$(grep -v "$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".nodata | awk '{ print $1 }')" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe
echo "$(grep -v "$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".nodata | awk '{ print $1 }' | egrep -v "::|D")" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market

grep -c "Oversold" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".oversold
grep -c "Neutral" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".neutral
grep -c "Overbought" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".overbought

TOTAL="$(wc -l "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe | awk '{ print $1 }')"
OVERSOLD="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".oversold)"
NEUTRAL="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".neutral)"
OVERBOUGHT="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".overbought)"

echo "$DATE :: Strategy $STRATEGY_TYPE :: Total $TOTAL Oversold $OVERSOLD Neutral $NEUTRAL Overbought $OVERBOUGHT" >>"${LOG_DIR:?}"/leeloo/robot.log

################################################################################
# targeting
################################################################################

# get oversold targets
cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".universe 2>/dev/null | grep "Oversold" | awk '{ print $1 }' >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".insight

# get target in sight
TARGET_IN_SIGHT="$(tail -1 "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".insight)"

if [[ ! "$TARGET_IN_SIGHT" == "$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | awk '{ print $1 }')" ]] &>/dev/null; then

  TARGET_CHECK="$(get_rsi 14 "$TARGET_IN_SIGHT")"
  TARGET_STATUS="$(echo "$TARGET_CHECK" | awk '{ print $1 }')"
  TARGET_VALUE="$(echo "$TARGET_CHECK" | awk '{ print $5 }' | awk -F. '{ print $1 }')"

  echo "$DATE :: Strategy $STRATEGY_TYPE :: Sniping! $TARGET_IN_SIGHT :: $TARGET_STATUS :: $TARGET_VALUE" >>"${LOG_DIR:?}"/leeloo/robot.log

  # if still below oversold, take target down
  if [[ "$TARGET_VALUE" -lt "30" ]] &>/dev/null; then

    # buy order ################################################################

    TYPE="buy"
    REFERENCE_STATUS="false"
    SNIPER_MARKET="$(egrep "$TARGET_IN_SIGHT/$HODL_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $1 }' | tr -d ':')"
    LISTING_CURRENCY="$(echo "$SNIPER_MARKET" | awk -F/ '{ print $1 }')"
    REFERENCE_CURRENCY="$(echo "$SNIPER_MARKET" | awk -F/ '{ print $2 }')"
    LISTING_AVAILABLE_BALANCE="$(grep "$HODL_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
    LISTING_AMOUNT="$(echo "$(echo "$HODL_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
    LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $3 }' | head -1)"

    if [[ -z "$LISTING_AMOUNT" ]] &>/dev/null; then
      LISTING_AMOUNT="0"
    fi
    if [[ -z "$LISTING_PRICE" ]] &>/dev/null; then
      LISTING_PRICE="0"
    fi

    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

      # placeorder market
      PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"

      echo "$DATE :: Strategy $STRATEGY_TYPE :: $TYPE $TARGET_IN_SIGHT @ $LISTING_PRICE :: $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log

      if [[ "$(grep "$TARGET_IN_SIGHT" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | wc -l)" -eq "0" ]]; then
        echo "$TARGET_IN_SIGHT Price $LISTING_PRICE Amount $LISTING_AMOUNT" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling
      fi

      # limit
    elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

      # placeorder limit
      PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"

      echo "$DATE :: Strategy $STRATEGY_TYPE :: $TYPE $TARGET_IN_SIGHT @ $LISTING_PRICE :: $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log

      if [[ "$(grep "$TARGET_IN_SIGHT" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | wc -l)" -eq "0" ]]; then
        echo "$TARGET_IN_SIGHT Price $LISTING_PRICE Amount $LISTING_AMOUNT" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling
      fi

    fi
  fi
fi

# sell order #################################################################

SNIPER_VICTIM="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | awk '{ print $1 }')"
LISTING_PRICE="$(grep "$SNIPER_VICTIM/$HODL_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $3 }' | head -1)"
SNIPER_PRICE="$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | awk '{ print $3 }')"
SNIPER_GAINS="$(echo "100/$LISTING_PRICE*$SNIPER_PRICE" | bc -l | awk '{ printf "%.2f\n", $1 }')"
SNIPED_BALANCE="$(echo "$SNIPER_VICTIM" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling | awk '{ print $5 }')"
REAL_GAINS="$(echo "$SNIPER_GAINS-100" | bc -l | awk '{ printf "%.2f\n", $1 }')"

echo "$SNIPER_VICTIM $SNIPED_BALANCE ${REAL_GAINS:?}%" >"${LOG_DIR:?}"/leeloo/robot.hodl

# sell if any profit
if [[ "$(echo "$SNIPER_GAINS" | awk -F. '{ print $1 }')" -gt "100" ]] &>/dev/null; then

  TYPE="sell"
  REFERENCE_STATUS="true"
  SNIPER_MARKET="$(egrep "$TARGET_IN_SIGHT/$HODL_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $1 }' | tr -d ':')"
  LISTING_CURRENCY="$(echo "$SNIPER_MARKET" | awk -F/ '{ print $1 }')"
  REFERENCE_CURRENCY="$(echo "$SNIPER_MARKET" | awk -F/ '{ print $2 }')"
  REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$HODL_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $3 }' | head -1)"

  if [[ -z "$REFERENCE_AMOUNT" ]] &>/dev/null; then
    REFERENCE_AMOUNT="0"
  fi
  if [[ -z "$REFERENCE_PRICE" ]] &>/dev/null; then
    REFERENCE_PRICE="0"
  fi

  if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then

    # placeorder market
    PLACE_ORDER="$(placeOrder_market "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"

    echo "$DATE :: Strategy $STRATEGY_TYPE :: $TYPE :: $TARGET_IN_SIGHT @ $LISTING_PRICE :: $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log

    # clean up hodling list
    echo "$(grep -v "$TARGET_IN_SIGHT" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling

    # limit
  elif [[ "$MARKET_LIMIT" == "limit" ]] &>/dev/null; then

    # placeorder limit
    PLACE_ORDER="$(placeOrder_limit "$TYPE" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "$AMOUNT_IN_REFERENCE_CURRENCY")"

    echo "$DATE :: Strategy $STRATEGY_TYPE :: $TYPE :: $TARGET_IN_SIGHT @ $LISTING_PRICE :: $LISTING_AMOUNT :: $PLACE_ORDER" >>"${LOG_DIR:?}"/leeloo/robot.log

    # clean up hodling list
    echo "$(grep -v "$TARGET_IN_SIGHT" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".hodling

  fi

  echo "$DATE :: Strategy $STRATEGY_TYPE :: Reloading! $TARGET_IN_SIGHT :: $SNIPER_PRICE :: $LISTING_PRICE :: ${REAL_GAINS:?}%" >>"${LOG_DIR:?}"/leeloo/robot.log
fi

# END
