#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

DATE="$(date | xargs)"
# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"

################################################################################
# snp strategy configuration (static)
################################################################################

STRATEGY_TYPE="Sniper"

# type
MARKET_LIMIT="$(grep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

# currency
HODL_CURRENCY="$(grep "HODL_CURRENCY=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"   # hodl currency
HODL_ALLOCATED="$(grep "HODL_ALLOCATED=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

# coins
HODL_COINS="$(grep "HODL_COINS=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

################################################################################
# strategy
################################################################################

################################################################################

# END
