#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

################################################################################

# configuration
source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# sniper strategy configuration (dynamic)
################################################################################

# XGX xeggex template

################################################################################

EXCHANGE_API=""           # exchange api (template)
MARKET_LIMIT="market"     # market or limit order
REFERENCE_CURRENCY=""     # reference currency
REFERENCE_ALLOCATED="0.1" # account allocated (0.1%)
SNP_RST_LIMIT=""          # minimum rsi before buying

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $1 }')"
bash "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".strategy

# END
