#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf

################################################################################
# snp strategy configuration
################################################################################

MARKET_LIMIT="market" # market or limit order

# hodl
HODL_CURRENCY="USDT"     # hodl currency
REFERENCE_ALLOCATED="90" # account allocated (90%)

################################################################################
# strategy
################################################################################

# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"
bash "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".strategy

# END
