#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

source /usr/local/bin/include/leeloo/broker.conf
source /usr/local/bin/include/leeloo/functions
# southxchange api
source /usr/local/bin/include/leeloo/api/southxchange/private_API
source /usr/local/bin/include/leeloo/api/southxchange/public_API

# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

DATE="$(date | xargs)"
# get strategy id.config, run strategy
BASENAME_STRATEGY="$(basename "$0" | awk -F. '{ print $2 }')"

################################################################################
# snp strategy configuration (static)
################################################################################

STRATEGY_TYPE="Sniper"

# type
MARKET_LIMIT="$(grep "MARKET_LIMIT=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # market or limit order

# currency
HODL_CURRENCY="$(grep "HODL_CURRENCY=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')"             # hodl currency
REFERENCE_ALLOCATED="$(grep "REFERENCE_ALLOCATED=" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # account allocated (90%)

################################################################################
# strategy
################################################################################

function worst_drop {
  # get top n coins that have dropped significantly
  cat "${LOG_DIR:?}"/leeloo/southxchange/market 2>/dev/null | sort -k5 -n -r | grep "/$HODL_CURRENCY" | tail -30 >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market
}

# update data every n seconds
if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market 2>/dev/null)))" 2>/dev/null)" -gt "900" ]] &>/dev/null; then
  worst_drop
fi
# update data if missing
if [[ ! -f "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market ]] &>/dev/null; then
  worst_drop
fi
# update data if empty
if [[ ! -s "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market ]] &>/dev/null; then
  worst_drop
fi

echo "$DATE :: Strategy $STRATEGY_TYPE :: Looking :: $HODL_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot.log

# target random coin from list
SNIPER_TARGET="$(sort -R "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market | head -1 | awk -F/ '{ print $1 }')"
echo "$DATE :: Strategy $STRATEGY_TYPE :: Target $SNIPER_TARGET" >>"${LOG_DIR:?}"/leeloo/robot.log

get_rsi 14 "$SNIPER_TARGET" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target

if [[ "$(egrep "null|error" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target | wc -l)" -gt "0" ]] &>/dev/null; then
  echo "$DATE :: Strategy $STRATEGY_TYPE :: Ignoring $SNIPER_TARGET." >>"${LOG_DIR:?}"/leeloo/robot.log
  echo "$(grep -v "$SNIPER_TARGET" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".target)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".ignored
fi

echo "$(grep -v "$(cat "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".ignored)" "${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market)" >"${SYS_DIR:?}"/robot/snp."$BASENAME_STRATEGY".market

# END
