#!/bin/bash

# shellcheck disable=SC2034  # Unused variables left for readability

# indicators
source /usr/local/bin/include/leeloo/indicators/rsi
source /usr/local/bin/include/leeloo/indicators/ema

################################################################################

function listing_data() {
  # get available listing data
  LISTING_AVAILABLE_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
  LISTING_UNCONFIRMED_BALANCE="$(grep "$LISTING_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $4 }' | awk '{ printf "%.8f\n", $1 }')"
  LISTING_AMOUNT="$(echo "$(echo "$LISTING_ALLOCATED/100" | bc -l 2>/dev/null)*$LISTING_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  LISTING_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"
  LISTING_AMOUNT_VALUED="$(echo "$LISTING_AMOUNT*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  LISTING_AVAILABLE_VALUED="$(echo "$LISTING_AVAILABLE_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  LISTING_UNCONFIRMED_VALUED="$(echo "$LISTING_UNCONFIRMED_BALANCE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"

  if [[ -z "$LISTING_AVAILABLE_BALANCE" ]] &>/dev/null; then
    LISTING_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT" ]] &>/dev/null; then
    LISTING_AMOUNT="0.00000000"
  fi
  if [[ -z "$LISTING_PRICE" ]] &>/dev/null; then
    LISTING_PRICE="0.00000000"
  fi
  if [[ -z "$LISTING_AMOUNT_VALUED" ]] &>/dev/null; then
    LISTING_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_AVAILABLE_VALUED" ]] &>/dev/null; then
    LISTING_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$LISTING_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    LISTING_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function reference_data() {
  # get available reference data
  REFERENCE_AVAILABLE_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $3 }' | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_UNCONFIRMED_BALANCE="$(grep "$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/balances | awk '{ print $4 }' | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_AMOUNT="$(echo "$(echo "$REFERENCE_ALLOCATED/100" | bc -l 2>/dev/null)*$REFERENCE_AVAILABLE_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_PRICE="$(grep "$LISTING_CURRENCY/$REFERENCE_CURRENCY" "${LOG_DIR:?}"/leeloo/southxchange/market | awk '{ print $2 }')"
  REFERENCE_AMOUNT_VALUED="$(echo "$REFERENCE_AMOUNT/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_AVAILABLE_VALUED="$(echo "$REFERENCE_AVAILABLE_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_UNCONFIRMED_VALUED="$(echo "$REFERENCE_UNCONFIRMED_BALANCE/$REFERENCE_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"

  if [[ -z "$REFERENCE_AVAILABLE_BALANCE" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_BALANCE" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_BALANCE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT" ]] &>/dev/null; then
    REFERENCE_AMOUNT="0.00000000"
  fi
  if [[ -z "$REFERENCE_PRICE" ]] &>/dev/null; then
    REFERENCE_PRICE="0.00000000"
  fi
  if [[ -z "$REFERENCE_AMOUNT_VALUED" ]] &>/dev/null; then
    REFERENCE_AMOUNT_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_AVAILABLE_VALUED" ]] &>/dev/null; then
    REFERENCE_AVAILABLE_VALUED="0.00000000"
  fi
  if [[ -z "$REFERENCE_UNCONFIRMED_VALUED" ]] &>/dev/null; then
    REFERENCE_UNCONFIRMED_VALUED="0.00000000"
  fi
}

################################################################################

function listing_total_value() {
  # calculate total values
  LISTING_TOTAL="$(echo "$LISTING_AVAILABLE_BALANCE+$LISTING_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  LISTING_TOTAL_VALUED="$(echo "$LISTING_AVAILABLE_VALUED+$LISTING_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
}

################################################################################

function reference_total_value() {
  # calculate total values
  REFERENCE_TOTAL="$(echo "$REFERENCE_AVAILABLE_BALANCE+$REFERENCE_UNCONFIRMED_BALANCE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
  REFERENCE_TOTAL_VALUED="$(echo "$REFERENCE_AVAILABLE_VALUED+$REFERENCE_UNCONFIRMED_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')"
}

################################################################################

function listing_allocated() {
  # total listing allocated
  LISTING_ALLOCATED_REAL="$(echo "100/$REFERENCE_TOTAL*$LISTING_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$LISTING_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="100"
  fi
  if [[ -z "$LISTING_ALLOCATED_REAL" ]] &>/dev/null; then
    LISTING_ALLOCATED_REAL="0.00"
  fi
}

################################################################################

function reference_allocated() {
  # total reference allocated
  REFERENCE_ALLOCATED_REAL="$(echo "100/$LISTING_TOTAL*$REFERENCE_TOTAL_VALUED" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"

  if [[ "$(echo "$REFERENCE_ALLOCATED_REAL" | awk -F. '{ print $1 }')" -gt "99" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="100"
  fi
  if [[ -z "$REFERENCE_ALLOCATED_REAL" ]] &>/dev/null; then
    REFERENCE_ALLOCATED_REAL="0.00"
  fi
}

################################################################################

function last_tx() {
  # last tx
  TX_ID_LAST="$(cat "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid 2>/dev/null)"
}

################################################################################

function listing_trigger() {
  # listing trigger
  if [[ "$(echo "$LISTING_TRIGGER" | egrep "[0-9]+" | tr -d '.' | sed 's/^0*//' | wc -l)" -gt "0" ]] &>/dev/null; then
    if [[ "$(echo "$LISTING_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$LISTING_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
      TRIGGER_L="1"
    else
      TRIGGER_L="0"
    fi
  fi
  if [[ -z "$TRIGGER_L" ]] &>/dev/null; then
    TRIGGER_L="0"
  fi
}

################################################################################

function reference_trigger() {
  # reference trigger
  if [[ "$(echo "$REFERENCE_TRIGGER" | egrep "[0-9]+" | tr -d '.' | sed 's/^0*//' | wc -l)" -gt "0" ]] &>/dev/null; then
    if [[ "$(echo "$REFERENCE_AVAILABLE_BALANCE" | tr -d '.' | sed 's/^0*//')" -ge "$(echo "$REFERENCE_TRIGGER" | tr -d '.' | sed 's/^0*//')" ]] &>/dev/null; then
      TRIGGER_R="1"
    else
      TRIGGER_R="0"
    fi
  fi
  if [[ -z "$TRIGGER_R" ]] &>/dev/null; then
    TRIGGER_R="0"
  fi
}

################################################################################

function total_trigger() {
  # get total trigger
  TOTAL_TRIGGER="$(echo "$TRIGGER_L+$TRIGGER_R" | bc 2>/dev/null)"
  if [[ -z "$TOTAL_TRIGGER" ]] &>/dev/null; then
    TOTAL_TRIGGER="0"
  fi
}

################################################################################

function cost_price() {
  echo "$LISTING_AVAILABLE_VALUED" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".cost
  echo "$LISTING_PRICE" >"${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".price
}

################################################################################

function tx_id {
  echo "$(echo "$PLACE_ORDER" | tr -d '"')" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".txid
}

################################################################################

function incoming_listing() {
  # incoming listing
  if [[ "$(echo "$LISTING_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ ! "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep "Incoming" | wc -l)" -gt "0" ]] &>/dev/null; then
      echo "$LOG_DATE :: Incoming $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: info :: $LISTING_UNCONFIRMED_BALANCE $LISTING_CURRENCY $LISTING_UNCONFIRMED_VALUED $REFERENCE_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    fi
  fi
}

################################################################################

function incoming_reference() {
  # incoming reference
  if [[ "$(echo "$REFERENCE_UNCONFIRMED_BALANCE" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    if [[ ! "$(tail -"$LOG_TIMER" "${LOG_DIR:?}"/leeloo/robot.log | grep "Incoming" | wc -l)" -gt "0" ]] &>/dev/null; then
      echo "$LOG_DATE :: Incoming $STRATEGY_TYPE :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: info :: $REFERENCE_UNCONFIRMED_BALANCE $REFERENCE_CURRENCY $REFERENCE_UNCONFIRMED_VALUED $LISTING_CURRENCY" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    fi
  fi
}

################################################################################

function open_positions() {

  ##############################################################################

  # currency
  LISTING_OPEN_CURRENCY="$LISTING_CURRENCY/$REFERENCE_CURRENCY"

  ##############################################################################

  # amount
  LISTING_OPEN_AMOUNT="$LISTING_AVAILABLE_BALANCE"

  ##############################################################################

  # make sure files has data
  until egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances &>/dev/null; do
    until egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/market &>/dev/null; do
      sleep 1
    done
    sleep 1
  done

  OPEN_POSITION_COST="${SYS_DIR:?}/robot/open.$BASENAME_STRATEGY.cost"
  OPEN_POSITION_PRICE="${SYS_DIR:?}/robot/open.$BASENAME_STRATEGY.price"

  if [ ! -f "$OPEN_POSITION_COST" ] &>/dev/null; then
    echo "$LISTING_AVAILABLE_VALUED" >"$OPEN_POSITION_COST"
  fi

  if [ ! -f "$OPEN_POSITION_PRICE" ] &>/dev/null; then
    echo "$LISTING_PRICE" >"$OPEN_POSITION_PRICE"
  fi

  LISTING_OPEN_BALANCE="$(cat "$OPEN_POSITION_COST" 2>/dev/null)"
  LISTING_OPEN_PRICE="$(cat "$OPEN_POSITION_PRICE" 2>/dev/null)"

  ##############################################################################

  # result
  LISTING_OPEN_RESULT="$(echo "$(echo "100/$LISTING_OPEN_PRICE*$LISTING_PRICE" | bc -l 2>/dev/null | awk '{ printf "%.8f\n", $1 }')-100" | bc -l | awk '{ printf "%.2f\n", $1 }')"
  if [[ -z "$LISTING_OPEN_RESULT" ]] &>/dev/null; then
    LISTING_OPEN_RESULT="0.00"
  fi

  ##############################################################################

  # age (seconds)
  if [[ -f "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".price ]] &>/dev/null; then
    LISTING_OPEN_AMOUNT_SECONDS="$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".price 2>/dev/null)))" 2>/dev/null)"
    if [[ -z "$LISTING_OPEN_AMOUNT_SECONDS" ]] &>/dev/null; then
      LISTING_OPEN_AMOUNT_SECONDS="0"
    fi
    LISTING_OPEN_AMOUNT_AGE=$(printf '%dh:%dm:%ds\n' $(("$LISTING_OPEN_AMOUNT_SECONDS/3600")) $(("$LISTING_OPEN_AMOUNT_SECONDS%3600/60")) $(("$LISTING_OPEN_AMOUNT_SECONDS%60")))
  fi

  ##############################################################################

  # make sure file has data
  until egrep "[0-9]+.[0-9]+" "${LOG_DIR:?}"/leeloo/southxchange/balances &>/dev/null; do
    sleep 1
  done

  # is this an open position?
  if [[ "$(echo "$LISTING_OPEN_AMOUNT" | awk -F. '{ print $2 }' | sed 's/^0*//')" -gt "0" ]] &>/dev/null; then
    # currency amount cost result age
    echo "$OPEN_STRATEGY $LISTING_OPEN_CURRENCY $LISTING_OPEN_AMOUNT $LISTING_OPEN_BALANCE ${LISTING_OPEN_RESULT:?}% $LISTING_OPEN_AMOUNT_AGE" >>"${SYS_DIR:?}"/robot/pool
    echo "$(cat "${SYS_DIR:?}"/robot/pool 2>/dev/null | column -t)" >"${SYS_DIR:?}"/robot/pool
  else
    rm "${SYS_DIR:?}"/robot/open."$BASENAME_STRATEGY".* &>/dev/null
  fi
}

################################################################################

function rogue_profit() {
  # rogue profit using rsi

  ROGUE_TIMER="3600"    # 1 hour cooldown
  ROGUE_AMOUNT="0.0369" # amount % to be used

  ##############################################################################

  function rogue_data() {
    echo "L $LISTING_CURRENCY $(get_rsi 14 "$LISTING_CURRENCY")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue
    sleep 1
    echo "R $REFERENCE_CURRENCY $(get_rsi 14 "$REFERENCE_CURRENCY")" >>"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue
  }

  ##############################################################################

  function rogue_stealth() {
    ROGUE_LRSI=$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | awk -F. '{ print $1 }')
    ROGUE_RRSI=$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | awk -F. '{ print $1 }')
    if [[ -z "$ROGUE_LRSI" ]] &>/dev/null; then
      ROGUE_LRSI="Z"
    fi
    if [[ -z "$ROGUE_RRSI" ]] &>/dev/null; then
      ROGUE_RRSI="Z"
    fi
    echo "$LOG_DATE :: Strategy RGP :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: ($ROGUE_LRSI $ROGUE_RRSI) :: Rogue in Stealth mode.." >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  }

  ##############################################################################

  function rogue_vanish() {
    echo "$LOG_DATE :: Strategy RGP :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Rogue used Vanishing Powder!" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    sleep 1
    # vanish the vanishing line
    echo "$(cat "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null | grep -v "Vanishing")" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  }

  ##############################################################################

  function rogue_buying() {
    # n% amount
    REFERENCE_AMOUNT="$(echo "$ROGUE_AMOUNT*$REFERENCE_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    echo "$LOG_DATE :: Strategy RGP :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Cheap Shot successfully! $REFERENCE_AMOUNT @ $REFERENCE_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_market "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "true")"
      rogue_vanish
    else
      PLACE_ORDER="$(placeOrder_limit "buy" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_PRICE" "$REFERENCE_AMOUNT" "true")"
      rogue_vanish
    fi
  }

  ##############################################################################

  function rogue_selling() {
    # n% amount
    REFERENCE_AMOUNT="$(echo "$ROGUE_AMOUNT*$REFERENCE_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    LISTING_AMOUNT="$(echo "$ROGUE_AMOUNT*$LISTING_AMOUNT" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    echo "$LOG_DATE :: Strategy RGP :: $LISTING_CURRENCY/$REFERENCE_CURRENCY :: Pick Pocket successfully! $LISTING_AMOUNT @ $LISTING_PRICE" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    if [[ "$MARKET_LIMIT" == "market" ]] &>/dev/null; then
      PLACE_ORDER="$(placeOrder_market "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$REFERENCE_AMOUNT" "false")"
      rogue_vanish
    else
      PLACE_ORDER="$(placeOrder_limit "sell" "$LISTING_CURRENCY" "$REFERENCE_CURRENCY" "$LISTING_PRICE" "$LISTING_AMOUNT" "false")"
      rogue_vanish
    fi
  }

  ##############################################################################

  function rogue_clean_lines() {
    # keep n lines (default: 24h*7d+1=169)
    echo "$(tail -169 "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null)" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue
  }

  ##############################################################################

  ROGUE_PROFIT="$(egrep "ROGUE_PROFIT=" "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".config | awk -F= '{ print $2 }' | tr -d '"' | awk '{ print $1 }')" # rogue profit enable, disable

  if [[ "$ROGUE_PROFIT" -eq "1" ]] &>/dev/null; then

    # missing, continue
    if [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
      touch "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue &>/dev/null
    fi

    # update data every n seconds
    if [[ "$(echo "$(($(date +%s) - $(date +%s -r "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null)))" 2>/dev/null)" -gt "$ROGUE_TIMER" ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
      # update data if missing
    elif [[ ! -f "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
      # update data if empty
    elif [[ ! -s "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue ]] &>/dev/null; then
      rogue_data
      rogue_stealth
      rogue_clean_lines
    fi
    ############################################################################

    # line count
    ROGUE_COUNT="$(wc -l "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $1 }')"

    # listing
    ROGUE_LISTING_NOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | tail -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_LISTING_HIGH="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_LISTING_LOW="$(grep "L " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_LISTING_TOTAL="$(echo "$ROGUE_LISTING_NOW+$ROGUE_LISTING_HIGH+$ROGUE_LISTING_LOW" | bc -l | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_LISTING_AVERAGE="$(echo "$ROGUE_LISTING_TOTAL/3" | bc -l | awk '{ printf "%.2f\n", $1 }')"

    # reference
    ROGUE_REFERENCE_NOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | tail -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_REFERENCE_HIGH="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | tail -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_REFERENCE_LOW="$(grep "R " "${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rogue 2>/dev/null | awk '{ print $NF }' | sort -n | head -1 | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_REFERENCE_TOTAL="$(echo "$ROGUE_REFERENCE_NOW+$ROGUE_REFERENCE_HIGH+$ROGUE_REFERENCE_LOW" | bc -l | awk '{ printf "%.2f\n", $1 }')"
    ROGUE_REFERENCE_AVERAGE="$(echo "$ROGUE_REFERENCE_TOTAL/3" | bc -l | awk '{ printf "%.2f\n", $1 }')"

    echo "U: ${ROGUE_TIMER:?}s L: $(echo "$ROGUE_COUNT/2" | bc 2>/dev/null)
L_NOW  $ROGUE_LISTING_NOW
L_High $ROGUE_LISTING_HIGH
L_LOW  $ROGUE_LISTING_LOW
L_AVG  $ROGUE_LISTING_AVERAGE

R_NOW  $ROGUE_REFERENCE_NOW
R_HIGH $ROGUE_REFERENCE_HIGH
R_LOW  $ROGUE_REFERENCE_LOW
R_AVG  $ROGUE_REFERENCE_AVERAGE" >"${SYS_DIR:?}"/robot/"$BASENAME_STRATEGY".rsi

    ############################################################################

    # rogue_selling config n% of allocated n%
    if [[ "$ROGUE_LISTING_NOW" -gt "70" ]] &>/dev/null; then
      # overbought, pick pocket at top!
      rogue_selling
    fi

    ############################################################################

    # rogue_buying config n% of allocated n%
    if [[ "$ROGUE_LISTING_NOW" -lt "30" ]] &>/dev/null; then
      # oversold, cheap shot at bottom!
      rogue_buying
    fi

    ############################################################################
  fi
}

################################################################################

function robot_Logs_by_date() {
  # sort by date
  echo "$(sort -k 1.5M -k 1.3n -k 1.4n -k 2n -k 3.1n -k 3.2n "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  if [[ "$(wc -l "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log | awk '{ print $1 }')" -gt "$MAX_LOG" ]] &>/dev/null; then
    echo "$(tail -"$(echo "$MAX_LOG/3" | bc 2>/dev/null)" "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
    echo "$LOG_DATE :: LogReset :: Line $MAX_LOG" >>"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  else
    echo "$(cat "${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log 2>/dev/null)" >"${LOG_DIR:?}"/leeloo/robot."$BASENAME_STRATEGY".log
  fi
}

################################################################################

# END
